### ISSUE TITLE
cqw in arbitrary values

### ISSUE THREAD

**Issue by evenwu** [tailwindlabs/tailwindcss#10080]
Hi

I use Tailwind CSS  v3.2.4

the container query is very popular and I am trying something.

I found this problem: if I use `cqw` units in arbitrary values, they will turn `cqw` into color.

Example:

```
text-[4cqw]
```

Result:

```
.text-\[4cqw\] {
  color: 4cqw;
}
```

**Comment by thecrypticace** [comment]
We should definitely adjust things to detect this automatically but you can work round this issue today by using arbitrary value types: `text-[length:4cqw]`

**Comment by thecrypticace** [comment]
Hey, I've merged in the fix for this (as well as added a handful other new length units that we were missing).

This will be available in the next release — but in the meantime you can test it using our insiders build which should be published in the next few minutes: `npm install tailwindcss@insiders`.
