### ISSUE TITLE
ring/outline coloring on `focus-visible` not working on firefox

### ISSUE THREAD

**Issue by zynth17** [tailwindlabs/tailwindcss#10226]
**What version of Tailwind CSS are you using?**

v.3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 4.0.3, postcss 8.4.20

**What version of Node.js are you using?**

v18.12.0

**What browser are you using?**

Firefox Developer Edition

**What operating system are you using?**

macOS

**Reproduction URL**
https://play.tailwindcss.com/kghLm9mhL0

**Describe your issue**

the focus-visible selector does not work, trying to change the color or adding ring on focus-visible is not working

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `focus-visible` works, but the issue is that the `outline` is behaving a bit odd in Firefox. The problem is that it is actually working, but you don't see it because the blue outline sits on top of the ring utilities. If you change `focus-visible:ring-1` to just `focus-visible:ring` without the `-1` then you will see this (notice the tiny little red corners):
<img width="139" alt="image" src="https://user-images.githubusercontent.com/1834413/210344945-3b8ec0cc-e2e0-4231-84cb-7df5e27e80c6.png">

So there are a few things you can do:
```html
<button class="w-max bg-blue-300 px-4 py-2 focus-visible:outline focus-visible:outline-red-500">Hello world</button>
```
I removed the ring utilities, and added an explicit `focus-visible:outline`. This will result in the following when focused:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/1834413/210345222-8bf01a9b-7598-4bfd-9365-a84bc27785de.png">

So the only odd thing here is that the outline does exist, but just setting the color in Firefox somehow doesn't work and you have to explicitly add the `outline-style` (you can use `focus-visible:outline`).

Another way of handling this is using the ring utilities as you mentioned, but then you have to explicitly turn off the outline using `focus-visible:outline-none`:
```html
<button class="w-max bg-blue-300 px-4 py-2 focus-visible:ring-1 focus-visible:ring-red-500 focus-visible:outline-none">Hello world</button>
```
Note that because of the `ring-1` value, you will only get a single pixel:
<img width="122" alt="image" src="https://user-images.githubusercontent.com/1834413/210345423-4ce9552c-028f-4a44-a3e0-7a002145c0f1.png">


Hope this helps!
