### ISSUE TITLE
Need a way to preserve the filter order

### ISSUE THREAD

**Issue by giripriyadarshan** [tailwindlabs/tailwindcss#10250]
**What version of Tailwind CSS are you using?**

3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Qwik and QwikCity (https://qwik.builder.io/integrations/integration/tailwind/)

**What version of Node.js are you using?**

18.11.16

**What browser are you using?**

Firefox

**What operating system are you using?**

Linux

**Reproduction URL**

NA

**Describe your issue**
Hi,

I added classes as 
`hover:invert-[48%] hover:sepia-[85%] hover:saturate-[1911%] hover:hue-rotate-[345deg] hover:brightness-[101%] hover:contrast-[98%]`

It is auto-sorting as 
`brightness(1.01) contrast(0.98) hue-rotate(345deg) invert(0.48) saturate(19.11) sepia(0.85)`

expected it to be sorted in the same way it was defined as filters order makes a huge difference

Please suggest a way to disable or override such auto-sorting.

Thank you

**Comment by adamwathan** [comment]
Hey! So the tricky thing with this sort of thing is that the order of classes in your HTML has no impact on the order your styles are applied (not Tailwind-specific, just how CSS works), so there's not much we can really do here. The classes can only appear in your actual stylesheet in one order of course, so if you wanted a different order on a per-element basis there's no way to do it.

If you need this sort of fine-grained control your best bet is to use [arbitrary properties](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties) to define the whole filter as a single rule:

```html
<div class="hover:[filter:invert(48%)_sepia(85%)_saturate(1911%)_hue-rotate(345deg)_brightness(101%)_contrast(98%)]">
```

**Comment by joshdavenport** [comment]
@adamwathan I think there is an argument that how the filters that are applied is Tailwind-specific because they apply in the order they are provided to the `filter` property which is generated by Tailwind. As OP mentioned, the order is important and does affect appearance, though I'm absolutely certain this is not news to you specifically. Debatably customising this belongs only in a plugin (I've made one) but imo it feels like there is merit to including it in Tailwind.

In this example I can completely change the appearance by re-ordering the Tailwind generated and css-var-based `filter` property value: https://play.tailwindcss.com/fNwA7oXgSb. This has no relation to class names or any order there, because `filter` is always `var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)`. This example is a minimal version of a real life use case I had, where I'm styling a third-party form (in this case a [Clerk](https://clerk.com/) login form)

I've created a [plugin](https://github.com/joshdavenport/tailwindcss-filter-order) ([NPM link here](https://www.npmjs.com/package/@joshdavenport/tailwindcss-filter-order), [descriptions weird atm though](https://github.com/serverless/serverless/issues/3157#issuecomment-1502304267)) adding a `filter-order` util used like `filter-order-facebook-icon` or `filter-order-[sepia_invert_brightness]`

Before/after:
![Screenshot 2023-04-14 at 18 19 58](https://user-images.githubusercontent.com/757828/232113589-3592895a-1ce5-453b-be97-0e0e35b01c4e.png)
