### ISSUE TITLE
Tailwind not compiled in docker on local (dev)

### ISSUE THREAD

**Issue by aandriamanga** [tailwindlabs/tailwindcss#10326]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.18, Next.js 13.1.2

**What version of Node.js are you using?**

v14.18.2

**What browser are you using?**

Chrome, Safari, Firefox

**What operating system are you using?**

MacOS, Ubuntu-20.0.4 (on WSL)

**Reproduction URL**

https://github.com/aandriamanga/nextjs-tailwindcss-docker

**Describe your issue**

My tailwindcss not compiled when I run « yarn dev » from docker.
For reproducing this there is differents steps:
- Run `yarn install`
- Run Docker Desktop app
- Run `docker network create my_network`
- Run `docker-compose build`
- Run `docker-compose up`
- Open browser on localhost:3000
- No style is applied

When I run it outside docker, tailwind css is compiled.
For reproducing this there is differents steps:
- Run `yarn dev`
- Open browser on localhost:3000
- The styles are applied

So, I think the issue is between docker and tailwind but maybe not with nextjs.

Thank you in advance for your investigation / help

**Comment by thecrypticace** [comment]
Hey! I took a look and your Dockerfile is missing the PostCSS config and Tailwind CSS config which is why it's not working. Since Docker is creating an isolated environment and these files are not in a volume you'll need to copy them over like you do for your next config, package.json, etc…

Add these lines to enable PostCSS and Tailwind support and everything will start working:

```docker
COPY postcss.config.js .
COPY tailwind.config.js .
```

**Comment by aandriamanga** [comment]
Hi @thecrypticace, thank you for your help!
It's work perfectly now.
