### ISSUE TITLE
Tailwind creates classes based on variable names in my typescript codes

### ISSUE THREAD

**Issue by hakobpogh** [tailwindlabs/tailwindcss#10424]
**What version of Tailwind CSS are you using?**
v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**
NX, with a React application, where I use it as an extension.

* nx: 15.3.0

**What version of Node.js are you using?**
v16.17.0

**What browser are you using?**
Chrome and Arc

**What operating system are you using?**
macOS

**Reproduction URL**
I'll try creating one.

**Describe your issue**
I believe you can reproduce it in a different way to. But what I see is when you have a variable named `visible`, or `container` then it just leaves the visible, and container class. But these are just typescript variables and they shouldn't be counted for.

These c lasses are left because of typescript variables with the same name:
```
.visible {
    visibility: visible
}
.\!visible {
    visibility: visible !important
}
.absolute {
    position: absolute
}
.transform {
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
}
.rounded {
    border-radius: 0.25rem
}
.filter {
    filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)
}
```

I believe it should only show for the expressions in jsx scope and not look for variable or function names. Or maybe we can have some flag to ignore standard classes in the result. Because I mostly use module files.

**Comment by adamwathan** [comment]
Hey! So this is actually by design to maximize compatibility with different templating languages, check out the explanation of how it works here:

https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

Your best bet if you want to prevent a class from being generated is to use the `blocklist` feature:

https://tailwindcss.com/docs/content-configuration#discarding-classes

Personally I would just ship the CSS with the 6 unused classes, of course it would be great to have no false positives at all but I think it's a better user experience to have a few false positives than to have the reverse and have situations where Tailwind doesn't add your classes at all because it's too particular about how you've got things set up.

Hope that helps!

**Comment by hakobpogh** [comment]
@adamwathan the difference between the blocklist and my case is that I just don't want to to appear in the final result. So in case I want to blacklist the class `absolute` I still want to be able to use it in the `.a { @apply absolute; }`. Do you think something like this is possible?
