### ISSUE TITLE
Error "[postcss] Cannot read properties of undefined (reading '5')" when use "peer"

### ISSUE THREAD

**Issue by vnvyvu** [tailwindlabs/tailwindcss#10443]
**What version of Tailwind CSS are you using?**

"tailwindcss": "^3.2.4"

**What build tool (or framework if it abstracts the build tool) are you using?**

"vite": "^4.0.4"

**What version of Node.js are you using?**

v16.14.2

**What browser are you using?**

Edge

**What operating system are you using?**

Linux

**Reproduction URL**

https://stackblitz.com/edit/vite-react-tailwind-gdzk4p?file=src/Dropdown.jsx

![image](https://user-images.githubusercontent.com/22812601/215420956-9ff02b70-6301-43de-bef2-d8b2b4235723.png)

Idk, sorry if this error isn't with Tailwind

**Comment by thecrypticace** [comment]
Hey! Thanks for the report. So there are two things here:
1. You're trying to generate dynamic names and have Tailwind CSS match them. As Tailwind CSS does not have a runtime component this will not work the way you will expect. Tailwind CSS does not "parse" your code and instead only looks for raw strings that could be classes. Our guide has a section on [dynamic class names](https://tailwindcss.com/docs/content-configuration#dynamic-class-names) which explains how things work in this regard.
2. The crash you're experiencing was fixed in our insiders build somewhat recently which you can test by installing it: `npm install tailwindcss@insiders`.

**Comment by prodkt** [comment]
This error is still occurring March 12. 2023
