### ISSUE TITLE
multiple pop up open prevent scroll of body after press back button of browser

### ISSUE THREAD

**Issue by vasu-aktivolabs** [tailwindlabs/tailwindcss#10501]
**What version of Tailwind CSS are you using?**

version: ^3.1.5

**What build tool (or framework if it abstracts the build tool) are you using?**

version: postcss-cli ^8.4.14

**What version of Node.js are you using?**

version: v16.17.0

**What browser are you using?**

browser: Chrome

**What operating system are you using?**

system: ubuntu

**Describe your issue**

When we open one modal on any click event and on that opened modal if we open another modal and now when we press back button of browser it doesn't remove overflow:hidden property from html tag instead it should automatically close both modal and remove overflow:hidden property from html tag

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I'm assuming this issue was meant for the Headless UI repo. Please open an issue there with a minimal reproduction repo attached so that we can take a look.

That said, we don't support multiple dialogs open at the same time _unless_ they are nested in each other. 
Also make sure that you are on the latest version of Headless UI.
