### ISSUE TITLE
Formatted string variables don't work as classnames when passed as an arbitrary value

### ISSUE THREAD

**Issue by slyofzero** [tailwindlabs/tailwindcss#10557]
I am currently using TailwindCSS version 3.2.4 in a NextJS 13 app, built using the command `npx create-next-app -e with-tailwindcss`. I have disabled the experimental features and am not using the NextJS 13 app directory and only working inside the traditional pages directory.

I am using Node version 18.13.0 on Firefox on a Windows computer.

**Reproduction URL** - https://github.com/slyofzero/tailwind-issue

---
I was trying to apply tailwind classes to the children element by only adding class names to the parent in this manner.

```tsx
const paragraph = "text-red-500";
const section = `leading-8 [&>p]:${paragraph}`;
```

These variables are then passed as the `classname` property for any tag or component.

I thought that this would apply red font color to all paragraphs inside a section tag but it doesn't, even though the developer tools show the `text-red-500` class on each paragraph.

The styles however are applied if we don't have any variables being passed as an arbitrary value or if we only have a formatted or a normal string as the classname. It just throws issues if the variable is passed as an arbitrary value.

**What does work -**
```tsx
const section = `leading-8 [&>p]:text-red-500`; //OR
const section = `leading-8 ${paragraph}`
```

It'll be really handy if we this can be fixed/enabled as it'll help really with scoping.

**Comment by adamwathan** [comment]
Hey! This is expected behavior, check out our documentation on dynamic class names:

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

We don't execute/evaluate your templates, we only scan them for static class names. Even if we did try to evaluate things there'd be lots of stuff that was impossible to make work, for example:

```js
const paragraph = await fetchFromSomeDatabaseOrApi(...)
const section = `leading-8 [&>p]:${paragraph}`;
```

...so no plans to really go further down that path — we're convinced at the moment that it's better to keep things simple and predictable 👍
