### ISSUE TITLE
Animation order not proper in Generated CSS

### ISSUE THREAD

**Issue by vpcvdc** [tailwindlabs/tailwindcss#10551]
**What version of Tailwind CSS are you using?**

v3.2.6

**What build tool (or framework if it abstracts the build tool) are you using?**

[play.tailwindcss.com](https://play.tailwindcss.com/)

**What version of Node.js are you using?**

N/A

**What browser are you using?**

N/A

**What operating system are you using?**

N/A

**Reproduction URL**

[Bug Link](https://play.tailwindcss.com/fFvgluCT5B)

**Describe your issue**

In Bug Link under Generated CSS panel Utilities tab, animate-none class generated after animate-bounce and before rest of animate classes. It's confusing right now. Please add animate-none class after all animate classes, it will be very easy to override  instead of adding important modifier.

**Comment by adamwathan** [comment]
Hey! This is just kinda how everything works in Tailwind, you aren't meant to ever add two utilities that conflict with each other. Rather than use the important modifier, just make sure you're only ever adding one class or the other:

```html
<div class="{{ shouldAnimate ? 'animate-bounce' : 'animate-none' }}">
  ...
</div>
```

Or in this case just only add the animation class if it's needed:

```html
<div class="{{ shouldAnimate && 'animate-bounce' }}">
  ...
</div>
```

Our IntelliSense plugin shows lint warnings for conflicting classes generally but looks like it's not doing it for animation classes — will raise that internally and see if we can get that sorted out:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/4323180/218160308-f4d8d9d5-62c4-44d4-942a-00eaf10a1b3c.png">


Hope that helps.
