### ISSUE TITLE
Not all classes in @apply end up in final css

### ISSUE THREAD

**Issue by tkalmar** [tailwindlabs/tailwindcss#10562]
**What version of Tailwind CSS are you using?**

v3.2.6

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 4.1.1 (with postcss 8.4.21)

**What version of Node.js are you using?**

For example: v18.14.0

**What browser are you using?**

N/A

**What operating system are you using?**

WSL (Debian) --Windows

**Reproduction URL**

https://github.com/tkalmar/tailwind_bug_repro/tree/main

**Describe your issue**
In the reproducer observe `./src/components/Box.vue` there are three styles applied via `@apply` only two of them are generated into the resulting style.css (dist folder after build)
If i change the declaration from:
```postcss
.default_title {
    @apply text-xl bg-green-400 border-orange-600;
}
```
to:
```postcss
.default_title {
    @apply text-xl bg-green-400 border-orange-600 ;
}
```
(notice the space before the final `;` ) all three utility classes are generated into the resulting style.css

Expectation is to not have to include an space before the last class name

**Comment by timkley** [comment]
@tkalmar is your issue that there isn't a class `border-orange-300` in the dist-file? Because that's not how `@apply` works. The styles you want is correctly generated for me:

```
.default_title[data-v-982eb908] {
    --tw-border-opacity: 1;
    border-color: rgb(234 88 12 / var(--tw-border-opacity));
    --tw-bg-opacity: 1;
    background-color: rgb(74 222 128 / var(--tw-bg-opacity));
    font-size: 1.25rem;
    line-height: 1.75rem
}
```

**Comment by adamwathan** [comment]
As @timkley mentioned this looks like it's working correctly — none of the classes listed in `@apply` need to be in the final CSS for things to work since you are applying those to your own custom class, so all that matters is that the custom class is generated. If anything, in a perfect world even the `text-xl` and `bg-green-400` classes would be excluded, and you can do that using a custom `transform` for handling `.vue` files as mentioned here:

https://github.com/tailwindlabs/tailwindcss/discussions/10529#discussioncomment-4913180

Hope that helps!
