### ISSUE TITLE
Conflict between animation and translate utilities

### ISSUE THREAD

**Issue by ChristianJacobsen** [tailwindlabs/tailwindcss#10665]
**What version of Tailwind CSS are you using?**

v3.2.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

N/A

**What browser are you using?**

Firefox 111.0b4

**What operating system are you using?**

Linux 6.1.12

**Reproduction URL**

https://play.tailwindcss.com/HPayg5O2vn

**Describe your issue**

When applying (in this case) both `animation-spin` and `-translate-y-1/2` to an SVG element, the object stops spinning and starts "bouncing" instead. I'm guessing this is because the `rotate` transform is being applied even if it's not in use, which would interfere with the keyframes' rotation.

Am I doing something dumb, or is this something I can expect to work?

**Comment by adamwathan** [comment]
Hey! You can see here this still happens in just vanilla CSS, simply because the animation is targeting the `transform` property and so is the translation, so they are stomping on each other:

https://jsfiddle.net/1r6khqm3/1/

Best bet in these situations is a wrapper element so you can separate the two behaviors:

https://play.tailwindcss.com/0hyQ55Iowv

Another option is to use the fairly new dedicated `translate` property as an arbitrary property in Tailwind:

https://play.tailwindcss.com/5Alxkz6Cqg

We'll probably swap from using `transform` to dedicated transform properties for v4 since it's a breaking change because of browser support.

**Comment by ChristianJacobsen** [comment]
Thank you @adamwathan! That clears it up for me.

Looking forward to the v4 changes! Thanks for making a great product!
