### ISSUE TITLE
Unexpected output with @apply and :not()

### ISSUE THREAD

**Issue by toddstoker** [tailwindlabs/tailwindcss#10660]
**What version of Tailwind CSS are you using?**

v3.2.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

Tailwind Play

**What browser are you using?**

N/A - Chrome

**What operating system are you using?**

N/A - macOS

**Reproduction URL**

https://play.tailwindcss.com/26xdkPKHeY

**Describe your issue**

When using `@apply` with any Tailwind utility and also using CSS psuedo-selector `:not()` with the same utility's class name, the resulting output includes unexpected CSS rule declarations. (See linked example.)

Including this in the source:
```
.foo {
    @apply hidden;
}

input:not(.hidden) {
    @apply block;
}
```

Results in this output:
```
.hidden {
  display: none;
}

.foo {
  display: none;
}

input:not(.foo) {
  display: block;
}

input:not(.hidden) {
  display: block;
}
```

The output `input:not(.foo)` selector rule is unexpected.

**Comment by adamwathan** [comment]
Hey! This looks like the right behavior to me — the culprit is that by including `.hidden` in your own selector you've "extended" the behavior of the `hidden` utility, and now by writing `@apply hidden` that extended behavior is getting carried through.

Basically by writing this:

```css
input:not(.hidden) {
  @apply block;
}
```

...you've effectively redefined the `hidden` utility to this:

```css
.hidden {
  display: none;
  
  input:not(&) {
    display: block;
  }
}
```

So now whenever you `@apply hidden`, you are applying all of those rules, not just the simple `display: none` that Tailwind ships with.

This works this way in service of this idea that any time you extract a selector using `@apply` that the behavior doesn't change.

This surprises a lot of people though so it's something we're trying to figure out how to change for v4. Until then though this is behavior is by design and intentional, otherwise refactoring with `@apply` isn't really guaranteed to be safe.

In general I would highly recommend against ever using Tailwind classes in your own custom selectors because of these sorts of side effects. I still believe this behavior is correct but most people just don't recognize that they are "extending" the behavior of existing utilities when including them in custom selectors.

Hope that helps!
