### ISSUE TITLE
Default theme's keyframes aren't steppable in Safari

### ISSUE THREAD

**Issue by callumacrae** [tailwindlabs/tailwindcss#10750]
**What version of Tailwind CSS are you using?**

3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.21, vite 4.0.1

**What version of Node.js are you using?**

v18.13.0

**What browser are you using?**

The bug happens in Safari

**What operating system are you using?**

Mac OS

**Reproduction URL**

https://play.tailwindcss.com/RC1nwpc3ui

**Describe your issue**

The default theme's CSS animations aren't stepped in Safari, meaning if you set `animation-timing-function: steps(4)` or something similar, it breaks the animation.

It seems like it's because there's no `from` step. Locally I've fixed it by changing it to the following:

```js
        spin: {
          from: {
            transform: 'rotate(0deg)',
          },
          to: {
            transform: 'rotate(360deg)',
          },
        },
```

I'm happy to contribute a fix for this (and the other keyframes) but it seemed like the kind of thing that could have wider implications and I haven't contributed to this project before so I wanted to check!

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The default animations we ship are more like helpful examples because they are very project specific (https://tailwindcss.com/docs/animation#customizing-your-theme). If you want to make the `spin` animation steppable then I would recommend you to override the existing spinner entirely with a version that works for you.

Hope this helps!

**Comment by callumacrae** [comment]
Fair enough, but surely if they're helpful examples for people to base their own animations off, they should be bug free? 😅
