### ISSUE TITLE
Configuration file type definitions

### ISSUE THREAD

**Issue by Glinkis** [tailwindlabs/tailwindcss#1077]
It would be awesome if we were able to get autocomplete working in the configuration file. Especially so with `theme` callbacks and plugins.

This should be possible to achieve by including typescript or jsdoc type definitions, and then doing something like:
```javascript
/**
 * @type {import('tailwindcss').Config}
 */
const config = {
 // everything inside of here would get autocomplete
};

module.exports = config;
```

**Comment by adamwathan** [comment]
Would be open to a PR for this, not something I have experience with myself though. One thing to be careful of though is that you can have any keys you want in that file, because plugins can expect custom keys to exist, so I'm not sure how easy it's going to be to capture that flexibility in a type definition.

**Comment by LouizFC** [comment]
I was about to open the same issue. Glad there are more people interested in this.

@adamwathan in typescript you can define something like: 
```typescript
interface Dictionary {
  some: string;
  keys: string;
  /**
   * and with this you are saying: "this type can have any field 
   * as long as the key is a string and it also return a string"
   */
  [key: string]: string;
}
```

@Glinkis I don't know how to "wire" the type definition to the raw javascript file, but I can help write the definition file if wanted

**Comment by Glinkis** [comment]
> I don't know how to "wire" the type definition to the raw javascript file
Not quite sure what you mean by this. It should be enough to just create a `types.d.ts`-file, and link to it via the `types` field in `package.json`.

One can then simply do `import('tailwindcss')` in the JSDoc comment like I did above.

Would you like to create a branch for this, and link it here? That way we could potentially collaborate on the type file.

**Comment by LouizFC** [comment]
@Glinkis I will create it on the weekend, I already have some types from a experiment that I did on tailwind. The only thing I can't get right are the default values.

Just inlining all the default values on a e.g `DefaultScreens`, `DefaultColors` types should be enough, but it introduces the overhead of modifying two files if Tailwind devs want to change a default value (or introduce new ones).

If you know something that could help (like a tool that extracts default values from an existing object) that would solve this problem.

**Comment by Glinkis** [comment]
@LouizFC I started a bit over [here](https://github.com/Glinkis/tailwindcss), with a very basic setup.
I've granted you contribution privileges.

**Comment by jonaskuske** [comment]
FYI, this gets you fairly close:

```js
/** @typedef { import('tailwindcss/defaultConfig') } TailwindConfig */
/** @typedef { import('tailwindcss/defaultTheme') } TailwindTheme */

/** @type { TailwindConfig & { theme: { extend: TailwindTheme } } } */
module.exports = {}
```

It's not perfect (e.g. `"purge"` is reported as `undefined[]` instead of `string[]`, some options are objects and some are functions...) but you do get nice autocomplete for most config and theme options and see all the available options without having to check the docs for their precise name. 👍🏻

**Comment by GaspardC** [comment]
@jonaskuske thanks seems great
how do we use this snippet to access the type then ?  😅

**Comment by jonaskuske** [comment]
@GaspardC The snippet directly applies the type to the exported object:
```js
/** @type { DefaultConfig & { theme: { extend: DefaultTheme } } } */
module.exports = {
 // you have autocomplete here, type "c" and it'll suggest "corePlugins"
}
```

If you want to use the type on it's own, you can define it as well rather than applying it directly:

```js
/** @typedef { import('tailwindcss/defaultConfig') } DefaultConfig */
/** @typedef { import('tailwindcss/defaultTheme') } DefaultTheme */
/** @typedef { DefaultConfig & { theme: { extend: DefaultTheme } } } TailwindConfig */

// now use the type "TailwindConfig" however you like:

// @type { TailwindConfig }
module.exports = {}

// or even in some TS file:

import { TailwindConfig } from './tailwind.config'
const config: TailwindConfig = { ... }
```

But note that the type is just infered from the default config and theme and thus not really accurate – fine to get autocomplete, not so much for proper TypeScript use.
For TS use, you'd at least want to use `Partial<TailwindConfig>` so it treats all properties as optional, otherwise TS won't be satisfied until you specify every single possible config property 😬

**Comment by GaspardC** [comment]
@jonaskuske thanks, exactly what I'm looking for

as you said I created a tailwind.config.js file with :

```js
/** @typedef { import('tailwindcss/defaultConfig') } DefaultConfig */
/** @typedef { import('tailwindcss/defaultTheme') } DefaultTheme */
/** @typedef { DefaultConfig & { theme: { extend: DefaultTheme } } } TailwindConfig */

/** @type {TailwindConfig} */
module.exports = {
// corePlugins hints working here
}
```

then in my TS file:

```ts
import { TailwindConfig } from './tailwind.config'
const config: TailwindConfig = { test: 1 }
//don't have any errors or autocompletion hints here
```

Do you know what is wrong with my code ?

**Comment by jonaskuske** [comment]
@GaspardC Hmm, good question. I tested it in `tailwind.config.js` and in an `index.ts` I created next to it and it worked, but my project wasn't actually set up for TS, there was no `tsconfig.json`. So my guess would be that as soon as you add a `tsconfig` to your project, TS/VSCode handles interop between `.ts` and `.js` with JSDoc differently?

Does it change anything if you add `"checkJS": true` to your `tsconfig`?

**Comment by phamhongphuc** [comment]
With `nuxt-ts` + `@nuxtjs/tailwindcss`, it's possible to use `tailwind.config.ts` as the config file (although there are still some bugs with hot-reload).
I think it would be better if we has the type definitions.

**Comment by phamhongphuc** [comment]
With `@nuxt/typescript-runtime` + `@nuxtjs/tailwindcss`, it's possible to use `tailwind.config.ts` as the config file.
Although there are some bugs with hot-reload, that's not a problem for me.
The problem is we don't have the type definitions. It's hard to write plugins or get autocomplete in the config file.
