### ISSUE TITLE
Can't remove the border around <Image />

### ISSUE THREAD

**Issue by hecker** [tailwindlabs/tailwindcss#10822]
**What version of Tailwind CSS are you using?**

v3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 13.2, Typescript, Tailwind CSS

**What version of Node.js are you using?**

v18.15.0

**What browser are you using?**

Safari 16.3

**What operating system are you using?**

macOS 13.2.1

**Reproduction URL**

https://play.tailwindcss.com/fvyq8GyyLq

**Describe your issue**

I tried everything to remove the border from this image, from using my global.css file, tailwind config or directly putting "border-0" or "border-transparent" etc. into className.

I would appreciate if anyone knows a solution. I also read the documentation but couldn't find anything.

<img width="440" alt="Screenshot 2023-03-20 at 10 26 21" src="https://user-images.githubusercontent.com/23746655/226298388-2918bee7-7c73-4b38-9b0e-9118dccd1e97.png">

**Comment by anasbehhari** [comment]
try removing :  ring-1

**Comment by reinink** [comment]
Hey! I think the issue here is simply that the image is not loading, and this is the style that Safari shows when that happens. By comparison, Chrome and Firefox don't show a border in this situation.

Here's a demo with an actual image loaded, and you can see there is no white border:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/882133/226321307-7cbb6c44-5404-4df7-99ad-9c12674067d7.png">

Find the source here: https://play.tailwindcss.com/4jkGOqYX65

Hope that helps! 🤙
