### ISSUE TITLE
Config: `boxShadow` property: TypeScript error `Type 'string[]' is not assignable to type 'string'.`

### ISSUE THREAD

**Issue by madebyfabian** [tailwindlabs/tailwindcss#10910]
**What version of Tailwind CSS are you using?**

v3.3.0

**What build tool (or framework if it abstracts the build tool) are you using?**

Nextjs 13.2, but appears in tailwind play too.

**What version of Node.js are you using?**

v16.18.1

**What browser are you using?**

Chromium: 111.0.5563.64

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/W4WIzvSESH?file=config

**Describe your issue**

Hi there, I was updating to 3.3.0, great work on the update! I was changing the config to typescript and was noticing that the types for the `boxShadow` property seem to miss the option for arrays, even though it works, gets transpiled and works in the css custom property. For `dropShadow`, there are no type errors.

I peeked into the types and noticed a difference:

`boxShadow` property: `boxShadow?: ResolvableTo<KeyValuePair<string, string>> | undefined`
`dropShadow` property: `dropShadow?: ResolvableTo<KeyValuePair<string, string | string[]>> | undefined`

Here is the config in the tailwind play:

```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      boxShadow: {
        100: [
          '0px 1px 5px 0px rgba(1, 3, 35, 0.03)',
          '0px 5px 18px 0px rgba(1, 3, 35, 0.04)',
          '0px 22px 80px 0px rgba(1, 3, 35, 0.07)',
        ],
      },
    },
  },
  plugins: [],
}
```

Which throws `Type 'string[]' is not assignable to type 'string'.`

I am wondering if this is intentional, but since the syntax does work and is also allowed by the types in `dropShadow`, I think this is an issue.

I can create a PR to fix this, if this is not intentional.

**Alternatives I considered**

What I've seen also does work is to just chain the multiple shadows within one string, seperated with a comma.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

In v4 we will be simplifying the configuration for each plugin such that the structure is simpler instead of taking `n` different shapes. In this case it means that we will only be supporting a `string` in the `boxShadow` even though an array works today.

There are a few solutions you can apply right now:
1. Provide a string instead of an array. Using `.join(', ')` should do the trick here. This will also allow you to be future proof.
2. Alternatively, you can use `@ts-ignore` and keep providing an array. This will work for now, but this will very likely be changed in v4 and will require an upgrade on your end.

Hope this makes sense!

**Comment by madebyfabian** [comment]
@RobinMalfait Thanks for the explanation and the quick fix to get the types in sync! I will transform my config into using a single string for now.
