### ISSUE TITLE
The same content cannot be compressed and merged, only a small part is compressed and merged

### ISSUE THREAD

**Issue by J-env** [tailwindlabs/tailwindcss#10973]
**What version of Tailwind CSS are you using?**

v3.2.7+

**What build tool (or framework if it abstracts the build tool) are you using?**

[Astro](https://astro.build/)

**What version of Node.js are you using?**

v16.18.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

[tailwindcss](https://github.com/tailwindlabs/tailwindcss.com) tailwindcss has the same problem 

**Describe your issue**

Use cssnano or csso to merge, only a small part is merged:
[link](https://github.com/tailwindlabs/tailwindcss/discussions/10820#discussion-4981939)

**Comment by adamwathan** [comment]
Hey! I'm not sure what output you expect here but this is what Tailwind itself generates and is intentional:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/4323180/230905260-74305ebb-6235-4a32-90da-2f270c8b28c5.png">

Any optimizations to this in my mind are better discussed in the relevant minification projects.

Generally though the output Tailwind is producing here compresses better over the network because there are bigger chunks of repeating strings — here's a good blog post that discusses the same general idea, assuming I'm understanding your report correctly:

https://csswizardry.com/2016/02/mixins-better-for-performance/
