### ISSUE TITLE
Flex justify content is not overridden by breakpoints.

### ISSUE THREAD

**Issue by PeytonHanel** [tailwindlabs/tailwindcss#11025]
**What version of Tailwind CSS are you using?**
3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

sveltekit 1.11.0
svelte 3.56.0
postcss 8.4.21
vite 4.1.4

**What version of Node.js are you using?**

19.7.0

**What browser are you using?**

Chrome, Brave, Firefox

**What operating system are you using?**
 
Ubuntu

**Reproduction URL**

https://play.tailwindcss.com/AIl9NEG9OW

**Describe your issue**

Attempting to override justify-* with a breakpoint does not work. Any justify-* without a breakpoint is always enabled. You can see in the reproduction that other breakpoints work as expected, but justify-center is not overridden by justify-left.

**Comment by adamwathan** [comment]
Hey! This is because there is no `justify-left` class in Tailwind, just `justify-start`:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/4323180/232630121-1a1e6974-e5c1-442f-9d21-842daddf6a1e.png">

Here's an updated version of your Play that does what I think you want:

https://play.tailwindcss.com/Fwg8hIYzIZ

Hope that helps!

**Comment by PeytonHanel** [comment]
:facepalm: thank you
