### ISSUE TITLE
Preflight img

### ISSUE THREAD

**Issue by papazetis** [tailwindlabs/tailwindcss#11044]
I think that img {display: block} is wrong - I haven't tested svg, video, canvas, audio, iframe, embed, object yet

It's causing an issue when you add an image next to a text

All modern frameworks, like bootstrap and uikit, have only {vertical-align: middle}

**Comment by adamwathan** [comment]
Hey! This is inspired by how it's handled in [CSS Remedy](https://github.com/jensimmons/cssremedy/blob/master/css/remedy.css#L129-L133) and is intentional. Changing it at this point would be a really big breaking change so that's off the table I'm afraid.

You can always change the display type on an image by using a utility class:

```html
<img src="..." class="inline">
```

Hope that helps!
