### ISSUE TITLE
Issue with spacing on the Y-axis and X-axis

### ISSUE THREAD

**Issue by TomGjeka** [tailwindlabs/tailwindcss#11080]
As the title implies there is a logic issue when using space-xy-(number) with row-reverse or column-reverse.

we got two divs which we give spacing-x-2 and it works in row -> the second div has the margin applied.

ordering div with row-reverse -> first div has the spacing on the left and the second div is next to the first one without spacing.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Make sure that you are also applying the `space-x-reverse` or `space-y-reverse` utility classes when reversing the columns: https://tailwindcss.com/docs/space#reversing-children-order.

If this doesn't work for you, could you open a new issue with a minimal reproduction repo or Tailwind Play attached (https://play.tailwindcss.com/) so that we can take a look?

Hope this helps!
