### ISSUE TITLE
Tailwind Config file: modules alias import errors

### ISSUE THREAD

**Issue by phatify** [tailwindlabs/tailwindcss#11097]
**What version of Tailwind CSS are you using?**

For example: v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.4.18, Next.js 13.3.1

**What version of Node.js are you using?**

For example: v16.16.0

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: Windows

**Describe your issue**

I am getting import errors on modules when using alias name in tailwind.config.js. This causing `Error: Cannot find module '@/my-plugin'`

tailwind.config.js:

```
import { myPlugin } from '@/my-plugin';

const twConfig = {
    darkMode: 'class',
    content: [
        './pages/**/*.{js,ts,jsx,tsx}',
        './components/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
    },
    corePlugins: {
        preflight: true,
    },
    plugins: [
        myPlugin(),
    ],
};

export default twConfig;
```

jsconfig.json:

```
{
    "compilerOptions": {
        "module": "esnext",
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "baseUrl": ".",
        "paths": {
            "@/*": ["./*"],       
            "@/my-plugin/*": ["my-plugin/*"],   
        }
    },
    "include": ["**/*.js", "**/*.jsx"],
    "exclude": ["node_modules"]
}
```

**Comment by adamwathan** [comment]
Hey! Unfortunately this seems to be a limitation of [jiti](https://github.com/unjs/jiti) which is the tool we use under the hood to transpile your config file at runtime — it's mentioned briefly by the maintainers here:

https://github.com/unjs/jiti/issues/104#issuecomment-1433917979

Basically you need to think of your config file as being loaded and processed totally separately from how your own application code is being bundled. Definitely agree it would be awesome if this just worked or could be made to work, but it would have to be done in jiti rather than in Tailwind itself.

Since we don't have any plans to fork jiti and make this sort of change ourselves I'm going to close this, but if support can get added over there we will definitely make sure to carry that over into Tailwind so it works here too 👍

**Comment by philbaker4** [comment]
It feels like Tailwind could utilize the [`alias`](https://github.com/unjs/jiti#alias) option for jiti to pass in alias maps from `tsconfig.json`, webpack configs, etc if they exist, though I'm unsure if I am ignoring other meaningful constraints. Does that seem reasonable?

**Comment by 7iomka** [comment]
Any news on this?
If you have local package in monorepo that uses other local packages with aliases from paths from tsconfig, you need to rewrite all of it that used inside file used in tailwind.config file.
This is a very bad practice, because some local packages have their own structure, like imports from subfolders, and you need to use direct file location in import rather than beautiful aliased one.
In my case I have a low of shared theme config files that I used in shared tailwind config
<img width="282" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/18473137/4b1fb488-848e-45db-ae47-6603d0a9648a">

```ts

import { tailwindConfig } from '@steklo24/config/tailwind';

export default {
  ...tailwindConfig,
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
   };

```
And the only workaround for me at the moment is to create a separate local package with separate rules for direct imports.
:(

**Comment by binaryartifex** [comment]
yeah im in the exact same boat. NX monorepo, trying to keep the integrated NX monorepo best practice gods happy. ive got a 'universal' theme preset in a library that gets imported by my web apps...the `@product-suite.....` import doesn't work and crashes the build so im forced to go the 'long way' around and include some lint disabling. i mean it works....but i feel dirty..... so very dirty.....

```typescript
import { workspaceRoot } from "@nx/devkit";
import { createGlobPatternsForDependencies } from "@nx/react/tailwind";
import { join } from "path";
import type { Config } from "tailwindcss/types/config";
// eslint-disable-next-line @nx/enforce-module-boundaries
import { preset } from "@product-suite/web/common/ui-theme"; // alias referencing lib in monorepo, doesn't work

const config = {
  presets: [preset],
  content: [
    join(__dirname, "app/**/*.{js,ts,jsx,tsx}"),
    join(__dirname, ".storybook/**/*.{js,ts,jsx,tsx,html}"),
    join(workspaceRoot, "libs/web/@(common|admin)/@(ui|feat)*/**/*.@(js|jsx|ts|tsx|mdx)"),
    ...createGlobPatternsForDependencies(__dirname, "/**/(*.{tsx,jsx,ts,js})"),
  ],
} satisfies Config;

export default config;
```

**Comment by bneigher** [comment]
dang this hurts the nx monorepo people 😢

**Comment by dlhck** [comment]
@bneigher just ran into this. So yeah, it hurts

**Comment by TheElegantCoding** [comment]
Same problem here i have a big config split in some ts files, the alias not work, why this issue is close ?

**Comment by konyogony** [comment]
Yeah hate this one

**Comment by CodesDoWork** [comment]
This is a though one!

My workaround for now is to build a `JITI_ALIAS` string from my tsconfig paths. Since I use many custom NX plugins in my workspace, I could inject it in my Vite plugin as env like this:

```ts
import type { ExecutorContext, PromiseExecutor } from "@nx/devkit";
import { join, relative } from "node:path";
import tsconfig from "@cdw/monorepo/tsconfig.json";
import { execAsync } from "@codesdowork/shared-utils";
import { logger } from "@nx/devkit";
import { projectRoot } from "nx-plugins-utils";

type ViteTarget = "build" | "dev" | "preview";

export function runViteExecutor(target: ViteTarget): PromiseExecutor {
    return async (_, context) => {
        try {
            const projectDir = projectRoot(context);
            await execAsync(`vite`, [target], {
                cwd: projectDir,
                shell: true,
                env: {
                    ...process.env,
                    JITI_ALIAS: getJitiAliasContent(projectDir, context),
                },
            });

            return { success: true };
        } catch (e) {
            logger.error(e);
            return { success: false };
        }
    };
}

function getJitiAliasContent(projectDir: string, context: ExecutorContext): string {
    const projectPathsPrefix = relative(projectDir, context.root);
    const tsConfigPaths = tsconfig.compilerOptions.paths;
    const jitiAliasObject = Object.entries(tsConfigPaths).reduce(
        (jao, [alias, paths]) => ({ ...jao, [alias]: join(projectPathsPrefix, paths[0] || "") }),
        {} as Record<string, string>,
    );

    return JSON.stringify(jitiAliasObject);
}
```
The code above is used in the `createNodes` function on NX to inject targets into projects.

Without a custom plugin, I think the only option will be to run a script, which injects the `JITI_ALIAS` into the environment. Unfortunately, jiti wants relative paths while tsconfig offers paths from the root. This is solved with the plugin approach, but will be a problem without. 🤔
