### ISSUE TITLE
Blog and docs difference for multi-config

### ISSUE THREAD

**Issue by federicocappellotto97** [tailwindlabs/tailwindcss#11206]
[Here](https://tailwindcss.com/blog/tailwindcss-v3-2#multiple-config-files-in-one-project-using-config) the @config directive is on top of the file, but [here](https://tailwindcss.com/docs/functions-and-directives#config) it says you don't have to put @config before the imports

**Comment by adamwathan** [comment]
Hey! I don't see any issues here, you can put it before `@tailwind` but you can't put it before `@import` because `postcss-import` is strict about the spec. Both the blog post and docs are consistent here, neither of them show putting `@config` before `@import` statements, only before `@tailwind` statements which is fine 👍

**Comment by federicocappellotto97** [comment]
> Hey! I don't see any issues here, you can put it before `@tailwind` but you can't put it before `@import` because `postcss-import` is strict about the spec. Both the blog post and docs are consistent here, neither of them show putting `@config` before `@import` statements, only before `@tailwind` statements which is fine 👍

Oooh you’re right, i totally misinterpreted @tailwind with @import 🤦🏻‍♂️
