### ISSUE TITLE
Tailwind causes webpack to recompile for any file change

### ISSUE THREAD

**Issue by uncaught** [tailwindlabs/tailwindcss#11213]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

create-react-app 5.0.1

**What version of Node.js are you using?**

18.15.0

**What operating system are you using?**

Ubuntu 20.04.6 under Window 10 WSL

**Reproduction**

Follow https://tailwindcss.com/docs/guides/create-react-app to the letter:

```
npx create-react-app my-project
cd my-project
npm install -D tailwindcss
npx tailwindcss init
sed -i 's|content: \[\]|content: ["./src/**/*.{js,jsx,ts,tsx}"]|g' tailwind.config.js
printf "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n" >> src/index.css
npm run start
```

**Describe your issue**

When you save/touch/modify _any_ file inside `src` the webpack recompile triggers. It doesn't matter if the file matches the provided pattern or not. E.g. `touch src/x.x`.

Without tailwind, webpack does not trigger in this manner.

Unfortunately this gets quite annoying when working on purely backend files in a larger project where the recompile takes some time and it shouldn't trigger at all.

Could you change the watch system so that webpack isn't triggered if the files don't actually match the pattern? Or maybe integrate with webpack's file detection - there won't be any other files to include other than those webpack is bundling anyway, I guess.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This is unfortunately a webpack problem. Tailwind itself doesn't setup its own watcher, instead we rely on dependency messages provided via PostCSS. PostCSS allows us to register a file dependency, a directory dependency or a glob. This is also where the issue is, webpack doesn't use the `glob` but it uses the directory itself. This means that the `src` folder is registered and the globs are ignored.

You mention that this gets annoying if you are only working in backend related files. Do these files contain any Tailwind classes? If not, then I would recommend to change the glob a bit.

Assuming you have a folder structure like this:
```
.
└── src
    ├── backend
    │   └── index.js
    └── frontend
        └── index.js
```

Then you can change the glob to a more specific glob:
```diff
- content: ["./src/**/*.{js,jsx,ts,tsx}"]
+ content: ["./src/frontend/**/*.{js,jsx,ts,tsx}"]
```

This will register the `src/frontend` folder instead of the `src` folder itself.

---

We are exploring some direct bundler plugins but I can't give you an ETA on this yet.

Does the workaround by making the glob more explicit work for you?

**Comment by uncaught** [comment]
Thank you for your quick response!

Unfortunately our project structure is a monorepo where each of the ~30 packages can contain both the frontend and backend code regarding the topic the package is for and the sub directories are not separated by front/backend. 

Like we might have a folder `packages/i18n/src/Language` containing a `Language.php` and `Language.tsx`.

So we already had to prepare patterns for each package to avoid the node_modules: ``fs.readdirSync('packages').map((p) => `${p}/src/**/*.tsx`)``. Maybe we can let it find even more specific dirs to avoid purely backend subdirs. Is there a limit for the contents array? 

Too bad you can't fix this from your end.
