### ISSUE TITLE
font weight `font-thin` is different with 'OpenType specification'

### ISSUE THREAD

**Issue by Quineone** [tailwindlabs/tailwindcss#1128]
1.https://docs.microsoft.com/en-us/typography/opentype/spec/os2#usweightclass
2.https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping

**Comment by hacknug** [comment]
Also on the `css-fonts` spec: https://www.w3.org/TR/css-fonts-4/#font-weight-numeric-values

Only issue with this is it would be a breaking change and, since you can already configure the class names, I'm pretty sure it won't be prioritized at least until we can justify breaking things again (new major version, probably).

**Comment by adamwathan** [comment]
Yeah I agree following those names would be better, but can't do anything about it until v2, and even then have to weigh the cost of that breaking change. Will tag this for v2 so we can circle back when we're closer to that time.

**Comment by adamwathan** [comment]
Going to update this for 2.0, will keep this open until we introduce it behind a flag.
