### ISSUE TITLE
Unexpected scrolling behaviour when applying effects to an image

### ISSUE THREAD

**Issue by FrancoCanzani** [tailwindlabs/tailwindcss#11525]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

 NextJs: "13.4.7", postcss: "8.4.24"

**What version of Node.js are you using?**

v18.13.0

**What browser are you using?**

Chrome, Edge

**What operating system are you using?**

Windows

**Reproduction URL**

https://codesandbox.io/p/sandbox/test-nextjs-13-tailwind-forked-pf6mf2?file=%2Fstyles%2Fglobals.css%3A4%2C1

**Describe your issue**

When applying brightness or other image effects to an Image, it goes over any sticky or fixed element when scrolling, like the header in my example. 

The example is written using Image API from NextJs but it also happens with the classic image. 

`      <header className="sticky top-0 w-full p-6 bg-black text-white flex items-center">
            <Link href="/">Hola</Link>
      </header>
      <section className="my-8">
            <Image
              src={"/apparel.jpg"}
              alt={"Apparel"}
              width={300}
              height={350}
              className="brightness-50 hover:brightness-100"
            />
      </section>`

Is this the expected behaviour?

**Comment by wongjn** [comment]
This is expected behavior of CSS. As per the [`filter` specification](hthttps://www.w3.org/TR/filter-effects-1/):

> A computed value of other than `none` results in the creation of a [stacking context](https://www.w3.org/TR/CSS21/zindex.html)

This would apply in the case of your `<img>` element which has `brightness-50 hover:brightness-100`. 

Then, as per the [Painting Order](https://www.w3.org/TR/CSS21/zindex.html):

> 8. All positioned descendants with 'z-index: auto' or 'z-index: 0', in tree order.

The `<header>` and `<img>` both have `z-index: auto` since [it is the default](https://drafts.csswg.org/css2/#z-index) so they are rendered in tree order. `<header>` is before `<img>` so the `<img>` renders over the `<header>` element.

If you'd like the `<header>` element to draw over the `<img>`, consider applying a `z-index` value larger than the `<img>` element, like `z-index: 10` via the `z-10` class: https://play.tailwindcss.com/s0bhjyZuAk

**Comment by bradlc** [comment]
Yep, @wongjn nailed it, thank you! 🤝
