### ISSUE TITLE
Unexpcted behavior of pseudo-selectors chain

### ISSUE THREAD

**Issue by omymenzies** [tailwindlabs/tailwindcss#11522]
Tailwind CSS 3.3.2
Node.js v18.15.0
Chrome
Windows 10

My relavant config:
addVariant('child-a', '& > a')

The code of pseudo-selectors chain:
`child:not(last):child:first:child-a:hover:`

Expected css generated:
`& > *:not(:last-child) > *:first-child > a:hover `

Actual css generated:
`&:hover > a:first-child > *:not(:last-child) > * `
This behavior is reversed and unintuitive.

**Comment by RobinMalfait** [comment]
Hey, thank you for your bug report! 🙏

When using stacked variants, the variants are applied from the inside-out. You can think about it as if they are nested function calls, more info about this topic: https://tailwindcss.com/docs/hover-focus-and-other-states#ordering-stacked-modifiers

---

You are using a few variants that we don't have by default so let's look at a simplified example. We're also going to look at it in a more technical way just to see how the variants are composed behind the scenes. Especially the usage of `&` in the variant definition.

Given the following HTML:
```html
<div class="foo:hover:flex"></div>
```

Where the variants `foo` and `hover` are implemented as:
```js
addVariant('foo', '& > .foo')
addVariant('hover', '&:hover')
```

This generates the following CSS:
```css
.foo\:hover\:flex:hover > .foo {
  display: flex;
}
```

Given that we implement everything inside-out, or from the right most variant to the left most variant, we can think of it like:
```js
foo(hover('flex'))
```

This also matches the same structure as the class in your HTML. A side-by-side comparison looks like this:
```html
<div class="foo:hover:flex"></div>
            foo(hover('flex'))
```

This means that we have to combine the following parts:
```css
.flex    /* 1. The utility itself */
&:hover  /* 2. The hover variant  */
& > .foo /* 3. The foo variant    */
```

Each line here would be injected into the next line in place of the `&` character.

We start with `.flex`, then we inject it into the `&:hover` variant. This results in the following selector:
```css
.flex:hover
```
This is because we replaced the `&` in the selector with the line above it, in this case `.flex`.

Next, we have to apply the `foo` variant (implemented as `& > .foo`). This results in the following selector:
```css
.flex:hover > .foo
```
Again, this is because we replaced the `&` in the selector with the line above it, in this case `.flex:hover`.

(To be 100% correct, the class should not be `.flex` but should be `.foo\:hover\:flex` because that's what we typed in the HTML. We can't just use `:` in the selector either, so we have to escape it. This now results in the following selector: `.foo\:hover\:flex:hover > .foo`).

---

Now, if you had written it the other way around:
```html
<div class="hover:foo:flex"></div>
```

This would generate the following CSS:
```css
.hover\:foo\:flex > .foo:hover {
  display: flex;
}
```

Then you can think of the function calls like this:
```js
hover(foo('flex'))
```

This means that we have to combine the following parts:
```css
.flex    /* 1. The utility itself */
& > .foo /* 2. The foo variant    */
&:hover  /* 3. The hover variant  */
```

If we break this down, then it would result in the following changes:
1. `.flex`
2. `.flex > .foo` (replaced `&` with `.flex`)
3. `.flex > .foo:hover` (replace `&` with `.flex > .foo`)
4. `.hover\:foo\:flex > .foo:hover` (If we want to be correct about the actual class name. We didn't type "flex", but we typed "hover:foo:flex")

The key thing to keep in mind is that we apply the variants from inside-out (aka right most variant to left most variant) then we replace the `&` by the layer above. Depending on how each variant is implemented, aka depending on the position of `&` it could result in complex CSS selectors and you might need to change the order of the variants.

It also looks like the variants you are trying to use result in very complex selectors that are hard to reason about. If you can tell me more about your use case you are trying to implement then I think this can be implemented in a different, less-complex way which should help with the mental model.

I hope this explanation helps with how we implemented these variants.
