### ISSUE TITLE
Gradient stop as CSS variable in combination with opacity not working

### ISSUE THREAD

**Issue by gauel** [tailwindlabs/tailwindcss#11593]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

SvelteKit

**What version of Node.js are you using?**

v18

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**
https://play.tailwindcss.com/IK7Xbw0Fhw

**Describe your issue**

When using custom variable with opacity it defaults to:
`--tw-gradient-to: rgb(255 255 255 / 0) var(--tw-gradient-to-position);`

Brief example:
`--color: #7204C9;`

`to-red-500/50` —> working
`to-[#7204C9]/50` —> working
`to-[var(--color)]` —> working
`to-[var(--color)]/50` —> Not working

**Comment by thecrypticace** [comment]
Hey! So this is because when using a variable it could be anything at runtime — and even affected by the cascade. If you use a variable directly we can't know what it is at compile-time and as such cannot generate the appropriate syntax to adjust the opacity. This may be something we are able to change in the future once relative color syntax becomes more widely supported but that's something that we'll have to investigate in the future.

For your case you could wrap the variable in `rgb()` or `hsl()` depending on what color space is being used and it gives Tailwind enough information to insert the opacity. We recommend that your color variables be just the channels because of this.

For example, the following HTML:
```html
<div class="bg-[rgb(var(--foo))]/50"></div>
```

Will produce this CSS:
```css
.bg-\[rgb\(var\(--foo\)\)\]\/50{
  background-color: rgb(var(--foo) / 0.5)
}
```

I've prepared an [example you can look at](https://play.tailwindcss.com/hKMToYM3E3) on Tailwind Play.

Hope that helps! ✨

**Comment by gauel** [comment]
Wow! Thank you @thecrypticace for thorough explanation and updated examples :) This makes sense since the variable is not known before hand
