### ISSUE TITLE
The `static` keyword

### ISSUE THREAD

**Issue by shenlong616** [tailwindlabs/tailwindcss#11640]
**What version of Tailwind CSS are you using?**

 "tailwindcss": "^3.3.3"

**What build tool (or framework if it abstracts the build tool) are you using?**

"next": "13.4.10"

**What version of Node.js are you using?**

v18.16.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Describe your issue**

Hi,

When I use `static` keyword in `javascript`, then `className: static` is generated ✨

- w/o `static` keyword

![image](https://github.com/tailwindlabs/tailwindcss/assets/15698245/286d8c58-b541-4f2f-b7cd-ed616e97640b)

- w `static` keyword

![image](https://github.com/tailwindlabs/tailwindcss/assets/15698245/5934618f-ac20-4c7f-bc12-2dea7d62d0c4)

- and make sure i don't use `static className`

![image](https://github.com/tailwindlabs/tailwindcss/assets/15698245/525c0ce1-8fe3-48e3-89c4-7f3283adbc3b)

**Comment by adamwathan** [comment]
Hey! This is by design — Tailwind only looks at your code [as a giant string](https://tailwindcss.com/docs/content-configuration#class-detection-in-depth) to find potential class names so that it can be compatible with as many templating languages as possible. If you'd like to make sure a specific class is not generated, you can use the `blocklist` feature:

https://tailwindcss.com/docs/content-configuration#discarding-classes
