### ISSUE TITLE
Excess generation of pseudo classes for the `label` html tag

### ISSUE THREAD

**Issue by dpytaylo** [tailwindlabs/tailwindcss#11767]
**What version of Tailwind CSS are you using?**: v3.3.3
**What build tool (or framework if it abstracts the build tool) are you using?**: cargo-leptos 0.1.11; leptos 0.4 
**What version of Node.js are you using?**: v18.17.0
**What browser are you using?**: Chrome
**What operating system are you using?**: Windows

**Reproduction URL**: https://play.tailwindcss.com/Y5XTAWlETw?file=css

**Describe your issue**:
Tailwind adds the excess pseudo class "checked":
![image](https://github.com/tailwindlabs/tailwindcss/assets/18236144/52adb629-3453-4e22-9c5f-792845c50519)

I expected this:  `#menu-button:checked ~ .menu-button-label`.

**Comment by adamwathan** [comment]
Hey! This is working as expected, anything you `@apply` is applied to the element being target by your selector, and your selector is targeting the element with the `.menu-button-label` class, so the classes you are applying are applied to that element.

To get the behavior you're looking for, you can just remove the `checked:` prefix completely because your selector is already specifying that `#menu-button` is checked 👍 

```css
@layer base {
    #menu-button:checked ~ .menu-button-label {
        @apply checked:block checked:absolute checked:right-1 checked:top-1
    }
}
```
