### ISSUE TITLE
Border Color not working when `focus:` in `darkMode: class`

### ISSUE THREAD

**Issue by hrvyncent** [tailwindlabs/tailwindcss#11800]
**What version of Tailwind CSS are you using?**

v3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

play.tailwindcss.com

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/sMKpyE0Ith

**Describe your issue**

So I want to see what my input would look like in dark mode so I enable the `darkMode` in configuration

```
module.exports = {
  darkMode: 'media',
  theme: {
    extend: {
      // ...
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
```

Then in FireFox dev tools I click one with moon icon
![image](https://github.com/tailwindlabs/tailwindcss/assets/131605935/07a197cc-5868-430e-a850-1892fd1eb7ca)
and it's working properly. It shows the border color when focused in dark mode.

But here's the problem, when I change the `darkMode` from `media` to `class` it's not changing the border color anymore.

Since I don't know how to add the `class="dark"` in html in the playground.  I change it directly in the dev tools.

![image](https://github.com/tailwindlabs/tailwindcss/assets/131605935/fdf20055-2aa3-4d4c-974e-e5e99491bff0)

**Comment by wongjn** [comment]
Thank you for the report!

So it seems that the `dark:border-gray-700` rule is generated after `focus:border-violet-500` and since they both have the same specificity, `dark:border-gray-700` takes precedence. You can work around this by either:

- Redeclaring `focus:border-violet-500` with `dark:` to increase its specificity and have it generate after `dark:border-gray-700` like `focus:dark:border-violet-500`.
- Use the [`!important` modifier](https://tailwindcss.com/docs/configuration#important-modifier) to ensure `focus:border-violet-500` takes precedence like `focus:`border-violet-500`

See [this Tailwind Play](https://play.tailwindcss.com/CcNowRVnhK) for both implementation examples.

**Comment by reinink** [comment]
Hey thanks for jumping in here @wongjn — great explanation 👍

@hrvyncent My recommendation here is the first option — combining the `dark` and `focus` modifiers. You can see that we do this ourselves on the Tailwind CSS website:

https://github.com/tailwindlabs/tailwindcss.com/blob/d782bd97a49374d971fcc8ea010889b1fc605f90/src/components/Button.js#L29

Hope that helps 🤙
