### ISSUE TITLE
Integration tests report success ✔️ while failing

### ISSUE THREAD

**Issue by szepeviktor** [tailwindlabs/tailwindcss#11810]
⚠️ Test could fail while being shiny green.
For example:
https://github.com/tailwindlabs/tailwindcss/actions/runs/5841674349/job/15842065117#step:11:142

The exit status does not change to non-zero.

https://github.com/tailwindlabs/tailwindcss/blob/f9d22f215814e25db64adf1d830d241e16929696/.github/workflows/integration-tests.yml#L94-L98

May be related: https://github.com/vercel/turbo/issues/5454

Discovered in #11808

**Comment by szepeviktor** [comment]
@adamwathan May I investigate? 🕵🏻‍♂️

**Comment by szepeviktor** [comment]
The victoroid solution would be to run test in CI only one and drill down to the root cause.

**Comment by thecrypticace** [comment]
**This is incorrect.** The tests can be a bit flaky because they rely on timing for synchronization. This probably isn't the best solution but it's the one we have that (generally) works. When a test fails all three integration test runs it's almost certainly a definitive failure. But if only one or two out of the three fail it's because of timeouts.

<img width="350" alt="Screenshot 2023-08-14 at 09 38 08" src="https://github.com/tailwindlabs/tailwindcss/assets/614993/2e558156-570c-4ae5-a665-05d1b644fdf5">
