### ISSUE TITLE
Setting default ring color to "inherit" fails.

### ISSUE THREAD

**Issue by acalvino4** [tailwindlabs/tailwindcss#11846]
**What version of Tailwind CSS are you using?**

3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite, but reproduced in tailwind play

**What version of Node.js are you using?**

18

**What browser are you using?**

Brave (Chromium)

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/xqF3SqtvfH

**Describe your issue**

Trying to set the default ring color to "inherit" fails. See tailwind play link.

**Comment by frs99** [comment]
You may need to customize it
You can see here [https://tailwindcss.com/docs/ring-width#customizing-your-theme](https://tailwindcss.com/docs/ring-width#customizing-your-theme)

or [https://tailwindcss.com/docs/adding-base-styles](https://tailwindcss.com/docs/adding-base-styles)

Or explain your problem more because I don't understand

**Comment by reinink** [comment]
Hey! Happy to help out here.

The issue here is that Tailwind currently tries to automatically apply a ring color opacity to the `ringColor.DEFAULT` color. It actually uses the `ringOpacity.DEFAULT` for this.

The problem here is that this doesn't work with the `'inherit'` value, as that's not a real color, so it fails and you end up getting a fallback color.

We're likely going to change this behavior in Tailwind v4 and simply use whatever value you pass to `ringColor.DEFAULT` — which can have an opacity baked into it if you want one.

We actually already have a future flag for this that you can opt into today. You can enable this by adding the following to your `tailwind.config.js` file:

```diff
  /** @type {import('tailwindcss').Config} */
  module.exports = {
+   future: {
+     respectDefaultRingColorOpacity: true,
+   },
    theme: {
      extend: {
        ringColor: {
          DEFAULT: 'inherit',
        },
        // ...
      },
    },
    plugins: [],
  }
```

With that added Tailwind will use the exact value you pass to `ringColor.DEFAULT`, including `'inherit'`, as you can see in this updated Tailwind Play:

https://play.tailwindcss.com/j0WkhCK33M?file=config

Hope that helps! 🤙
