### ISSUE TITLE
Provide hashes for release binaries to ensure the integrity and authenticity

### ISSUE THREAD

**Issue by simonsan** [tailwindlabs/tailwindcss#11888]
Currently, the released binaries are missing hashes. To ensure that what is being downloaded is also what has been built by your pipeline, could you please distribute hashes together with the binaries?

![2023-08-24 07_32_27-Releases · tailwindlabs_tailwindcss — Mozilla Firefox](https://github.com/tailwindlabs/tailwindcss/assets/14062932/6241d945-4f8b-404c-aa50-d60d3cc1a2de)

**Comment by thecrypticace** [comment]
Hey! This is a good idea. I've added the checksums for all v3.3 releases and am working on automating it such that it's automatically published for every future release.

Thanks for the suggestion!

**Comment by thecrypticace** [comment]
I considered that option but ended up doing basically what prometheus does for all their tools which is what you get when you do run this:
```shell
shasum -a 256 ./*
```

You can verify the sums of one or more binaries with a one-liner too:
```shell
echo sha256sums.txt | tr '\n' '\0' | xargs -0 -n1 shasum -c --ignore-missing
```

This one-liner only checks binaries that exist in the current directory and ignores any files that are missing — but it still errors if no checksums were verified because no files were found.

> CI-Snippet
> ```shell
> if [[ ${{ runner.os }} == 'Windows' ]]; then
>   certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
> else
>   shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
> fi
> ```

It'll be a bit more complicated but I'm gonna end up calculating the checksums in Node (that's how I did the above files). Though I did use `shasum` as a verification just to be sure they were correct before pushing them up. Thanks for the snippet!
