### ISSUE TITLE
Stop converting issues to discussions. Issues are issues. 

### ISSUE THREAD

**Issue by pagoru** [tailwindlabs/tailwindcss#11955]

**Comment by reinink** [comment]
Hey! So we get a ton of issues posted that are definitely not issues with the library, but are more end user support issues where folks aren't using the tool correctly, haven't read the documentation properly, or haven't tried reaching out to the community either in the discussions or on Discord for help first.

As much as we'd love to personally help everyone, this puts a significant maintenance burden on our small team. For that reason when we see a new issue posted that looks more like a request for help, or even a feature request, than an actual issue with the library, we convert those to discussions so that the community at large can help out. Often times we also reply to those discussions with a quick answer if we know what the problem is.

We are absolutely not trying to be dismissive, this is simply a method of triaging for real bugs so we can focus on fixing those and avoid getting DDoS'd working through beginner questions.

Hope that makes sense.
