### ISSUE TITLE
line-clamp and first-letter: doesn't work together

### ISSUE THREAD

**Issue by Xeronic** [tailwindlabs/tailwindcss#12030]
**What version of Tailwind CSS are you using?**
v 3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

What tailwind play is using

**What version of Node.js are you using?**

What tailwind play is using

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOS

**Reproduction URL**

https://play.tailwindcss.com/lt8kpsOSYS

**Describe your issue**

When I add `line-clamp` to an element the first-letter utility doesn't work anymore. In the example I am clamping a div and also try to make the first letter red.

**Comment by thecrypticace** [comment]
Hey! So unfortunately this one is working as expected given the limitations of browsers today.

The short version is the `line-clamp-*` utilities today require `display: -webkit-box` which is incompatible (by design) with the `::first-element` pseudo-element.

The longer explanation is a bit dense but I'll give it a go:

We use the `-webkit-line-clamp` property for these utilities internally as that is the only way to achieve this today in CSS (and contrary to the property prefix being `-webkit-` — it's well supported in all browsers). Using this property also requires setting the element to `display: -webkit-box` (basically a much older flex box). [Per the CSS spec](https://drafts.csswg.org/css-pseudo/#first-letter-application), `::first-letter` only works on elements with a display of `block`, `inline-block`, and `flow-root` (collectively called [block containers](https://drafts.csswg.org/css-display-4/#block-container)). This means things like `flex`, `inline-flex`, `grid`, `-webkit-box`, etc… just do not work with it.

In the future we should see a `line-clamp` property in CSS itself which will work directly with block containers. As far as I know it's still in the draft phase so it probably be quite a while before it shows up in browsers.

Sorry, I don't have better news but this one is basically working as is expected today. Hopefully we can change this in the future though when better line-clamping support comes to CSS.
