### ISSUE TITLE
hover:invisible flicker

### ISSUE THREAD

**Issue by christinolb** [tailwindlabs/tailwindcss#12130]
Tailwindcss Version: v3.3.3

Browser: Edge

operating system: Windows

**Reproduction URL**
https://play.tailwindcss.com/314bI1Lp7S

**Expectation**: Hover over button and text goes invisible

**Issue**: When hovering over the button it flickers instead of staying invisible.

**Comment by RobinMalfait** [comment]
Hey!

This is because `invisible` and `visible` use the `visibility` property. This is a side effect of how that property behaves. It's visible, but when you hover it becomes invisible and therefore it is not hovered anymore because it is not drawn, therefore becomes visible again, but then you are hovering and it becomes invisible again. This but very very fast.

You want to use `opacity` instead. This means that you want to use `opacity-0` and `opacity-100` instead. Bonus: you can transition these. https://play.tailwindcss.com/e4IxyoFgjp

Hope this helps!
