### ISSUE TITLE
Tailwind CLI --minify breaks translate utility classes

### ISSUE THREAD

**Issue by abinoda** [tailwindlabs/tailwindcss#12160]
**What version of Tailwind CSS are you using?**

3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Just Tailwind CLI

**What version of Node.js are you using?**

v18.16.0

**What browser are you using?**

Chrome and Safari

**What operating system are you using?**

macOS

**Reproduction URL**

Live demo:  
https://652194c88fddba1fc7db6eb6--lustrous-cactus-773f60.netlify.app

Repository:  
https://github.com/abinoda/tailwindcss-bug

**Describe your issue**

Visit the [live demo](https://652194c88fddba1fc7db6eb6--lustrous-cactus-773f60.netlify.app) in both Chrome and Safari and you'll see that the styling is broken in Safari.

I can resolve the issue by building my CSS _without_ the `--minify` flag, as mentioned in https://github.com/tailwindlabs/tailwindcss/discussions/8788#discussioncomment-4760955.

Full steps to test and reproduce locally are included in the repository I created.

**Comment by adamwathan** [comment]
Hey! I tried your demo and it works fine for me in Safari 15.5:

https://github.com/tailwindlabs/tailwindcss/assets/4323180/f890817c-5a96-4121-a260-af5e29e069ff

I'm guessing you're using a very old Safari, like 14.1 or something. If so this issue is due to cssnano combining the `*, ::before, ::after` and `::backdrop` selectors into one selector, and very old versions of Safari don't support `::backdrop`. That's what appears to be happening for you based on the compiled CSS I see in dev tools on your demo site:

<img width="675" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4323180/744dc005-cf4e-432c-a233-404f5547c40f">

You can make cssnano aware of the browsers you need to support by providing a [Browserslist config](https://browsersl.ist/#q=%22browserslist%22%3A+%5B%0A++%22defaults%2C+safari+%3E%3D+14.1%22%0A%5D).

Add something like this to your `package.json`:

```
  "browserslist": [
    "defaults",
    "safari >= 14.1"
  ]
```

Then when you build and minify, cssnano will make sure it keeps the `::backdrop` selector separate 👍

The `::backdrop` selector was added in Safari 15.4 and we're on Safari 17 now which is why Tailwind/cssnano assume support for it by default.

Hope that's helpful!

**Comment by abinoda** [comment]
@adamwathan Thanks for the response!

Interesting - I'm using Safari v15.2 which seems to be the furthest version macOS Monterey.

I think that I need to upgrade to macOS Sonoma to get to Safari v14.4.
