### ISSUE TITLE
Angular component host (conditional class)

### ISSUE THREAD

**Issue by sream** [tailwindlabs/tailwindcss#12176]
**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Angular v16

**What version of Node.js are you using?**

v18

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

(https://stackblitz.com/edit/stackblitz-starters-cb8u9t)

**Describe your issue**

I'm currently working on a Tailwind based and Angular Material inspired component library. Since one of the optimal ways to develop components and directives inside Angular is the use of classes thru host binding I've expected that Tailwind fully supports them. As you can see from the Stackblitz repro tests 4 and 6 worked where the rest of the tests like the use with decimals or brackets doesn't work ideally most of the time.

Last week I've reported a similar missing support for conditional classes using the Tailwind CSS IntelliSense plugin. If this is also impacted by your decision making I expect at least to have that documented for Angular developers that take this journey since there is no mention how much of the Angular API surface is supported during the installation nor for the IntelliSense plugin.

**Comment by RobinMalfait** [comment]
Hey!

I did some digging, and there are cases where Tailwind is not picking up the values correctly. This happens in 2 spots:

1. The custom html attributes that look like this: `[class.pb-2.5]="fifthTest"`
2. The object keys with special class syntax: `{ '[class.px-2.5]': 'firstTest', }`

One way to solve this is by using a custom [transformer](https://tailwindcss.com/docs/content-configuration#transforming-source-files). This allows you to modify the source code before Tailwind tries to pluck out all the interesting classes.

We can convert the "special" syntax, to a syntax that is more understandable. For example Tailwind can interpret `[class.px-2.5]` as an invalid arbitrary value.

You can introduce the transformer in your `tailwind.config.js` file:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: ['./src/**/*.{html,ts}'],

    // https://tailwindcss.com/docs/content-configuration#transforming-source-files
    transform: {
      DEFAULT: (content) => {
        return (
          content
            // HTML attributes: [class.pb-2.5]="fifthTest"
            .replace(/\[class\.(.*?)\]=/g, 'class="$1" ')
            // Object keys:
            .replace(/(['"])\[class\.(.*?)\]\1:/g, 'class="$2"')
        );
      },
    },
  },
  theme: {
    extend: {},
  },
  plugins: [],
};
```

Now, this does solve the part where Tailwind wasn't generating all the styles. But Angular itself is still spitting out the incorrect classes as mentioned in my previous comment.

I couldn't find a way to escape the classes in a way that it would work.

The good thing is that the special syntax in the HTML file worked, it's the `HostBind` and `host` object that isn't working properly. E.g.: `[class.px-[10px]]` is translated into `px-[10px` (notice the missing closing `]`).

If you know a way to properly generate them than I would love to know how! 

But since this problem in Tailwind is solved with the custom transform I'm going to close this issue for now.

If you can't figure out how to escape them or find a workaround where they are correctly generated, then I would suggest to either use simple classes (without the arbitrary square brackets), or to keep them in your HTML.

Hope this helps!
