### ISSUE TITLE
Tailwind generates redundant CSS 

### ISSUE THREAD

**Issue by enkot** [tailwindlabs/tailwindcss#12328]
**What version of Tailwind CSS are you using?** 

v3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/MG0mxnouJI

**Describe your issue**

Tailwind generates a redundant CSS when using a float value:

<img width="340" alt="Screenshot 2023-10-30 at 23 50 38" src="https://github.com/tailwindlabs/tailwindcss/assets/10506522/938f3b54-122d-411c-8f9c-d46c2f6347ca">

**Comment by thecrypticace** [comment]
Hey! So this is intentional and it's a byproduct of our scanning also handling more than just HTML. For example, Pug uses selectors to generate html elements (certain flavors of Markdown do as well for some things iirc) — and in these cases a list of classes are separated with `.` — just as in CSS.

For example, the following is a valid pug template:
```pug
div.p-1.m-5
  Hello world!
```

Because of this, when we see `p-1.5` we _also_ match `p-1`. This works as designed today. Though, I think we _may_ have some improvements to this in the coming months but can't speak to anything definitive yet.
