### ISSUE TITLE
Problem with after::top negative value

### ISSUE THREAD

**Issue by CodeTorso** [tailwindlabs/tailwindcss#12526]
**What version of Tailwind CSS are you using?**

v3.3.5 (I was just playing with the Tailwind Play CDN)

**What build tool (or framework if it abstracts the build tool) are you using?**

I was just writing my code in simple html file with the Tailwind Play CDN

**What version of Node.js are you using?**

That should not be a question with Play CDN as I was using Live Server

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction Code**
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>I might have found a bug in tailwindCSS</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <nav class="h-16"> 
    <img class="h-full" src="https://picsum.photos/id/237/200/300" alt="random big image">
  </nav>

  <hr class="border-t-[3px] border-double border-gray-900 overflow-visible text-center after:bg-white after:content-['§'] after:px-1 after:relative after:top-[-13px]">
</body>
</html>
```
**Describe your issue**

In hr element's class attribute there is this class called `after:top-[-13px]`  now this code is working the way I want it. I may ask you to run the above code in a browser. The problem appears really when you change the `after:top-[-13px]` to `after:top--3`. The whole code breaks. Image is not inside navbar etc etc. 

It's probably because `after:top--3` is not a valid tailwind class. But then why is rest of my tailwind css not working. Here is the image of `after:top--3` class using the tailwind intellisense.
<img width="300" alt="Screenshot 2023-12-04 005058" src="https://github.com/tailwindlabs/tailwindcss/assets/129188028/c37504e9-5490-4200-9bbc-118020952f06">

**Comment by thecrypticace** [comment]
Hey! So when processing that utility Tailwind CSS v3.3.5 currently crashes when building. Good news is I've already fixed this and we've got a patch release coming out soon (should be later today — time permitting) so this won't crash anymore. The produced selector by intellisense is also a bug that I need to look into but probably related (and likely will fixed by our upcoming patch) as that class shouldn't be considered valid.

The correct way to write this utility is `after:-top-3` — **the negative goes before the utility name**. This works today and doesn't crash: https://play.tailwindcss.com/ZK00mMteax

Also, fyi `-top-3` is `-12px` instead of `-13px` so if that one pixel is important you might want to stick with the arbitrary value.
