### ISSUE TITLE
.browserslistrc not used by tailwinds-cli

### ISSUE THREAD

**Issue by sdavids** [tailwindlabs/tailwindcss#12565]
**What version of Tailwind CSS are you using?**

3.3.6

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwindcss-cli

**What version of Node.js are you using?**

v20.9.0

**What browser are you using?**

N/A

**What operating system are you using?**

N/A

**Reproduction**

```shell
$ mkdir /tmp/test && cd "$_"
$ npm init -y
$ npm i -D tailwindcss lightningcss-cli
$ npx tailwindcss init
$ printf 'defaults' > .browserslistrc
$ printf '@tailwind base;@layer base{html,:host{line-height:1.5;}}' > test.src.css
$ tree  -a -L 1
.
├── .browserslistrc
├── node_modules
├── package-lock.json
├── package.json
├── tailwind.config.js
└── test.src.css
$ npx tailwindcss -c ./tailwind.config.js -i ./test.src.css -o ./test.css
$ npx tailwindcss -c ./tailwind.config.js -i ./test.src.css -o ./test.css.min.tw -m
$ npx lightningcss --minify test.css --browserslist > test.css.min.lcss-bl

$ diff test.css.min.tw test.css.min.lcss-bl
```

**Describe your issue**

lightningcss-cli will split `html,:host`.
tailwindcss-cli does not.

```css
html{line-height:1.5}:host{line-height:1.5}
```

vs.

```css
:host,html{line-height:1.5}
```

The minified output is comparable to the one produced by lightningcss without the `--browserslist` parameter.

I suspect tailwinds-cli does not pass `--browswerslist` correctly.

```shell
$ npx lightningcss --minify test.css > test.css.min.lcss

$ diff test.css.min.tw test.css.min.lcss
```

**Comment by adamwathan** [comment]
Hey! Tailwind respects your browserslist config for vendor prefixing using autoprefixer but we use cssnano for minification which as far as I can tell will not split up selectors when minifying even if your browserslist config indicates that a rule won't be valid for the browsers you support.

So for example Tailwind includes this rule in Preflight:

```css
html, :host {
  /* ... */
}
```

Lightning CSS seems to be smart enough to break this into two rules if you need to support really old browsers like Safari 9, but cssnano (and therefore Tailwind CLI) won't do anything with it — cssnano doesn't really try to "unminify" to satisfy browser requirements, it only considers browser requirements while minifying.

These sorts of transformations aren't really a goal of Tailwind itself, and browser support for `:host` is very good (about on par with CSS variables, which Tailwind also requires in order to work) so I think unfortunately if you are targeting environments that don't support `:host` then the current version of Tailwind might not be a good choice for your project.

Sorry but hope that at least helps clarify what's happening!
