### ISSUE TITLE
`md:col-span-10` overrides `sm:col-start-2`

### ISSUE THREAD

**Issue by tremby** [tailwindlabs/tailwindcss#12713]
**What version of Tailwind CSS are you using?**

v3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**

n/a, can replicate on TW Play

**What version of Node.js are you using?**

n/a

**What browser are you using?**

n/a

**What operating system are you using?**

n/a

**Reproduction URL**

https://play.tailwindcss.com/DX0YS0r320

**Describe your issue**

I expect `sm:col-start-2` to apply to `sm` and above, so including `md`, if I haven't overridden it at a wider range.

But if I also include `md:col-span-10`, it now starts from column 1.

It's happening because they both set the `grid-column` property, and there's no custom properties magic going on to avoid the collisions, unlike transform etc.

I can work around it by also adding `md:col-start-2`.

**Comment by RobinMalfait** [comment]
Hey!

This is currently expected since you are indeed applying classes that happen to work on the same kind of properties and `md:` "wins" form `sm:` related classes.

There are a few options, 
1. The one you mention, is to duplicate `md:col-start-2` to make this one win from `md:col-span-10`
2. Alternatively, you can also change `md:col-span-10` to `md:col-end-12` to get the same effect.

Tailwind Play in action: https://play.tailwindcss.com/NWL9BUtMaA

Right now I don't think this is a bug bug, but it can potentially be improved. For now, I'm going to keep it as is, but if more people run into this then I think we can try to find a solution that could potentially improve the experience. But doing this will require a bunch of testing to make sure that everything keeps working as expected.

Hope this makes sense!

**Comment by adamwathan** [comment]
Another sort of strange solution to this is to use `md:col-end-[span_10]` instead of `md:col-span-10`, which sets `column-end: span 10` and won't override the `column-start` value.

Agree with @RobinMalfait this is sort of unexpected behavior in general and there's probably some clever ideas to improve it — would be a breaking change probably so have to be careful but going to toss it around in my head and see if I can think of anything.

**Comment by janus-reith** [comment]
> For now, I'm going to keep it as is, but if more people run into this then I think we can try to find a solution that could potentially improve the experience

I ran into this 👋

**Comment by fweth** [comment]
I also just ran into this :)

**Comment by fweth** [comment]
I wonder if introducing more granular classes like `col-start-span-<number>` and `col-end-span-<number>` would help without changing the semantics of existing classes?
