### ISSUE TITLE
Shadows get blocked by ring offset (even if ring-offset-transparent is set)

### ISSUE THREAD

**Issue by tcolinpa** [tailwindlabs/tailwindcss#12731]
Reproduction URL: https://play.tailwindcss.com/M36yIyIMVp 

https://github.com/tailwindlabs/tailwindcss/assets/44402590/4b9e3ec7-0f9b-4415-bded-029bd24d184f

I made this bizarre demo just to see better, but if you use the `ring` utility to show focused elements, the ring offset will block the shadow... it doesn't work if I set `focus-visible:ring-offset-transparent` as well.

I guess this could be solved by just inverting the order of the shadow-* utility from

```
box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000);
```

to 

```
box-shadow: var(--tw-shadow), var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000);
```

If this is expected behavior, please ignore :)

**Comment by adamwathan** [comment]
Hey! Yeah so rings are deliberately in front of shadows as they are meant to be a foreground layer for focus rings and stuff, and as you've noticed they block what's behind them because unfortunately CSS has no concept of a `box-shadow-offset`, and rings are built with box shadows. So the `ring-offset` is actually a hack — it's just another solid color ring that covers up part of the other ring to make it appear offset, as long as the ring offset matches the background color behind the element. That's why `ring-4 ring-offset-4 ring-black ring-offset-transparent` looks like an 8px black ring, because the transparent offset reveals the 2x thick ring behind it.

Now that all major browsers support rounded corners on `outline`, I'd just use that instead since it actually does support offsets:

https://play.tailwindcss.com/4F9FU1Fpvw

Nothing we can really change here unfortunately due to limitations in CSS so going to close, but hope that helps!
