### ISSUE TITLE
Incorrect spacing behavior in RTL

### ISSUE THREAD

**Issue by flowmanSF** [tailwindlabs/tailwindcss#12825]
**What version of Tailwind CSS are you using?**

v3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 14.1.0, postcss-cli 8.4.33

**What version of Node.js are you using?**

v21.5.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/FPC3QEXsus

**Describe your issue**

Applying [Space Between](https://tailwindcss.com/docs/space) classes (such as `space-x-4`) to elements on an RTL page results in incorrect spacing behavior.

**Comment by adamwathan** [comment]
Hey! See previous discussion here: https://github.com/tailwindlabs/tailwindcss/issues/5792#issuecomment-944298930

We do plan to change this to use `margin-inline-start` for v4 👍 But currently this is by design as we didn't support logical properties when this feature was introduced, and changing it is a breaking change.
