### ISSUE TITLE
Group hover leaks when applying to SVG defs

### ISSUE THREAD

**Issue by Jonhyfun** [tailwindlabs/tailwindcss#12876]
**Tailwind CSS version:** v3.2.4

**Framework:** Next.js 13.0.0

**Node.js version:** v20.3.0

**Browser:** Chrome, Firefox

**Operating System:** Windows

**Reproduction URL:** https://play.tailwindcss.com/hkfzY1h86v

**Describe your issue**

When using group hover with SVG defs (in my example a `<stop>` inside `<linearGradient>`, but it doesnt work in `<linearGradient>` itself too), the group causes a leak, in which every svg in the page is affected, and only the first hover works.

In my example there are 3 group divs each inside of a different flex container where the behaviour i just explained, happens.

It also breaks if they are on a grid, which was my initial use case that triggered this bug, i just removed the grid in the reproduction to display that the bug is not related to what container the groups are in.

Using [Named Groups](https://tailwindcss.com/docs/hover-focus-and-other-states#differentiating-nested-groups) also results in the same buggy outcome.

**Comment by wongjn** [comment]
Hi! Thank you for your report! The behavior you are experiencing is due to the fact that the `id` of the `<linearGradient>` are considered unique for the webpage. Any subsequent elements specified with the same `id` are ignored. So even though you have `<linearGradient id="linear">` in all three `<svg>` elements, the `<linearGradient id="linear">` from the first `<svg>` is the one referenced and used. Thus when you hover over it, all three `<svg>`s take the styles of the first `<linearGradient id="linear">`.

To better illustrate the point, [here's a modified version of your Tailwind Play](https://play.tailwindcss.com/cQUF7Vt2bd). In the second `<svg>`, you can see that I have modified the `stop-color` attributes of the `<linearGradient>` in the second `<svg>` but you should see that the second `<svg>`'s colors still match the first's. This shows that the `<linearGradient>` in the second `<svg>` is ignored, and the appearance is taken from the `<linearGradient>` in the first `<svg>`.

In the third `<svg>`, the `<linearGradient>` is given a different unique `id` and thus does exhibit the same "leaking" behavior.

**Comment by Jonhyfun** [comment]
Ohh thats right, i forgot about that sorry!

Thanks
