### ISSUE TITLE
No error when non existing class is used in Vue template

### ISSUE THREAD

**Issue by pbrzosko** [tailwindlabs/tailwindcss#12908]
**What version of Tailwind CSS are you using?**

For example: v3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: vite 5.1.1

**What version of Node.js are you using?**

For example: v18.18.0

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-hahtpp?file=src%2Fcomponents%2FHelloWorld.vue

**Describe your issue**

When non existing class name is used inside <style> tag like 'text-xlg' then tailwind throws an error. But when it is used inside <template> tag, there is no error.

**Comment by adamwathan** [comment]
Hey! We don't show any sort of error here because that class could exist in some other CSS file in your project or might be being used purely as a hook for JavaScript, so we have to be very conservative around errors otherwise we could be raising errors in situations where there's actually no error at all.

I'd recommend using our [Prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/) — unknown classes get sorted to the front of the list which is often the only clue you need to realize you've made a mistake 👍
