### ISSUE TITLE
cluttered layout on quick scroll or any update on page

### ISSUE THREAD

**Issue by Raghav-Sao** [tailwindlabs/tailwindcss#13083]
**What version of Tailwind CSS are you using?**
v3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.35 Next.js 14.1.2,

**What version of Node.js are you using?**

v20.2.0

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**
- with tailwind: https://double-rendering-minimal.vercel.app/pcr
- without tailwind: https://double-rendering-minimal.vercel.app/pcr-no-tailwind

- issue recording (as not reproducible on all devices):
https://drive.google.com/file/d/1HhvPlCAwkIPjIyMiewO7BHyATi8RNt1s/view?usp=drive_link

- github link: https://github.com/Smiles-ai/rendering-issue-demo

**Describe your issue**

We are encountering a cluttered layout issue when quickly scrolling or updating the page (however, repetitive elements are not present in the DOM, it's solely a layout issue). We have built the same layout using two screens: one utilizing Next.js + Tailwind CSS and the other using Next.js + normal CSS. The issue only manifests in the repository where Tailwind CSS is used. Additionally, this problem is not reproducible on all devices. I am sharing a screen recording of the issue and device information.
Note: The cluttered layout issue is not limited to the SVG teeth chart; it is randomly occurring on all elements. Additionally, this problem is not confined to this specific page; it is happening on all other pages as well. We are just sharing a sample page link for demonstration purposes.

- Device details:
Device: OnePlus Nord CE2 (IV2201)
Android Version: 13 (Oxygen OS 13)
Screen Size: 6.43 inches
Browser: Chrome 122.0.6261.90
We have attempted to connect the Chrome debugger tool to inspect the mobile code. However, in the DOM, the cluttered layout changes are not reflected. Furthermore, since this issue is limited to very few devices, it is proving to be quite challenging to debug. Additionally, we have tried removing the teeth chart and other elements that frequently exhibit the cluttered layout, but the issue persists in other elements.
<img width="295" alt="Screenshot 2024-03-05 at 7 49 48 AM" src="https://github.com/tailwindlabs/tailwindcss/assets/10258164/d6de3a9d-7658-4665-ad45-91f40d2eae6d">

**Comment by rlidev** [comment]
I have the same problem, after investigating it seems that it has been happening for a few months with the release of 121 and the default use of webgpu.

https://www.linkedin.com/pulse/google-enables-webgpu-default-chrome-121-quad-plexs-jgedf/

After continuing to investigate forums like reddit, they talk about activating vulkan from chrome://flags, it seems that this solves the problem of overlapping divs, but this does not solve the problem from the perspective of a web user, who is going to go to flags to solve this problem? Who knows Vulkan? I guess no one. Then you have to continue investigating what the problem is.

https://www.reddit.com/r/chrome/comments/191cme3/bug_visual_glitch_on_android/

In my case I am using Tailwind and I have noticed that it happens when I use SVG.

Follow these steps to test my solutions that I am still researching:

1 - try to remove the svg and test
2 - instead of removing the svgs, try adding transform-gpu to the svg component class -> class="transform-gpu". In my case it is solved, I don't really understand why, I continue investigating.

https://tailwindcss.com/docs/translate#hardware-acceleration

Any answer is welcome to solve this problem, thank you.

**Comment by Raghav-Sao** [comment]
adding Raghav in loop
With Regards,
Raghavendra Sao

**Comment by KrisBraun** [comment]
Hey! This is definitely a curious one. We've tried and failed to reproduce it, so your recording is quite helpful. 

The visual artifacts and GPU transformation change definitely suggest a browser rendering bug. The role of Tailwind CSS in triggering that bug is mysterious. If anyone can create a minimal reproduction that narrows the change down to a particular CSS property, we could consider a workaround. It may be more productive to raise a browser bug to have the underlying issue diagnosed and fixed.

Thanks for raising this, and feel free to re-open if your investigation reveals details that could be actionable in Tailwind.

**Comment by machour** [comment]
Sorry to comment on a closed issue, but this is simply to thank @Raghav-Sao as I don't feel alone on this universe anymore.

I recently worked on something using tailwindcss, and then had to port my work to a bootstrap5 website. In my port, I copied some of the generated classes from tailwind.

After the whole thing went to production, some users started complaining about the exact same visual glitch reported here, although I haven't had the issue on my OnePlus Nord CE2. 

Affected devices seems to be Redmi & Oppo phones, and again, it's totally random.

**Comment by machour** [comment]
```
svg { transform: matrix(1, 0, 0, 1, 0, 0); }
```
Or 
```
svg { @apply transform-gpu; }
```

This makes chrome render svgs on the GPU and the bug goes away 🎉

I think that they screwed up the last update. 
And when a device is a bit old, or does not have a fast enough CPU, as soon as it struggles to render an SVG the painting bug appears!

All in all, this had nothing to do with tailwind. Thank you @rlidev for the pointers!

PS: dear visitor from the future, you're welcome !

**Comment by KrisBraun** [comment]
We're thrilled you've found a solution! Thanks for tracking it down and sharing.

**Comment by RaghavDoc32** [comment]
i'm travelling this weekend, sure will try and let you know, 
ty for your response :)

**Comment by Raghav-Sao** [comment]
@machour yes its working for me also, tysm :)
