### ISSUE TITLE
[v4] Missing CSS properties in utility classes 

### ISSUE THREAD

**Issue by lubomirblazekcz** [tailwindlabs/tailwindcss#13114]
**What version of Tailwind CSS are you using?**

For example: v4.0.0-alpha.3

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 5.1.5

**What version of Node.js are you using?**

v20

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-iarmom

**Describe your issue**

Firsty let me congratulate you on v4, I really love the changes and the direction to the CSS-native feeling! I've actually had similiar ideas with [winduum.dev](https://winduum.dev), utilizing CSS properties, color-mix etc. via [TailwindCSS plugin](https://github.com/winduum/winduum/blob/main/plugin/index.js)

I just had a quick look at v4 locally and maybe found a bug, but not sure though, could be also inteded.

Currently the CSS properties defined in `@theme` are not used in the utility classes? I would expect it to work this way since the properties are defined in `:root` for usage. Wouldn't they be redundant this way if not used in custom CSS?

So when defining properties like this

```css
@theme {
    --color-primary: blue;
    --color-secondary: red;
    --font-weight-bold: 700;
}
```

I would expect the result be

```css
.text-primary {
    color: var(--color-primary);
}

.text-secondary {
    color: var(--color-secondary);
}

.font-bold {
    font-weight: var(--font-weight-bold);
}
```

This allows more control over the utilities, you could for example change the color if needed from the parent with [--color-primary:red], or on hover etc.

It's possible to define CSS properties in `@theme` now, but you would have to define them in :root elsewhere and that seems redundant.

Also just wondering why introducing the `@theme` at-rule? Wouldn't be better just use the layer theme and properties defined in there under :root or :host? Seems more CSS friendly, also opens possibilities like `@import "custom-theme.css" layer(theme);`

**Comment by KennethHoff** [comment]
I agree. The `@theme` change is a really great change, but considering you're already using cascade layers it would be really cool if that would also be the source of truth. Would be really cool to be add the entire design system with two lines;

```css
@import "Tailwindcss"
@import "@/design.css" layer(theme)

```

**Comment by adamwathan** [comment]
Hey! This is something I've thought about a lot and struggle to form a firm decision on. We've gone with this approach up until now for a few reasons:

1. **Theme values are more like constants than variables** — a class like `mt-px` should always be `margin-top: 1px`. Overriding `--spacing-px` to be anything other than 1px seems like a cursed thing to do. Same for `--color-pink-500`, the color is in the name, it should stay that color.
2. **Performance concerns** — need to measure this of course but in my head, asking the browser to resolve a variable value when we know the value at build-time feels wasteful.
3. **Dev tools experience** — I'm sure it doesn't bother everyone, but I kinda hate when I see a CSS variable in dev tools when trying to debug something because it means I have to dig deeper to get to the bottom of things. Using variables where we don't have to feels like it would be annoying in these situations.

Now I do think it's reasonable to want these to be variables if you are adding a layer of semantically named variables in your project, like `--color-primary` or `--color-button-text`, that sort of thing, but in my head anyways I've expected that the way you'd handle that is by assigning those variables to other variables:

```css
@theme {
  --color-primary: var(--color-primary);
  --color-secondary: var(--color-secondary);
}

:root {
  --color-primary: var(--color-blue-500);
  --color-secondary: var(--color-red-500);
}

[data-theme="candy"] {
  --color-primary: var(--color-pink-400);
  --color-secondary: var(--color-yellow-300);
}
```

It's a little bit odd and possibly unintuitive though if for what you're doing you kind of expect it to just work without doing any of that.

I asked on Twitter to get a sense of what people want here and it's pretty split — about 60/40 against using variables the first time I asked:

https://twitter.com/adamwathan/status/1765496800289415621

...and 70/30 when I asked the same thing with a focus on the dev tools experience:

https://twitter.com/adamwathan/status/1766563488665645535

One possible option is to use the variables but bake-in the bare value as the fallback so you can still see the value in dev tools:

```
.pt-4 {
  padding-top: var(--spacing-4, 1rem);
}
```

...but it doesn't really solve the performance hit (again I need to find a way to measure this to be certain it even matters) or the fact that so many of these variables are actually constants, and being able to override them is just going to cause people to do totally insane things (but maybe who cares, let people do whatever stupid stuff they want as long as it doesn't result in more work for me).

It would also make the compiled CSS meaningfully bigger which is a bummer.

I am still considering this option though, and it's definitely a _lot_ more appealing to me than some sort of configuration option for controlling this behavior which is pretty much a total non-starter for me — _hate_ configuration options.

> Also just wondering why introducing the @theme at-rule? Wouldn't be better just use the layer theme and properties defined in there under :root or :host?

Couple reasons:

1. **Explicitness** — we don't want any variable you define in your whole project to magically make a corresponding utility exist if it happens to use the same naming convention. Feels better for that to be something you do intentionally.
2. **Syntax strictness** — with a custom at-rule like `@theme` we can be strict about what's allowed inside of it, but with `:root` or `:host` people can do anything they want, like put media queries in there, nested selectors, all sorts of stuff, and that's just a lot to consider and figure out how to deal with. I have no idea how this could possibly work for example:

  ```css
  :root {
    & .potato {
      --colors-*: initial;
    }
  }
  ```

  Somehow that would have to make the `bg-red-500` utility stop working when it's inside a `.potato` container.

  So by using something like `@theme` we can say "this can only contain custom property declarations, no rules", kind of like the rules around [`@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#formal_syntax) or other similar at-rules.

**Comment by lubomirblazekcz** [comment]
Thanks for the explanation! And I completely understand, this one will be hard to decide 🤔

The main problem I have with the current approach is that there will be a lot of duplicated variables in result css, the example you provided would result into this.

```css
:root {
  --color-primary: var(--color-blue-500);
  --color-secondary: var(--color-red-500);
}

:root {
 /*....*/
  --color-primary: var(--color-primary);
  --color-secondary: var(--color-secondary);
}
```

And once you have a big project with a lot of variables it will get really big. :/ 

@argyleink actually did a [demo](https://github.com/argyleink/twop/blob/main/app/tailwind.css) using openprops and v4 which is a great example how this approach could be used in practice. And I see the same problem, really a lot of CSS properties and duplications which make the css unnecessarily bigger.

Regarding this

```
.pt-4 {
  padding-top: var(--spacing-4, 1rem);
}
```

That's actually how Figma does it for CSS properties too. But this would make the css bigger, so yeah that would be a bummer. I use to write the variables in Winduum this way and didn't go with it for the same reason.
<img width="294" alt="obrazek" src="https://github.com/tailwindlabs/tailwindcss/assets/6872956/54c12f81-d927-4a56-a88b-67cad9cb6e75">

To be honest, I don't mind if it's not visible in dev tools on first sight. You just have to hover, this is pandacss btw.
<img width="199" alt="obrazek" src="https://github.com/tailwindlabs/tailwindcss/assets/6872956/1357f713-e416-4fb9-a928-4ef068059359">

**Comment by adamwathan** [comment]
Just a follow-up here, we shipped alpha-10 today which includes the variables in the output by default, with the raw value as a fallback like I mentioned:

```css
.pt-4 {
  padding-top: var(--spacing-4, 1rem);
}
```

I did some tests on some real projects and the compressed CSS file actually didn't even change enough to register when rounded to the nearest 1/10th of a kb, so not the issue I thought it might be with the file size 👍 

Definitely like the change overall and how much easier it makes it to theme things, thanks for the nudge to play with it more.

Going to close this as one as resolved since we've shipped this! 🥳
