### ISSUE TITLE
[v4] Not generating styles for a Laravel project

### ISSUE THREAD

**Issue by mokhosh** [tailwindlabs/tailwindcss#13132]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.6

**What build tool (or framework if it abstracts the build tool) are you using?**

vite

**What version of Node.js are you using?**

v20.9.0

**What browser are you using?**

Arc

**What operating system are you using?**

macOS

**Describe your issue**

I'm trying v4 on a Laravel 11 project. I followed the vite installation steps, installed tailwind and the vite plugin, added the plugin to vite config, imported tailwind in my app.css, and it is compiling, but it doesn't pick up any of the classes that I'm using in my views.

Do I have to somehow tell it where my views are?

**Comment by adamwathan** [comment]
I think the issue is that our Vite plugin only really works for full-blown Vite projects, and only sees template files actually served by Vite. Blade templates and stuff don't go through Vite, so our Vite plugin doesn't see them and can't pull out the classes.

Try using our PostCSS plugin with Vite instead of the Vite plugin and see if that works.

**Comment by mokhosh** [comment]
Yup, just tried it and it works with postcss.

Anything we can do to help vite plugin discover blade files?

**Comment by mokhosh** [comment]
@Cnexb shouldn't it be tailwindcss with a c?

**Comment by corneliusio** [comment]
This issue should probably be renamed as it's not necessarily a Laravel specific issue but actually applies to any projects that integrate with a separate, template handling backend. Or to put it another way if you're using something Blade in Laravel or Twig in Craft CMS with a setup similar to what is outlined at https://vitejs.dev/guide/backend-integration.html, your template files will not be part of the Vite dependency graph. 

Based on https://vitejs.dev/guide/backend-integration.html, you'd be forced to use PostCSS (or CLI) to opt into the alternative content detection.

Would be interesting if we could simply pass a flag to the TailwindCSS Vite plugin that would indicate you're using external template files and opt you into the PostCSS/CLI method for content detection.

**Comment by jrmajor** [comment]
Try adding this after importing Tailwind (paths should be relative to your CSS file):

```css
@source "../views/**/*.blade.php";
@source "../../app/View/Components/**/*.php";
```

**Comment by philipp-spiess** [comment]
Like @jrmajor said, we've added support for the `@source` directive to Tailwind CSS V4 so that it's now possible to extend which sources Tailwind will look at when creating the classes. This is our recommended solution for this problem if you still want to use your existing Vite setup to generate the Tailwind CSS file for all templates. By default, the Vite plugin will only look at files that Vite actually transforms. 

Let us know if you run into any issues with this though!
