### ISSUE TITLE
[v4] Inputs, textareas and selects now brings a border by default

### ISSUE THREAD

**Issue by Facug03** [tailwindlabs/tailwindcss#13232]
**What version of Tailwind CSS are you using?**

tailwindcss: 4.0.0-alpha.8
@tailwindcss/vite: 4.0.0-alpha.8

**What build tool (or framework if it abstracts the build tool) are you using?**

vite: 5.1.6
react: 18.2.0

**What version of Node.js are you using?**

v18.17.1

**What browser are you using?**

Edge

**What operating system are you using?**

Windows

**Reproduction URL**

![imagen](https://github.com/tailwindlabs/tailwindcss/assets/107658697/f0ba0263-90d8-40e2-86bb-9a97f67475d1)

**Describe your issue**

Now when you use an input, textarea or select by default has a border and in the previous version wasn't like that

**Comment by adamwathan** [comment]
Hey! Yeah this is an intentional change in our reset — I feel like this is a better default because otherwise `input` elements are completely invisible by default which I think is pretty surprising.

It's also not great for accessibility and we'd rather not be the ones responsible for the borders missing — I'd rather that be a deliberate choice end users make. It's important in forced-colors mode for example to _always_ have a border on inputs (even if it's transparent outside of forced-colors mode), even if you're using a box shadow or something to outline your inputs instead, because box shadows don't render in forced-colors mode.

So with this change, you just need to do this to hide the borders in a forced-colors-accessible way:

```html
<input class="border-transparent" />
```

Whereas previously you'd have to do this, which is hard to understand as a reader ("if there's no border by default, why are they adding one and then making it invisible?"):

```html
<input class="border border-transparent" />
```

At least in the first example it's a bit easier to read it as "ah there's a border by default and they are trying to hide it".

If you want to remove borders by default, I'd just add this to your CSS:

``css
@import "tailwindcss";

@layer base {
  input:where(:not([type='button'], [type='reset'], [type='submit'])),
  select,
  textarea {
    border: 0 solid;
  }
}
```

We'll include this information in the upgrade guide when we are close to a stable release 👍
