### ISSUE TITLE
System fonts at bigger sizes have too narrow line heights

### ISSUE THREAD

**Issue by filiptronicek** [tailwindlabs/tailwindcss#13293]
**What version of Tailwind CSS are you using?**

`v3.4.1`

**What build tool (or framework if it abstracts the build tool) are you using?**

CRA, but can reproduce on the Tailwind playground.

**What browser are you using?**

Applies to Chrome, Safari and Firefox.

**What operating system are you using?**

macOS and Windows.

**Reproduction URL**

https://play.tailwindcss.com/BeWzKMu0aN

**Describe your issue**

When using bigger font sizes, the line height when using the default system fonts on macOS and Windows is not enough for descenders. This can lead to unexpected behavior, such as cropped descenders when using `truncate`.

This issue is present on macOS with `text-5xl` and larger, while on Windows, it happens at text sizes `text-3xl` and larger. The reason for this, as far as I can tell, is the difference in the default font on the platforms, where Segoe UI requires a bigger line height than SF NS. In my case, I was able to fix this issue with using `leading-normal` (`line-height: 1.5`), but I assume there is a good reason it's set to `1` on the larger font sizes and the rem sizes for the smaller ones.

**Comment by adamwathan** [comment]
Hey! Yeah so these values were all chosen based on optimizing how the text looks when it wraps, so situations like this:

<img width="1283" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4323180/d3755937-2154-4758-9064-f033f069616a">

Making the line-height here taller by default would look a lot worse here so it's one of those annoying situations where you have to kind of pick one thing to optimize for, and tweak things for situations where the defaults don't quite work.

When you are using `overflow: hidden` (like with `truncate`) I would personally just increase the line-height for that situation to make it match the height you want the element to be:

https://play.tailwindcss.com/5iSUEaaWIh

No plans to change the defaults here because if we did, then you'd need to override them for different situations anyways so kinda can't win 😕 Hope that helps though!

**Comment by filiptronicek** [comment]
Thank you for the useful insights, it's understandable to not want to change such a core variable of Tailwind's typography. Looking back at it, one could also fix this case with setting a `min-height`, so to not mess with potential multi-line strings.
