### ISSUE TITLE
space-x-4 not working in alpha-10 with Vite plugin and Svelte and Firefox

### ISSUE THREAD

**Issue by danielniccoli** [tailwindlabs/tailwindcss#13310]
**What version of Tailwind CSS are you using?**

@tailwindcss/vite@4.0.0-alpha.10
tailwindcss@4.0.0-alpha.10

**What build tool (or framework if it abstracts the build tool) are you using?**

https://tailwindcss.com/blog/tailwindcss-v4-alpha#using-vite

**What version of Node.js are you using?**

v20.10.0

**What browser are you using?**

Firefox
Edge

**What operating system are you using?**

Windows

**Reproduction URL**

Working example:
![grafik](https://github.com/tailwindlabs/tailwindcss/assets/2971735/dfcb5e13-a834-4d01-9373-b95acfb107be)
https://play.tailwindcss.com/w72rt8GFon

Non-working example (Firefox):
![grafik](https://github.com/tailwindlabs/tailwindcss/assets/2971735/539c8dc8-fd9a-437a-b6ee-ba7e051d474b)
https://github.com/danielniccoli/twcss-alpha10-bug

**Describe your issue**

1. Create a SvelteKit app with `npm create svelte@latest; npm install`
2. Add Tailwind v4-alpha10 as per https://tailwindcss.com/blog/tailwindcss-v4-alpha#using-vite
3. Use the `.space-x-4` class

Check the result. With Firefox, it doesn't display correctly. Edge does, for some reason. However, the working example works in both browsers.

**Comment by adamwathan** [comment]
Hey! This will work in Firefox Nightly but not in the latest stable Firefox because we use `@property` to define our custom properties which won't be in Firefox stable until May:

https://caniuse.com/?search=%40property

Give it a shot there and it should work as expected! We may polyfill this for our stable v4.0 release, will have to see when we get closer to a release date.
