### ISSUE TITLE
[v4]: Border and Outline styles don't work

### ISSUE THREAD

**Issue by cybercoder-naj** [tailwindlabs/tailwindcss#13413]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.11

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite in Nuxt 3.10

**What version of Node.js are you using?**

v21.7.1

**What browser are you using?**

Firefox Developer Edition

**What operating system are you using?**

EndeavourOS (Arch-based Linux)

**Reproduction URL**

```html
<div class="flex justify-center border border-black"> 
Flex, Justify are applied correctly!

Border and border-black do not apply
</div>
```

![image](https://github.com/tailwindlabs/tailwindcss/assets/48282810/1c591952-a5a5-49ef-a943-be53da7c8d93)

**Describe your issue**

When I apply the styles:  `border border-black`, there should be a black border on the element.  I notice that `--tw-border-style` is not defined and `border-black` doesn't seem to be an available class.

**Comment by adamwathan** [comment]
Hey! This will work in Firefox Nightly but not in the latest stable Firefox because we use `@property` to define our custom properties which won't be in Firefox stable until May:

https://caniuse.com/?search=%40property

Give it a shot there and it should work as expected! We may polyfill this for our stable v4.0 release, will have to see when we get closer to a release date.

**Comment by HiggsWRX** [comment]
@adamwathan sorry to highjack this thread but having so many fetures from tailwindcss v4 use property and not providing a polyfill for the release would be a pretty big deal, there's a considerable amount of people who use firefox, and many of them will not upgrade to firefox's latest version as soon as it releases.

I hope providing polyfills is not just a consideration but a big requirement.
