### ISSUE TITLE
Talwind 4 alpha firefox space-x issues

### ISSUE THREAD

**Issue by traderift** [tailwindlabs/tailwindcss#13508]
**What version of Tailwind CSS are you using?**

^4.0.0-alpha.13

**What build tool (or framework if it abstracts the build tool) are you using?**

sveltekit5 

**What version of Node.js are you using?**

For example: v18

**What browser are you using?**

Firefox

**What operating system are you using?**

macOs

**Reproduction URL**

When you add space-x-any or space--y whatever between elements it doesn't give spacing in firefox

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by RobinMalfait** [comment]
Hey! 

Yeah this is known/by design right now — things will work in Firefox Nightly but not in the latest stable Firefox because the stable channel won't support `@property` until May:

https://caniuse.com/?search=%40property

Give it a shot there and it should work as expected! We may polyfill this for our stable v4.0 release, but sort of hoping we don't have to since Firefox is an evergreen browser and we won't be releasing v4 until after Firefox releases support for `@property` anyways.
