### ISSUE TITLE
[v4] "ring" doesn't show in Firefox

### ISSUE THREAD

**Issue by ArekBartnik** [tailwindlabs/tailwindcss#13593]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.14

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwind playground

**What version of Node.js are you using?**

n/a

**What browser are you using?**

Firefox 125, Chrome 124

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/BGx685b0oP

**Describe your issue**

![CleanShot 2024-04-26 at 23 52 56@2x](https://github.com/tailwindlabs/tailwindcss/assets/1569446/444886a4-3a1d-4b7b-a6c7-d3fca2e47855)

**Comment by adamwathan** [comment]
Hey! This will work in Firefox Nightly but not in the latest stable Firefox because we use `@property` to define our custom properties which won't be in Firefox stable until May:

https://caniuse.com/?search=%40property

Give it a shot there and it should work as expected! We may polyfill this for our stable v4.0 release, will have to see when we get closer to a release date.
