### ISSUE TITLE
TailwindCSS is using stderr to log the messages "Rebuilding..." and "Done in [x]ms"

### ISSUE THREAD

**Issue by gc-victor** [tailwindlabs/tailwindcss#13656]
**What version of Tailwind CSS are you using?**

3.4.3 & next

**Describe your issue**

I'm working on a library that executes commands, prints errors on red when there is a stderr, and omits the stdout in case is not used the flag `--verbose`. TailwindCSS is using stderr to log the messages "`Rebuilding...`" and "`Done in [x]ms`", so it is causing a miss communication.

**In the version 3.4.3:**

Looks like this line is the `Rebuilding...`:

https://github.com/tailwindlabs/tailwindcss/blob/f1f419a9ecfcd00a2001ee96ab252739fca47564/src/cli/build/plugin.js#L278

Looks like this line is the `Done in`:

https://github.com/tailwindlabs/tailwindcss/blob/f1f419a9ecfcd00a2001ee96ab252739fca47564/src/cli/build/plugin.js#L364

In both cases there is a previous `console.error()` too.

**In the next version:**

Case 1:
https://github.com/tailwindlabs/tailwindcss/blob/cb17447ff1aadbef482a3daceb5035b7decb6b79/packages/%40tailwindcss-cli/src/commands/build/index.ts#L208

Case 2:
https://github.com/tailwindlabs/tailwindcss/blob/cb17447ff1aadbef482a3daceb5035b7decb6b79/packages/%40tailwindcss-cli/src/commands/build/index.ts#L135

**Comment by toothbrush7777777** [comment]
Note that printing status updates and other diagnostic information to stderr is a common practice endorsed by POSIX, so your library will not work properly with many command line applications. The stderr stream is also not buffered, so that means updates are shown immediately, as required for status updates. See https://unix.stackexchange.com/a/331808 for more details.

**Comment by gc-victor** [comment]
I've addressed this issue by omitting those strings in my program, so it's no longer a problem. However, I believe there's a potential for improvement in how TailwindCSS handles this.

Are they relevant diagnostic information? I don't think so. "Rebuilding..." is shown when the user executes the command, and it has been removed in the next version. "Done in [x]ms" isn't accurate, and you can use `time` instead.

I do think that it could make sense when the `--watch` flag is set.

**Comment by thecrypticace** [comment]
Hi! This is intentional and follows the standard conventions around how CLI tools are built.

[Per the POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html) stderr is **not** strictly for errors. It's meant to be used for any diagnostic output. This includes things like human readable output, user-interactive prompts (several shells do this), information messages, warnings, errors, progress reporting (e.g. this is what curl does). Generally stdout should be used for things you'd want to pipe to either a file or another program.
