### ISSUE TITLE
[v3] Double quotes break arbitrary variants

### ISSUE THREAD

**Issue by GitMazzone** [tailwindlabs/tailwindcss#13737]
**What version of Tailwind CSS are you using?**

v3.4.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Just using Tailwind CLI

**What version of Node.js are you using?**

v18.17.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

[Link to Tailwind Play](https://play.tailwindcss.com/QvJPIRVnqD)

**Describe your issue**

I found that while trying to use an arbitrary selector (to choose a child by role attribute) you **must** use single quotes. Double quotes break the selector.

**Comment by wongjn** [comment]
You *can* use double quotes, as long as you **don't** use double-quotes for the `class` attribute quotes. This is because the browser would see the matching double-quote as closing the attribute value. Alternatively, you can also use no quotes at all. [Tailwind Play examples](https://play.tailwindcss.com/BvBiLrNJNP).
