### ISSUE TITLE
Unable to set default light mode in Vercel portfolio template

### ISSUE THREAD

**Issue by haroonchoudery** [tailwindlabs/tailwindcss#13772]
**What version of Tailwind CSS are you using?**

4.0 alpha

For example: v2.0.4

**What build tool (or framework if it abstracts the build tool) are you using?**

      "dependencies": {
        "@tailwindcss/postcss": "4.0.0-alpha.13",
        "@types/node": "20.11.17",
        "@types/react": "18.2.55",
        "@types/react-dom": "18.2.19",
        "@vercel/analytics": "^1.1.3",
        "@vercel/speed-insights": "^1.0.9",
        "geist": "1.2.2",
        "next": "canary",
        "next-mdx-remote": "^4.4.1",
        "postcss": "^8.4.35",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "sugar-high": "^0.6.0",
        "tailwindcss": "4.0.0-alpha.13",
        "typescript": "5.3.3"

**What version of Node.js are you using?**

 "@types/node": "20.11.17",

**What browser are you using?**
Arc Browser

**What operating system are you using?**

macOS

**Reproduction URL**

haroon.ai

**Describe your issue**

I'm using this Vercel portfolio template (which uses Tailwind 4.0) and I can't figure out how to turn off dark mode by default (i.e. I want light mode by default). 

https://vercel.com/templates/next.js/portfolio-starter-kit

**Comment by wongjn** [comment]
As per the [release blog post](https://tailwindcss.com/blog/tailwindcss-v4-alpha#roadmap-to-v4-0):

> - **Support for other dark modes** — right now we only support dark mode using media queries, and still need to reimplement the selector and variant strategies.

This means that the `dark:*` classes will apply if [`prefers-color-scheme: dark` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) matches, such as if you have your machine set to dark mode in its OS settings. For now, the way to "disable" dark mode would be to remove all the classes in template code that have the `dark:` variant.

**Comment by thecrypticace** [comment]
As @wongjn said, for now v4 only uses media queries for dark mode so it's based on the user's operating system color scheme rather than the presence of a class in the HTML. So you'd want to either:
- Remove the `dark:` classes (if you don't want dark mode at all)
- Override appearance in your browser (if supported — they usually do in at least the dev tools)
- Change the appearance on your OS

**Comment by IonelLupu** [comment]
@thecrypticace none of these are a solution. We don't have the dark mode ready yet, but we have the light mode ready. We want to work on the dark mode one page at a time, without releasing it yet. When we are done, we will activate the theme switcher button.

But, we can't do that because some users will see the dark theme due to their OS settings 🤦

**Comment by thecrypticace** [comment]
A lot has changed this issue was opened. You can override the variant [in your CSS](https://play.tailwindcss.com/jdZkNy3rn5?file=css):

```css
@variant dark (&:where(.dark, .dark *));
```


Additionally, the latest alphas have backwards compatibility for most v3 config file options (including `darkMode`). You'll need to specify the location of the config file in your css like so and we'll load it:
```css
@config "../../../path/to/my/tailwind.config.js"
```

**Comment by IonelLupu** [comment]
@thecrypticace, I am on tailwind v3. How do I set this up in there?

**Comment by thecrypticace** [comment]
@IonelLupu It's covered in the docs: https://tailwindcss.com/docs/dark-mode

```js
/** tailwind.config.js */
module.exports = {
  darkMode: 'selector', // <-- this line in your config
}
```

**Comment by IonelLupu** [comment]
@thecrypticace , yeah. I tried everything from the docs, internet, and forums: classes, configs, CSS, javascript. Nothing works on V3. I guess we need to move to v4.

**Comment by ianJINW** [comment]
I have light and dark modes in my react. The @config and  @variant are unknown

**Comment by bilogic** [comment]
> Additionally, the latest alphas have backwards compatibility for most v3 config file options (including `darkMode`). You'll need to specify the location of the config file in your css like so and we'll load it:
> 
> @config "../../../path/to/my/tailwind.config.js";

@thecrypticace 

Do you know if this is in 4.0.13 released 2 days ago? I added `@config "../../../path/to/my/tailwind.config.js";` into my style.css and it has no effect

```
// tailwind.config.js
module.exports = {
    darkMode: 'selector'
}
```
