### ISSUE TITLE
Compiler Memory Leak when (repeatedly) copying files on Win x64

### ISSUE THREAD

**Issue by aduggleby** [tailwindlabs/tailwindcss#13794]
**What version of Tailwind CSS are you using?**
3.4.3

**What build tool (or framework if it abstracts the build tool) are you using?**
`npx tailwindcss -i` directly via `npm run tailwind`

**What version of Node.js are you using?**
v20.14.0 x64

**What browser are you using?**
N/A 

**What operating system are you using?**
Windows 11 x64 (Fresh Development Image)

**Issue Description**

During development the Tailwind compiler was crashing about every 15min for a specific Visual studio project. The reproduction is based on some of the files from that development project (only CSHTML files). 

When these files are copied (repeatedly) into a directory Tailwind is watching, it causes the node process memory allocation to increase until a out of memory exception occurs.

The reproduction below has worked multiple times without fail with somewhere between 2-5 iterations of copying and then removing the files.

**Reproduction**

Reproduction is on a fresh Windows 11 Development VM (the one available on any Windows Machine with Hyper-V) with no additional software except Node + NPM to rule out any side effects from my own dev system.

- Hyper-V Windows > Create New VM > Windows 11 Development
- Install Node v20.14.0 x64 and NPM
- Copy Files as-is to C:\Test
- Run "npm install"
- Run "npm run tailwind"

Observe memory allocation for node process while repeating these steps:
- Copy all files from "C:\Test\TailwindMemoryIssue\ProblemFiles" to "C:\Test\TailwindMemoryIssue\Pages\InsertProblemFilesHereWhenTailwindIsRunning"
- Delete all files from "C:\Test\TailwindMemoryIssue\Pages\InsertProblemFilesHereWhenTailwindIsRunning"
- And repeat this (for me runaway memory leak usually happens after 3rd time)

**Video of Reproduction**

- https://www.loom.com/share/6f6a4dcd97cc49cead58927332c1f1b2

**Project Files (Zip)**

- without node_modules (requires npm install):
https://e.pcloud.link/publink/show?code=XZo1zTZofpxPU6vCMBNLhROcTm7Nups8HWk

- with node_modules (in case that's relevant): https://e.pcloud.link/publink/show?code=XZvDzTZnkOH1ghBP7H2nfULSqwdJQyYAw37

VM is available on request too (~30GB Hyper-V Image)

**Console Output for Error**
```
<--- Last few GCs --->

[3060:0000025BF067BE40]    93645 ms: Mark-Compact (reduce) 2045.5 (2083.7) -> 2044.7 (2083.9) MB, 1876.40 / 0.00 ms  (average mu = 0.122, current mu = 0.005) allocation failure; scavenge might not succeed
[3060:0000025BF067BE40]    95472 ms: Mark-Compact (reduce) 2045.7 (2083.9) -> 2045.0 (2084.2) MB, 1822.47 / 0.00 ms  (average mu = 0.067, current mu = 0.003) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF77D796CEB node::SetCppgcReference+18123
 2: 00007FF77D708A74 v8::base::CPU::num_virtual_address_bits+90708
 3: 00007FF77E180101 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF77E169858 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF77DFCB2A0 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF77DFC8328 v8::Platform::SystemClockTimeMillis+647176
 7: 00007FF77DFDD63A v8::Platform::SystemClockTimeMillis+733978
 8: 00007FF77DFDDEB7 v8::Platform::SystemClockTimeMillis+736151
 9: 00007FF77DFE6AEE v8::Platform::SystemClockTimeMillis+772046
10: 00007FF77DFF7436 v8::Platform::SystemClockTimeMillis+839958
11: 00007FF77DFFC008 v8::Platform::SystemClockTimeMillis+859368
12: 00007FF77DD7313A v8::base::Thread::StartSynchronously+372186
13: 00007FF77DC908D5 v8::CodeEvent::GetFunctionName+2549
14: 00007FF71E1DAAFA
```

**Misc references**
- Original Gist: https://gist.github.com/aduggleby/909eee25dc8aef66a3bf15e647426aa3
- Original Tweet: https://x.com/alexduggleby/status/1798260194255794686

**Comment by thecrypticace** [comment]
Leaving myself some notes of the investigation so far:

I've been doing a ton of testing in Windows and it seems like this might be a bug with `chokidar`. It causes very high memory usage on Windows when handling a ton of filesystem events on Windows specifically.

It also seems like _something_ doesn't give the GC enough opportunities to cleanup and/or release resources. While it runs, it's usually either not often enough or is unable to free enough memory.

But I can repro this without Tailwind involved by adding the following two files to that repo and running them:

```js
// copy.mjs
import { cp, rm, readdir } from "node:fs/promises";
import path from "node:path";

// Repeatedly copy files into and remove files from directory being watched
while (true) {
  process.stdout.write('.')

  // Copy the ProblemFiles directory to the Pages directory
  await cp("ProblemFiles", "Pages/InsertProblemFilesHereWhenTailwindIsRunning", {
    recursive: true,
    force: true,
  })

  await new Promise((resolve) => setTimeout(resolve, 1000));

  // Remove all files in the Pages directory
  let toRemoveEntries = await readdir("Pages/InsertProblemFilesHereWhenTailwindIsRunning", {
    withFileTypes: true,
  });

  let toRemove = toRemoveEntries.map((entry) => path.join(entry.parentPath, entry.name));

  await Promise.all(toRemove.map((file) => rm(file, { recursive: true })));

  await new Promise((resolve) => setTimeout(resolve, 1000));
}
```

```js
// watch.mjs
import chokidar from "chokidar"

let watcher = chokidar.watch([
  './Pages/**/*.cs',
  './Pages/**/*.js',
  './Pages/**/*.html',
  './Pages/**/*.cshtml',
], {
  usePolling: false,
  atomic: true,
  awaitWriteFinish: {
    stabilityThreshold: 80,
    pollInterval: 10,
  }
})

watcher.on('raw', () => process.stdout.write('R'))
watcher.on('add', () => process.stdout.write('A'))
watcher.on('change', () => process.stdout.write('C'))
watcher.on('unlink', () => process.stdout.write('U'))
```

If you run both of these files simultaneously you'll eventually get an out of memory error. It takes quite a bit _longer_ (couple of minutes) to happen because there's basically nothing going on except listening to file events and writing to stdout. The GC _does_ kick in occasionally too but the OOM error does seem to happen. If you watch in task manager the memory usage will often skyrocket to around 1.5–2GB before dropping again.

If you throw in reading files, parsing, postcss stuff, etc… that can have a decent bit of memory overhead too which makes sense as to why it happens earlier when Tailwind is involved.

**Comment by thecrypticace** [comment]
Also found this existing issue in the Chokidar repo: https://github.com/paulmillr/chokidar/issues/1282

**Comment by thecrypticace** [comment]
So, after some discussion with the team, we're going to close this one as something we're not going to try fixing _in v3_. Partially because the issue is caused by an upstream dependency (chokidar) that we don't have control over and partially because fixing it in v3 would likely take a good bit of development effort, testing, etc…

In the Tailwind CSS v4 CLI we've moved to using `@parcel/watcher` which handles file watching across all platforms much more consistently. I ran a similar test to the above with `@parcel/watcher` and the memory usage is basically constant — even after several thousand file copies.

We discussed potentially switch to `@parcel/watcher` in v3 but that would be a significant change, could come with it's own differences/issues, and would definitely cause some problems with our Standalone CLI build given `@parcel/watcher`'s use of native node modules (`.node` files). Bundling those into the Standalone CLI is currently not possible and it's something we're still investigating for v4.

Not the greatest news (sorry! 😞), but hopefully it helps explain the situation a bit better. Thanks for reporting this — was a fairly interesting one to dig into.

**Comment by xantari** [comment]
Just reporting i'm also getting the same issue... --watch just doesn't work in windows for very long without heap failure.

> npx tailwindcss -i wwwroot/css/app.css -o wwwroot/css/appbundle.css --watch

npm : 
At line:1 char:1
+ npm run buildtailwind-watch
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Rebuilding...

Done in 4646ms.

Rebuilding...

Done in 703ms.

Rebuilding...

Done in 956ms.

Rebuilding...

Done in 835ms.

Rebuilding...

Done in 660ms.

Rebuilding...

Done in 893ms.

Rebuilding...

Done in 1087ms.

Rebuilding...

Done in 1210ms.

Rebuilding...

Done in 1123ms.

Rebuilding...

Done in 1345ms.

Rebuilding...

Done in 7084ms.

Rebuilding...

Done in 5660ms.

Rebuilding...

Done in 49ms.

Rebuilding...

Done in 1945ms.

Rebuilding...

Done in 2551ms.

Rebuilding...

Done in 2410ms.

Rebuilding...

Done in 67858ms.

Rebuilding...

Done in 59848ms.

<--- Last few GCs --->

[27752:00000280ED9F6050]   627111 ms: Mark-Compact 4038.2 (4137.6) -> 4025.6 (4141.1) MB, 1771.80 / 0.00 ms  (average mu = 0.185, current mu = 0.013) allocation failure; scavenge 
might not succeed
[27752:00000280ED9F6050]   630083 ms: Mark-Compact 4041.6 (4141.1) -> 4029.0 (4144.6) MB, 2934.57 / 0.00 ms  (average mu = 0.084, current mu = 0.012) allocation failure; scavenge 
might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF769D472EB node::SetCppgcReference+18123
 2: 00007FF769CB8F04 DSA_meth_get_flags+90724
 3: 00007FF76A730701 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF76A719E58 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF76A57B8A0 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF76A578928 v8::Platform::SystemClockTimeMillis+647176
 7: 00007FF76A58DC3A v8::Platform::SystemClockTimeMillis+733978
 8: 00007FF76A58E4B7 v8::Platform::SystemClockTimeMillis+736151
 9: 00007FF76A59CDAF v8::Platform::SystemClockTimeMillis+795791
10: 00007FF76A25CD05 v8::CodeEvent::GetFunctionName+116773
11: 00007FF70A79AAFA

**Comment by Reactlucky** [comment]
I'm also facing the same issue in react native app

**Comment by xantari** [comment]
> I'm also facing the same issue in react native app

Move to tailwind V4 to solve the issue.
