### ISSUE TITLE
[v4] issue with generating `:root` variables when symbol in css variable

### ISSUE THREAD

**Issue by SandroMaglione** [tailwindlabs/tailwindcss#13973]
**What version of Tailwind CSS are you using?**

`4.0.0-alpha.17`

```json
{
  "name": "repro-issue-tailwindcss-v4-root-vars",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.2.4"
  },
  "devDependencies": {
    "@tailwindcss/postcss": "4.0.0-alpha.17",
    "tailwindcss": "4.0.0-alpha.17",
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18"
  }
}
```

**What build tool (or framework if it abstracts the build tool) are you using?**

`"next": "14.2.4"`

**What version of Node.js are you using?**

`v20.10.0`

**What browser are you using?**

`Brave`

**What operating system are you using?**

`macOS`

**Reproduction URL**

[Repo repository](https://github.com/SandroMaglione/repro-issue-tailwindcss-v4-root-vars)

**Describe your issue**

When a css variable inside `@theme` contains a special character (in the repo the `/` character) the following happens:
- In dev mode (`npm run dev`) everything works as expected
- In production (`npm run build`) the `:root` variables are missing

In the repro the following css causes the `:root` issue after build:
https://github.com/SandroMaglione/repro-issue-tailwindcss-v4-root-vars/blob/f58e8d4da4a328f61183175daa70d24fb7146d60/app/globals.css#L1-L7

In this situation the output contains the following but no definition of the variable `--spacing-24` in `:root`:
```css
@layer utilities {
  .mt-24 {
    margin-top: var(--spacing-24, 24px);
  }
}
```

If instead you escape the `/` character everything works as expected:
```css
@theme {
  --spacing-24: 24px;
  --spacing-1\/2: 50%;
}
```

**Comment by RobinMalfait** [comment]
Hey!

The problem here is that `--spacing-1/2` is not a valid CSS custom property (syntax wise), which means that you won't be able to set the variable, update the variable via JS or read from the variable. We could magically escape `--spacing-1/2` and generate `--spacing-1\/2`, but then wherever you use it, you still have to use `--spacing-1\/2` anyway which would cause even more confusion I think.

When you mention that it works in dev mode, it only works in the sense that it generates the variable, but that's about it.

Instead, I would recommend to either use the escaped syntax, or use another character. Internally we already had to do something like that for `0.5` values. For this we use `--spacing-0_5` ourselves.

That said, depending on where you use this value, fractional values work in some utilities automatically already. For example `aspect-123/456` or `w-123/456` already work without a custom value in your `@theme`.

Going to close this for now since it's out of our control without introducing magic conventions. If more people run into it we can reconsider how we tackle this.

Hope this helps!

**Comment by SandroMaglione** [comment]
@RobinMalfait would it be possible to catch this issue when generating the final css file with tailwindcss (and possibly any syntax error in general)?

Debugging this issue took some time because on dev everything works correctly. If someone does a similar mistake, it would be problematic since all the builds are successful but ultimately "wrong".

Any ideas?
