### ISSUE TITLE
[v4] @source directive is included in the generated CSS

### ISSUE THREAD

**Issue by phenomen** [tailwindlabs/tailwindcss#14142]
**What version of Tailwind CSS are you using?**

`4.0.0-alpha.18`

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite `5.3.5`

**What version of Node.js are you using?**

Bun `1.1.21`

**Reproduction URL**

https://play.tailwindcss.com/wBAMLvsEJZ?size=1874x1117

**Describe your issue**

In the reproduction generated CSS you can see `@source "../templates/**/*.hbs";` even though it should have been purged.

**Comment by RobinMalfait** [comment]
Hey!

The reason it's not removed is because the `@source` feature has not been released yet, and we don't remove CSS we don't own.

Once we release it, it will be removed from the output CSS.

Some small notes:
- Your CSS is invalid, and the `@source` should end with a `;`
- The `@source` won't work in Tailwind Play (but we will still remove it from the CSS 👍)


Hope this helps!
