### ISSUE TITLE
Using rem values instead of px makes xs class override larger breakpoints

### ISSUE THREAD

**Issue by Burtonium** [tailwindlabs/tailwindcss#14204]
**What version of Tailwind CSS are you using?**

For example: v3.4.10

**Reproduction URL**

https://play.tailwindcss.com/CAY0v1N8oa

**Describe your issue**

Using something like "xs:hidden md:block" will stay hidden at the md: size for some reason when using rem values but not when using px.

```
module.exports = {
  theme: {
    extend: {
      screens: {
        xs: '32rem',
        sm: '48rem',
        md: '75rem',
        lg: '92rem',
        xl: '112rem',
      },
    },
  },
}


```

**Comment by adamwathan** [comment]
Hey! So what's happening here is you are extending the default breakpoints but not replacing all of them (you aren't overriding the `2xl` breakpoint), and since the default breakpoints are defined in `px`, your final set of breakpoints have mixed units.

If Tailwind detects that your set of breakpoints don't have consistent units, it assumes you have put them in a specific order yourself on purpose and doesn't try to sort your breakpoints from smallest to largest.

Now because all of your breakpoint names do match default breakpoints except for `xs`, those breakpoints end up in the spot in the object that they were already (just how JavaScript orders object keys), so your final breakpoint config looks like this:
```
screens: {
  // Default breakpoints you've replaced
  sm: '48rem',
  md: '75rem',
  lg: '92rem',
  xl: '112rem',

  // Default breakpoint that's still there because you didn't replace it
  '2xl': '1536px',

  // New breakpoint that didn't already exist as a key in the list
  xs: '32rem',
},
```

Because of the presence of the `2xl` breakpoint, Tailwind doesn't sort them for you, and your `xs` breakpoint ends up taking over.

Two solutions for you:

1. **Don't use `extend`** — if you just replace the `screens` configuration, the `2xl` breakpoint won't exist and everything will sort correctly:

    https://play.tailwindcss.com/T1GMFrQXTl

2. **Add a `2xl` breakpoint of your own** — if you replace this one as well, all of the units will be the same so things will sort:

    https://play.tailwindcss.com/0Qcw6lBoS8

My guess is option 1 is the option that makes the most sense for you, since I don't think you actually want the default `2xl` breakpoint in your project 👍
