### ISSUE TITLE
Getting a stringified JS function in the CSS output with `matchUtilities` and `type: 'color'`

### ISSUE THREAD

**Issue by benface** [tailwindlabs/tailwindcss#14218]
**What version of Tailwind CSS are you using?**

v3.4.10

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

Tailwind Play

**What browser are you using?**

All

**What operating system are you using?**

All

**Reproduction URL**

https://play.tailwindcss.com/1OtR3kLe72?file=config

**Describe your issue**

I am writing a custom plugin that generates color utilities, and I want it to support opacity modifiers like the core color plugins do. I found [this nice answer on how to do that](https://github.com/tailwindlabs/tailwindcss/discussions/12337#discussioncomment-7445342), but unfortunately I ran into an issue when combining it with [the trick to define colors with CSS variables](https://tailwindcss.com/docs/customizing-colors#using-css-variables). As you can see, the rule generated for `fade-red/50` looks as expected, but the `fade-red` class with no modifier generates this weird CSS:

```css
.fade-red {
  --foo: ({opacityValue:e=1})=>t.replace(/<alpha-value>/g,e);
}
```

Thanks in advance!

**Comment by adamwathan** [comment]
Hey! Yeah so what you're seeing is that any color defined with `<alpha-value>` is converted to a function internally so it can receive the alpha value to fill in that slot with. Internally we use this `toColorValue` helper for everything that uses colors that invokes those functions with a value of `1`:

https://github.com/tailwindlabs/tailwindcss/blob/main/src/corePlugins.js#L2000

You could import that function into your own plugin like people often do with `flattenColorPalette` (even though neither are really officially public API), but I think honestly the better solution is just don't use `<alpha-value>` — if you just put `1` there instead everything still works:

https://play.tailwindcss.com/Yf1hptaNv5?file=config

We realized this after we already did all the `<alpha-value>` crap — as long as our color parser can infer which piece is the alpha value, you don't actually need the placeholder.

Should just remove that from the documentation altogether at this point, I don't think it's actually needed at all.

In v4 since we use `color-mix` for this stuff, this whole class of problem just disappears thank god!

**Comment by benface** [comment]
Awesome, I will be using `/ 1`. Thanks @adamwathan! 🙏

**Comment by adamwathan** [comment]
If you run into a situation where for some reason that doesn’t work let me know!
