### ISSUE TITLE
3.4.10 - Warning regarding node_modules in pattern persist for skeleton theme (svelte)

### ISSUE THREAD

**Issue by Mellowchan** [tailwindlabs/tailwindcss#14367]
Hello, I've setup sveltekit project with skeleton theme according to official guidelines which includes tailwind.config.js setup too:  https://next.skeleton.dev/docs/get-started/installation/sveltekit

Since recent versions of talwindcss I get this warning:
```
warn - Your `content` configuration includes a pattern which looks like it's accidentally matching all of `node_modules` and can cause serious performance issues.
warn - Pattern: `../**/*.ts`
warn - See our documentation for recommendations:
warn - https://tailwindcss.com/docs/content-configuration#pattern-recommendations
```

Besides this warning, everything works great. I don't know what I did wrong since the glob pattern is included in the official guidelines.

The relevant lines in tailwind.config.js to this warning look like this:
```
export default {
	darkMode: 'selector',
	content: [
                './src/**/*.{html,js,svelte,ts}',
                join(require.resolve('@skeletonlabs/skeleton-svelte'), '../**/*.{html,js,svelte,ts}')
        ],
	theme: {
		extend: {
			colors: Object.keys(myproject_theme.properties).reduce((acc, k) => {
				if (k.startsWith('--on-')) {
					const color = k.substring('--on-'.length);
					acc[color] = `rgb(var(--color-${color}-500) / <alpha-value>)`;
				}
				return acc;
			}, {})
		}
	},
	plugins: [
		forms,
		skeleton({
			themes: {
				custom: [myproject_theme]
			}
		})
	]
}; // satisfies Config

```

My project folder structure is like this:
```
.git/
.svelte-kit/
node_modules/
src/
static/
.gitignore
.npmrc
.prettierignore
.prettierrc
README.md
jsconfig.json
package.json
package-lock.json
postcss.config.cjs
svelte.config.js
tailwind.config.js
vite.config.js
```

**What version of Tailwind CSS are you using?**

3.4.10

**What version of Node.js are you using?**

v20.15.1

**What operating system are you using?**

Linux (NixOS 24.11)

**Comment by philipp-spiess** [comment]
Hey @Mellowchan. We added this rule because in our experience, whenever a glob like this matches over the `node_modules` folder, it's going to slow builds down dramatically and it's almost never what people want.

`join(require.resolve('@skeletonlabs/skeleton-svelte'), '../**/*.{html,js,svelte,ts}')` does look like it might match more than expected here too. It will look over _all_ files within the installed `@skeletonlabs/skeleton-svelte` npm package which contains all the dependencies of this package inside `node_modules/@skeletonlabs/skeleton-svelte/node_module`. 

Looking at the [contents of this package](https://www.npmjs.com/package/@skeletonlabs/skeleton-svelte/v/1.0.0-next.7?activeTab=code), there's already a `dist/` folder so maybe you only want to scan files within that `dist/` folder like this:

```ts
join(require.resolve('@skeletonlabs/skeleton-svelte'), '../dist/**/*.{html,js,svelte,ts}')
```

I recommend you reach out to the authors to clarify exactly where the templates files are located. If they indeed want to scan inside the `node_modules`, we recommend adding each package as a rule separately, so that in the future if another package is added, it's not going to be scanned. 

I don't think this is a bug in Tailwindcss and the warning is justified, so I’m going to close this issue but feel free to reopen if you run into any issues.

**Comment by Akkuma** [comment]
The warning still seems to be overly aggressive. I have an absolute path being created that looks like `"/Users/[user]/git/[project]/packages/web/node_modules/[specific_package]/**/*.tsx"`. This isn't  "accidentally matching all of `node_modules`". This is matching a specific package in the node_modules.
