### ISSUE TITLE
[v4] Theme and apply functions do not work inside CSS Modules

### ISSUE THREAD

**Issue by boylett** [tailwindlabs/tailwindcss#14390]
**What version of Tailwind CSS are you using?**
4.0.0-alpha.23

**What build tool (or framework if it abstracts the build tool) are you using?**
Vite + Remix

**What version of Node.js are you using?**
22.4.1

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS Sonoma 14.6.1

**Reproduction URL**
[https://github.com/boylett/tailwind-v4-theme-in-css-modules-demo](https://github.com/boylett/tailwind-v4-theme-in-css-modules-demo)

**Describe your issue**
The `theme()` and `apply()` functions do not work correctly when used within [CSS Modules](https://github.com/css-modules/css-modules).

The repro demonstrates that `theme` does not find the breakpoint variable, and if you add the following it also demonstrates that `apply` cannot resolve values from the theme config:

Add to `root.css`:
```css
body {
  @apply text-2xl;
}
```
(demonstrates that basic CSS files can import variables)

Add to `index.module.css`:
```css
.test {
  @apply text-2xl;
}
```
(demonstrates that CSS Modules cannot import variables)

**Comment by philipp-spiess** [comment]
Hey! This is because the CSS Module file does not implement a Tailwind theme so the `@apply` method can not resolve the size `2xl`.

This is the same issue as https://github.com/tailwindlabs/tailwindcss/issues/14211 and https://github.com/tailwindlabs/tailwindcss/issues/14020#issuecomment-2340332805, so please check out my response there for how to fix this. I’m going to mark this one as duplicate so we don't track the same problem multiple times, thanks for the report, though!
