### ISSUE TITLE
max-breakpoint:class not working when raw screen setup present in tailwind config

### ISSUE THREAD

**Issue by SebastianMarzecCodewise** [tailwindlabs/tailwindcss#14429]
**What version of Tailwind CSS are you using?**

v3.4.10

**Reproduction URL**

https://play.tailwindcss.com/rHaI81WQuv

**Describe your issue**

In example above class `max-lg:hidden` is not working, but of course none of max:breakpoint classes works when I have custom media-query with `raw` setup in tailwind config.
If you'll remove this line (in tailwind play/config): 
`'shortdesktop': { 'raw': '(max-height: 950px) and (min-width: 768px)' },`
it works again

**Comment by adamwathan** [comment]
Hey! This is by design at the moment — it's critical that all breakpoint variants are sorted in a particular order and when you introduce complex custom breakpoints that becomes sort of impossible for us to do intelligently, so we don't support the `max-*` or `min-*` variants when you've customized your config in that way:

https://github.com/tailwindlabs/tailwindcss/pull/9558#user-content-restrictions

Hope that helps! We should probably mention this in the documentation because it comes up often.
