### ISSUE TITLE
Build performance with custom classes in @layer is much slower than without

### ISSUE THREAD

**Issue by joshdavies14** [tailwindlabs/tailwindcss#14454]
Tailwind CSS v3.4.10, vite v4.4.0, Vue v3.4.15, Node v18.19.1.

We have a large Vue SPA project that we build with Vite and use Tailwind as our main framework throughout, and make use of a small number of custom classes with the `@apply` directive, contained within an `@layer` group in our SCSS files (that are transformed by vite upon build). We also define colours using CSS variables in the same way as [outlined in the docs](https://tailwindcss.com/docs/customizing-colors#using-css-variables) (which uses another `@layer` group).

In the past few months we have noticed our initial load times when first starting the app going >20s, sometimes with requests failing and needing to refresh to load in, and hot reload taking up to 10s sometimes to load our changes. Changes were made to our Vite config with no improvement.

One of my colleagues recently ran a CPU profile across the build process in dev, and we spotted that `expandTailwindAtRules` was taking close to 10s, sometimes more, and clearly being the bottleneck in our build process. I expect our build to not be super quick due to the size but this one function is much slower than I would expect!

<img width="772" alt="Screenshot_2024-09-18_at_12 06 30" src="https://github.com/user-attachments/assets/24190e8c-95dd-4eb3-b86e-a902e4cfc51a">

To test this case, I removed the `@layer` groupings from these classes and restarted the dev process, and both myself and my colleague noticed clear speed differences in the dev build process.

is there anything that can be done to improve the performance of builds here? It makes day-to-day development much slower than it needs to be.

**Comment by joshdavies14** [comment]
Hey @RobinMalfait - thanks for the reply! I've got a minimal reproduction repo for you linked below.

When I was playing with this I started with our `tailwind.config.js` file (which has more in it than the one in the repo) and worked backwards, and observed that deleting the safe list reduced the times back to normal in this repo - not sure if that is linked/the cause here?

https://github.com/joshdavies14/tailwind-build-repro

**Comment by RobinMalfait** [comment]
Hey!

So the issue is with the safelist pattern. You are essentially generating ~5mb of CSS or in other words, around ~50 000 utilities. If you look at this pattern: 

https://github.com/joshdavies14/tailwind-build-repro/blob/a37ce8b363cd490a068a9521f4446ce349afd5d1/tailwind.config.js#L35

my assumption is that you want all the width related utilities. But the way regex works is that it matches even if it exists inside any of the string.

In your case, `shadow-red-500` also contains `w-`. So this is generation all shadow colors for example.

If you want width utilities, you can apply the following change:
```diff
diff --git a/tailwind.config.js b/tailwind.config.js
index 2edbc63..f0f3795 100644
--- a/tailwind.config.js
+++ b/tailwind.config.js
@@ -26,13 +26,13 @@ module.exports = {
     },
     safelist: [
         {
-            pattern: /max-w-*/,
+            pattern: /^max-w-*/,
             variants: ['sm', 'md', 'lg'],
         },
         'h-screen',
         'min-h-screen',
         {
-            pattern: /w-*/,
+            pattern: /^w-*/,
             variants: ['sm', 'md', 'lg'],
         }
     ],
```
These regexes only match classes that start with the `max-w-*` and `w-*` part. This means that the CSS will only be a ~24 kb file, or around ~600 utilities instead of ~50 000.

Hope this helps!

**Comment by joshdavies14** [comment]
Sorry for not replying earlier (been a hectic few weeks)) but thanks so much for this - silly regex strikes again for me! This was the cause and making your suggested change drastically improved our build times (not just dev builds but also production ones too) :)
