### ISSUE TITLE
[Feature Proposal] CSS class override utility for component composition.

### ISSUE THREAD

**Issue by harryhorton** [tailwindlabs/tailwindcss#1446]
First, ❤️ Tailwind!!!

## Problem
Working within the scope of a large FE application (my use case is React with hundreds of components), it's common to create styled components that are composable. Reading through the doc notes on composability, the standard answer seems to be to split the utilities that COULD change into their own classes (or in our case, components that would merge the class list with the base).

While that seems like it could work, in our situation, splitting things up this way doesn't feel reliable as we often receive adjustments to styles that can wildly change the look of a component that we're composing off of. It would result in having a lot of base components with next to no utility classes, and a lot of additional utilities on a hierarchy of composing components that feels like it would be difficult to manage. Additionally, if render functions or props were used to override all of the classes, then a developer would easily loose track of duplicate utilities across compositions, where they should have been simply extending the base.

It's possible to work within the limitations of the current recommendation, but, after testing, I don't expect this to be a good developer experience at scale.

## Possible solution
Create a JS utility that can merge utility classes based on what can be overriden.

This would allow developers to write base common styles on a usable component, while easily using component composition to override only the utilties that they wish to change.

`tailwindMerge('bg-gray-500 p-4 mb-3', 'bg-blue-500 pr-2 mb-4')  =>  'p-4 bg-blue-500 pr-2 mb-3' `

### React
```javascript
const BaseButton = ({ className, ...props }) => (
  <button className={tailwindMerge('bg-blue-700 px-3 py-1', className)} {...props} />
);

const SpecialButton = ({ className, ...props }) => (
  <BaseButton className={tailwindMerge('bg-green-700 px-5 py-2 text-lg', className)} {...props} />
);
```

 This would also work with other front-end frameworks.

## Additional considerations.
- Since developers can add custom utilities, it would be helpful if there was an override group configuration option in the tailwind config.

**Comment by benface** [comment]
I would very much like to see something like this. I'm not sure if it makes sense for it to be part of the main codebase though.

**Comment by Johnhhorton** [comment]
Probably doesn't make sense in the main codebase, but I wanted to raise the issue here to get more feedback. I tried my hand at understanding the tailwind full config and developing something for this. It turned out to be a lot more complicated than I was initially expecting. I'm happy to do the work and create an NPM module for it, but I'll definitely need some guidance on how to get the full computed config via JavaScript and how to get the class string groups and match them with config groupings to do the merge.

**Comment by adamwathan** [comment]
This is a pretty complex problem and probably out of scope for Tailwind itself unfortunately.

> how to get the full computed config via JavaScript and how to get the class string groups and match them with config groupings to do the merge.

^ This of course is the really hard part and I can't even provide guidance on a good approach for doing it :/

One day I'd like to explore a proper CSS-in-JS flavor of Tailwind that would handle stuff like this better but I'm going to close this for now as a "not working on this any time soon" sort of thing unfortunately. If you do end up hacking on it as a separate project I'd love to see how it goes 👍

**Comment by SeanRoberts** [comment]
I created a really simple and naive helper for this but there are a number of utilities it doesn't work with at all.  The approach is to simply split each classname by the final instance of `-` and then rebuild based on the last value of each class with those prefixes.  Where it falls apart is on utilities like `border` and `text` where multiple utilities share the same prefix (e.g. `text-red-500 text-xl`)

The proper solution would be to iterate over each classname, figure out which utility it belonged to, and then make sure each utility only has one value.  However, like @harryhorton I have no idea how to actually begin doing that.  The only other alternative would be to tweak your own tailwind config so that no two utilities have the same prefix (e.g. replace `text` with `text-color` and `text-size`)

Anyway, here's the little helper I created, it is still useful as long as you only stick to utilities that don't share prefixes, but it's probably just as likely to drive you insane when you can't figure out why you can't set text size and text colour at the same time.  Again, just to be clear to anyone who stumbles into this issue: **This snippet not a good solution!  Don't start using it without understanding why it will probably break your code**

```
import cx from 'classnames';
import { ClassValue } from 'classnames/types';

/*
  Wrapper around the classnames library that makes later instances of any
  Tailwind utility classes take precedence.  e.g.:

  twcx('text-18 text-14 p-0') returns 'text-14 p-0'
  twcx('p-0', { 'p-1: true }) will return 'p-1'
*/

export default function twcx(...classes: ClassValue[]) {
  const classlist = cx(...classes).split(' ');
  const result = classlist.reduce((result, c) => {
    const prefix = c.substring(0, c.lastIndexOf('-') + 1 || c.length);
    return { ...result, [prefix]: c };
  }, {});

  return Object.values(result).join(' ');
}
```

**Comment by harryhorton** [comment]
@SeanRoberts looks cool! Thanks for sharing! I tried creating utilities too, but there was complicated to try to cover all the use cases.

I ended up using https://github.com/ben-rogerson/twin.macro

Not as good for minimal css, but great for the kind of flexibility I needed. By compiling to CSS, you can do simple overrides and easily use tailwind classes via props.

I start with classes only, and move to twin macro when I need more flexibility.

**Comment by SeanRoberts** [comment]
@harryhorton Oh cool, I hadn't heard of this before!  What approach do you use for the problem we're talking about in this issue?  Does it just handle merging classnames automatically?  If you do `<div className={tw`p-0 p-2`} />` does that just take care of it?  If so this seems like a perfect solution.

**Comment by harryhorton** [comment]
@SeanRoberts My preferred approach looks like this:

If I'm not doing anything programmatic with tailwind classes

```tsx
 const Thing: FC = ()=>(<div className="bg-red-500" />)
```

If I have ANY conditional logic, I'll take this approach:

```tsx
import tw from "twin.macro";
import { ButtonProps } from "./types";
import styled from "styled-components";

export const StyledButton = styled.button<ButtonProps>(
  ({ flat, fullWidth, small, text, disabled }) => [
    tw`text-white rounded px-6 py-2 bg-blue-600 shadow`,
    fullWidth && tw`w-full`,
    small && tw`text-sm px-5 py-1`,
    flat && tw`bg-transparent shadow-none`,
    text && tw`p-0 bg-transparent shadow-none`,
    disabled && tw`opacity-75`,
  ]
);
```

Passing values like nubmers or colors  is a little wonky as I'm pretty sure twin-macro will complain if anything but a complete tailwind class is output, but I haven't had to do that yet.

One of the benefits of this approach is that it makes it easy to mix with regular CSS using styled components. With overrides, anything that comes after will override the first just like css (because that's what it copiles to).

Another benefit is that you can use Styled components to compose styles together using tailwind. Something you can't easily do with just classes and requires overrides.

Hope that helps!

**Comment by SeanRoberts** [comment]
@harryhorton Awesome, thanks for sharing!  Hopefully at some point we'll have the tools to be able to just merge the classNames rather than having to generate more CSS with a macro but this definitely solves the problem for me and probably anyone else who finds this issue in the meantime.

**Comment by simonswiss** [comment]
Reopening this and moving to discussions 👍
