### ISSUE TITLE
Responsive classes do not work

### ISSUE THREAD

**Issue by fcrozatier** [tailwindlabs/tailwindcss#14598]
Tailwind v4-alpha.26
Svelte v5-alpha.262
Node v22
Chrome v129 
macOS

repo: https://github.com/fcrozatier/tailwind-media-modifiers

**Issue**

the responsive modifiers `sm:*`, `md:*` do not work with custom classes, like `sm:[.btn-sm] md:[.btn-md]`

reproduction: `pnpm i`, `pnpm dev`, resize window. Modify layers and classes in `src/app.css`, `src/routes/+page.svelte` and `src/routes/Component.svelte`

**Comment by philipp-spiess** [comment]
Hey there! `btn-sm` and `btn-md` in your example are just plain CSS classes because Tailwind CSS v4 does not have the concept of components anymore (The `@layer components` just puts it into a different [CSS layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer))

What you want to do in your case is create custom utilities for these. Something like this should work:

```css
@import "tailwindcss";

 @utility btn-sm {
   @apply padding-1 bg-indigo-500 text-grey-700
 }
```

Utilities can be combined with variants like so:

```
sm:btn-sm
```

Regarding the other comment in your repro about Svelte: We haven't decided on the best way to add support for processing Tailwind CSS inside `<style>` block in Svelte components so we'd definitely recommend putting this into `src/app.css` for now (we have another issue for this if you want to track it: https://github.com/tailwindlabs/tailwindcss/issues/13305

Going to mark this as finished since it's working as expected. We're currently working on a v3->v4 upgrade tool that will rewrite `@layer components` rules to utilities which should avoid confusion in the future. Plus we're still owing you all a bunch of docs for v4 😬. Thanks for early-adopting it though! Feel free to reopen/ping me if you have other quesitons.

**Comment by fcrozatier** [comment]
This is great, thank you!

Related to the fact that we only have the `utilities` layer now, I'm considering opening an issue about #14551  

Maybe having another layer for plugins would be good to allow both having custom CSS defaults and overriding them with utilities

Please let me know if I should go ahead and open another issue for this or whether I'm missing something and there already is a solution

Thanks again!
