### ISSUE TITLE
[V4]: Custom keyframes in `@theme` won't apply correctly

### ISSUE THREAD

**Issue by Matheun** [tailwindlabs/tailwindcss#14622]
For some reason, the custom keyframes in my theme config wont correctly apply in my component layer. i'm using scss files

**Comment by philipp-spiess** [comment]
@Matheun Do you mind sharing a quick repro, maybe via https://play.tailwindcss.com/? :)

**Comment by Matheun** [comment]
@philipp-spiess Used this for older issues, so some comments might be left from that, but the code is correctly updated

https://github.com/Matheun/tailwind-v4-case-3

**Comment by philipp-spiess** [comment]
@Matheun Thanks! I was taking a quick look.

The problem here is that `@keyframes` inside `@theme` are only emitted if there's also a `--animate` theme variable that uses it. If I add that to your example, it works like expected: https://play.tailwindcss.com/8IZctruIOO?file=css

If you want `@keyframes` to be added unconditionally, you can put it outside the `@theme` 🙂

**Comment by Matheun** [comment]
Ah, thank you.

Do you have an update on the HMR issue? it was supposed to be fixed in alpha 26, but i still need to double layer my files

**Comment by philipp-spiess** [comment]
@Matheun Not yet. I have been knee deep in compat work and built up a bit of a backlog for things to follow up which includes this issue. Sorry about that!

**Comment by Matheun** [comment]
No worries, happy to hear its still on your radar
