### ISSUE TITLE
Using tailwind classes in your own css style selectors breaks @keyframe that include @apply

### ISSUE THREAD

**Issue by neochief** [tailwindlabs/tailwindcss#14660]
Hi!

When you override the tailwind classes, as shown in the bottom, AND have these classes as part of the @apply in the keyframes, the resulting code after the build is broken CSS.

SOURCE:
```
.some-custom-class .text-white {
    /* ... */
}

@keyframes text-color {
    from {
        @apply text-black;
    }
    to {
        @apply text-white;
    }
}
```

BUILT:
```
@keyframes text-color {
    from {
        --tw-text-opacity: 1;
        color: rgb(0 0 0 / var(--tw-text-opacity));
    }
    to {
        --tw-text-opacity: 1;
        color: rgb(255 255 255 / var(--tw-text-opacity));
    }

.some-custom-class to {
}

}
```

As you see, the `.some-custom-class to { ... }` is inserted inside the @keyframes definition, which is unexpected.

**Comment by adamwathan** [comment]
Hey! Two things here — first thing is that you've extended the behavior of `text-white` and effectively redefined it as this:

```css
.text-white {
  --tw-text-opacity: 1;
  color: rgb(255 255 255 / var(--tw-text-opacity));

  .some-custom-class & {
    /* ... */
  }
}
```

...so any time you `@apply text-white`, it's going to carry that behavior with it, and since Tailwind (at least in v3) expects flattened CSS and `@keyframes` is nested structure, weird stuff like what you're seeing there happens.

Second thing is you really just shouldn't use `@apply` with `@keyframes` at all and we should probably just error on this, because this can't work either for example:

```css
@keyframes my-keyframes {
  from {
    @apply hover:bg-red-500;
  }
}
```

...since there's no way to put hover styles into keyframes.

I would recommend using the [`theme` function](https://tailwindcss.com/docs/functions-and-directives#theme) instead here, since `@apply` is meant for use with selectors and keyframes aren't selectors.

**Comment by neochief** [comment]
Hi Adam!

Thanks a lot man, didn't expect such an elaborate reply from you personally.

Now I understand why it was expanded that way, I totally didn't understand why it was happening in the first place.
