### ISSUE TITLE
SVG Linear Gradient Not Displaying Properly With Breakpoints

### ISSUE THREAD

**Issue by stephen-tribefibre** [tailwindlabs/tailwindcss#14833]
Tailwind v6.12.2
Nuxt v3.13.2
Node v22.9.0
Edge Version 130.0.2849.56 (Official build) (x86_64)
Chrome Version 130.0.6723.92 (Official Build) (x86_64)
macOS

Tested on play.tailwindcss.com as well

repo - https://github.com/Tribe-Fibre/tailwind-svg-issue

When using breakpoints to show and hide svg's if the fill="url(#paint1)" <linearGradient id="paint1" has the same id for each of the svg's including if I use a component to hold the svg. After the first screen break the svg is not displayed.

**Comment by wongjn** [comment]
The problem is indeed due to the repeated `id`. To be clear, the problem you are seeing that the SVG `<path>` fill is not rendering, not that the classes of the `<div>` parent do not work.

However, this is not a Tailwind problem, rather it is a restriction with how references in SVGs work in HTML in general – you would still see this problem without Tailwind. You'd need to ensure all the `id`s are unique.

**Comment by stephen-tribefibre** [comment]
Ah ok. So I'll need a different component for each breakpoint with different id's then?

**Comment by wongjn** [comment]
Yes, you'd need to ensure all the `id`s are unique.
