### ISSUE TITLE
Use Oklab for gradient interpolation

### ISSUE THREAD

**Issue by aaronadamsCA** [tailwindlabs/tailwindcss#14955]
Gradient interpolation (and any future `color-mix` utilities) should be using the Oklab colour space.

https://play.tailwindcss.com/B5DPkOnhjl

You'll generally want the uniform colour space (Oklab) for mixing/interpolating between colours, and the cylindrical colour space (Oklch) for modifying the lightness/chroma/hue of individual colours.

<img src="https://github.com/user-attachments/assets/1a844858-8280-46a1-8d74-0185f5de9bee" width="414" height="542">

**Comment by philipp-spiess** [comment]
Hey @aaronadamsCA! Thanks for the report. Agree that this particular example is really unexpected in Chrome. We did some comparison between `oklch` and `oklab` in different browsers and still think `oklch` is what you want in most cases. It's more vivid and less grayish. E.g. look at the subtle difference in this gradient:

![image](https://github.com/user-attachments/assets/f9df22a4-73d1-4983-bc1e-57ad6ac84942)

(the one underneath is oklab, ignore the label)

What we'll do though is to make it very easy to change the interpolation mode. We'll add modifier support to all gradients so it's very easy to control this because of these inconsistencies.

**Comment by aaronadamsCA** [comment]
That makes sense!

I still think you'll end up finding `in oklab` is the right default because it produces the most consistent results, with `in oklch` and `in oklch longer hue` offering artistic alternatives.

Put another way, most people probably won't expect to pick two colours and end up with a third:

https://play.tailwindcss.com/ie9lFqoVOq?layout=horizontal
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/6b015d43-c8ad-4594-a1e6-4f6d9b83191b">

https://play.tailwindcss.com/MN1X0EuhWr?layout=horizontal
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/d9570bff-3384-4143-9eb7-4ab2ab8bfe27">

https://play.tailwindcss.com/x3ptQxqsew?layout=horizontal
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/a317c376-4867-4354-bcb2-7ca7783085d6">

Still, as long as it's easy enough to change, it'll be great to have them all as options!
