### ISSUE TITLE
Performance Monitoring flags two regex taking majority of cli time

### ISSUE THREAD

**Issue by JasonKleban** [tailwindlabs/tailwindcss#14990]
**What version of Tailwind CSS are you using?**

3.4.14

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-loader: 8.1, webpack 5.96

**What version of Node.js are you using?**

v21.1.0

**What operating system are you using?**

Mac, Windows

**Describe your issue**

In a fairly small project tailwind is taking 26 seconds.  I profiled it with Chrome DevTools `npx --node-options=--inspect-brk tailwindcss -i .\src\input.css` and see that some specific regexes are taking up a majority of the time:

![image](https://github.com/user-attachments/assets/4884d5ed-c456-4d83-94df-d20829b6f117)

I don't think this is project-specific.  I'm suspecting that these regexes should be re-evaluated for performance - but I have not been able to find where these regexes are in the source.

> ```((?=(((?:([^\s"'`\[\\]+-)?\[[^\s`]+\]\/[\w_-]+:|([^\s"'`\[\\]+-)?\[[^\s`]+\]:|[^\s`\[\\]+:))+))\2)?!?(?:\[[^\s:'"`]+:[^\s\[\]]+\]|\[[^\s:'"`\]]+:[^\s]+?\[[^\s]+\][^\s]+?\]|(?:-?(?:\w+)|@(?:\w+))(?:(?:(?:-(?:\w+-)*\['[^\s]+'\]|-(?:\w+-)*\["[^\s]+"\]|-(?:\w+-)*\[`[^\s]+`\]|-(?:\w+-)*\[(?:[^\s\[\]]+\[[^\s\[\]]+\])*[^\s:\[\]]+\])(?![{([]])(?:\/[^\s'"`\\><$]*)?|(?:-(?:\w+-)*\['[^\s]+'\]|-(?:\w+-)*\["[^\s]+"\]|-(?:\w+-)*\[`[^\s]+`\]|-(?:\w+-)*\[(?:[^\s\[\]]+\[[^\s\[\]]+\])*[^\s\[\]]+\])(?![{([]])(?:\/[^\s'"`\\$]*)?|[-\/][^\s'"`\\$={><]*))?)```

> ```((?=(((?:@\[[^\s"'`]+\](\/[^\s"'`]+)?:|([^\s"'`\[\\]+-)?\[[^\s"'`]+\]\/[\w_-]+:|([^\s"'`\[\\]+-)?\[[^\s"'`]+\]:|[^\s"'`\[\\]+:))+))\2)?!?(?:\[[^\s:'"`]+:[^\s\[\]]+\]|\[[^\s:'"`\]]+:[^\s]+?\[[^\s]+\][^\s]+?\]|(?:-?(?:\w+)|@(?:\w+))(?:(?:(?:-(?:\w+-)*\['[^\s]+'\]|-(?:\w+-)*\["[^\s]+"\]|-(?:\w+-)*\[`[^\s]+`\]|-(?:\w+-)*\[(?:[^\s\[\]]+\[[^\s\[\]]+\])*[^\s:\[\]]+\])(?![{([]])(?:\/[^\s'"`\\><$]*)?|(?:-(?:\w+-)*\['[^\s]+'\]|-(?:\w+-)*\["[^\s]+"\]|-(?:\w+-)*\[`[^\s]+`\]|-(?:\w+-)*\[(?:[^\s\[\]]+\[[^\s\[\]]+\])*[^\s\[\]]+\])(?![{([]])(?:\/[^\s'"`\\$]*)?|[-\/][^\s'"`\\$={><]*))?)```

**Comment by philipp-spiess** [comment]
@JasonKleban Hey! Do you have a repro setup for the issue here including the config that's causing the 26 seconds builds? That's definitely not expected and also not what we're seeing. 

I also tried to look for and can't find out where this regex comes from 🤔  Mind sharing the perf recording so we can look into the trace? 

Generally, we are very close to cutting a beta release of Tailwind CSS v4 which is going to make it much easier for us to debug issues like this and since performance was a huge priority for v4 from the start, it's probably going to behave differently here already, if you want to give that a try. 👀

**Comment by JasonKleban** [comment]
Looks to be generated at runtime in _lib\defaultExtractor.js_:

    let patterns = Array.from(buildRegExps(context));

and so this is the _lib/regex.js_ concatenating the subpatterns for `function* buildRegExps()`

**Comment by thecrypticace** [comment]
Yeah this is a built regex but without a reproduction it's going to be very difficult to figure out the source of the slowness.

> is parsing my javascript file

We're scanning files for things that _might_ be utilities but we don't _parse_ them per se. That would require parsers for many possible languages, ability to take an AST from each of those languages and potentially reason about how its used, etc…

We have to cast a broad net just because of the sheer number of ways people can write utilities in various languages.

**Comment by thecrypticace** [comment]
I would definitely try using v4 for this though. Chances are it's going to significantly faster.

**Comment by adamwathan** [comment]
Can you share your `content` configuration? Any chance it’s accidentally scanning node_modules or minified JS files?

**Comment by JasonKleban** [comment]
Yes, not minified but other one-liners like sourcemaps and tsbuildinfo.  Not sure about this, but I suspect those long single lines could be especially hard on the regex compared to if they were split up by `\n`.  Or just the nature of those file contents being a sadistic case.  Thanks for the feedback!
