### ISSUE TITLE
Selection is broken in Chrome 131 due to --tw-text-opacity and friends

### ISSUE THREAD

**Issue by schenney-chromium** [tailwindlabs/tailwindcss#15000]
**What version of Tailwind CSS are you using?**

Not sure what version sites are using, but I suspect less than a year old.

**What build tool (or framework if it abstracts the build tool) are you using?**

Don't know

**What version of Node.js are you using?**

Don't know

**What browser are you using?**

Chrome and Edge

**What operating system are you using?**

All

**Reproduction URL**

See https://issues.chromium.org/issues/378754060 for numerous reproductions. From The Verge:
```
.selection\:bg-franklin-20::selection {
    --tw-bg-opacity: 1;
    background-color: rgb(216 255 246/var(--tw-bg-opacity));
}
```
All selection is blank in Chrome 131 and later on The Verge, Bloomberg news, ...

**Describe your issue**

Chrome 131 and browsers using Chromium enable CSS Highlight Inheritance for ::selection. In this model custom properties for ::selection and other highlight pseudos are taken from the originating element, and not the pseudo itself. All custom properties defined on highlight pseudos are ignored. But Tailwind defines a custom property for opacity on every use of a color, including ::selection colors. There is no practical use for this because the variable is redefined all over the place and any given usage inside ::selection applies only within that ::selection block (with the old behavior).

See https://developer.chrome.com/blog/selection-styling and https://blogs.igalia.com/schenney/css-custom-properties-in-highlight-pseudos/

I might try to figure out how to fix this and put up a PR for you.

**Comment by adamwathan** [comment]
_Cross-posting from the Chromium issue —_

Quick fix for all Tailwind users — as long as you aren't using any of the `bg-opacity-*`, `text-opacity-*`, etc. utilities (which are deprecated and haven't been documented in a few years), you can use this feature flag to remove the problematic variables from your generated CSS:

```js
// tailwind.config.js
module.exports = {
  future: {
    disableColorOpacityUtilitiesByDefault: true
  },
  // ...
}
```

This will work immediately, without having to upgrade Tailwind to the latest patch that we're tagging right now. This might be the best solution for the folks at The Verge because they are currently on Tailwind CSS v3.3 and might want to do more extensive testing before upgrading to v3.4 even though there should be no breaking changes.

**Comment by thecrypticace** [comment]
v3.4.15 was released with a fix on our side for this 👍

**Comment by schenney-chromium** [comment]
Thanks for the fix. It's great to see you're already on top of it.

Allowing and using custom variables that are defined in the selection block itself is something a least one other person has asked for. Maybe there is a reasonable way to implement it to at least solve the particular problem with your older version. I doubt that every site with an older version is going to update, and Safari will take a bit longer to ship this (not sure how long).
