### ISSUE TITLE
[V4] Theme colors broken on build result

### ISSUE THREAD

**Issue by danie-ramdhani** [tailwindlabs/tailwindcss#15018]
**What version of Tailwind CSS are you using?**

4.0.0-alpha.33

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 5.4.11

**What version of Node.js are you using?**

—

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

—

**Describe your issue**

`--color-primary` is not works properly on build result but works as expected in development mode.

**Steps to Reproduce**

```html
<div
        style="background-color: var(--color-primary); width: 40px; height: 40px; margin-top: 10px; margin-bottom: 10px;">
</div>
```

```css
@theme {
    --color-primary: light-dark(theme(--color-cyan-700), theme(--color-cyan-300));
}
```

**dev mode result**

![dev mode result](https://github.com/user-attachments/assets/a9300be4-16d1-4f15-bd9d-3b86e658f341)

![dev mode result 1](https://github.com/user-attachments/assets/c1611ded-e7ce-4710-8c2d-c19ae79da90b)

**build result**

![build result](https://github.com/user-attachments/assets/33e1b80d-fb21-4958-a654-373f561b6d40)

![build result 1](https://github.com/user-attachments/assets/de430058-4843-4891-bba0-9dbe0341dd9c)

**Comment by philipp-spiess** [comment]
Heya! I don't think this is a Tailwind CSS bug. First of all, I was only able to reproduce this with a Vite config where `transformer` is set to `lightningcss`. Can you confirm this is part of your setup as well? When I use the _default_ postcss transformer, the `--color-primary` function would transform as expected:

<img width="706" alt="Screenshot 2024-11-18 at 11 44 42" src="https://github.com/user-attachments/assets/b9c53b57-6e2c-4334-a2fe-35b8bf19dd3f">

Now, when you do use `lightningcss` as the Vite transformer, there are some caveats that are documented in the lightningcss docs: https://lightningcss.dev/transpilation.html#light-dark()-color-function

The `light-dark()` function compiles to a nested `var()` lookup and in order for this to work, you _need_ to include the `color-scheme` property so that the root of these variables are defined. I was able to make your example work by changing the CSS to:

```css
@theme {
    --color-primary: light-dark(theme(--color-cyan-700), theme(--color-cyan-300));
}

html {
  color-scheme: light dark;
}
```

<img width="566" alt="Screenshot 2024-11-18 at 11 51 38" src="https://github.com/user-attachments/assets/e9a2007d-1df8-4c07-a58a-10b9e551bccd">
