### ISSUE TITLE
[v4]: `@apply` no longer allows referencing custom utilities after `alpha-32`

### ISSUE THREAD

**Issue by bczsalba** [tailwindlabs/tailwindcss#15314]
**What version of Tailwind CSS are you using?**

v4.0.0-beta.5

**What build tool (or framework if it abstracts the build tool) are you using?**

@tailwindcss/cli@v4.0.0-beta.5

**What version of Node.js are you using?**

v22.9.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/xky1QCZccs?file=css

**Describe your issue**

Using `@apply` with user-defined styles works from `alpha-3` (the first version I could get to build with only a CSS file as config) all the way to `alpha-31`, after which it results in `Cannot apply unknown utility class: ...`.

Tried:

- Moving around the initial tailwind import
- Moving the `@apply` call in/out of the `utilities` layer
- Adding `@import "tailwindcss/theme" theme(reference);` at various points in the file

The only thing I could come up with to get around this was to use the CSS vars the declaration would've referenced (`--font-family-example`, in this case) to manually set the style within the utility. This doesn't seem very convenient, and is practically useless when chaining multiple utilities in a single `@apply` call (which is 99% of my usage of the feature).

I couldn't find any references to this change of behaviour, but I might have just overlooked something since of course the docs aren't quite complete yet. It feels a bit weird that this _wouldn't_ have already been reported, but I couldn't find anything relevant.

Thank you!

**Comment by bczsalba** [comment]
Submitted before the content was in, so I'm reopening it now that it's actually ready :)

**Comment by RobinMalfait** [comment]
Hey!

We've renamed `--font-family` to just `--font`, if you update your code with that, then it should work again. Here is an updated Tailwind Play: https://play.tailwindcss.com/z3J5TNSoMT?file=css

This was changed as part of alpha 32 (https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-alpha.32).

If you are using alpha and/or beta versions it's important to checkout the release notes for every new version since these are not subject to semver, even though we try to keep the breaking changes to a minimum. So sorry about the inconvenience here.

We also have a list of variable namespaces which you can reference: https://tailwindcss.com/docs/v4-beta#namespace-reference

Hope this helps!

**Comment by bczsalba** [comment]
Ah cool, thanks!
