### ISSUE TITLE
@tailwindcss/vite plugin issue with @apply directive

### ISSUE THREAD

**Issue by amanmavai** [tailwindlabs/tailwindcss#15324]
**What version of Tailwind CSS are you using?**

4.0.0-beta.5

**What build tool (or framework if it abstracts the build tool) are you using?**

vite

**What version of Node.js are you using?**

20.8.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**
https://github.com/amanmavai/tailwind_v4_repro_01

**Describe your issue**
not able to use @apply directive in vite + react project
when I am running dev server or build getting below error
error during build:
[@tailwindcss/vite:generate:build] Cannot apply unknown utility class: text-3xl

**Comment by adamwathan** [comment]
Hey! Instead of importing `loading.css` in your `main.tsx` file, you should import it in your `index.css` file.

The way you have it set up now, Tailwind is being run twice (once for each CSS file), and your `loading.css` file contains no `@theme` which is why it's complaining that `text-3xl` doesn't exist because the `--text-3xl` theme variable isn't defined. If you import `loading.css` inside of `index.css`, everything will work the way you expect 👍 

If you _really_ want to import those CSS files separately in `main.tsx`, your other option is to add `@import "tailwindcss" reference` to the top of `loading.css` so all of the default `@theme` variables are available without unnecessarily duplicating a bunch of CSS.

**Comment by amanmavai** [comment]
I think this was not the case earlier, previous version of tailwindcss, let's consider the case when I have a loading component
- loading.tsx
- loading.css
and I am importing loading.css inside of loading.tsx
is it not the valid adding tailwind classes inside of loading.css or am I missing something here?
as per your comment if I have multiple components with their own css files, can I not use @apply directive in those css files without importing @tailwindcss directive.

**Comment by amanmavai** [comment]
> Hey! Instead of importing `loading.css` in your `main.tsx` file, you should import it in your `index.css` file.
> 
> The way you have it set up now, Tailwind is being run twice (once for each CSS file), and your `loading.css` file contains no `@theme` which is why it's complaining that `text-3xl` doesn't exist because the `--text-3xl` theme variable isn't defined. If you import `loading.css` inside of `index.css`, everything will work the way you expect 👍
> 
> If you _really_ want to import those CSS files separately in `main.tsx`, your other option is to add `@import "tailwindcss" reference` to the top of `loading.css` so all of the default `@theme` variables are available without unnecessarily duplicating a bunch of CSS.

I think this was not the case earlier, previous version of tailwindcss, let's consider the case when I have a loading component

loading.tsx
loading.css
and I am importing loading.css inside of loading.tsx
is it not the valid adding tailwind classes inside of loading.css or am I missing something here?
as per your comment if I have multiple components with their own css files, can I not use https://github.com/apply directive in those css files without importing https://github.com/tailwindcss directive.
