### ISSUE TITLE
Not recognising arbitrary style

### ISSUE THREAD

**Issue by pjebs** [tailwindlabs/tailwindcss#15505]
**What version of Tailwind CSS are you using?**

For example: current latest via `<script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio"></script>`

**What build tool (or framework if it abstracts the build tool) are you using?**

None

**What version of Node.js are you using?**

None

**What browser are you using?**

Chrome

**What operating system are you using?**

macos

**Reproduction URL**

I was just playing around locally

**Describe your issue**

I have created a multi-column layout.

I have some content such as this: `<h1 class="[column-span: auto] [break-before: column]">XXX</h1>`

The break before doesn't work.

However this does work:

I have some content such as this: `<h1 class="[column-span: auto]" style="break-before: column">XXX</h1>`

**Comment by wongjn** [comment]
Spaces delimit class names so they must be removed from arbitrary classes for them to work. In this situation, we can simply remove them like so:

```html
<h1 class="[column-span:auto] [break-before:column]">XXX</h1>
```

Though, you don't need to use an arbitrary property class for `break-before` since there is [a built-in utility class](https://tailwindcss.com/docs/break-before):

```html
<h1 class="[column-span:auto] break-before-column">XXX</h1>
```
