### ISSUE TITLE
Slow compile, gulp recompiling everything even when no changes are made in tailwind config

### ISSUE THREAD

**Issue by RomkaLTU** [tailwindlabs/tailwindcss#1620]
This problem bothering me so long now, I constantly returning to it when coding Design to HTML and using Gulp or Webpack. Build time is very slow (~3 seconds) when changing anything not related to tailwind config. For example my main.css file looks like this:

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import '_global.css';
```

I change something in _global.css and gulp starting to build EVERYTHING including not changed tailwind-config.js 

gulp function
```
function css() {
    return gulp.src('./src/assets/css/main.css')
        .pipe(postcss([
            require('postcss-import'),
            require('tailwindcss'),
            require('postcss-nested'),
            require('postcss-custom-properties'),
            require('autoprefixer'),
            require('cssnano')({
                preset: 'default',
            }),
        ]))
        .pipe(gulp.dest(PATHS.dist + '/assets/css'))
        .pipe(browser.reload({ stream: true }));
}
```

I somehow managed to work around this when using laravel mix by creating main.css, tailwind.css files:

tailwind.css
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

main.css
```
@import 'tailwindcss.css';
@import '_global.css';
```

By doing this changes in globa.css is compiled instantly only when changing something in tailwind-config.js then build proccess taking around 3 sec. depending on config complexity. 

webpack.mix.js
```
mix.postCss('css/main.css', 'dist/', [
    require('tailwindcss'),
    require('postcss-nested'),
    require('postcss-custom-properties'),
    require('autoprefixer'),
]);
```

Why I can't reproduce this workaround on gulp?

**Comment by RomkaLTU** [comment]
Ok it's second time in this week I answering my own question, looks like duck debugging now. Anyway: main bottleneck in gulp config is:

```
...
require('cssnano')({
    preset: 'default',
}),
...
```

Minification should be done when building for production. It will reduce build time from 3sec to aprox 500ms.

**Comment by adamwathan** [comment]
We've recently done a series of optimizations that basically does everything we can to avoid re-computing things unnecessarily in long watch processes — can you test with the latest version of Tailwind and see if you see any improvements for subsequent builds after the first one?

I'm afraid there's not much we can do besides what we've done though, Tailwind has to do a lot of work to generate all of the classes so if you aren't seeing improvements now it's not likely that we can do anything about it. Could just be that gulp in watch mode doesn't reuse things the way webpack and others do, making our new improvements not helpful :/ Going to close because no plans to act on this right now but we are always looking for ways to improve performance regardless.
