### ISSUE TITLE
Tailwind utility plugin generates invalid css when class is used in @apply

### ISSUE THREAD

**Issue by brettdorrans** [tailwindlabs/tailwindcss#1710]
Minimal reproduction repo and steps to demonstrate the issue here: https://github.com/brettdorrans/tailwind-bug

## The gist

Using a Tailwind plugin that utilises the @apply syntax as documented [here](https://github.com/tailwindcss/tailwindcss/discussions/1556#discussioncomment-4330) produces invalid CSS.

## Steps to reproduce:

1. Pull the repository and install dependencies: `npm i`
2. Inspect the plugin `tailwind.config.js` which uses the syntax documented [here](https://github.com/tailwindcss/tailwindcss/discussions/1556#discussioncomment-4330)
to @apply inside css-in-js plugin.
3. Inspect `src/test.css` which uses @apply with this plugin class.
4. Run `npm run serve` and inspect the generated CSS in `./dist/main.css`

## What I expect

```css
.broken-class {
  padding: 0;
}
```

## What actually generates

```css
.broken-class {
  @apply p-0 {
  }
}
```

**Comment by brettdorrans** [comment]
After some digging this seems to be due to nested @apply not being supported in `parseObjectStyles.js`. Here is a test I'd expect to pass if this were implemented:

```
test('it parses nested @apply', () => {
  const result = parseObjectStyles({
    '.foo': {
      backgroundColor: 'red',
      color: 'white',
      padding: '1rem',
      '@apply m-0': {},
    },
  })

  expect(css(result)).toMatchCss(`
    .foo {
      background-color: red;
      color: white;
      padding: 1rem;
      margin: 0
    }
  `)
})
```

**Comment by adamwathan** [comment]
Yeah this is by design, `apply` is not meant to work recursively, it's meant for applying utility classes, not applying classes that are already composed of utility classes. We are unlikely to invest in making this any more sophisticated because we generally discourage over-use of `apply`. If I were going to design Tailwind again from scratch today we'd probably only include the `theme` helper and not include `apply` at all.

**Comment by brettdorrans** [comment]
Hmm I suspected as such. In that case I think the bug here is that compilation succeeds with no error message and generates invalid css.

**Comment by adamwathan** [comment]
Yep agree. I think the right improvement to make here is to look for any remaining `@apply` rules at the very end of processing and throw an error letting the user know that recursive `@apply` is not supported, but it's somewhat of a breaking change because recursive `@apply` _does_ work (just by coincidence) if the classes happen to be in the right order:

```css
.foo {
  @apply px-2;
}

.bar {
  @apply foo;
}
```

**Comment by brettdorrans** [comment]
Ah, that explains why I had issues reproducing this in a larger project. Sometimes it'd work, others not. Frustrating!

Cheers for the clarification.
