### ISSUE TITLE
Pseudo-classes odd/even don't work with `hover` state.

### ISSUE THREAD

**Issue by icaroscherma** [tailwindlabs/tailwindcss#2082]
### Describe the problem:

When using pseudo-class variants like `odd`, `even` they won't accept element state changes on top of it (like `hover`).

For instance:
```HTML
<table class="w-full">
  <tr class="bg-gray-100 odd:bg-white hover:bg-blue-100">
    <td>example 1</td>
  </tr>
  <tr class="bg-gray-100 odd:bg-white hover:bg-blue-100">
    <td>example 2</td>
  </tr>
</table>
```
Only the non-odd row will get the hover class styling applied to it.

**Comment by icaroscherma** [comment]
Nevermind, guys on the Discord channel helped me to solve this.
The variants on the `tailwind.config.js` needs to follow an order.
It's supposed to be:
`backgroundColor: ['responsive', 'odd', 'even', 'hover', 'focus'],`
It was:
`backgroundColor: ['responsive', 'hover', 'focus', 'odd', 'even'],`

It would be good to include a note about this on the docs.

**Comment by adamwathan** [comment]
Glad you got it sorted! This is covered in the docs here:

https://tailwindcss.com/docs/configuring-variants#ordering-variants

**Comment by kkdima** [comment]
@adamwathan I went through the docs and it's a bit confusing because of the different examples for activation 'odd' & 'even' variants. Can you point where's the mistake in this example?
<img width="408" alt="Screen Shot 2021-08-24 at 5 38 25 PM" src="https://user-images.githubusercontent.com/17368311/130709726-410dc8d6-89c7-436e-b65b-cbada34fe984.png">
<img width="799" alt="Screen Shot 2021-08-24 at 5 53 32 PM" src="https://user-images.githubusercontent.com/17368311/130709730-5c2d30b4-8bdf-45d0-a5e0-48c48028fe3e.png">
