### ISSUE TITLE
group-hover:translateX Not Working as Expected

### ISSUE THREAD

**Issue by mikehawkfish** [tailwindlabs/tailwindcss#2177]
### Describe the problem:

Hey Tailwind team,

Using the variants config option with `translateX` I'm unable to use `group-hover`.

Here's my variants: 
```javaScript
variants: {
    translateX: ['group-hover'],
    backgroundColor: ['group-hover'],
  },
```

Expected to be able to do this:

```javaScript
<div class="group">
        <div class="group-hover:translate-x-1">
          group-hover:translate-x-1
        </div>
</div>
```

No classes are generated and this doesn't work.

### Link to a minimal reproduction:

https://codesandbox.io/s/wandering-platform-1ytxy?file=/public/index.html

Let me know if I'm doing something wrong or if you can fix this. 

Thanks!

**Comment by IL4Miy** [comment]
@mikehawkfish 
You have to add `translate` variant instead of `translateX`.
`translate: ["responsive", "hover", "focus", "active", "group-hover"],`
In addition, you have to add `transform` to your class in order to make translate-x working.
` <div class="transform border border-1 group-hover:translate-x-1">
      group-hover:translate-x-1
    </div>`

Moreover, make sure you keep in mind that with the variant you **overwrite** the existing variants for translate.
https://tailwindcss.com/docs/configuring-variants

**Comment by mikehawkfish** [comment]
Ah yeppp. Totally right.

I looked at this for so long and didn't catch the `translate` vs `translateX`.

Thanks @alexanderbluhm for your hlep!
