### ISSUE TITLE
@apply doesn't work inside <style jsx></style> with react not next.js 

### ISSUE THREAD

**Issue by developerajendra** [tailwindlabs/tailwindcss#2180]
I am facing similar issue to https://github.com/tailwindlabs/tailwindcss/issues/1234 but with React JS. Can someone please help me with this?

Repo: https://github.com/sabio-aprendiz/react-story-jsx

**Comment by adamwathan** [comment]
The way that project is set up, Tailwind is only running against your `tailwind.css` file:

https://github.com/sabio-aprendiz/react-story-jsx/blob/master/package.json#L34

It doesn't appear that PostCSS is processing anything other than that file, so none of Tailwind's features will work outside of that file.

Looks like you need to look into how to actually integrate PostCSS into Storybook's build process instead of compiling your CSS in an isolated process. This comment might help:

https://github.com/storybookjs/storybook/issues/6319#issuecomment-477852640

Closing as not an issue with Tailwind sadly, and just an issue with how complex Storybook is to configure 😞

**Comment by sabio-aprendiz** [comment]
@adamwathan
I have tried the same without storybook. I create the setup by using React(CRA)+typescript+styled-jsx+tailwindCSS and also configured the .babelrc file with plugins styled-jsx , styled-jsx-plugin-sass and styled-jsx-plugin-postcss but still i am not able to use the @apply directive of tailwind css inside the styled-jsx like this

`<style jsx>{` 
        .btn-blue {
          @apply bg-blue-500 text-white rounded-lg;
          padding:20px;
        }
      `}</style>`

**Comment by sabio-aprendiz** [comment]
I think there is some issue with **styled-jsx-plugin-postcss** because when i am configuring it inside webpack.js file after ejecting, my application is not loading on the browser.

**Comment by HamidReazaNikoonia** [comment]
I found this issue too 
in React next js + typeScript + TailwindCSS

Styles doesn't set in the component ( Just Tailwind classes in both @apply and set to className )
