### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Nick-Mazuk** [tailwindlabs/tailwindcss#2357]
### Describe the problem:

First off, really like the new dark mode!

There are just two things I noticed that didn't work the way I expected. Also, don't know if this is a bug or feature request, so feel free to move or tag it to where it needs to go.

1) When setting `dark: 'media'` in tailwind.config.js, tailwind ignores all `.dark` classes. I would have expected that `.dark` would still be interpreted correctly because sometimes you want a section to always be dark. For instance, even [Stripe's homepage](https://stripe.com/) has a few sections that are local dark modes. In other words, `dark: 'media'` says "also add the media attribute for me!" instead of "Only look for the media attribute and ignore all `.dark` classes"

2) Ok, this one is a feature request, but an `.invert` class would be nice. This would essentially invert the mode for a given container. `.invert` in light mode creates a dark section and vice versa. Without an `.invert` class, there isn't a problem with straight HTML but there is when using components.

### Link to a minimal reproduction:

Can create one if desired, but even the most basic Tailwind setup should suffice.

Thanks!

**Comment by adamwathan** [comment]
Hey!

Point 1 is by design (at least for now), we recommend that if you want to support _both_ that you just use the "class" strategy and use JS + the `matchMedia` API to set the class yourself. The CSS gets very complicated otherwise.

Point 2 about trying to change the mode per section and explicitly opt-in to light mode and stuff is an interesting idea but not something we plan to tackle right now. For now just want to keep it really simple. 

Appreciate the suggestions and can definitely keep them in mind for the future but for now not planning to add this sort of thing 👍🏻
