### ISSUE TITLE
Bounce animation jarring when used on hover

### ISSUE THREAD

**Issue by dskrepps** [tailwindlabs/tailwindcss#2404]
When hovering an element with `hover:animate-bounce` the element jumps up, then if your mouse is in the bottom quarter it flashes back and forth. Swapping the keyframes mostly fixes this.

The bottom example is much smoother: https://codepen.io/temp_/pen/poyOaKM

**Comment by adamwathan** [comment]
This one is sort of tough because I agree it looks a little better on hover, but in general it's also weird that the animation now would be starting from the midpoint essentially instead of the beginning. It bounces up without ever falling down to build up the energy needed to bounce back up and the first loop looks really unnatural.

Here's a new one that feels most natural to me but also feels wrong because it's emphasizing a point on the screen that isn't the actual position of the element:

https://codepen.io/adamwathan/pen/gOMpOEj?editors=1100

Sort of a tough thing to get universally right.

I think for a bounce on hover animation, the absolute best design would be something that does a little "squash" scaling at the beginning like it's preparing for a jump, then pops up, so it doesn't look like it's just bouncing up unnaturally. I think that would be a bit more opinionated that what we actually want to ship by default though.

Here's a side-by-side version of the example you originally posted that isn't running on hover, just on loop:

https://codepen.io/adamwathan/pen/ExyjaYZ?editors=1100

To me the one on the left feels much more correct because you see it fall before it pops up. So I'm not really sure what the best compromise is. Generally we consider the default animations to just be examples and not really universally useful, so we expect them to be customized anyways. I dunno, any thoughts?

**Comment by adamwathan** [comment]
Decided we'll just keep this as-is for now since there are drawbacks to both approaches. As we mention in the docs these animations are just designed to serve as ideas/examples anyways, and in reality you will almost always be customizing/providing your own animations for real projects.

Really appreciate the discussion though, thanks!

**Comment by dskrepps** [comment]
I wouldn't want to give the user the impression something is _falling_ out of place. Feeling like your mouse is pushing it up before it drops down is preferable. But I agree, overriding animations is best.
