### ISSUE TITLE
Problems with "radius-full"

### ISSUE THREAD

**Issue by kalmerrautam** [tailwindlabs/tailwindcss#2407]
I had trouble with appying `"rounded-full"` class to element. After checking my scaffolded full config file I discovered that "full" property had apostrophes missing. Got it fixed after defining `'full': '100%' `in my config file.

```
translate: (theme, { negative }) => ({
      ...theme('spacing'),
      ...negative(theme('spacing')),
      '-full': '-100%',
      '-1/2': '-50%',
      '1/2': '50%',
      full: '100%',
}),
```

Currently on **ver. 1.8.10**

**Comment by adamwathan** [comment]
Not sure what the issue could really be here because JS object keys don't need quotes — `rounded-full` definitely works fine out of the box:

https://tailwind.run/oiiy1Q

Going to close as you managed to sort out your issue regardless and there doesn't appear to be a bug here but feel free to open a new issue with a reproduction if you run into it again.
