### ISSUE TITLE
Disable attribute doesn't work

### ISSUE THREAD

**Issue by lourencelinao** [tailwindlabs/tailwindcss#2420]
### Describe the problem:

  I tried to disable a button using vue js ":disable", it doesn't work if there's a hover class attribute present.

**Comment by adamwathan** [comment]
Hey! Unfortunately this isn't enough information to help, please open a new issue that includes a reproduction of the actual problem. I suspect this is just a misunderstanding of how some Vue or Tailwind features work, because there's no way that adding a hover style via Tailwind would break how disabling buttons works in Vue. You might still see the hover style but the button will definitely still be disabled (as in it won't fire any events).

I'm just guessing but what you probably want is to only apply the hover styles when the button is not disabled, rather than all the time.

Something vaguely like:

```html
<button :disabled="disabled" :class="{'hover:bg-blue-500': !disabled}">
```

**Comment by acabreragnz** [comment]
Hey @adamwathan !

Same happens to me on react, I copied your example from [here](https://tailwindcss.com/docs/pseudo-class-variants#disabled)

```javascript
<button class="ml-4 disabled:opacity-75 bg-blue-500 active:bg-blue-700 text-white font-semibold hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline">
  Submit
</button>
```

```javascript
<button disabled class="ml-4 disabled:opacity-75 bg-blue-500 active:bg-blue-700 text-white font-semibold hover:text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline">
  Submit
</button>
```

And this was the result:
![Screenshot from 2020-10-21 12-22-47](https://user-images.githubusercontent.com/6330366/96741453-2d3f1e00-1398-11eb-8073-43feb0ee63d4.png)

It is a nextjs app:
```json
{
    "tailwindcss": "1.8.10",
    "react": "16.13.1",
}
```

I would like to know what am I doing wrong, thank you for this amazing css framework :)!

**Comment by mannieschumpert** [comment]
I am also currently having this problem in a React app.

`"tailwindcss": "^1.9.6"`

**Comment by mannieschumpert** [comment]
Oops, never mind. I see this is a configuration issue.

https://github.com/tailwindlabs/tailwindcss/issues/2661#issuecomment-715498692

**Comment by Alex2718281828** [comment]
asd

**Comment by doom-goober** [comment]
> Oops, never mind. I see this is a configuration issue.
> 
> [#2661 (comment)](https://github.com/tailwindlabs/tailwindcss/issues/2661#issuecomment-715498692)

I added "disabled" to the configuration at the end of the appropriate array and hover still overrules disabled.

How did you fix your configuration? Did you use the after() function as described in the bug?
