### ISSUE TITLE
typography plugin fails when used in CSS-in-JS

### ISSUE THREAD

**Issue by GHNewbiee** [tailwindlabs/tailwindcss#2493]
### Describe the problem:
CSS rendering never takes place, even when backticks are escaped (#2492).

### Link to a minimal reproduction:
https://github.com/QuinsZouls/lit-tailwindcss
https://github.com/QuinsZouls/lit-tailwindcss/blob/master/tailwindcss.js

Build a css file which includes:
```js
  plugins: [
    require('@tailwindcss/typography')
  ],
```
and try to render the page of the repo. It does fail.

**Comment by adamwathan** [comment]
This isn't really a Tailwind issue — if you want to copy and paste any string into a JavaScript file that contains the same quotes you are using to craft the string you will have to escape those quotes.

Since you are just copying and pasting the entire Tailwind output into a JS file all you need to do is manually escape the backtick instances with a `\`.
