### ISSUE TITLE
Space-Between Utility not spacing on both sides of Divide-Width (not using @apply)

### ISSUE THREAD

**Issue by pdevito3** [tailwindlabs/tailwindcss#2525]
### Describe the problem:
When I do something like this:
```html
    <div class="py-3 space-x-3 divide-x-2 flex items-center justify-center">
      <svg class="w-5 h-5 text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
      </svg>
      <p class="text-white font-bold">val 1</p>
      <p class="text-white font-bold">val 2</p>
      <p class="text-white font-bold">val 3</p>
    </div>
```

I'd expect that the `space-x` utility would apply the spacing and the divider would come up in the middle of it, but it instead ends up butted against one of the controls. At the moment, I'd have to add `pl` or `px` classes  to each of the subsequent controls other than the first one if I want it to operate this way. Feels like this is how the space-between utility should be interacting with the divide utility, but maybe I'm wrong :-) Sorry if I'm missing something here.

### Link to a minimal reproduction:
https://play.tailwindcss.com/W0VLTNAEmK

**Comment by adamwathan** [comment]
Hey! This is expected behavior at the moment, see the previous discussion here:

https://github.com/tailwindlabs/tailwindcss/discussions/1712

Think of the space utilities as a sort of backwards-looking version of the new CSS `gap` property, which would also have this issue. They are just really simple shortcuts for adding margin to every item except the first, and not meant to be super sophisticated or magical or anything.
