### ISSUE TITLE
tailwindcss/resolveConfig causing an error with version 1.9.0

### ISSUE THREAD

**Issue by haydencleary** [tailwindlabs/tailwindcss#2547]
### Describe the problem:

After upgrading to tailwindcss 1.9.0 Next.js began throwing an error during development:

<img width="427" alt="Screenshot 2020-10-13 at 11 38 21" src="https://user-images.githubusercontent.com/5160414/95843993-af03cb80-0d48-11eb-9485-f96b9ab8c2be.png">

I was able to narrow it down to components that use tailwindcss/resolveConfig to access the theme.
If I roll back to tailwindcss 1.8.13 everything works as expected.

### Link to a minimal reproduction:

[https://github.com/haydencleary/tailwind-issue](https://github.com/haydencleary/tailwind-issue)

**Comment by schabluk** [comment]
Same here. Next has build-in CSS support, that allows 3rd party imports only from _app.js.

See here: https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules

The workaround is to use `@zeit/next-css`, however is someone is using CSS Modules, this is no-go, because it allows to use either Global CSS, or CSS Modules, without mixing. Only build-in CSS support allows for using both, however the 3rd party has to be imported from _app.js.

**Comment by adamwathan** [comment]
Weird, we don't actually import any CSS files so I'm not sure why this would happen, and nothing around this has changed between 1.8 and 1.9. Asked the Next team for some help tracing it down.

You can see here we're not actually importing any CSS, just resolving the path to the file on the filesystem:

https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/preflight.js#L6

Though I do wonder why this code is even running at all when calling `resolveConfig`. Will try and trace that down, maybe that's what has changed.

**Comment by red545** [comment]
Getting the same error after upgrading to 1.9 - really hard to pinpoint the source

**Comment by adamwathan** [comment]
Will be fixed in a couple minutes after CI runs have no fear :)

**Comment by adamwathan** [comment]
Fixed in v1.9.1 👍🏻
