### ISSUE TITLE
-none should take precedence over -value

### ISSUE THREAD

**Issue by mokhosh** [tailwindlabs/tailwindcss#2576]
### Describe the problem:

I have a card with `max-w-sm` and in some cases I need to override this behaviour with `max-w-none`. But if I add that class through Laravel `$attributes` it doesn't respect `max-w-none` probably because it's defined before `max-w-sm`.
But why would anyone use `max-w-none` other than overriding since it is the default?
I think default values should override all other values if they are explicitly included in classes.

Am I missing something?

**Comment by adamwathan** [comment]
Hey @mokhosh! The root of the problem you're experiencing is that CSS specificity is directly impacted by CSS source order, so since `max-w-none` is defined earlier in the file than `max-w-sm`, `max-w-sm` takes precedence. This could be changed by changing the order of the keys in the Tailwind config file, but then someone else might want things to work the opposite way.

Generally I would just recommend that you never add two classes at the same time that are trying to compete with each other for a single CSS property. From our perspective that's undefined behavior. The VS Code IntelliSense plugin will even give you a lint error if you do this:

![image](https://user-images.githubusercontent.com/4323180/96338639-9f90c500-105d-11eb-9c17-78726bd28d1f.png)

No plans to change anything about this so going to close, but again would just recommend not adding conflicting classes.

In your case I would consider adding a custom prop to your Blade component for controlling the max-width, then translating that to the appropriate class inside the component:

```
// In your HTML
<my-component :constrain="false"/>

// In your component:
<div class="... {{ $constrain ? 'max-w-sm' : '' }}">
```

**Comment by mokhosh** [comment]
Thanks @adamwathan makes sense.
