### ISSUE TITLE
col-start-n and col-span-n not working together

### ISSUE THREAD

**Issue by paulcanning** [tailwindlabs/tailwindcss#2579]
I am trying to use col-start and col-span as described in the documentation, https://tailwindcss.com/docs/grid-column#starting-and-ending-lines

I have a 16 column container, and on the first child element, I set `col-start-2` and `col-span-2` to start on the 2nd oclumn, and span 2 columns. But it just doesn't work. the element is starting at column 1.

I tried adding the `important: true` entry to my config, but it hasn't helped, whilst I can see loads of `!important` rules added to tailwindcss in the compiled CSS, it's just not pulling through.

**Comment by adamwathan** [comment]
Hey! Can you create a demo on play.tailwindcss.com that reproduces the issue?

**Comment by paulcanning** [comment]
https://play.tailwindcss.com/sSfWLCnh0y

**Comment by adamwathan** [comment]
Since you are using `@apply` you have to make sure the classes are in the right order, as they are applied in the order you write them.

`col-start-2` needs to come _after_ `col-span-3` for things to work the way you want:

https://play.tailwindcss.com/uA4e8BAKsj?file=css

```
.header__logo {
  background-color: grey;
  height: 48px;
  width: 213px;
  @apply col-span-3 col-start-2;
}
```

In Tailwind 2.0 (coming out next month) this behavior will be a bit different and the order won't have any impact, it'll "just work".

You can opt-in to that behavior now by adding this to your config:

```js
module.exports = {
  experimental: {
    applyComplexClasses: true,
  },
  // ...
}
```

**Comment by paulcanning** [comment]
Is this ordering mentioned in the documentation? I couldn't find anything about it...

**Comment by adamwathan** [comment]
It's not but definitely something we could add. It works like CSS does in that sense, things defined later take precedence.

If you'd like to PR a change to the docs I'd be happy to merge it:

https://github.com/tailwindlabs/tailwindcss.com
