### ISSUE TITLE
Postcss 8 support

### ISSUE THREAD

**Issue by abhaykeerthy12** [tailwindlabs/tailwindcss#2670]
### Describe the problem:

Tailwind 1.9.6 is not working with postcss-cli version 8, giving error : "Error: true is not a PostCSS plugin"

`module.exports = {
    plugins: [
        require("postcss-import"),
        require("tailwindcss")("tailwind.config.js"),
        require("autoprefixer")
    ]
}
`
### Link to a minimal reproduction:

Use this versions of postcss-cli, autoprefixer, and postcss-import to reproduce bug

`"autoprefixer": "^10.0.1",
"postcss-cli": "^8.1.0",
"postcss-import": "^13.0.0",
"tailwindcss": "^1.9.6",
`

And run this command, btw, i'm using angular

`postcss src/theme/tailwind.css -o src/styles.css
`

**Comment by khatabwedaa** [comment]
You can use `npx tailwindcss build src/theme/tailwind.css -o src/styles.css` instead

**Comment by adamwathan** [comment]
Tailwind definitely works with PostCSS 8, it sounds like perhaps you forgot to install `postcss` when installing postcss-cli. Run npm install postcss and try again.

**Comment by adamwathan** [comment]
Here's a simple PostCSS 8 project that includes Tailwind and builds as expected:

https://github.com/adamwathan/postcss8-tailwind

Going to close as based on the original message it appears to me that the issue is just not adding `postcss` as a dependency, which is outlined as one of the installation steps for postcss-cli:

https://github.com/postcss/postcss-cli#install

![image](https://user-images.githubusercontent.com/4323180/97112764-7e168580-16bc-11eb-9e96-713791fbe720.png)
