### ISSUE TITLE
Custom colors in my tailwind.config.js file not showing on page

### ISSUE THREAD

**Issue by Ekeu** [tailwindlabs/tailwindcss#2731]
Hello,

Please I having the same issue trying to use custom colors in tail wind but with no avail.

I'm actually using Tail wind with Nuxt and I followed the steps given by the docs but up till now I can't still make it work.

Here is the basic config I did :

```
module.export = {
  purge: [],
  theme: {
    extend: {
      colors: {
        'nebula': "#5468ff"
      }
    }
  },
  variants: {},
  plugins: []
};
```
When using it for example on this hr tag:

`<hr class=" w-12 h-1 bg-nebula rounded-full mt-8" />`

It won't work.

After setting up the config I ran again` npm run dev` to recompile the css but it isn't working.

Please Help

_Originally posted by @Ekeu in https://github.com/tailwindlabs/tailwindcss/discussions/2016#discussioncomment-120798_

**Comment by AndrewFlook** [comment]
First and foremost, check your compiled css and make sure that the color is being processed and added to your app's css file.

If it's not there, chances are there was an error compiling. If absolutely nothing from Tailwind is showing up, then your sass/less/etc files are missing the @tailwind tags for compiling the Tailwind config file.

Finally, `<hr>` tags use border-color `"border border-nebula"` instead of background color.
