### ISSUE TITLE
When extending media queries, .max-width-screen-{size} looses CSS

### ISSUE THREAD

**Issue by jen-prince** [tailwindlabs/tailwindcss#2763]
### Describe the problem:

Thank you so much for this library! 1st project using and loving!  Mad props on the search in the docs!!  Im a designer so do forgive if Im really bungling this.... but since i could reproduce I figured id write up:

  When I extend in tailwind.config.js with this:

```
screens: {
                xl: { max: '1279px' },
                // => @media (max-width: 1279px) { ... }

                lg: { max: '1023px' },
                // => @media (max-width: 1023px) { ... }

                md: { max: '767px' },
                // => @media (max-width: 767px) { ... }

                sm: { max: '639px' },
                // => @media (max-width: 639px) { ... }
            },
```

 This class breaks:
`max-w-screen-sm`
tested and it looks like its the whole fam `max-w-screen-xl` etc. 
They are no longer present in the output css.  I tried to add them to the purge whitelist so i could keep on trucking but didnt have success with that approach. Could be user error on my part with that.

### Link to a minimal reproduction:

I put `max-w-screen-sm` on the parent div.  Just remove screens config in tailwind.config.js to see `max-w-screen-sm` stying kick back in.

https://play.tailwindcss.com/8eu4JVczGa?file=config

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `max-w-` (maxWidth) utilities are implemented based on there own values and also partially derived from the `screens`. The default looks like this:

```js
    maxWidth: (theme, { breakpoints }) => ({
      none: 'none',
      0: '0rem',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      '7xl': '80rem',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      prose: '65ch',
      ...breakpoints(theme('screens')),
    }),
```

This means that we will spread the `screens` using the `breakpoints` function. Essentially what this breakpoints function does is 2 things:

- Use `screen-${x}` as a name of the key for each value defined in `screens`.
- Use the `value` of each `screen`. 

However this is where the issue is, a `max-width` wants a single value. 
This means that we would create something like `max-w-screen-xl: { max: '1279px' }` which is obviously wrong.
We could hover try and guess the intended value:

- Is it a number? -> `${number}px`
- Is it an object with a `min` in there? -> `x.min`
- Is it an object with a `max` in there? -> `x.max`

But here is the tricky one, if you defined a screen like his:

```js
screens: {
  oops: { min: '500px', max: '600px' }
}
```

- Do we use `500px` as the value? 
- Do we use `600px` as the value?
- Do we use `${(500 + 600) / 2}px` as the value?

I can also see multiple use cases for this where you want either the `min` or the `max` value. That said, I don't think it is a good idea for *us* to make assumptions here (especially for the case where you define `min` and `max` values). But maybe @adamwathan has some ideas around this behaviour.

Here is my proposed solution for you:
Explicitly extend your `maxWidth` config with the value you want:

```js
theme: {
  extend: {
    maxWidth: {
      'screen-xl': '1279px'
    }
  }
}
```

Example: https://play.tailwindcss.com/WtMObBJSVE?file=config

---

Also a very important note: with switching from the default `min` screens to `max` screens doesn't make it "mobile" first anymore. By default classes apply on every breakpoint, if you provide something like `sm:bg-gray-100`, then `bg-gray-100` will kick in from `sm` (639px) and up.

By switching to a `max` value for each screen you reverse this behaviour.

**Comment by RobinMalfait** [comment]
We've had the same issues come up before (https://github.com/tailwindlabs/tailwindcss/issues/2076) and since the behaviour can't be defined in a good and expected way I believe that the best way to work around it is to use the proposed solution I mentioned.
