### ISSUE TITLE
Theme extend arrays are not merged

### ISSUE THREAD

**Issue by flybayer** [tailwindlabs/tailwindcss#2798]
### Describe the problem:

v2 now deeply merges theme extensions, so I also expected arrays to be merged.

I.e. I want the below to keep the default fontFamily.sans config but add `Inter Var` to the beginning.

```
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter var"],
      },
    },
  },
}
```

### Link to a minimal reproduction:

https://play.tailwindcss.com/VWhUl3yiv2?file=config

**Comment by benji014628** [comment]
put `const` defaultTheme = require('tailwindcss/defaultTheme');` at the top before module.exports &  `['Inter` var', ...defaultTheme.fontFamily.sans]`

**Comment by flybayer** [comment]
Yeah, that's what I'm doing as a workaround.

**Comment by benji014628** [comment]
(arrays like in fontFamily are not deep merged)
https://github.com/tailwindlabs/tailwindcss/pull/2679

**Comment by flybayer** [comment]
Yeah, I know. I'm suggesting that be changed :)

The docs indicated that everything would be merged, hence why I initially thought this was a bug.

**Comment by benji014628** [comment]
Ohhh

**Comment by benji014628** [comment]
> Yeah, I know. I'm suggesting that be changed :)
> 
> The docs indicated that everything would be merged, hence why I initially thought this was a bug.

Ohhh gotcha

**Comment by adamwathan** [comment]
@flybayer If we merged arrays you couldn't override a single font-family without overriding all of them and not using `extend`. It's also unintuitive that arrays are merged by adding things to the beginning (makes sense for font-family, but that feels like an edge-case).

It would also be annoying if you wanted to override the `shadow-xl` shadow without your own `shadow-xl` only to find that your shadows were combined (since shadows can be defined as arrays too).

So no plans to change this for now unfortunately.
