### ISSUE TITLE
Using @apply in a Vue style block throws "class does not exist" error after upgrade to 2.0

### ISSUE THREAD

**Issue by jessegavin** [tailwindlabs/tailwindcss#2846]
### Describe the problem:

I recently upgraded Tailwind from `1.4.1` to `2.0.1-compat` on a Vue app that has been working great for a long time.

I made no changes to any of my Vue code after upgrading, but now I am getting build errors on `@apply` directives in my Vue `<style>` blocks.

One example

```
(261:10) The `border-b-3` class does not exist, but `border-b-0` does. If you're sure that 
`border-b-3` exists, make sure that any `@import` statements are being properly processed
before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  259 | }
  260 | .tab:hover {
> 261 |   @apply border-b-3 border-blue-500;
      |          ^
  262 | }
  263 | 
```

### Link to a minimal reproduction:

Here is my `postcss.config.js`

```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
};
```

I have am not using a custom tailwind config file.

I am not sure how to provide a reproduction of this problem.

**Comment by adamwathan** [comment]
Can you share the whole project? There is no `border-b-3` class in Tailwind, never has been (only 0, 1, 2, 4 and 8) so if it was working before you must have defined that class custom somehow.

Going to close as the error is correct based on the config you've provided (the class doesn't exist if you haven't added it to your config since it's not in Tailwind by default) but happy to help troubleshoot if you can provide more information.

**Comment by clintongreen** [comment]
I reckon its the change from default values needing to be defined as `DEFAULT` vs `default` prior to V2
