### ISSUE TITLE
"max-width" Breakpoints Do Not Override Each Other

### ISSUE THREAD

**Issue by jen-prince** [tailwindlabs/tailwindcss#2920]
### Describe the problem:

When using multiple max-width breakpoints on an element, the smaller size breakpoint does not override the the larger one.
This is mentioned [here](https://github.com/tailwindlabs/tailwindcss/issues/1382) after the thread was closed.

### Link to a minimal reproduction:

Added to line 11: `sm:py-12 md:py-10` and [per documentation](https://tailwindcss.com/docs/breakpointsl):

```
 screens: {
                xl: { max: '1279px' },
                // => @media (max-width: 1279px) { ... }

                lg: { max: '1023px' },
                // => @media (max-width: 1023px) { ... }

                md: { max: '767px' },
                // => @media (max-width: 767px) { ... }

                sm: { max: '639px' },
                // => @media (max-width: 639px) { ... }
            },
```
https://play.tailwindcss.com/omaMfkc6Hb

**Comment by adamwathan** [comment]
Hey! It does work but you can't define your screens under `extend` if you are trying to completely replace them with max-width breakpoints:

https://play.tailwindcss.com/LCL6ahV0Tq?file=config

If you use extend, we merge the objects and since you are overriding the keys, the keys maintain their original order (just JavaScript behavior) which is the reverse of the order you defined under extend.

You'll notice the documentation does not use `extend` either:

https://tailwindcss.com/docs/breakpoints#max-width-breakpoints

Hope that helps!

**Comment by jen-prince** [comment]
oh geez, yes, that helps indeed! Thank you!!!
