### ISSUE TITLE
variantOrder doesn't seem to take 'DEFAULT' into account

### ISSUE THREAD

**Issue by kripod** [tailwindlabs/tailwindcss#2954]
### Describe the problem:

While using [tailwindcss-children](https://github.com/benface/tailwindcss-children), I wanted to extend a theme [by leveraging the new `variantOrder`](https://tailwindcss.com/docs/configuring-variants#ordering-custom-variants) key. Unfortunately, it seems like [the special `DEFAULT` value](https://tailwindcss.com/docs/configuring-variants#default) isn't taken into account while evaluating `variantOrder`.

### Minimal reproduction:

```js
// tailwind.config.js
module.exports = {
  // ...
  variantOrder: [
    'children',
    'DEFAULT', // This doesn't seem to be taken into account
    'first',
    'last',
    // (And the list goes on…)
  ],
  variants: {
    extend: {
      maxWidth: ["children", "DEFAULT"],
    }
  }
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you elaborate on what you mean exactly? The code you shared seems to work as expected here.

Some things to notice:
- In the default `variantOrder`, we only order the relation between certain variants that are important. For example, it's good to have `disabled` after `hover` because `disabled` is more "important".
- If we don't have the variant in the list (for example `DEFAULT` or `responsive`), then it means that we move those variants to the very front.

If you want to have fine grained control on where the `DEFAULT` variant lives, then you can dan 2 things:

1. Update the variantOrder, as you did in your config:

```js
const defaultConfig = require('tailwindcss/defaultConfig');

module.exports = {
  // ...
  variantOrder: ['DEFAULT', ...defaultConfig.variantOrder], // This will put it in the very front
}
```
 
2. You can use the non-extend version of variants:

```js
const defaultConfig = require('tailwindcss/defaultConfig');

module.exports = {
  // ...
  variants: {
    maxWidth: ['children', 'DEFAULT', ...defaultConfig.variants.maxWidth]
  }
}
```

**Comment by kripod** [comment]
Thank you for your insightful answer, it really helps a lot! It seems that my problem has gone away since then and I also cannot reproduce this issue again. I highly appreciate all the efforts you’ve put into your reply. Closing this issue for now, keep up the awesome work! 🙌
