### ISSUE TITLE
Error `cb.apply is not a function` on using `tailwindcss-cli`

### ISSUE THREAD

**Issue by dector** [tailwindlabs/tailwindcss#2972]
### Describe the problem:

1. Run `npx tailwindcss-cli@latest build` as described in [docs](https://tailwindcss.com/docs/installation#using-tailwind-without-post-css)

ER: output css file is built

AR: `npm ERR! cb.apply is not a function`

### Environment

```
$ node --version
v15.3.0

$ npm --version
6.14.9
```

**Comment by adamwathan** [comment]
Hmm can't seem to reproduce (but using node 14 and npm 7). Can you try using npm 7?

**Comment by dector** [comment]
Hm.. When I'm installing dependencies via `npm` to local folder - `npx tailwindcss build` works as expected. But otherwise I have different kind of errors.

Sorry, I'm not from JS world. Shouldn't `npx` execute my `tailwindcss@latest` and resolve it's dependencies automatically (without installing them in local folder) or am I missing something?

**Comment by adamwathan** [comment]
You will have errors using `npx tailwindcss@latest build` if you don't have it installed locally, but `npx tailwindcss-cli@latest build` should work. The CLI package includes Tailwind's peer dependencies.

**Comment by adamwathan** [comment]
Going to close since no further information has been provided and can't reproduce even after switching to same node and npm versions. I suspect maybe you were running the wrong command based on your previous comment (`tailwindcss@latest` instead of `tailwindcss-cli@latest`), so hopefully that's the only issue.

If still running into this feel free to open another issue 👍

**Comment by dector** [comment]
Unfortunately nor `npx tailwindcss@latest` neither `npx tailwindcss-cli@latest` didn't work without installing packages with `npm install` before that 😞 .
