### ISSUE TITLE
Gradient from-transparent to-white show's dark gradient on safari

### ISSUE THREAD

**Issue by delz-dev** [tailwindlabs/tailwindcss#2985]
### Describe the problem:

![image](https://user-images.githubusercontent.com/54885840/101005547-2bed3d80-3561-11eb-9fd1-6507214cfd02.png)

CSS Generated by tailwind:
```
.to-white {
--tw-gradient-to: #fff;
}
.from-transparent {
--tw-gradient-from: transparent;
--tw-gradient-stops: var(--tw-gradient-from),var(--tw-gradient-to,transparent));
}
```

The problem is: `--tw-gradient-from: transparent;`
Safari renders transparent as rgba(0,0,0,0) (maybe a safari bug?)

If I change `transparent` to `rgba(255,255,255,0)` it looks good and as intended.

![image](https://user-images.githubusercontent.com/54885840/101007617-c51c5400-3561-11eb-98d4-3294208d18ef.png)

### Link to a minimal reproduction:

Check in safari: https://play.tailwindcss.com/rRYc62m5n4
Looks right in chrome: https://play.tailwindcss.com/rRYc62m5n4

**Comment by joshhanley** [comment]
I just ran into the same issue on Safari for MacOS (Safari v14.0.1) and iOS (iOS v14.2).

See below screenshot, top half is Chrome on Mac, bottom half is Safari on Mac.

![Screen Shot 2020-12-05 at 12 15 49 pm](https://user-images.githubusercontent.com/882837/101229381-13f9f300-36f4-11eb-8d62-70b5307e20dc.png)

Version:
tailwindcss/postcss7-compat: 2.0.1

**Comment by adamwathan** [comment]
Never use `from-transparent`, Tailwind will automatically do the transparent stuff for you magically in a way that works with Safari by default if you just leave off one of the gradient stops.

Instead of `bg-gradient-to-b from-transparent to-white` use `bg-gradient-to-t from-white`, the transparent side will be handled automatically in a Safari-compatible way by correctly calculating the right transparent color to use based on the from color.

https://play.tailwindcss.com/Sc3YgAy74n

**Comment by joshhanley** [comment]
Thanks Adam! Worked for me. Sorry I missed it in the docs! For anyone else looking, note here in the docs https://tailwindcss.com/docs/gradient-color-stops#starting-color

>Starting Colour
>Gradients fade out to transparent by default.

>Ending Colour
>Gradients to do not fade in from transparent by default. To fade in from transparent, reverse the gradient direction and use a from-{color} utility.
