### ISSUE TITLE
Animations pulse and ping do not work as expected

### ISSUE THREAD

**Issue by jevail** [tailwindlabs/tailwindcss#3007]
When using the default examples from tailwindcss.com for animations, i get unexpected results in Safari and Firefox (not tested other browsers).
Pulse only pulses the border of the divs.
Ping has a huge effect and does not align with the div.

Link to example:
https://play.tailwindcss.com/lZ4n9h5D8P

<img width="719" alt="Schermafbeelding 2020-12-05 om 09 56 08" src="https://user-images.githubusercontent.com/24815508/101238373-1baf9c80-36e0-11eb-8049-4cb7432811d9.png">

**Comment by jevail** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/24815508/101239422-b069c880-36e7-11eb-8438-c0510d6683cc.png">

**Comment by adamwathan** [comment]
Hey! I'm not really sure what you're expecting here because this demo is a bit all over the place, but everything is working the way it's supposed to.

This is the element you've added ping to, which is a huge full screen circle, so when it pings, its a huge full screen ping:

![image](https://user-images.githubusercontent.com/4323180/101246556-1ce1c900-36e2-11eb-9041-1d1914876511.png)

Pulse works as expected as well, but you were using `light-blue` which isn't an actual color in the default Tailwind config so you weren't seeing anything:

https://play.tailwindcss.com/oBq75XBeAD

The examples on the website are not meant to be copied and pasted, they are trimmed down just to show you the code that is relevant. If we showed all of the code for an example it would be extremely noisy and hard to see the relevant classes, because so much of the code is just design stuff for making the demo look nice in that specific context. We also use a custom config for the actual Tailwind site that includes extra colors and stuff, which is why when you copy from dev tools you see stuff that doesn't exist in the default config.

**Comment by jevail** [comment]
So much thanks for your personal answer! It’s much appreciated.  The fact that I’m not a native speaker makes it quite hard to  specify the problem I encountered. When i pulse a div (sorry, in my own code i use lightBlue which is specified in my custom tailwind config), i only see the border pulsing. I will be looking at the source code of the website. I was not informed that the example code is not exactly the rendered version.

Have a nice weekend!

Huge fan of all your work.

Kind regards,
Jesse

Verstuurd vanaf mijn iPhone
