### ISSUE TITLE
Shadow on an input is not rendered on iOS 14 Safari

### ISSUE THREAD

**Issue by edgarasben** [tailwindlabs/tailwindcss#3009]
Shadow on an input is not rendered on iOS 14 Safari.

https://play.tailwindcss.com/gLuPbHB8Zo

![4915076C-E680-485E-B03A-23006A68020B](https://user-images.githubusercontent.com/725324/101260708-fb103280-3731-11eb-9686-67013f4c3052.png)

**Comment by saadeghi** [comment]
Try adding `appearance-none` class

**Comment by adamwathan** [comment]
Yep as @saadeghi this is just due to how Safari renders form controls by default — they don't respect certain properties unless you override the `appearance` property.

https://play.tailwindcss.com/FPG9eLVcN5

I would recommend using the [`@tailwindcss/forms`](https://github.com/tailwindlabs/tailwindcss-forms) plugin if you want a sensible starting point for form styles that behaves consistently across different browsers.

**Comment by edgarasben** [comment]
Surely works now, thank you!
