### ISSUE TITLE
Suggested Create React App Install Not Compatible With React Scripts 4

### ISSUE THREAD

**Issue by shantiscript** [tailwindlabs/tailwindcss#3031]
The in the docs suggested route of installing tailwind 2.0 with CRACO (https://tailwindcss.com/docs/guides/create-react-app)
creates an issue when using React Scripts 4 (https://github.com/DocSpring/craco-less/issues/52) as craco is not working with react scripts 4 yet. 
I have seen installations just using npm scripts to handle the build process. But the ones i found are outdated (purge and postcss still need to be setup separatly)
Any chance  you could provide an alternative setup that doesn't use craco but still works with all the new features?

**Comment by shantiscript** [comment]
Craco v 6 was just realeased and this https://github.com/gsoft-inc/craco/pull/219 fixed the issue mentioned.
Please close this if using npm scripts is not a valid second option

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Our guides are mainly focused so that you can integrate tailwindcss with your existing (or new) build chain. 
We've seen people use separate npm scripts so that they can build their JS and tailwind separately and use something like `concurrently` to make it all work.

However we like to keep everything in the same build chain, that's one of the reasons why we chose `craco` instead of a few npm scripts.
