### ISSUE TITLE
@fullhuman/postcss-purgecss@3.1.0 unexpectedly causes postcss@8.2.1 to be installed

### ISSUE THREAD

**Issue by danielbachhuber** [tailwindlabs/tailwindcss#3094]
### Describe the problem:

I'm using `@tailwindcss/postcss7-compat@^2.0.1`. Starting this morning, when I ran `npm install`, the `@fullhuman/postcss-purgecss` dependency updated to 3.1.0, which would unexpectedly case `postcss@8.2.1` to be installed.

#3090 was my confusing first report of this. There's also a confusing Twitter thread about it: https://twitter.com/dbchhbr/status/1338633809223241729

Here's my original `package.json` and `package-lock.json` https://github.com/danielbachhuber/tailwind-issue-3090/commit/ac5ca03419ec038010a32d8ac2bdd6037b7f8073

Here's what happens to my `package-lock.json` when I run `npm install`: https://github.com/danielbachhuber/tailwind-issue-3090/commit/62bfd44b293e251c3abc6dabdb0697d41585b1e3

I was able to force downgrade with `npm install @fullhuman/postcss-purgecss@3.0.0`.

It seems like this might be the culprit but I'm unsure: https://github.com/FullHuman/purgecss/commit/beb4a5913c5508a88053aa77926b9db9354013ee#diff-8ff946405ac17a6430f833861aa54304d9fbec7ba577b111e4550ee08f05472cL29-R36

**Comment by adamwathan** [comment]
Looking at your package.json file you have some mismatched version, for example you have PostCSS 8 installed but you're using the PostCSS 7 compatibility build of Tailwind. Wonder if this could be contributing to any issue you are seeing.

Can you create an actual minimum reproduction repo that demonstrates the error (not just a package.json file) and only includes the relevant dependencies? Currently I can't reproduce the issue as there is not enough information in the repository.

What is the actual error you are seeing and does dropping to PurgeCSS 3.0.0 fix it? PurgeCSS 3 is meant to be compatible with PostCSS 7 and 8, so just being installed is not a problem, the problem is whatever actual error you are seeing as a result.

**Comment by danielbachhuber** [comment]
I can't reproduce the issue now 🤕 

I spent another half hour writing out reproduction steps, only to find that `npm remove @fullhuman/postcss-purgecss` and allowing the silent upgrade works as expected.

🤷 

In any regard, thanks for your help!
