### ISSUE TITLE
Responsive directive bug when multiple classes are used

### ISSUE THREAD

**Issue by tskaiste** [tailwindlabs/tailwindcss#3279]
### Describe the problem:

When using the `@responsive` directive for multiple custom classes only the last class in the selector gets the `:sm`, `
:md`, etc. But when using HTML tags, the selector is generated correctly. Is this a bug or is it intended to work like that?

CSS code:
```
.logo {
  @apply hidden;
}

@responsive {
  .logo-container .logo {
    @apply block;
  }
  .logo-container img {
    @apply block;
  }
}
```

Generated output:
```
.logo-container .sm\:logo {
    display: block;
}

.sm\:logo-container img {
    display: block;
}
```
Expected output:
```
.sm\:logo-container .logo {
    display: block;
}

.sm\:logo-container img {
    display: block;
}
```
### Link to a minimal reproduction:

Reproduced on tailwind playground:
https://play.tailwindcss.com/iWn5uGpBI2

**Comment by adamwathan** [comment]
This is by design currently, variants always target the last class in the selector because that's what made sense for any complex selectors that were included in Tailwind.

One simple workaround for now is to rewrite your rules like this:

```css
.logo {
  @apply hidden;
}

@responsive {
  .logo-container [class~="logo"] {
    @apply block;
  }
  .logo-container img {
    @apply block;
  }
}
```

No plans to change this at the moment so going to close, but hope that solution helps 👍🏻
