### ISSUE TITLE
Td borders are not set to 0 by default when requiring @tailwindcss/typography

### ISSUE THREAD

**Issue by DamienFF** [tailwindlabs/tailwindcss#3290]
### Describe the problem:

In Tailwind 2.0.2, preflight set all table cell borders to 0.
When requiring @tailwindcss/typography in tailwind.config.js, this is however not the case anymore: 
- the rows (except the last one) have a border.

What is expected: not having a border when the typography plugin is used.

Thanks in advance.

### Link to a minimal reproduction:

https://play.tailwindcss.com/auIX2nmTGp

**Comment by adamwathan** [comment]
Hey! This is by design, that's how tables are meant to look inside of a `prose` block. The typography plugin is designed to add sensible opinionated default styles to blocks of content coming from markdown/CMS databases/etc. If you want to custom style a table, don't put it inside a `prose` parent 👍🏻
