### ISSUE TITLE
Incorrect position for pointer to a nonexistent in error messages

### ISSUE THREAD

**Issue by stancl** [tailwindlabs/tailwindcss#3299]
### Describe the problem:

Here I use `dark:...` correctly, then I use `dark` incorrectly, and then I use it correctly again.

The error message should show the `^` character below my second use of `dark`, but it shows it below the first — correcy — use/
```
The `dark` class does not exist. If you're sure that `dark` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

   7 | 
   8 | .my-class {
>  9 |     @apply bg-gray-100 text-black dark:bg-gray-800 dark dark:text-gray-200;
     |                                   ^
  10 | }
  11 | 
```

### Link to a minimal reproduction:

Playground link: https://play.tailwindcss.com/AE21y2T8X6?file=css

(Though the full error message doesn't show up on playground)

**Comment by adamwathan** [comment]
I don't think this can easily be fixed on our end unfortunately, as we are just using a fairly constrained API exposed via PostCSS:

https://postcss.org/api/#nodeerroroptions

Not ideal for sure but going to close because just no plans to prioritize this one. If someone is bothered by it enough to PR a fix I'm happy to look at it though 👍🏻
