### ISSUE TITLE
Ring classes produced syntactic error in compiled CSS

### ISSUE THREAD

**Issue by gorilas** [tailwindlabs/tailwindcss#3328]
The compiled css that looks like this: `--tw-ring-inset:var(--tw-empty, )` throws an error in an accessibility validator tool because of syntactic error in compiled css file.

The source from error could be this: https://github.com/tailwindlabs/tailwindcss/blob/879f0887ed07d29edf2bc558507699c10bdb02a0/src/plugins/ringWidth.js#L24

**Comment by adamwathan** [comment]
That is valid CSS, `var(--tw-empty, )` resolves to the empty value (just blank), it's a technique for conditionally rendering a value in a CSS declaration.

See the end of this article for more explanation:

https://adamwathan.me/composing-the-uncomposable-with-css-variables/

This trick is necessary for the ring classes to work. Is there an actual bug or unexpected behavior you are running into that you assumed was because of this? If so please open a new issue that describes the actual problem you are seeing along with a reproduction 👍🏻

**Comment by quietmint** [comment]
Can you set it to `0px` as mentioned in https://github.com/tailwindlabs/tailwindcss/issues/2889? Do you really **need** this problematic syntax in this case?

**Comment by adamwathan** [comment]
Yes it is necessary. How else would you conditionally add just the word `inset` in a box-shadow?

```css
box-shadow: var(--ring-inset) 0 0 0 2px blue;
```

The only way that can work is if it's possible for `--ring-inset` to resolve to an empty value, there's no "outset" keyword or anything you can use.

It's not problematic syntax at all, it's 100% supported in all browsers that support CSS variables and is part of the spec.

https://www.w3.org/TR/css-variables-1/#syntax

<img width="740" alt="image" src="https://user-images.githubusercontent.com/4323180/107886621-e89f3b80-6ece-11eb-9884-f8ac1b0a52fe.png">

**Comment by giuliac1989** [comment]
Hi! I've minified my code with cleanCSS but still got the error
<img width="457" alt="Schermata 2021-03-17 alle 12 27 02" src="https://user-images.githubusercontent.com/33481534/111460377-343a4480-871c-11eb-8821-193c85e1f22a.png">

**Comment by adamwathan** [comment]
Hey! That's syntactically valid, the error is with whatever the lint tool is you are using.

```css
/* This is totally valid CSS */
foo {
  color: var(--color, );
}
```

**Comment by imperatormk** [comment]
![twringinsetw3](https://user-images.githubusercontent.com/23061008/129120473-7116c849-4155-4fa2-939e-be9b2d57fbd0.png)

What about this on validator.w3 also?
