### ISSUE TITLE
 space-x-* applied after input type hidden

### ISSUE THREAD

**Issue by riencoertjens** [tailwindlabs/tailwindcss#3350]
### Describe the problem:

when using `flex space-x-8` when there is a `<input type="hidden" />` as a the first child, a margin is applied to the first visible child element

## expected
no extra spacing

### Link to a minimal reproduction:

https://play.tailwindcss.com/OTcySBQoic

**Comment by adamwathan** [comment]
Hey! This is expected behavior, if you want an element to be ignored by the `space` utilities you need to add the `hidden` attribute:

```
<input type="hidden" hidden ... />
```

A little weird I know but it's the only practical solution. Here's another thread with more conversation:

https://github.com/tailwindlabs/tailwindcss/issues/2740#issuecomment-736711525
