### ISSUE TITLE
Tailwind styles not importing in Vue.js project

### ISSUE THREAD

**Issue by fydbill** [tailwindlabs/tailwindcss#3355]
### Describe the problem:

Hello,

 I am setting up a new Vue.js project, for which I am trying to set up Tailwind CSS. I am doing all steps I've found online, but I cannot seem to get the styles to be compiled at all. They just... don't get injected. I must be doing something wrong, but I cannot find anything about it online. 

### Link to a minimal reproduction:

I have the following on my "index.css"...

```
@tailwind base;
@tailwind components;
@tailwind utilities;

```
The following on postcss.config.js...

```
// ./postcss.config.js

const autoprefixer = require('autoprefixer');
const tailwindcss = require('tailwindcss');

module.exports = {
    plugins: [
        tailwindcss,
        autoprefixer,
    ],
};
```

And here's my main.js with what should be the correct import statement (the folder is correct, I have double checked)

```
import Vue from 'vue';
import App from './App.vue';

import('@/assets/styles/index.css');

Vue.config.productionTip = true;

new Vue({
    render: h => h(App)
}).$mount('#app');

```

I have tried to add the import on my App.vue file but it did not solve the issue. If any more code is needed I will provide it upon request. My tailwind.config.js is the one npm generated, I have not touched that file. 

Meanwhile, using Inspect Element in Chrome shows this "<style>" tag inside the head section of the page, which was what made me think of a configuration issue; I do not think this is expected behaviour.

```
<style type="text/css">
@tailwind base;
@tailwind components;
@tailwind utilities;
</style>
```

**Comment by adamwathan** [comment]
Hey! This is definitely a configuration issue in the project but since no actual reproduction has been provided (in the form of a project I can actually clone down and use to help fix the issue), there's not much I can do to help without manually creating a Vue project from scratch (and is it Vue 2? Vue 3? Using Vue CLI? Using Nuxt? Using Vite? I don't know) and trying to recreate this problem.

My only hunch is that using a dynamic import is the problem, and you should try a regular import:

```js
import Vue from 'vue';
import App from './App.vue';

import '@/assets/styles/index.css';

Vue.config.productionTip = true;

new Vue({
    render: h => h(App)
}).$mount('#app');
```

Going to close since I can't help troubleshoot without a reproduction and this is not actually a bug in Tailwind, but consider opening a [discussion thread](https://github.com/tailwindlabs/tailwindcss/discussions) if this is still a problem for you and make sure to actually provide a GitHub repository with all of the code otherwise it's not possible for anyone to help.

**Comment by fydbill** [comment]
So... it's a little bit of a freak issue to me, but maybe you can explain - it's been solved, but how?

I was creating the project using the Visual Studio IDE (to take advantage of its code editor). For a seemingly peculiar reason, PostCSS doesn't mesh well with Visual Studio or it's compile/build processes. Once I recreated the project using Vue CLI, everything worked. So the issue was... nothing? The configuration and everything is identical!
