### ISSUE TITLE
@apply doesn't respect "important" complex variable

### ISSUE THREAD

**Issue by kctdfh** [tailwindlabs/tailwindcss#3374]
### Describe the problem:

I've defined a complex variable called "important" using the plugin code provided in the docs [here](https://tailwindcss.com/docs/plugins#complex-variants). I've added it as a variant to a few utilities using extend - padding being one. In my HTML, I can use `!p-0` and it applies as `{padding: 0 !important}` but when I try to use `@apply` to define a custom class, it doesn't apply the `!important` declaration.

`.no-padding {@apply !p-0;}` comes out as `.no-padding {padding: 0}` without !important.

I've tried both the code example offered in the docs and `tailwindcss-important` package. In both cases, !p-0 is generated but won't be applied as important when using the apply directive.

### Link to a minimal reproduction:

Try it here:
https://play.tailwindcss.com/Uj7G1ByZY2

Please inspect the rendered page to see what is applied to the class.

I initially thought maybe `@apply` has an issue with the exclamation mark and somehow ignores it. So I defined another variable called `important-noHyphen` with the same code and set the prefix to `.IMP-` but `@apply` still ignores the important declaration. 

### Question

Is this an intended behavior? Should I stick to using `.no-padding {@apply p-0 !important;}` or can I make a change somewhere and make `.no-padding {@apply !p-0;}` work?

Thanks!

**Comment by Lacroute** [comment]
Maybe you can try the interpolation style? https://v1.tailwindcss.com/docs/using-with-preprocessors#sass

**Comment by adamwathan** [comment]
This is just part of the design of `@apply`, it automatically strips all `!important` stuff since typically you don't want that. You can add `!important` to the end of an `@apply` statement to make something important:

https://tailwindcss.com/docs/functions-and-directives#apply

<img width="860" alt="image" src="https://user-images.githubusercontent.com/4323180/106318631-33b61f00-623e-11eb-9b6e-e6e7f8e7886b.png">

No plans to change this currently but you should be able to work around it with the information provided 👍
