### ISSUE TITLE
Tailwind 2.0.2 Escaping special characters problem while creating custom theme variables

### ISSUE THREAD

**Issue by mudassirzr** [tailwindlabs/tailwindcss#3428]
I'm getting this error when adding a custom translate scale in my tailwind config and using the same using `@apply`:
`Error: Unexpected '/'. Escaping special characters with \ may help.`

I added a custom translate like this:
```
module.exports = {
  theme: {
    extend: {
      translate: {
        '5/11': '45.45454545%',
      },
    },
  }
}
```
Dependencies:
```
{
    "@fortawesome/fontawesome-free": "^5.15.1",
    "autoprefixer": "^10.2.1",
    "next": "10.0.5",
    "node-sass": "^5.0.0",
    "postcss": "^8.2.4",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tailwindcss": "^2.0.2"
  }
```
can be reproduced here:
https://play.tailwindcss.com/VzpgKSl4wu?file=css

**Comment by arthurpietruch** [comment]
Looks like the escaping problem appears only when you apply the custom translation in your CSS with a negative value (```-translate-x-5/11```).

You just have to provide a custom value for the negative side of your translation 5/11 and it works perfectly :
```
translate: {
        '5/11': '45.45454545%',
        '-5/11': '-45.45454545%',
      },
```
On the contrary, ```-translate-y-1/2``` does not trigger an error because ```-1/2``` already exists by default.

**Comment by mudassirzr** [comment]
I was of the impression that it creates the negative one on it's own.
Anyways, I appreciate the time you took to answer this. Thanks!
