### ISSUE TITLE
some styles are broken when the app is deployed for production using vue cli 4

### ISSUE THREAD

**Issue by boussadjra** [tailwindlabs/tailwindcss#3436]
### Describe the problem:

The styles work fine in local development mode but when I deploy the app on netlify, some styles are broken, for example for the circular badges which are defined [here](https://github.com/boussadjra/vue3-tailwind2/blob/main/src/components/data-display/Badge.vue) and used [here](https://github.com/boussadjra/vue3-tailwind2/blob/main/src/views/components-demo/Badges.vue)

**dev** :
![image](https://user-images.githubusercontent.com/11801238/105696478-af912e00-5f03-11eb-8d07-577301edf416.png)

**deployed** : 

![image](https://user-images.githubusercontent.com/11801238/105696525-bfa90d80-5f03-11eb-8727-dedd7d1d0230.png)

### Link to a minimal reproduction:

the github repo https://github.com/boussadjra/vue3-tailwind2

the live demo https://vuewind.netlify.app/ to reproduce the behavior you could click on components in the navbar the select badges from  the sidebar

**Comment by adamwathan** [comment]
Hey! This is because you are dynamically creating classes using string interpolation (bg-${color}-500, etc) which means PurgeCSS doesn't know what classes to keep.

Make sure you read our documentation on writing purgeable HTML:

https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html
