### ISSUE TITLE
[2.x] Default screen breakpoints gone after defining custom ones inside extend!

### ISSUE THREAD

**Issue by mnaderian** [tailwindlabs/tailwindcss#3472]
### Describe the problem:

When defining new breakpoints in `tailwind.config.js` and inside `extend`, the breakpoints are supposed to exist alogside the default ones. But unfortunately the default ones stop working! even though I have defined my screen breakpoints inside `extend`. 

So I redefined all my custom ones plus the default ones inside `screen` and outside of `extend`, and it worked!

Seems that there's a problem with custom screens when defined inside `extend`!

### Link to a minimal reproduction:

https://play.tailwindcss.com/LYuof35Xuy?file=config

**Comment by adamwathan** [comment]
This is because when you extend anything, it's added to the end of the defaults, and with screens the order is important since everything is supposed to start from the smallest breakpoint and go to the largest.

If you look at the compiled CSS you'll see all the screens _are_ being generated, but the 450px ones are at the very end, so they are overriding the others. The right approach at least until we decide to come up with a different API for this is to do what you suggested:

```js
const defaultTheme = require('tailwindcss/defaultTheme')
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
      screen: {
        'cbp': '450px',
        ...defaultTheme.screens,
      },
    extend: {
      colors: {
        'light-blue': colors.lightBlue,
        cyan: colors.cyan,
      },
    },
  },
  variants: {},
  plugins: [],
}

```

**Comment by mnaderian** [comment]
Thank you. You are are my hero.

**Comment by dalmo3** [comment]
There's a typo in both examples above. `screen: ...` should be `screens: ...`. 

Just thought it was worth mentioning so future readers don't spend minutes confused by it like I did.
