### ISSUE TITLE
Not reloading changes? Have to stop and start service

### ISSUE THREAD

**Issue by joshbedo** [tailwindlabs/tailwindcss#3487]
Wondering if live reload is something that is supposed to work or if it doesn't work? Any time I change my CSS input file I have to stop CRA and restart it to see the new CSS changes. This is what my scripts look like. 

```
    "start": "npm run build:style && react-scripts start",
    "build:style": "tailwind build src/styles/index.css -o src/styles/tailwind.css",
 ```

**Comment by richadr** [comment]
Live reload will work if you configure it.  In the config that you posted, you are building css once (without watch and live reload) before starting the CRA webserver (which does watch and live reload).

Instead of building with a separate command, consider: https://create-react-app.dev/docs/adding-a-stylesheet

If you wish to keep a separate build command, you need to configure a way to watch for file changes and trigger rerunning that build command yourself.

**Comment by adamwathan** [comment]
Yeah you are building your CSS once in your command, not using any sort of watch setup. I would recommend following our guide for using Tailwind with CRA, then things will rebuild automatically:

https://tailwindcss.com/docs/guides/create-react-app
