### ISSUE TITLE
Dark mode background color not applying when `body` styles are extracted using @apply

### ISSUE THREAD

**Issue by david-buck** [tailwindlabs/tailwindcss#3942]
I have this in my globals.css:

`body {
  @apply font-body antialiased max-w-xl mx-auto text-gray-900 bg-white dark:bg-gray-800 dark:text-white transition-colors;
}`

And it works in the old way, but with JIT, it doesn't apply the `dark:bg-gray-800`, while the `dark:text-white` works fine. 

The result is white text on a white background in dark mode. 

Background colour changes to other elements apply fine, only `body` is unaffected.

**Comment by bradlc** [comment]
This issue is a bit dated now that JIT mode has been added to `tailwindcss`. I have taken a look at your reproduction @alizahid and the issue seems to be resolved when using `tailwindcss` with JIT mode enabled, instead of the old `@tailwindcss/jit` module.

For anyone having a similar issue, make sure you aren't using the `@tailwindcss/jit` module. If you are still having issues after that please open a new issue with a reproduction, thanks!
