### ISSUE TITLE
Using prefix in config causes compilation issues with @apply

### ISSUE THREAD

**Issue by austenc** [tailwindlabs/tailwindcss#3966]
### What version of @tailwindcss/jit are you using?

v0.1.18

### What version of Node.js are you using?

v15.5.0

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel Mix 6 / PostCSS latest

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/austenc/tailwindcss-jit-bug

Using a `prefix` function in the Tailwind config causes an error in the build when using utility classes with `@apply`. Removing the `prefix` function allows the build to work as expected. 

Here's the error:
![image](https://user-images.githubusercontent.com/575421/113323601-667aa300-92d3-11eb-8fd1-0f216685c1d5.png)

**To Reproduce:**
- Clone the example repository (https://github.com/austenc/tailwindcss-jit-bug)
- Run `npm install`
- Try running `npm run dev`

Let me know if there is more helpful information I can provide, and thank you!

**Comment by bradlc** [comment]
Hey @austenc. Cloned your repo and was able to reproduce but it looks like upgrading to `tailwindcss@canary` with JIT mode enabled resolves the issue 👍 Feel free to open a new issue if you're still running into this

Also the `prefix` function [works slightly differently](https://github.com/tailwindlabs/tailwindcss-jit/issues/159#issuecomment-808914202) in JIT mode so that's worth keeping in mind.

**Comment by austenc** [comment]
Hey @bradlc, thanks for digging in on this.

We've been using the JIT mode in production for a few weeks, works great! 🤘
