### ISSUE TITLE
[JIT] outputting classes in a different order that non-JIT Tailwind

### ISSUE THREAD

**Issue by brandonpittman** [tailwindlabs/tailwindcss#3995]
### What version of Tailwind CSS are you using?

2.1

### What version of Node.js are you using?

15.12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/brandonpittman/tailwind-jit-transparent/blob/master/styles.css

Until now, you could use `border border-transparent border-blue-400` and the blue border color would when. When using JIT, the transparent wins. Now transparent comes after everything but `border-black`. Suddenly I have buttons with transparent borders because the color classes are defined before the transparent border

**Comment by paste** [comment]
same here, I am getting randomly different order of classes in compiled JIT css, even from one compilation to the next.

**Comment by innocenzi** [comment]
Not sure if it's the same issue, but I just stumbled upon a case where the order of generated classes was different from JIT and the production build. Didn't try without JIT. Specifically, `focus-visible:ring-offset-<color>`, where I had to change `color` in my configuration.

**Comment by adamwathan** [comment]
Hey! Yeah this is by design, internally we mark each class with a "sort number" to make sure the final CSS order makes sense, but for classes that are part of the same category we give them the same number to avoid ending up with really huge sort numbers. We're using BigInt but BigInt math starts to slow down the bigger the number gets.

Solution is just to not use ambiguous classes on an element, like don't put two border color classes, just put one. We've have a lint warning for this in the VS Code extension for a long time now because it bites people in other ways even without JIT.

**Comment by brandonpittman** [comment]
@adamwathan I think this should be mentioned somewhere then because it works quite differently than how it used to. It may be a bad idea, but it worked the past three years, and switching to JIT was an hours-long process to make sure things like border color weren’t appearing twice.

**Comment by rightaway** [comment]
@adamwathan Would the difference in ordering change how things look? For example if a vue component has `border-transparent` then from that component's parent you add `border-black`, you'd expect it to override the border color only if `border-black` appears in the CSS file after `border-transparent` since the last one in the CSS file takes precedence. But if the order gets generated differently then won't it really affect things? Shouldn't the order be deterministic in some way?

**Comment by rightaway** [comment]
@adamwathan At least for numeric values like `opacity` and anything that uses `spacing` or `color` shouldn't there be a consistent order whether it's high to low or low to high? That's how it used to be and would decrease any unexpected issues in how things appear.

**Comment by rightaway** [comment]
@adamwathan Whats the recommended way to override? If a vue component has `opacity-50` inside it and you want to call it as `<Component class="opacity-100">` expecting that the value you provided overrides the value set inside, what is the tailwind approach to doing it?

**Comment by adamwathan** [comment]
You can't really do that, that's just a limitation of CSS. In the AOT engine, if a component had `opacity-75` and you wanted to override it with `opacity-25` you'd be screwed too you know?

The answer is to make that sort of thing a prop in your Vue component and have it handled internally, or if you _really_ want to override use the important modifier `<Component class="!opacity-100">`.

You shouldn't ever add two classes that are competing for the same property though, only ever one at a time. How you ensure that only one is being added is really up to you and how you want to design the API of your component.

**Comment by rightaway** [comment]
@adamwathan That makes sense, but how about for the arbitrary styles like `top-[-113px]`? Can't those be put at the end of the generated css since there's probably never a case where you don't want it to have precedence over the built in styles?
