### ISSUE TITLE
Using prefix tw- using Create React App, classes are not applied on save reload

### ISSUE THREAD

**Issue by ciaranmccaughey** [tailwindlabs/tailwindcss#3996]
### What version of Tailwind CSS are you using?

2.0.2

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/ciaranmccaughey/tailwind-prefix-issue.git

I am using Create React App with Tailwind CSS. I am also using the prefix 'tw-', so in my codebase every class starts with 'tw-'. 

I am having the issue of when I use a class for the first time, save and CRA reloads, it does not apply the CSS class that I added. However, if I run npm run start or save my tailwind.config.js file, the CSS class will work.

tailwind.config.js file below:

```const colors = require('tailwindcss/colors')

module.exports = {
  purge: {
    enabled: true,
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    options: {},
  },
  prefix: 'tw-',
  important: true,
   darkMode: false, // or 'media' or 'class'
   theme: {
    zIndex: {
     '50': 100000,
    },
     extend: {},
   },
   variants: {
     extend: {},
   },
   plugins: [],
 }
```
craco.config.js
```
module.exports = {
    style: {
      postcss: {
        plugins: [
          require('tailwindcss'),
          require('autoprefixer'),
        ],
      },
    },
  }
  ```

**Comment by adamwathan** [comment]
Hey! Looks like the reproduction repository is empty — do you mind opening a new issue with a reproduction? I try to close things here as much as possible if I can't troubleshoot it because if not, they tend to stay open forever as it's pretty common that people end up figuring out the issue themselves and never coming back to close the issue.

Closing this so we can get a new issue with a reproduction but more than happy to help if can be reproduced, just don't want to let stuff get stale here while waiting for the reproduction in case this isn't an issue for you anymore.
