### ISSUE TITLE
Seemingly can't combine .container with padding or margin utilities.

### ISSUE THREAD

**Issue by iantbutler01** [tailwindlabs/tailwindcss#4028]
### What version of Tailwind CSS are you using?

2.1.1

### What version of Node.js are you using?

15.4.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux Pop-OS

### Reproduction repository

https://www.youtube.com/watch?v=R3shJUjWFtM

### Describe your issue

Simple issue, applying the container class and then any of the margin or padding utility classes, the utility classes are ignored. I was surprised because the container docs even tell you to use the utility classes to control things like that.

**Comment by adamwathan** [comment]
Hey! I cannot reproduce this, it definitely works:

https://play.tailwindcss.com/WI8TLbPNPn

If this is still an issue after seeing the playground instance, please open a new issue and include a reproduction.

My only guess is you have your `@tailwind` directives in the wrong order, `components` must come before `utilities` since declaration in CSS order is important:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
