### ISSUE TITLE
JIT includes non-strings in javascripts for matching classnames

### ISSUE THREAD

**Issue by regularlabs** [tailwindlabs/tailwindcss#4057]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

cli

### What version of Node.js are you using?

12.13.1

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

N/A

### Describe your issue

When using jit mode, words found inside javascript files are included in the final CSS.
For instance:
```
if(!button) {
   el.classList.add('hidden');
}
```
That will result in CSS containing the classes for `.\!button` and `.hidden`. The `.\!button` class should not be included of course.

This is not an issue when not using jit and relying on purgecss.

**Comment by bradlc** [comment]
Hey @regularlabs. This is by design. We use [simple regular expressions](https://github.com/tailwindlabs/tailwindcss/blob/master/jit/lib/expandTailwindAtRules.js#L12-L13) to extract possible classes from the file contents. If we were to actually parse JavaScript files it would dramatically increase the time taken to extract the classes. False-positives can absolutely occur, like you described, but these are typically rare and we consider this to be a good trade-off against extraction performance.
