### ISSUE TITLE
@tailwind directives present in output files (webpack 5)

### ISSUE THREAD

**Issue by pavelloz** [tailwindlabs/tailwindcss#4074]
### What version of Tailwind CSS are you using?

2.1.1 (JIT mode)

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 5.27.1

### What version of Node.js are you using?

14.4

### What browser are you using?

n/a

### What operating system are you using?

macos

### Reproduction repository

https://github.com/pavelloz/tailwindbug

### Describe your issue

When i use `@import "tailwindcss/base";` etc. imports in my CSS (using `postcss-import`) i get properly working tailwind build, but `@tailwind` directives are in production css output files. 

<img width="351" alt="image" src="https://user-images.githubusercontent.com/546845/114719236-2a195f00-9d37-11eb-9878-6a14dff2db8f.png">

I tried to switch to `@tailwind base` (because i was afraid minifier will get lost in those unknown directives for it) directives to get rid off them, but then tailwind is generated fine, but custom classes that our team has created are not included in the build, which means i cannot use it.

Example custom class:
```
.button {
  @apply
    px-5
    py-2
    inline-flex
    items-center
    justify-center
    align-top
    border-2
    border-transparent
    rounded
    bg-interaction
    whitespace-nowrap
    leading-6
    text-center
    text-content-inverted
    transition-colors;
}
```

To reproduce close repo and run:

    npm ci && npm run build

    grep @tailwind app/assets/css/app.css

**Comment by meeq** [comment]
I experienced this when I enabled [`webpack5`](https://nextjs.org/docs/messages/webpack5) in a Next.js app.

For now I've reverted back to Webpack 4, but Next.js plans on automatically opting-in to Webpack 5 in the next minor version (10.2.x)

**Comment by adamwathan** [comment]
Hey! The problem is you are including all of Tailwind's styles in your CSS twice:

https://github.com/pavelloz/tailwindbug/blob/master/src/css/base/body.css#L14

https://github.com/pavelloz/tailwindbug/blob/master/src/css/app.css#L1

Tailwind is only expected `@tailwind base` once, and only replaces the first one. We should probably throw an error here but the problem is in your CSS in this case — I don't think there's a reason to generate one stylesheet that includes Tailwind twice.

Going to close as this is isn't really a bug in our stuff but will make a note to throw an error if we detect mistakes like this.

**Comment by pavelloz** [comment]
Duh, thank you. Too much conflict resolution along the years and this is probably the result :)

**Comment by bagsa** [comment]
- [x] ]()
