### ISSUE TITLE
Support watch mode with `tailwindcss build`

### ISSUE THREAD

**Issue by mainej** [tailwindlabs/tailwindcss#4097]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

`tailwind build`

### What version of Node.js are you using?

v14.7.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/mainej/tailwindcss-build-jit-issue

### Describe your issue

It appears that the CLI tool `tailwindcss build` does not support JIT mode. See the README.md in the associated repository for steps to reproduce. The main point is that in JIT mode, `tailwindcss build` does not notice changes in source files, while `postcss ... -w` does.

At a minimum, I suggest updating the JIT docs to say you *must not* use `tailwindcss build`, and that `postcss ... -w` is a replacement. Preferably though, `tailwindcss build` would support JIT mode.

On a related note, I'll observe that though the installation docs mention postcss-cli and give examples of using the `postcss` CLI command, they do not explicitly state that you must `npm install` it. It's a small thing, but I think that if the project is moving away from `tailwindcss build`, then the alternatives should be very clearly documented, especially for first-time users.

**Comment by adamwathan** [comment]
Yeah the `tailwindcss build` command has no watch mode at all, so the long-running process you are seeing is just because the JIT starts a watcher in the background for different purposes and the process never finishes.

The command does support JIT mode, it just doesn't support watching, never has. You'll want to add the `TAILWIND_MODE=build` env variable when using the Tailwind CLI tool to make sure the script exits when it's finished:

```
TAILWIND_MODE=build tailwindcss build
```

Since the JIT functionality is still in experimental preview there are definitely lots of little things that aren't explicitly documented yet, will make sure the CLI supports it properly when it's properly released.

Will leave this open but rename for clarity 👍🏻

**Comment by mainej** [comment]
Ah, right, I was misusing the terminology. Where I said "JIT mode" I should have said "JIT watch mode". Thanks for the clarification. And understood about it being in experimental preview. I'm glad to hear it will be part of `tailwindcss build` eventually. 👍

**Comment by ralphjsmit** [comment]
Any idea of the timeframe in which this can be implemented?

**Comment by adamwathan** [comment]
Hopefully in a few weeks, in the mean time I would recommend just using postcss-cli which has a watch mode.

**Comment by adamwathan** [comment]
This is done, can play with it like this now if you want:

`npx tailwindcss@canary`

Party on.
