### ISSUE TITLE
[JIT] Arbitrary values not working

### ISSUE THREAD

**Issue by randyridge** [tailwindlabs/tailwindcss#4113]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

sveltekit / vite 2.1.0

### What version of Node.js are you using?

15.10.0

### What browser are you using?

chrome

### What operating system are you using?

windows

### Reproduction repository

https://github.com/randyridge/tailwind-arbitrary-repro

### Describe your issue

unable to get arbitrary widths/heights, probably other arbitrary values as well.

**Comment by bradlc** [comment]
Hey @randyridge. This is happening because [you are overriding the default extractor](https://github.com/randyridge/tailwind-arbitrary-repro/blob/main/tailwind.config.cjs#L10-L13) and the classes are not being extracted correctly. Since you are using JIT mode the `mode`, `whitelistPatterns` and `keyframes` purge options do not have any effect. Simplifying your config will fix your issue:

```
module.exports = {
  darkMode: 'class', // or 'media' or 'class'
  mode: 'jit',
  plugins: [],
  purge: ['./src/**/*.html', './src/**/*.svelte']
};
```

**Comment by randyridge** [comment]
Gah!  thanks so much, was a carryover from my previous config and I totally overlooked it.
