### ISSUE TITLE
[JIT]: not generate class .backdrop-*

### ISSUE THREAD

**Issue by kenhyuwa** [tailwindlabs/tailwindcss#4176]
### What version of Tailwind CSS are you using?

^2.1.2-compact

### What build tool (or framework if it abstracts the build tool) are you using?

Nuxt.js

### What version of Node.js are you using?

v12.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/kenhyuwa/nuxtjs-tailwindcss

### Describe your issue

All class `.backdrop-[*]` not generate, on `dev` and `prod` mode.
```html
<nav class="sticky top-0 bg-gray-900 bg-opacity-50 backdrop-filter backdrop-blur">
  ...
</nav>
```
my config,
```js
// nuxt.config.js
export default {
  tailwindcss: {
    jit: true // work if false
  }
}
```

**Comment by adamwathan** [comment]
Hey! This is because Nuxt hasn't updated their module for the latest changes in Tailwind, which unfortunately is always a problem with these sorts of wrapper packages :/

It looks like if you configure the JIT stuff the regular way instead of the special Nuxt way it works,

```diff
  // nuxt.config.js
  export default {
    tailwindcss: {
-     jit: true
    }
  }
```

```diff
  module.exports = {
+   mode: 'jit',
    purge: [
      './components/**/*.{vue,js}',
      './layouts/**/*.vue',
      './pages/**/*.vue',
      './plugins/**/*.{js,ts}',
      './nuxt.config.{js,ts}',
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
      extend: {},
    },
    variants: {
      extend: {},
    },
    plugins: [],
  }
```

You can track progress on Nuxt updating the module itself here:

https://github.com/nuxt-community/tailwindcss-module/issues/330

**Comment by kenhyuwa** [comment]
Thank you @adamwathan

**Comment by JaavierR** [comment]
Hi @adamwathan and @kenhyuwa,

In the latest versions of the nuxt module for tailwind support for postcss8 has been added. So now, those who are using @nuxt/tailwindcss version 4.0.1 or higher, just by installing tailwindcss@latest (see below) will be able to make use of the new classes and jit mode, although I only tested loading the configuration as you suggest above.

```
# Using npm
npm i -D tailwindcss@latest

# Using yarn
yarn add --dev tailwindcss@latest
```

I attach a screenshot with tailwind 2.1.2 running in conjunction with the nuxt module (remember that backdrop-blur firefox does not support it without some options, for those who want to test and run into that the class is not applied).

![imagen](https://user-images.githubusercontent.com/4650238/116051535-b46e9680-a646-11eb-9aa7-3c0668241765.png)

I will do more tests these days to see that everything works fine, but maybe it's time to update the documentation of tailwindcss for nuxt, since it seems that it would not be necessary to install the compatibility build (PostCss7). I wanted to comment it before making any PR to the documentation so you could see it if you have some time.

The steps to reproduce what I am saying are:

```
# Create new nuxt app with create-nuxt-app and select tailwind in the UI framework
npx create-nuxt-app tailwind-test

# When installation is complete, you need to install the tailwindcss library
yarn add --dev tailwincss@latest

# And after that create the tailwind.css file in the assets/css folder and also the tailwind.config.js with the following configuration

  module.exports = {
   mode: 'jit',
    purge: [
      './components/**/*.{vue,js}',
      './layouts/**/*.vue',
      './pages/**/*.vue',
      './plugins/**/*.{js,ts}',
      './nuxt.config.{js,ts}',
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
      extend: {},
    },
    variants: {
      extend: {},
    },
    plugins: [],
  }
```

I hope it will be useful to someone. 🙌
