### ISSUE TITLE
[JIT]: passing color as props does not render color

### ISSUE THREAD

**Issue by maximegheraille** [tailwindlabs/tailwindcss#4191]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

10.1.3

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/maximegheraille/tailwindcss_bug

### Describe your issue

Hi,

when passing my color as props like this `<List text="something" color="#84AB86" />` and using in the code    `className={'bg-[${color}] '} ` it does not render properly.

my component does see it correctly but does not display it 
![image](https://user-images.githubusercontent.com/32335849/116143666-b46ca600-a6db-11eb-9962-1d645bfd7b69.png)

while putting the color manually without taking it from props, it does work correctly

after more testing it seems not possible either to do it like this 
` const color = "#84CC79"`
` className={"bg-[${color}]"}`

**Comment by CTOJoe** [comment]
The JIT compiler cannot use string concatenation for class names. The JIT compiler reads the raw source and does not know what class name to generate since the code you wrote would be computed during runtime. Class names need to be a full class name string before runtime for the browser to receive them. 

See the docs linked below where is says "Don't use string concatenation to create class names".
https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support

You could instead do something like the following:
```TSX
export type ExampleCustomProps = {
  color?: "purple" | "teal";
};

export type ExampleComponentProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  keyof ExampleCustomProps
>;

export type ExampleProps = ExampleCustomProps & ExampleComponentProps;

export const Example = (props: ExampleProps) => {
  const { color, className, children, ...componentProps } = props;

  const colorClass = color
    ? {
        purple: "bg-[#b247e0]",
        teal: "bg-[#2abeb7]",
      }[color]
    : null;

  return (
    <div
      className={`${[className, colorClass]
        .filter((cN) => typeof cN === "string")
        .join(" ")}`}
      {...componentProps}
    >
      {children}
    </div>
  );
};
```

This would also enable Intellisense to autocomplete the component with strict type checking:
<img width="513" alt="Screen Shot 2021-04-28 at 11 34 40 AM" src="https://user-images.githubusercontent.com/2642064/116432577-b0916e80-a816-11eb-8c76-4d32da1b9493.png">

The following code:
```TSX
<Example color="purple">Example</Example>
```

Produces:
<img width="100" alt="Screen Shot 2021-04-28 at 11 35 19 AM" src="https://user-images.githubusercontent.com/2642064/116432732-d61e7800-a816-11eb-9135-691681bc7c91.png">


I feel defining a set number of colors is better practice. If you really need to set the color based on an arbitrary  random prop hex, then use the style prop directly.
```TSX
export type ExampleCustomProps = {
  color?: string;
};

export type ExampleComponentProps = Omit<
  React.ComponentPropsWithoutRef<"div">,
  keyof ExampleCustomProps
>;

export type ExampleProps = ExampleCustomProps & ExampleComponentProps;

export const Example = (props: ExampleProps) => {
  const { color, children, ...componentProps } = props;

  return (
    <div style={{ backgroundColor: color }} {...componentProps}>
      {children}
    </div>
  );
};
```

**Comment by maximegheraille** [comment]
An working option is to do this [this](https://stackoverflow.com/questions/67289894/jit-tailwindcss-using-variable-in-bg-not-rendering-color/67298861#67298861)

make safelist.txt in your src folder, then add classes there just like so:

```
'bg-[#84AB86]';
'bg-[#fffeee]';

// etc..
```
And dont' forget to include this safelist.txt file to your config so tailwind could watch it.
