### ISSUE TITLE
[Bug]: Important modifier not working

### ISSUE THREAD

**Issue by jaulz** [tailwindlabs/tailwindcss#4202]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

vue-tailwind 2.2.1, webpack 5.21.2

### What version of Node.js are you using?

v15.11.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/qVS5lsqxMS

### Describe your issue

The important modifier does not work as announced here:
https://tailwindcss.com/docs/just-in-time-mode

The attached reproduction link should have a blue background but it is still gray:
![image](https://user-images.githubusercontent.com/5358638/116396493-c2c6d900-a825-11eb-8988-a407b536fbb0.png)

**Comment by bradlc** [comment]
Have you enabled JIT mode [as described in the documentation](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode)? JIT mode is not currently supported in Tailwind Play, and you are using `jit: true` there instead of `mode: 'jit'`.

If you have enabled JIT mode correctly and it's still not working please provide a repository which reproduces the issue, thanks!

**Comment by Zertz** [comment]
We're running into this with `mode: "jit"` and `@tailwindcss/postcss7-compat`:

Input:
```css
.ui-state-active{
    @apply !bg-none !whitespace-normal;
}
```

Output:
```css
.ui-state-active {
    white-space: normal;
    background-image: none;
}
```

**Comment by adamwathan** [comment]
Added support for this, will be in v2.2 but can test now in canary:

`npm install -D tailwindcss@canary`
