### ISSUE TITLE
[Bug]: Default focus ring is not removed when using focus class

### ISSUE THREAD

**Issue by lawrencek76** [tailwindlabs/tailwindcss#4204]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

postcss

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/ziUo8o5WxQ

### Describe your issue

Adding a focus:ring a tag and then using the keyboard to tab to the link includes both chromes default ring and the ring specified.  

https://play.tailwindcss.com/ziUo8o5WxQ

Potential fix:
all focus:ring and its variants could set
{
    outline: none;
}

**Comment by lawrencek76** [comment]
After a bit of more looking at the documentation I see by inspecting the element the example does set focus:outline-none for the focus ring example but that class is not included in the example text.

So this may be a feature request?  Is there any case where you would set the focus ring and not set outline to none?  
So either a documentation change to show the additional class to avoid a bit of confusion or a feature request.

**Comment by adamwathan** [comment]
Hey! Yeah this is by design, there are definitely places where you might use the `ring` utilities and still want a default focus ring, such as when you are actually using rings as a sort of faux-border instead of a focus ring (we do this in Tailwind UI for dropdown panels for example).

I've updated the code sample in the docs to include `focus:outline-none` in case it helps others in the future 👍🏻
