### ISSUE TITLE
Configure .container max-width at specific breakpoints - Tailwindcss[Bug]: 

### ISSUE THREAD

**Issue by hdliyu** [tailwindlabs/tailwindcss#4323]
### What version of Tailwind CSS are you using?

v2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

playground.tailwindcss.com

### Describe your issue

Please how can I configure tailwind .container max-width at various breakpoints.

Tailwind sets the max-width of the .container equal to the width of the breakpoint by default.

I want to set it to a custom value (a little bit less)

Please how can I do this?

**Comment by adamwathan** [comment]
Hey! This isn't currently supported by the `container` plugin out of the box. You can disable it and provide your own custom container classes instead if you like, or rather than changing the actual `max-width` value per breakpoint, you can add a padding value:

https://tailwindcss.com/docs/container#horizontal-padding

Adding padding will have the same effect for most common cases, as it reduces the content area of the container.

**Comment by hdliyu** [comment]
ok,thanks!
