### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by magejunkie** [tailwindlabs/tailwindcss#4328]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What version of Node.js are you using?

12.18.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/magejunkie/tailwindbug/blob/7f8259eee406984c5d85d7bafa5fc11f0307f92d/tailwind.config.js

### Describe your issue

I am trying to add a font family on tailwind, if I add it using display: it works. If I try to type in a custom name like "proxima" it doesn't generate the font class in .css file.

**Comment by adamwathan** [comment]
Hey! This definitely works but hard to troubleshoot without a complete reproduction. The Tailwind config file you've provided is totally correct so not really sure what to suggest.

You are using JIT mode so make sure you actually use the `font-proxima` class in your HTML otherwise it won't be generated,  and also make sure you have the font set up correctly with the appropriate `@font-face` rule in your CSS.

We use custom fonts on all of our projects using this exact approach so definitely some sort of mistake in the project itself and not a Tailwind bug.
