### ISSUE TITLE
[Bug]: Not able to update variables with JIT

### ISSUE THREAD

**Issue by Thompson-Jordon** [tailwindlabs/tailwindcss#4333]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss@^7

### What version of Node.js are you using?

v15.13.0

### What browser are you using?

Chrome, Edge, Safari

### What operating system are you using?

macOS, Linux

### Reproduction repository

https://github.com/Thompson-Jordon/jit-tailwindcss-bug

### Describe your issue

I am trying to pass in variables to change the background color on a class with a hex value (ie bg-[#252a5e]). I want to change the color depending on what variable I pass in as the hex but it is not working. I was able to reproduce the problems with using default tailwind colors. When using default colors it works without 'jit' and does not work once it is enabled.

![without_jit](https://user-images.githubusercontent.com/47086230/118021872-efe0b480-b318-11eb-9ecd-5675f03d752c.png)
![with_jit](https://user-images.githubusercontent.com/47086230/118021877-f40cd200-b318-11eb-90bc-7b0f757dbbb3.png)

**Comment by adamwathan** [comment]
Hey! This is expected, Tailwind generates all of the styles you are using at _build-time_ so you can't use new classes at run-time.

For example there's no way this could ever work since the CSS file is a static asset produced at build-time:

```
<div className={`bg-${someValueThatCameFromAnApi}`}>
```

See the relevant documentation here:

https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support
