### ISSUE TITLE
[Bug]: Create React App ( Craco ) - Re-compilation doesn't occur unless 'tailwind.config.js' is changed

### ISSUE THREAD

**Issue by swport** [tailwindlabs/tailwindcss#4423]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

webpack - create react app

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

chromium

### What operating system are you using?

Ubuntu

### Reproduction repository

https://github.com/swport/setup-cra-tailwind-bootstrap

### Describe your issue

I'm not sure if it's a bug but it's bit inconvenient.

Hot reloading is working okay on JS, JSX files. The page gets reloaded on change, but the tailwind styles don't load. For e.g. if I were to change, in a JS file, className from `my-4` to `my-8`, page will reload and the html will be updated but no respective styles are loaded.

Unless, I re-save the file: `tailwind.config.js` which forces it to recompile and then everything works.

Earlier, I was using JIT mode, but the problem persist even after removing it from the config.

**Comment by adamwathan** [comment]
Hey! Your issue is that you have PurgeCSS configured twice. You only need it in your `tailwind.config.js` file, you have it here as well:

https://github.com/swport/setup-cra-tailwind-bootstrap/blob/master/craco.config.js#L10-L18

By configuring it in `craco.config.js` you are telling your CSS to purge always, not just in production. This means your initial CSS build is purging all unused styles, so when you try to use another class, that class doesn't exist yet so you don't see anything update. Your template files are not considered dependencies of the CSS by CRA, so it doesn't rebuild the CSS when your JSX changes, only when the CSS changes or the Tailwind config changes 👍🏻 

I've tested your project with both JIT and AOT mode and after deleting those lines from your CRACO config, everything works 🥳

**Comment by cosmin-techoff** [comment]
Hey @adamwathan,

I have the same issue with an ejected react app 

in my tailwind.config.js file contains :
`  
...
  mode: "jit",
  purge: [
      "./src/**/*.{js,jsx,ts,tsx}",
      ....
  ]
...
`

and in postcss.config.js :
`
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`

Everything worked fine before updating to 2.2.4 ( from 2.1.2 - using the JIT plugin ).

**Comment by adamwathan** [comment]
That's because CRA uses old versions of PostCSS and postcss-loader, update to the latest versions of those dependencies (since you're ejected) and you should be good.

See our troubleshooting documentation on the JIT docs page as well.

**Comment by cosmin-techoff** [comment]
updating postcss-loader to latest version, requires webpack 5 .. which seems impossible :) 

Is there any other way to do make it work? I tried the TAILWIND_WATCH mode without success

**Comment by adamwathan** [comment]
The latest postcss-loader ^4 will work too 👍🏻

**Comment by cosmin-techoff** [comment]
thanks @adamwathan - i can confirm that this works properly using   

-  "postcss": "^8.3.5",
-  "postcss-loader": "^4.3.0",
