### ISSUE TITLE
[Bug]:  Extended screens always override default screens

### ISSUE THREAD

**Issue by Danon** [tailwindlabs/tailwindcss#4435]
### What version of Tailwind CSS are you using?

newest

### What build tool (or framework if it abstracts the build tool) are you using?

webpack, newest

### What version of Node.js are you using?

14

### What browser are you using?

Chrome 89.0.4389.128, 64-bit

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/bzMYnQQmwr?layout=horizontal

### Describe your issue

Normally, classes with higher resolution width take precedense over lower ones. So if I have `sm:w-full md:w-6/12`, and I am on `md` resolution, the `w-6/12` will take precedense. This isn't resolved by CSS specificity or anything, this is just achieved by the order of declaration.

By that, when I add a new, custom breakpoint, like say `xs: 520px` in `tailwind.config.js`, in `theme.extend.screens` (like in the example), it will be added at the end of the styles, thus making `xs:` breakpoint take over anything. You can see in the reproduction repository, that when you open developer tools, you will see that `lg:w-auto` can override the width from `sm`, but not from `xs`. 

To properly allow for custom `screens` in `theme.extend.screens`, the tailwind should sort declarations of breakpoints by their resolutions, and not by the order of declaration.  Without it, you can't declare any new custom breakpoint lower than `2xl`, because if you do, it will take precendece over higher breakpoints. 

Currently, the only way to overcome this issue, is never to use `theme.extend.screens`, but `theme.screens`, and redeclare the breakpoints manually, with proper order. In the documentation:https://tailwindcss.com/docs/theme#extending-the-default-theme there's not a word about order of breakpoints.

**Comment by adamwathan** [comment]
Hey! The documentation outlines this here:

https://tailwindcss.com/docs/breakpoints#extending-the-default-breakpoints

<img width="841" alt="image" src="https://user-images.githubusercontent.com/4323180/119275241-eb9e7c00-bbe1-11eb-9363-333c73beb6d8.png">

**Comment by Danon** [comment]
Why cant we just sort the values? Why should the user remember about that? Sorting is not hard.

**Comment by adamwathan** [comment]
I've thought about it but haven't had a chance to think it all the way through or implement it. It's not as simple as it sounds because we support very complex media query structures, and mixing many different types. There's also the question of "what if someone doesn't want them sorted and wants it to stay sorted in the order they provided?"

So for now I think the best solution is what is in the documentation.

**Comment by Danon** [comment]
> It's not as simple as it sounds because we support very complex media query structures, and mixing many different types. 

Well, maybe it's not simple to implement, but shouldn't it be what `extend` does? It is supposed to add additional feautres to tailwind, without having to re-declare the values, and in the case of `screens`, `theme.extend.screens` is practically useless (it's only useful, if you want to add breakpoint bigger than `2xl`). And it's actually less than useless, because it actually is a trap, a gotcha, that tailwind has set on its users. At first, it took me good 15 minutes to figure out why my styles weren't set. There's a whole bunch of ideas that come to your head, possible reasons for your bug, before you think that maybe `theme.extend.screens` wasn't set correctly.

And if you don't wish to implement sorting on `extend`, perhaps it would be better to simply remove `theme.extend.screens`, and only allow to use `theme.screens`? Because, honestly, `theme.extend.screens`, where it's only usecase are breakpoints larger than `2xl`, and causes wierd, unexpected behaviour for any other breakpoint is really bad idea IMO.

> There's also the question of "what if someone doesn't want them sorted and wants it to stay sorted in the order they provided?"

Surely you can make it so that `theme.screens` doesn't sort, but `theme.extend.screens` does.

**Comment by adamwathan** [comment]
Deciding what the actual behavior should be is not simple given a sufficiently complex screens definition. The point is I just have way more higher priority problems to solve than this since it's already very solvable in user land, so I just haven't dedicated a day to explore it in depth. I realize this feels like the most important thing to improve in the whole framework to _you_ right now but I have hundreds of issues and PRs to work through + our own roadmap, so even if it's a one day problem to explore and solve I can't afford a day on this particular problem any time soon.

**Comment by Danon** [comment]
@adamwathan Maybe we can just throw exception in that case?
