### ISSUE TITLE
Purge Failure with sass like structure

### ISSUE THREAD

**Issue by alperyazgan** [tailwindlabs/tailwindcss#4486]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel Mix 6.0

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrome, Safari, Edge Chromium

### What operating system are you using?

macOS, Windows

### Reproduction repository

alperyazgan/soon-will

### Describe your issue

Something like the following  which has the sass like structure in a layer does fail (purge them all while they are in use) when purging in  production state; is this an expected outcome of the design or am I missing some point ? Any comment will be appreciated. 

Kind Regards,

```
@layer components
{
.app
{
  &-focus-ring-border
  {
    @apply focus:border-primary-500 focus:ring focus:ring-primary-200 focus:ring-opacity-50;
  }

  &-secondary-focus-ring-border
  {
    @apply focus:border-secondary-400 focus:ring focus:ring-secondary-200 focus:ring-opacity-50;
  }
}
}
```

**Comment by adamwathan** [comment]
Hey! Sorry really need a proper reproduction repo to help with this. Can you open a new issue when you've had a chance to put together a minimal reproduction?

My only guess would be that something is misconfigured either with Sass + PostCSS, or whatever PostCSS nesting plugin you're using. You should make sure all of the nesting is processed and flattened _before_ Tailwind sees your CSS for things to work properly, as Tailwind itself has no understanding of nesting since it's not valid CSS (yet at least!)
