### ISSUE TITLE
 Can't complete build project when use jit.

### ISSUE THREAD

**Issue by nvthuong1996** [tailwindlabs/tailwindcss#4534]
### What version of Tailwind CSS are you using?

@tailwindcss/postcss7-compat version 2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 4.46.0

### What version of Node.js are you using?

12.20.0

### What browser are you using?

chrome

### What operating system are you using?

macos

### Reproduction repository

https://github.com/nvthuong1996/web-mobile-codebase.git

### Describe your issue

to simulate error you can clone repo :
`https://github.com/nvthuong1996/web-mobile-codebase.git`

run `yarn` to install package

after run 'npm run build:mobile' to build app mobile

Please note that the build process cannot be completed. i must use `control + c` to exit process.

if i disabled jit. it working exactly.

![image](https://user-images.githubusercontent.com/24992586/120408684-b6302600-c379-11eb-872c-e5b762bcbb39.png)

**Comment by adamwathan** [comment]
Hey! I cloned your project and followed the reproduction steps and the process exited as expected:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/4323180/120483079-c3501380-c37f-11eb-95eb-3ad365227641.png">

One thing that can cause this is if you have `NODE_ENV=development` while trying to do a one-off build. We have docs explaining that here:

https://tailwindcss.com/docs/just-in-time-mode#watch-mode-and-one-off-builds

I suspect your issue is related to that in some way, and setting `TAILWIND_MODE=build` explicitly will fix it.

Going to close since I can't reproduce and 99% sure this will fix your issue, but if not please open another issue and include the reproduction with whatever steps I must be missing to actually reproduce and happy to look again ❤️

**Comment by nvthuong1996** [comment]
thank you.
