### ISSUE TITLE
JIT causing some classes to just not work

### ISSUE THREAD

**Issue by kylesloper** [tailwindlabs/tailwindcss#4552]
### What version of Tailwind CSS are you using?

v2.0.1

### What build tool (or framework if it abstracts the build tool) are you using?

eleventy-plugin-tailwindcss + eleventy

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Chredge

### What operating system are you using?

Win 10

### Reproduction repository

https://github.com/kylesloper/tailwindjittest

### Describe your issue

When tailwind's `JIT` is enabled, some classes just do not work. These classes do not have a regular pattern, all that is clear is that some classes do work some do not. I am using Tailwind via an Eleventy plugin (https://github.com/dafiulh/eleventy-plugin-tailwindcss) so this could have a relation to a bug in that plugin however I have noticed a large amount of issues in this repo regarding `JIT` so thought it a good idea to run it by the big guys as well.

For a reproducible example, go to the linked repo and follow instructions. The class of `p-52` in `.components/nav.njk`  does not work when `JIT` is enabled and vice-versa.

Please let me know if you think this is an issue with the plugin itself, I have also opened an issue over on that repo so the author can investigate.

Thanks in advance.

**Comment by adamwathan** [comment]
Hey! When I start the project in JIT mode the padding is there:

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/4323180/120830748-d227f900-c52c-11eb-926c-3fdb97fb1117.png">

But when I change the padding, the changes aren't picked up.

A few things I noticed:

1. You are watching an enormous amount of files because your purge config is capturing all of `node_modules`. The JIT takes 17s to run because it is evaluating 22,957 files and finding 1,132,230 potential classes. Make sure you change your purge config so it doesn't include the entire `node_modules` directory.
2. You are putting your templates in hidden folders like `.components`, and glob patterns ignore hidden folders, so I suspect when we pass those globs to our watch process they are being ignored 🤔  I tried switching to regular folders though and it didn't fully resolve the issue.
3. I think the main issue is that the eleventy plugin is just not designed to work with the JIT engine. It is doing a lot of manual file watching and stuff rather than working like a traditional PostCSS plugin, which means (I suspect) that the dependency messages we send out to PostCSS aren't being respected, and the plugin is not triggering a CSS rebuild when your template files change.

I did verify after changing the purge config and changing the hidden folders to be regular folders that re-saving the _config_ file _did_ trigger a CSS rebuild and make everything look correct, and I noticed the plugin is explicitly watching the config file, so I think the change that needs to happen here is that the plugin needs to watch the purge paths as well. Because it is such an incredibly low-level integration doing a bunch of stuff manually that we normally expect to "just work" when we fire out a PostCSS dependency message, there's not really anything we can change on our end to improve this I'm afraid :/

I think your best option is to compile your CSS separately instead of relying on the integration, using postcss-cli or our new JIT-compatible CLI tool we will be releasing in a week or so if you can wait. Then just import the compiled CSS into your 11ty project, and run both the 11ty server and the PostCSS watch process simultaneously using `npm-run-all` or `concurrently`. Hope that helps.
