### ISSUE TITLE
disabled:hover: not working without JIT, which breaks certain colours styling

### ISSUE THREAD

**Issue by n8udd** [tailwindlabs/tailwindcss#4560]
### What version of Tailwind CSS are you using?

2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel Mix

### What version of Node.js are you using?

v15.14

### What browser are you using?

Firefox & Safari

### What operating system are you using?

Macos

### Reproduction repository

https://github.com/n8udd/tall-events/

### Describe your issue

New default Laravel install using Sail and Breeze.

With the default mode enabled, I am unable to use `disabled:hover:bg-green-500`. Trying to debug, I changed the more to JIT, which then worked, but I lost my background colurs from an SVG (which work with it disabled).

JIT Enabled:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/2293192/120814762-158f6100-c547-11eb-8350-0ae718e165fc.png">

Hover on disabled button with JIT enabled:
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/2293192/120814813-2213b980-c547-11eb-8b71-5ebdf2810393.png">

Normal "mode"
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/2293192/120814980-50919480-c547-11eb-9158-87b405c65714.png">

Hover on disabled with normal mode (not showing disabled bg-green on hover):
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/2293192/120815223-85055080-c547-11eb-95a7-c5c37339ce39.png">

JIT Mode: 
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/2293192/120815969-3ad09f00-c548-11eb-9263-67eb714217a7.png">

Normal Mode: 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/2293192/120816084-589e0400-c548-11eb-9ee1-cb0b6de6b9d4.png">

**tailwind.config.js**
```
const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');

module.exports = {
    mode: 'jit',
    darkMode: 'class',
    purge: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Fira Sans', ...defaultTheme.fontFamily.sans],
                mono: ['Fira Code', ...defaultTheme.fontFamily.mono]
            },
        },
        colors: {
            orange: colors.orange,
            transparent: 'transparent',
            current: 'currentColor',

            black: colors.black,
            white: colors.white,
            gray: colors.coolGray,
            red: colors.red,
            yellow: colors.amber,
            green: colors.emerald,
            blue: colors.blue,
            indigo: colors.indigo,
            purple: colors.violet,
            pink: colors.pink,
        }
    },

    variants: {
        opacity: ['disabled', 'hover'],
        backgroundColor: ['disabled', 'hover'],
        textColor: ['disabled', 'hover'],
    },

    plugins: [
        require('@tailwindcss/forms'),
        require("nightwind")
    ],
};
```

**Comment by adamwathan** [comment]
Hey! Yeah it's expected that `disabled:hover` doesn't work without JIT — "variant stacking" is a new feature that wasn't realistic for us to include until the JIT engine.

Can you open a new issue for the SVG stuff with the JIT engine and provide a very stripped down minimal example? The Laravel project you provided requires me to setup a database, seed the data, etc. etc. which is all not really necessary to reproduce the bug and makes it less likely I can find time to look at it. Ideally you can create a reproduction just using play.tailwindcss.com since it should be reproducible with simple HTML + CSS.

I tried looking through the codebase to find the views where those screenshots come from but I can't easily find them since all of the content is dynamic so a global search in the project doesn't help.
