### ISSUE TITLE
rounded-r-full cancels out rounded-l-md etc.

### ISSUE THREAD

**Issue by jasonbarrows** [tailwindlabs/tailwindcss#4652]
### What version of Tailwind CSS are you using?

v2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

NextJS 10.1.3

### What version of Node.js are you using?

v14.15.4

### What browser are you using?

Edge

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/jasonbarrows/tailwindcss-border-radius-issue

### Describe your issue

Rounded borders have not been behaving as expected when mixing any rounded classes with rounded-full classes on elements.

In my particular example "rounded-r-xl" is completely ignored when used in combination with "rounded-l-full".

This may be a side-effect of the 9999px border radius implementation.

I did manage to solve my particular problem by extending borderRadius with a 50% option in the config which will only really work on square elements.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The short answer is: `border-radius` is complex.

They behave relative to each other, the `rounded-full` is implemented as `9999px` is is very large compared to the `2rem` for example.
The reason we don't use `100%` or `50%` is because indeed it will not work as expected on non-square elements.

Here are a few solutions you can use: https://play.tailwindcss.com/rqciMqM2F0

**Comment by jasonbarrows** [comment]
Hi Robin, thanks so much.  Those solutions are great!
