### ISSUE TITLE
Infinite loop when watching for changes with a wildcard only PurgeCSS content entry

### ISSUE THREAD

**Issue by jeffreyvr** [tailwindlabs/tailwindcss#4691]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

laravel-mix 6.0.22

### What version of Node.js are you using?

15.2.1

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/jeffreyvr/tailwindcss-purgecss-loop

### Describe your issue

Specifically, when using a wildcard only content option.

This wasn't the case with Tailwind CSS 2.1.0.

```js
module.exports = {
    mode: 'jit',
    purge: {
        content: ['./*.php'], // infinite loop
        content: ['./partials/*.php'], // works
    }
}
```
 
https://user-images.githubusercontent.com/9550079/122551728-ad0bae00-d035-11eb-8401-c16ddce08807.mov

Reproduction repository: https://github.com/jeffreyvr/tailwindcss-purgecss-loop

**Comment by adamwathan** [comment]
Hey! Ugh this one sucks but unfortunately it's not fixable from our end.

The root cause is that even though you are registering your content files as a glob (`./*.php`), webpack doesn't support registering globs as dependencies, only directories. So we have to resolve the glob to real directories, and register those instead.

That means webpack (via mix) is trying to rebuild your CSS every time _any_ file in `./` changes, and since your output file is in that folder, it is causing an infinite loop.

Hopefully webpack will let us actually register the globs one day, but until then the only solution here is to be more specific with the paths you list in your purge config.

Hope that helps.

**Comment by jeffreyvr** [comment]
Damn that's a pity. Thanks for your quick response @adamwathan! Much appreciated!

**Comment by subhaze** [comment]
I'm running into this issue as well, building for WordPress and using their deps plugin, which, generates .php files with a list of WP js dependencies you import into your JS files; I believe this maybe causing the loop on my side.

@adamwathan if this is unfixable is there any way to support negative patterns? Doing a very brief dive into the code it appears fast-glob is used, I test that package on my end and it appears to respect negative patterns but when added to the content list I'll still end up in an infinite webpack build 🤞

**Comment by adamwathan** [comment]
No way to support negative patterns unfortunately, since webpack won't respect them anyways — can you create a project that reproduces your WordPress issue? Maybe can just suggest something else that will work 👍🏻

**Comment by subhaze** [comment]
Sad :( thanks for the quick reply and offer of help!

From what i'm gathering all globs get reduced to nearest dir and that dir is fully watched for changes; So, with the new purge system we'd need to basically have a 'src' dir for all things in our theme folder and just let that be watched since it's not based on file (when using globs)?

Least that's the way it sounds and seems to work that way exploring this a bit more, I replaced the .{php,js} extensions with a bogus extension and it'll still cause an infinite build loop `content: ["./wp-content/themes/twentytwentyone/**/*.made-up-extension"]`

**Comment by adamwathan** [comment]
Yeah extensions are ignored in terms of what is actually watched and triggers rebuilds. Can you provide the project so I can look and make a recommendation?

**Comment by subhaze** [comment]
I can't lift this exact project I was testing JIT on (we're basically running a lean docker image with the bulk of the build tools in it as a side-cart so all our projects have a baseline build system), but, I can try to work through a minimized/remove work related stuff example.

But! FWIW, I've just moved over to using fast-glob directly within the tailwind.config.js file and it's no longer loop'n! So, there's that at least, and the builds on css changes are waaaayyyyyy faster (which i kind of figured since the looping rebuild was fast, ha!), great job TW team!!

Current workaround is:

```js
const fg = require("fast-glob");
module.exports = {
	mode: "jit",
	purge: {
		content: fg.sync([
			"./wp-content/themes/twentytwentyone/**/*.{php,html,vue,jsx,js,json}",
			"!./wp-content/themes/twentytwentyone/dist/**",
		]),
		safelist: purgeKeep,
	},
	...
};
```

**Comment by adamwathan** [comment]
Ah nice! The only issue you are gonna have there is that when you create new files, they won't be picked up, since the glob is gonna be evaluated and flattened out to just the current files that exist.

**Comment by subhaze** [comment]
Good catch, that crossed my mind shortly after sending that. We're probably going to wait on moving over to JIT to allow it to stabilize more (excellent job so far!), if globs still aren't playing nice with this and webpack by then, I'll look into setting up chokidar to watch the pattern and touch the config in the sidecar to cause a rebuild to see if that works well enough 🤔

I really appreciate the time and feedback you've provided, thanks so much!

And I'm really starting to miss the old days of a Makefile with a bit of cat and uglify sprinkled in to 'build', ha!

**Comment by adamwathan** [comment]
Worth mentioning, if you just use our new CLI tool instead of whatever existing build tool you're using the globs will work properly.
