### ISSUE TITLE
Intellisense 

### ISSUE THREAD

**Issue by AverTry** [tailwindlabs/tailwindcss#4702]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

none

### What version of Node.js are you using?

v15.7.0

### What browser are you using?

Chrome

### What operating system are you using?

Win10 up to date

### Reproduction repository

Whats new in 2.2 No intelisense

### Describe your issue

(1) No Intellisense

(2) transform crashes the build, transform-gpu is ok.

(3) For some reason padding got remove on all selects, after upgrade. (Could be my issue, needs further investigation)

![image](https://user-images.githubusercontent.com/72357571/122579041-69706e80-d04c-11eb-8460-119f3856fe38.png)

**Comment by adamwathan** [comment]
Hey! Please provide a GitHub repository that reproduces your issue in a minimal way (not your full project). Unfortunately just not possible to troubleshoot any of this stuff in an efficient way without a reproduction.

My guesses:

1. You don't have a `tailwind.config.js` file perhaps, or don't have Tailwind actually installed in your project (maybe you switched to the new CLI and removed your dependencies). IntelliSense depends on Tailwind being installed in your project to work (at least for now).
2. You were using `@apply` with `transform` which doesn't work anymore in JIT mode since the `transform` class was removed. Just remove `@apply transform`, you don't need it anymore and don't need to switch to `transform-gpu`.
3. Not sure on this one, nothing in the forms plugin has changed. But if you removed Tailwind from your project to use the new CLI, maybe you removed `tailwindcss/forms` as well? Or maybe you don't have a config file pulling in the plugin? Not sure.

**Comment by AverTry** [comment]
The Padding was an easy fix by adding padding, I only mentioned it, in case others also notice it. 
I'm using the new-cli and imported forms. 
The transform I removed, I only mentioned it, as the update was supposed to be backwards compatible.

My main issue was the Intellisense, so thanks for the answer. 

I will consider this closed now. Thanks for the quick response and a great tool.
