### ISSUE TITLE
`via-transparent` utility broken in Safari

### ISSUE THREAD

**Issue by kripod** [tailwindlabs/tailwindcss#4703]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.0

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/kripod/tailwindcss-bug-via-transparent

### Describe your issue

In Safari, the `via-transparent` utility doesn’t work correctly, resulting in wrong colors as shown on the left below:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/14854048/122580071-dfc59e80-d055-11eb-9a47-2bf279918e16.png">

In other browsers (e.g. Chrome), the two gradients in the reproduction repo look identical:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/14854048/122580189-fcfa6d00-d055-11eb-95b6-a6b4a65df513.png">

A solution could be using `hsla(0,0%,100%,0)` as the `transparent` color.

**Comment by adamwathan** [comment]
Hey! Yeah this is just a bug in Safari in general, if you want to use transparent in a gradient it has to be the transparent version of the color you are transitioning from, otherwise it'll look gray. So you can't use `hsla(0,0%,100%,0)` either unfortunately.

Same thing happens if you just use vanilla CSS so nothing unique to Tailwind about it I'm afraid.

In Tailwind, we default to transparent when you omit the `to` color stop, and we make sure the exact transparent we use matches the `from` color so that it transitions properly in Safari. We can't do that for `via` unfortunately though because we can't assume you even want to use `via` until you actually add it (although now that I think about it maybe there are clever ways to do it with CSS variables...)

An easy solution though is to use the new color opacity stuff:

https://play.tailwindcss.com/XKUUOqB0oc

Just make your `via` color the same as your `from` color but with `/0` at the end.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/4323180/122599189-f2cb7500-d03b-11eb-9ccd-3bb7efe18a69.png">

Gonna close as not something we plan to really try and improve, just one of those things you have to work around due to different browser behaviors.
