### ISSUE TITLE
`col-end-x` gets overriden by `col-span-x`

### ISSUE THREAD

**Issue by cipriancaba** [tailwindlabs/tailwindcss#4754]
### What version of Tailwind CSS are you using?

2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

next 11

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/5dPTR8ZWoe

### Describe your issue

`col-end-13` in my example gets overriden by `sm:col-span-3`. That should propagate to all the breakpoints if not overriden. Only way to make that work is to add another `sm:col-end-13`

**Comment by andronocean** [comment]
Problem here is that `col-end-*` classes set the `grid-column-end` CSS property, and `col-span-*` classes set `grid-column`, which as a shorthand property _also_ controls `grid-column-end`. Since the responsive variant is printed later in the CSS, it wins out in the cascade.

If possible, you can use a `sm:col-start-*` class instead of `sm:col-span-*`. That way you're only changing `grid-column-start`, so the `grid-column-end` prop won't be overriden by the responsive class. Update to your demo: https://play.tailwindcss.com/6EKlVGoN0X?size=854x720

**Comment by adamwathan** [comment]
Hey! Yeah this is by design as there's no real other way to make them composable. So you have to re-specify the `col-end` value if you change the `span` value at another breakpoint.

Think of it kind of like `col-span` is `mx`, `col-start` is `ml`, and `col-end` is `mr`. `col-span` sets both start and end, and the start and end utilities override only one of those values.

**Comment by kerryj89** [comment]
The way I solved it might be crude but it works for my grid system component - I set all my col/row start/end x/y to !important (yes, I know, but only in this capacity)... now it busts through the breakpoints and shorthands and acts more modifier-like as one would expect it to.
