### ISSUE TITLE
Issue with snowpack and tailwindcss JIT mode

### ISSUE THREAD

**Issue by loctran016** [tailwindlabs/tailwindcss#4774]
### What version of Tailwind CSS are you using?

v2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

snowpack v3.5.9, @snowpack/plugin-postcss v1.4.1, postcss v8.3.5

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Brave

### What operating system are you using?

Windows 10 21H1

### Reproduction repository

https://github.com/loctran016/eleventy-kickstart-blog/tree/snowpack

### Describe your issue

Any helps? Even though I've set like @bradlc said in #3950, it doesn't work, no errors in the console, but I still can't use tailwindcss. I've run `cross-env NODE_ENV=development TAILWIND_DISABLE_TOUCH=true yarn clean && npx @11ty/eleventy && snowpack dev`:

![image](https://user-images.githubusercontent.com/64778285/123102667-80a1c880-d45f-11eb-826b-3e85d1fb135a.png)

**Comment by bradlc** [comment]
Hey @loctran016. Here's how to fix your issue:

- You need to reference `index.css` instead of `main.css` in your `main.ejs` file (line `59`)
- You should remove `./public/**/*.html` and `./src/**/*.css` from your `purge` config to prevent [infinite rebuild loops](https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop)

**Comment by loctran016** [comment]
Thanks for helping a lot
