### ISSUE TITLE
Bug: `from-transparent` appears as gray in iPhone (Both safari & chrome)

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss#4820]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

NA

### What version of Node.js are you using?

NA

### What browser are you using?

iPhone Safari & Chrome

### What operating system are you using?

iOS

### Reproduction repository

https://play.tailwindcss.com/JZiWcixjf3

### Describe your issue

`from-transparent` appears as gray in iPhone (Both safari & chrome). It should be transparent. 

**Desktop Preview**
![image](https://user-images.githubusercontent.com/1884712/123598684-9ee22e00-d7a9-11eb-9aa3-04bd1a69885b.png)

**iOS Preview (Safari & Chrome)**
![image](https://user-images.githubusercontent.com/1884712/123598603-8eca4e80-d7a9-11eb-8487-d66effce03c0.png)

**Comment by surjithctly** [comment]
Closing since this is already been discussed here: https://tailwindcss.com/docs/gradient-color-stops#fading-to-transparent

**Comment by markitics** [comment]
# Alternative solution — TL;DR
Replace [this line](https://tailwindcss.com/docs/customizing-colors#using-custom-colors) in your tailwind.config.js:
```
      transparent: "transparent",
```

with this line:
```
    transparent: "rgba(255,255,255,0)",
``` 


# Problem
If the parent div itself has a gradient, then simply leaving off `from-transparent` or `to-transparent`, [as advised](https://tailwindcss.com/docs/gradient-color-stops#fading-to-transparent), might not look ideal.


# Solution

Try leaving `from-transparent` in your code, but add this one line to `tailwind.config.js`:

```
      transparent: "rgba(255,255,255,0)" // to fix `to-transparent` gradient on Safari
```

In context, that is:
```
module.exports = {
  future: {},
  purge: [],
  theme: {
    extend: {},
    colors: {
      // We need to import the ones we'll actually use.
      // Recommended: don't import all 22, or we'll have paradox of choice and a large bundle size
      black: colors.black,
      white: colors.white,
      gray: { ...colors.gray, 375: "#aeaeb6", 350: "#bbbbc2" },
      prim: { // our primary color
        ...colors.fuchsia,
        1000: "#5c1560",
      }, 
      // other named colors
      amber: colors.amber,
      green: colors.green, 
      transparent: "rgba(255,255,255,0)", // fix for to-transparent gradient
      // See https://stackoverflow.com/a/46165475/870121 and https://stackoverflow.com/a/56548711/870121
      // Ignore https://github.com/tailwindlabs/tailwindcss/issues/4820#issuecomment-869626853
      // Official docs (https://tailwindcss.com/docs/gradient-color-stops#fading-to-transparent)
      // recommend just avoiding using to-transparent, but this looks messy if the parent's div
      // also has a gradient - tailwind will fade to one color in an attempt to fade to the "right" color.
    },
  },
  variants: {},
  plugins: [],
};

``` 

# Screenshots

Compare A, B and C:

A. `transparent: "transparent"` in tailwind.config.js, `className="bg-gradient-to-r from-white to-transparent"` in three divs:
Result is awful unwanted gray as discussed.
<img width="856" alt="bad with to-transparent and normal config" src="https://user-images.githubusercontent.com/855207/151672777-153a4a62-fb04-431b-a9dd-00ca61416567.png">


B. `transparent: "transparent"` in tailwind.config.js, `className="bg-gradient-to-r from-white"` in three divs (no `"to-transparent"`):
<img width="784" alt="tailwind docs say don't use to-transparent" src="https://user-images.githubusercontent.com/855207/151672815-f718c988-6d9e-4d4b-8875-1d31f015b498.png">

Result is pretty good, but notice at the right end of the "FILTER RESULTS" div, you see an unwanted border effect, because the parent's div itself has a gradient – it's not obvious what the "right" color is to fade to.
<img width="787" alt="without to-transparent" src="https://user-images.githubusercontent.com/855207/151672829-e8ebdd4d-b21c-49cb-a6cc-fcc58777d557.png">


C. `transparent: "rgba(255,255,255,0)"` in tailwind.config.js, `className="bg-gradient-to-r from-white to-transparent"` in three divs:
This is ideal, and looks good in Safari desktop and mobile.
<img width="825" alt="with-to-transparent" src="https://user-images.githubusercontent.com/855207/151672844-e9de3555-6eb5-4fc4-856e-298f77c3b7d3.png">


# Suggestion for docs
https://tailwindcss.com/docs/customizing-colors#using-custom-colors gave me the idea to have this line in tailwind.config.js:
```
      transparent: "transparent",
```

Perhaps it might make sense to suggest having this line instead?
``` 
      transparent: "rgba(255,255,255,0)",
``` 

[Caveat: I've very new to all this, and there may be many issues I haven't yet tested/encountered and don't know about. Proceed with caution and do your own tests.]
