### ISSUE TITLE
Custom extended translate classes are not compiled in production!!!!!!

### ISSUE THREAD

**Issue by vinhphamthanh** [tailwindlabs/tailwindcss#4821]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js latest

### What version of Node.js are you using?

14.15.0

### What browser are you using?

chrome, firefox, Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/vinhphamthanh/tailwindcss-carousel

### Describe your issue

I tried to add custom class in the extended of theme to add translate X with values.
In dev mode it's working smooth as charm.
But there is no compiled classes for these customs in production.
`theme: {
  extend: {
    translate: {
      'full-0': '0%',
      'full-1': '-100%',
      'full-2': '-200%',
      'full-3': '-300%',
      'full-4': '-400%'
    }
  }
}`

**Comment by adamwathan** [comment]
This is because you are using interpolation to generate your class names in your templates:

https://github.com/vinhphamthanh/tailwindcss-carousel/blob/84867bc55ffbce22d2499f3f856d8250ed2ee955/pages/index.js#L11-L12

See the docs here:

https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

<img width="874" alt="image" src="https://user-images.githubusercontent.com/4323180/124109536-3e672100-da35-11eb-94df-a42d091bf358.png">

Please never open an issue with "!!!!!!!!!" at the end ever again.

**Comment by vinhphamthanh** [comment]
Thanks for your time and your great contribution to the Tailwindcss.

IMHO, interpolation makes Tailwindcss neatly and powerful. 
Anyway, I just custom the purge options and achieve what I mean from dev mode to production seamlessly.

Regards
