### ISSUE TITLE
Base Import Now Required for Utilities (i.e. rotate)

### ISSUE THREAD

**Issue by mattwaler** [tailwindlabs/tailwindcss#4825]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind CLI

### What version of Node.js are you using?

14.16.1

### What browser are you using?

N/A

### What operating system are you using?

MacOS

### Reproduction repository

https://github.com/mattwaler/tailwindcss-base-bug

### Describe your issue

In version 2.2.4, many of the utilities that are now altered via CSS variables do not work at all when removing `@tailwind base`. A prime example are the `rotate` utilities.

This stems from the fact that these variables are defined and set in the `base` layer, not at the beginning of the `utilities` layer.

Many projects utilize Tailwind on top of a pre-existing CSS build, with a prefix. In these projects, the `base` portion of Tailwind cannot be used as it would globally impact the site. In previous versions, omitting that import did not lead to any utility classes no longer working.

Possible solutions:
- Another import that only includes these variable definitions like `@tailwind variables`
- Moving these definitions to the top of the `utilities` layer, not placing them in `base`

**Comment by adamwathan** [comment]
Hey! Yeah this is by design and actually has been true since we introduced the JIT engine (it's a JIT-only thing).

This is still in flux a bit, but I expect this might remain a requirement going forward even as we iron out some final quirks in this part of the system.

The better solution for your case is not to disable the base layer entirely, but just to disable Preflight:

```js
// tailwind.config.js
module.exports = {
  // ...
  corePlugins: {
    preflight: false
  }
}
```

Then you can still include `@tailwind base` to make sure these base styles are emitted while also not messing up your existing base styles in your project.

**Comment by mattwaler** [comment]
Thanks @adamwathan, good to know!
