### ISSUE TITLE
Dark mode matches last rather than first class

### ISSUE THREAD

**Issue by samrobbins85** [tailwindlabs/tailwindcss#4837]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind Play

### What version of Node.js are you using?

Tailwind Play

### What browser are you using?

Firefox and Chrome

### What operating system are you using?

Linux

### Reproduction repository

https://play.tailwindcss.com/ux8h35racV

### Describe your issue

I expected that dark mode on `.prose .a` would put the dark selector on the first class (`.prose`), so that I could do `dark:prose` and it would style elements inside prose that match `.a`. However, instead it puts the dark selector on the final class giving the selector `.prose .dark\:b`

This leads to inconsistencies between dark and light mode, as can be demonstrated in the tailwind play

Apologies if this is the expected behaviour

**Comment by adamwathan** [comment]
Hey! Yeah this is currently by design but I agree it's not always ideal or intuitive. Eventually I'd like to add an API that lets you sort of control from userland which part of the selector receives the variant but not sure when I'll be able to explore it.

In the mean time I would just write your CSS like this:

https://play.tailwindcss.com/NBKRVQ3T2j?file=config

That's how we do it in the actual typography plugin itself for the `lead` class for example to make sure that the variants land on `prose` and not on `lead` 👍🏻 

Going to close as no immediate plans to change anything here but would like to figure out that "explicit variant target" feature one day.
