### ISSUE TITLE
classes are not generated via AddUtilities in JIT Mode

### ISSUE THREAD

**Issue by AndreaChiabotto** [tailwindlabs/tailwindcss#4862]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind Play

### What version of Node.js are you using?

Tailwind Play

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/hPJWduAB1k?layout=horizontal&file=config

### Describe your issue

I Reopen the Issue because I cut all the options out, tested other way and found the problem. ( Kind of)

For the History, I need a set of classes intended as a Mixin, so i generate them via the addUtilities function.
For these, I don't need the responsiveness via tailwind, because the columns behave different on different breakpoint ( 2 columns on Mobile, 6 columns on tablet and 12 on desktop).

The naming of the classes, starting with the breakpoint ( xs,s an l) are there because we wanted that the classes pop up during development, and the intellij plugin help us delivering them. Of course, we can rename these classes with other prefix, but we wanted to be consistent with the Tailwind logic.

and here is the problem:
the Old way worked fine with this:
[`.${item.breakpointName}\\:col-${index}`]

the Jit Mode not... for example, if i rename the class in this way ( and update the html), everything works as expected
[`.${item.breakpointName}-col-${index}`]

still, i Don't understand why the Jit mode cannot generate the classes in the old way

I needed to add this logic into the Tailwind config, because it's the core part of our design library and therefore we didn't want to outside into a separate css file.

**Comment by adamwathan** [comment]
Hey! In JIT mode your separator character (`:` by default) is basically a reserved character and can't be used in class names or the compiler will think it is delimiting variants.

Generally this just looks like not what `addUtilities` is meant for — it's meant for adding simple little rules like:

```
.flex {
  display: flex;
}
```

...and then automatically generating the variant versions, like `sm:flex`, `hover:flex`, etc.

In your case though you are adding very complex classes like:

```
.col-half {
  width: 100%;
  padding-left: var(--column-gap);
  padding-right: var(--column-gap);
}

@media (min-width: 376px) {
  .col-half {
    width: 50%;
  }
}
```

...or:

```
@media (min-width: 575px) {
  .s\:col-2 {
    width: calc(100% / 6 * 2);
  }
}
```

Tailwind is trying to generate variant versions of that, so it thinks you want to be able to use stuff like `lg:s:col-2` which doesn't really make any sense since you already have this custom breakpoint variant baked in to the class.

No plans to make this work like this I'm afraid, I would recommend just using a different character or writing this out as just plain custom CSS because registering it as a utility is telling Tailwind to do a lot of fancy things with these rules that I don't think you actually want.
