### ISSUE TITLE
JIT in CRA: classes added after start do not appear in DOM

### ISSUE THREAD

**Issue by SpadarShut** [tailwindlabs/tailwindcss#4874]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

CRACO

### What version of Node.js are you using?

16.4

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://github.com/SpadarShut/tailwind-jit-compat-hmr-bug

### Describe your issue

1) create new project with CRA and Craco, enable JIT mode
2) run `npm start`, wait for compilation
3) add classes to JSX
4) in browser, they won't get generated/applied

**Comment by adamwathan** [comment]
Hey! The problem here is that CRA uses very old versions of things like `postcss-loader` so it is not compatible with how we track dependencies by default in JIT.

You'll want to use the `TAILWIND_MODE=watch` environment variable in your scripts to use the alternate dependency tracking strategy.

See the troubleshooting docs here:

https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

Personally if this is a new project I would highly consider trying [Vite](https://vitejs.dev) instead — it does everything CRA does but is much faster and more actively maintained.

**Comment by SpadarShut** [comment]
Thank you!
