### ISSUE TITLE
JIT mode not generating classes

### ISSUE THREAD

**Issue by fac42** [tailwindlabs/tailwindcss#4912]
### What version of Tailwind CSS are you using?

2.2.4 Compatibility Build

### What build tool (or framework if it abstracts the build tool) are you using?

vue-cli 4.5.13

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/fac42/tailwind-minimal

### Describe your issue

Using JIT mode, whenever I try to implement an arbitrary class, such as `bg-[coral]` in the example repo, I have to completely restart the project in order for the CSS classes to be generated and applied. This causes for an annoying workflow, as each time I am trying to quickly prototype a new component, it requires me to stop and restart the project again.

To quickly reproduce my issue, run the project, and change `bg-[coral]` to another colour, like `bg-[lightblue]`.

The example repo provided is pretty much a stock Vue3 build generated with the defaults from the latest vue-cli.

**Comment by adamwathan** [comment]
Hey! This is because vue-cli is using old versions of important dependencies like `postcss-loader`. It's use 3.0, and you need at least 4.0 for dependency tracking to work out of the box.

You can try the `TAILWIND_MODE=watch` flag, or use Tailwind CLI to compile your CSS instead.

Please read the troubleshooting docs:

https://tailwindcss.com/docs/just-in-time-mode#troubleshooting
