### ISSUE TITLE
sveltekit + tailwind since 2.2.x `@responsive` is used but `@tailwind utilities` is missing.

### ISSUE THREAD

**Issue by istarkov** [tailwindlabs/tailwindcss#4929]
### What version of Tailwind CSS are you using?

2.2.4 (jit)

### What build tool (or framework if it abstracts the build tool) are you using?

sveltekit postcss

### What version of Node.js are you using?

14.16.0

### What browser are you using?

All

### What operating system are you using?

Linux ubuntu

### Reproduction repository

https://github.com/realadvisor/tailwind-issue

### Describe your issue

I updated taiwind from 2.1.4 to 2.2.4 in our sveltekit project and start getting the error
```
`@responsive` is used but `@tailwind utilities` is missing.
```

The project setup is pretty simple:
postcss - https://github.com/realadvisor/tailwind-issue/blob/main/postcss.config.cjs
css -  https://github.com/realadvisor/tailwind-issue/blob/main/src/routes/__layout.svelte#L6-L15

The error occurs here https://github.com/tailwindlabs/tailwindcss/blob/master/src/jit/lib/normalizeTailwindDirectives.js

Moving of Sets https://github.com/tailwindlabs/tailwindcss/blob/master/src/jit/lib/normalizeTailwindDirectives.js#L2-L3 out of function solves the issue and all is working like before.

Now investigating what it can be.

PS:
With 2.1.4 tailwind all is fine

**Comment by adamwathan** [comment]
Started looking into this but don't have enough time to go super deep so wanted to just leave some notes.

It looks like SvelteKit is compiling Tailwind like _eight_ times for some reason:

![image](https://user-images.githubusercontent.com/4323180/134100036-57dca8a0-dabc-43b1-bdde-21dfa127d667.png)

I would expect max _twice_ since there are only two CSS sources in the project. It seems to compile the actual `_layout.svelte` component styles about three times, and if you look at the error at the bottom it looks like it's actually feeding Tailwind's own _output_ into itself as _input_, but keeping the `@responsive` rule.

This may have been "working" in 2.1.4 but I suspect the exact same thing was still happening in SvelteKit but we were just silently ignoring the error, which is that `@responsive` doesn't work unless `@tailwind utilities` is present in the same file. Because the file is being compiled on top of itself three times the styles were probably there in the output and working but the compilation was still messed up and doing bad things.

Will try to look into this first week of October or so once we are wrapped up with our current projects. Ultimately I have to believe this is an issue with how SvelteKit is actually compiling the CSS, either a bug in the tooling itself or a configuration problem.

**Comment by nikosgpet** [comment]
Any news on this one? Maybe there is a workaround?

**Comment by thecrypticace** [comment]
This is a SvelteKit issue for sure. It's doing something even weirder now with Tailwind v3 if you use it in a `<style>` tag. It's still feeding tailwind's output into itself as input over and over again, it's mangling class names, the `@responsive` directive is still present but empty, and it's throwing out a bunch of classes.

```
.s-PoaHcXV6SIWL,.s-PoaHcXV6SIWL::before,.s-PoaHcXV6SIWL::after{box-sizing:border-box;border-width:0;border-style:solid;border-color:#e5e7eb}.s-PoaHcXV6SIWL::before,.s-PoaHcXV6SIWL::after{--tw-content:''}.s-PoaHcXV6SIWL:-moz-focusring{outline:auto}.s-PoaHcXV6SIWL:-moz-ui-invalid{box-shadow:none}.s-PoaHcXV6SIWL::-webkit-inner-spin-button,.s-PoaHcXV6SIWL::-webkit-outer-spin-button{height:auto}.s-PoaHcXV6SIWL::-webkit-search-decoration{-webkit-appearance:none}.s-PoaHcXV6SIWL::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}.s-PoaHcXV6SIWL:disabled{cursor:default}.s-PoaHcXV6SIWL,.s-PoaHcXV6SIWL::before,.s-PoaHcXV6SIWL::after{--tw-translate-x:0;--tw-translate-y:0;--tw-rotate:0;--tw-skew-x:0;--tw-skew-y:0;--tw-scale-x:1;--tw-scale-y:1;--tw-pan-x:;--tw-pan-y:;--tw-pinch-zoom:;--tw-scroll-snap-strictness:proximity;--tw-ordinal:;--tw-slashed-zero:;--tw-numeric-figure:;--tw-numeric-spacing:;--tw-numeric-fraction:;--tw-ring-inset:;--tw-ring-offset-width:0px;--tw-ring-offset-color:#fff;--tw-ring-color:rgb(59 130 246 / 0.5);--tw-ring-offset-shadow:0 0 #0000;--tw-ring-shadow:0 0 #0000;--tw-shadow:0 0 #0000;--tw-shadow-colored:0 0 #0000;--tw-blur:;--tw-brightness:;--tw-contrast:;--tw-grayscale:;--tw-hue-rotate:;--tw-invert:;--tw-saturate:;--tw-sepia:;--tw-drop-shadow:;--tw-backdrop-blur:;--tw-backdrop-brightness:;--tw-backdrop-contrast:;--tw-backdrop-grayscale:;--tw-backdrop-hue-rotate:;--tw-backdrop-invert:;--tw-backdrop-opacity:;--tw-backdrop-saturate:;--tw-backdrop-sepia:}@responsive{}.s-PoaHcXV6SIWL{}
```

I would suggest following our [installation guide on SvelteKit](https://tailwindcss.com/docs/guides/sveltekit) in which the key differences are:
1. We use an external CSS file that we import in a script tag.
2. We do **not** use svelte-preprocess as it's not needed.
