### ISSUE TITLE
Missing binary links with aliased PostCSS 7 compatibility build

### ISSUE THREAD

**Issue by drubb** [tailwindlabs/tailwindcss#4966]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

N/A

### What version of Node.js are you using?

14.17.2

### What browser are you using?

N/A

### What operating system are you using?

Linux

### Reproduction repository

https://github.com/drubb/tailwind-compatibility-alias-bug

### Describe your issue

Tailwind docs suggest installing the PostCSS 7 compatibility build as aliased package:

`npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat`

When I do this, there are no binary links created for Tailwind in node_modules/.bin, so the cli is not usable.

Without aliasing the package, the links (tailwind / tailwindcss) are created:

`npm install -D @tailwindcss/postcss7-compat`

So for now I go with a combination of both:

`npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat @tailwindcss/postcss7-compat`

This works, but feels weird of course. Why aren't the links created using only the aliased package?

**Comment by drubb** [comment]
Did some further testing, and for now my impression is, that the Tailwind CLI, albeit being delivered in the compatibility build, requires PostCSS 8 and doesn't work with the PostCSS 7 compatibility build.

**Comment by adamwathan** [comment]
Hey @drubb! Yeah correct — the CLI just uses PostCSS 8 internally no matter what. We are going to stop supporting PostCSS 7 in v3 (~November) so hopefully this will be less awkward then. The PostCSS 7 compatibility build is provided for situations where you are integrating Tailwind into a project that is already using PostCSS 7, but if you are going to use our CLI tool you should just install the regular PostCSS 8 version of Tailwind since you aren't actually integrating it with PostCSS yourself.

Hope that helps!
