### ISSUE TITLE
`transform` universal selector causes unwanted wiggliness while transitioning

### ISSUE THREAD

**Issue by navin-moorthy** [tailwindlabs/tailwindcss#4983]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.1 & Vite(Storybook Core) 2.4.2

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Chrome 91.0.4472.114

### What operating system are you using?

Both macOS & Windows

### Reproduction repository

https://stackblitz.com/edit/github-5zejzr?file=package.json

### Describe your issue

As demonstrated in the videos below, we are seeing the wiggliness in out button intermittently when adding `translate-y-0 hover:-translate-y-px active:translate-y-0`.

But the same doesn't happen when using vanilla css for the same.

**Additional link:**
- https://github-5zejzr--3000.local.webcontainer.io/components/button?size=xl (from attached Stackblitz project)
- https://play.tailwindcss.com/e3NgsywrP6 (Tailwind Play)

**Videos**
**macOS - Chrome latest**

https://user-images.githubusercontent.com/39694575/125915511-151fa8e4-c478-4f17-9ed5-f3cdc2592da1.mp4

**Windoes - Chrome latest**
![button-bug](https://user-images.githubusercontent.com/39694575/125915670-94958228-97d2-47f0-a167-86191faaf2f2.gif)

**Comment by FallDownTheSystem** [comment]
This is an issue with sub-pixel rendering. Normally the browser will try to use hardware acceleration to let the graphics card handle these transforms, but I suspect in this case since we're using classes with custom properties (CSS Variables), it can't figure out that there is going to be a transform. Luckily we can instruct to the engine that the transform property of this element will change, with the `will-change: transform` declaration.

Here's an example: [https://play.tailwindcss.com/MXvGTYBM6m?layout=horizontal](https://play.tailwindcss.com/MXvGTYBM6m?layout=horizontal)

**Comment by AverTry** [comment]
? still failed

https://user-images.githubusercontent.com/72357571/126072902-b83286e0-4bd8-4218-ab6b-1e0f8f8a0c27.mp4

**Comment by FallDownTheSystem** [comment]
That looks perfectly fine to me

**Comment by navin-moorthy** [comment]
Yup, I think "will-change": "transform" does the trick.
Much thanks for your insight on this.


https://user-images.githubusercontent.com/39694575/126100612-c80f0815-fbd6-48ff-9e56-ed0a69ec30e9.mp4

**Comment by AverTry** [comment]
My bad I should have understood the issue better. Thanks.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Looks like everything is working now. As others pointed out, in this case it could help to add `will-change-transform`.
