### ISSUE TITLE
How to generate percentage spacing, similar to the size of `w-1/2`

### ISSUE THREAD

**Issue by jiangmaniu** [tailwindlabs/tailwindcss#4994]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Playground

### What version of Node.js are you using?

/Omit

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/nvFcSsg154

### Describe your issue

I need to set the percentage spacing, but unfortunately I can't find the relevant introduction of the percentage spacing in the official website document.

I try to use `w-1/2` similar to the syntax `pl-1/10`, but the syntax does not generate related spacing classes.

The solution I can find so far is to set a custom spacing in `tailwindcss.config.js` according to the documentation

```js
 // tailwind.config.js
  module.exports = {
    theme: {
      spacing: {
        '.10': '10%',
      }
    }
  }
```

However, there is a problem with this scheme. It is necessary to define a different percentage each time in `tailwindcss.config.js`. The most extreme may be to define 100 identifiers. Taking the most extreme case as an example, it means that when writing `px-`, `vs code` will prompt these 100 signs, which will reduce the speed of the smart prompt and seriously occupy the position of the smart prompt menu.

```js
// tailwind.config.js
  module.exports = {
    theme: {
      spacing: {
        '.1': '1%',
        // ...omit
        '.100': '100%',
      }
    }
  }
```

![image](https://user-images.githubusercontent.com/50100681/126024813-501aebfe-a9cb-4eee-9074-e0cbb9f625e1.png)

May I ask whether the spacing does not support the percentage problem (similar to `pl-1/2`) is it a `bug` or is it designed with special considerations? If this is the design, is there a better way to write percentage spacing?

**Comment by adamwathan** [comment]
Hey! We don't include percentage padding values out of the box because they just aren't very commonly needed (we don't use them a single time in close to 500 templates in Tailwind UI for example).

You can add them to your config if you need them like this:

https://play.tailwindcss.com/NKvWMrp2dk?file=config

If you want access to every possible percentage value you might be better off just relying on arbitrary value support in the JIT engine:

https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support

Adding every value from 1% – 100% to your design system feels off to me personally.

No bugs here, all of what you want to do is already possible by customizing your config.
