### ISSUE TITLE
Syntax error: Unknown word using JIT compiler

### ISSUE THREAD

**Issue by denisbrogg** [tailwindlabs/tailwindcss#5035]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.1

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Brave

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/denisbrogg/issues-tailwind-unknown-word

### Describe your issue

If I have JIT enabled and try to assign to elements dynamic className strings :

```javascript
const customStyle = `p-[${300 * 2}px] my-[20px]`
...
<h1 className={customStyle}>
  Test
</h1>
```
I get the error
```
error - ./styles/globals.css:1:1
Syntax error: Unknown word
```
And after that nothing but giving up using jit (commenting it in the tailwind.config.js) seems to make it work again. Using the style tag for custom absolute positions now.

Am I missing  something or doing something wrong ?

Thank you

**Comment by sachinraja** [comment]
Classes are generated at build time, not runtime so using a dynamic class string would not work. It errors when parsing the CSS file because the JIT generated the following class:
```css
.p-\[\$\{300\}px\] {
  padding: ${300}px;
}
```
which is not valid css. You must explicitly use the class `p-[600px]` or `safelist` it. Note: I'm able to reproduce with `p-[${300}px]` (used in the reproduction repo), but not `p-[${300 * 2}px]`. More info is available on [the JIT docs](https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support) (under "Dynamic values").

**Comment by denisbrogg** [comment]
Hi, thank you for your reply!

JIT docs are very clear about that! thank you

However I find myself concatenating strings like this (this is the actual code that is doing what I wanted to to when I raised the issue):
```javascript
const getProblemColor = (problems) => {

    const colors = {
        'none': "bg-green-200 hover:bg-green-400",
        // red for spikes
        'spikes': "bg-red-200 hover:bg-red-400",
        // yellow for holes
        'holes': "bg-yellow-200 hover:bg-yellow-400",
        // spikes and holes? Purple
        'spikes_holes': "bg-orange-200 hover:bg-orange-400",

    }
    // ...

    if(hasSpikesAndHoles){
        return colors['spikes_holes']
    }else if(hasSpikes){
        return colors['spikes']
    }else if(hasHoles){
        return colors['holes']
    }
    return colors['none']

}


logs.map((item, index) => (
    <div key={index}
        className={"border-2 align-middle text-center cursor-pointer " + getProblemColor(item.data.problems)}
        style={{position: "absolute", width: cellDim, height: cellDim, top: (item.gridCoordY + 1 ) * cellDim, left: (item.gridCoordX + 1 ) * cellDim,}}
    />
))
```

And it actually works. 

![Screenshot 2021-07-22 103705](https://user-images.githubusercontent.com/38075497/126611489-670bed45-a0af-43b9-9e3d-6a0b95b8260c.png)

Why does string concatenation work while string templating doesn't? Aren't they both dynamic? 

ps 1: Just curiosity, I don't mind using both tailwind classes and styles, and this is also a very specific task that I am unlikely to repeat elsewhere.

ps 2: I am not a JS developer, so again I may be missing some fundamental knowledge that makes these questions silly, sorry about that.

**Comment by sachinraja** [comment]
Tailwind analyzes your code at build time to find all the classes that it should generate. String concatenation works because Tailwind still finds all the necessary classes in your code **statically**. Templating doesn't work because Tailwind finds the class string `p-[${300}px]` and generates an invalid class for it because it still matched a certain regex. Note that this will only error when using the JIT's arbitrary values. 

Say you were using this:
```jsx
const color = isDark ? 'gray-500' : 'white'
return <div className={`text-red-400 bg-${color}`} />
```
Although Tailwind wouldn't error here, it wouldn't know which classes to generate. `bg-${color}` doesn't match anything, and that is all Tailwind can see. No work is done when the app is actually running, so templating will not work.

**Comment by denisbrogg** [comment]
Understood! Thank you for your time.
