### ISSUE TITLE
PostCSS 8 requirement even with npm:@tailwindcss/postcss7-compat

### ISSUE THREAD

**Issue by joshcomley** [tailwindlabs/tailwindcss#5064]
### What version of Tailwind CSS are you using?

npm:@tailwindcss/postcss7-compat

### What build tool (or framework if it abstracts the build tool) are you using?

N/A

### What version of Node.js are you using?

14.17.1

### What browser are you using?

N/A

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/joshcomley/bugs-tailwindpostcss

### Describe your issue

After following the guidelines on avoiding `PostCSS plugin tailwindcss requires PostCSS 8.`, I still get the message.

Here is a simple repro where I am unable to compile `tailwind` at all in its most basic way, even with all the correct "compat" packages installed.

To see this in action:

- Clone the repo
- Install packages
- Run `yarn build:css`

**Comment by HartS** [comment]
I'm encountering the same, which causes issues with tailwind and create-react-app applications, even when following the instructions on the Tailwind website:

- https://tailwindcss.com/docs/guides/create-react-app
- https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by highhi** [comment]
How do I install an older version of postcss7-compat?

**Comment by mpalmer685** [comment]
I ran into this issue, too. Reverting to a version earlier than 2.2.0 does fix it.

If you need this, you can change the dependency in your `package.json` to:
`"tailwindcss": "npm:@tailwindcss/postcss7-compat@2.1.4"`

**Comment by D-Pagey** [comment]
> I ran into this issue, too. Reverting to a version earlier than 2.2.0 does fix it.
> 
> If you need this, you can change the dependency in your `package.json` to:
> `"tailwindcss": "npm:@tailwindcss/postcss7-compat@2.1.4"`

This is the only thing that worked for me. Thank you @mpalmer685

**Comment by mgav** [comment]
> @tailwindcss/postcss7-compat

@highhi 

To install an older version:

1. go to [https://www.npmjs.com/package/@tailwindcss/postcss7-compat](https://www.npmjs.com/package/@tailwindcss/postcss7-compat ), then
2. click "XX Versions" on the upper right, then 
3. click the number of the version you are seeking (2.2.3 for example), then 
4. look on the upper-right for a box that says "Install" and then finally
5. copy-paste that code into terminal (into the proper directory, of course).

**Comment by mgav** [comment]
Even though my problem ("Error: PostCSS plugin tailwindcss requires PostCSS 8") related to using Vue version 3.2.10 without Vite and trying to install Tailwind CSS version 2.2.14, this may still be helpful: [https://github.com/tailwindlabs/tailwindcss/discussions/5452#discussioncomment-1303157](https://github.com/tailwindlabs/tailwindcss/discussions/5452#discussioncomment-1303157)

**Comment by brendonrapp** [comment]
Publishing a "postcss7-compat" package that requires postcss8.

🌈 JavaScript 🌈

**Comment by adamwathan** [comment]
Hey! In this case there is no reason to use the PostCSS 7 build since you aren't actually running PostCSS yourself. To get things building in your repo you have a few options:

1. **Just use the latest version**. If you aren't actually trying to integrate with an existing PostCSS pipeline, there's no need to use the PostCSS 7 version:

    ```diff
      {
        "name": "twtest",
        "version": "1.0.0",
        "description": "",
        "main": "index.js",
        "scripts": {
          "build:css": "tailwind build -i src/index.css -o src/build.css",
          "test": "echo \"Error: no test specified\" && exit 1"
        },
        "author": "",
        "license": "ISC",
        "devDependencies": {
    -     "autoprefixer": "9",
    -     "postcss": "7",
    -     "tailwindcss": "npm:@tailwindcss/postcss7-compat"
    +     "tailwindcss": "^2"
        },
      }
    ```

2. **Integrate with PostCSS in a PostCSS 7 project**. If you actually are integrating with PostCSS 7, things _will_ work since you won't be using our CLI. Here's an example using `postcss-cli`, it works as expected:

    ```js
    {
      "name": "twtest",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "build:css": "postcss src/index.css -o src/build.css",
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "autoprefixer": "9",
        "postcss": "7",
        "postcss-cli": "^7",
        "tailwindcss": "npm:@tailwindcss/postcss7-compat"
      }
    }
    ```

I'll make a note to consider replacing the CLI in the compat build with a simple script that just throws an error, since there's no reason for our actual CLI tool to have a PostCSS 7 version.

We will be dropping PostCSS 7 support in November when Tailwind CSS v3 is release for what it's worth, so hopefully the rest of the ecosystem (I think really just CRA) catches up by then. I'd recommend using Vite instead of CRA personally, does all the same stuff but is faster and more modern.
