### ISSUE TITLE
Fill utility class `fill-amber-300` doesn't work

### ISSUE THREAD

**Issue by MartinMa** [tailwindlabs/tailwindcss#5103]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Vite

### What version of Node.js are you using?

v16.5.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/7rSPaqBWD7?file=config

### Describe your issue

I'm trying to use the `fill-amber-300` utility class to change the fill color of an embedded svg. The fill style is not applied. On the other hand, `fill-yellow-300` works. I tried to override the amber class using the config which didn't work either. What could possibly go wrong here?

I tried with and without JIT mode.

See play link for reproduction.

**Comment by simonswiss** [comment]
Hey!

In your Tailwind Play, you're trying to access the colors with the `theme()` function, which doesn't use the `colors` that you have imported at the top of your config file, but the theme's existing colors instead.

And... `amber` does not exist in the default theme colors.

To use the colors you have imported,  you need to use the `colors` object directly:

```diff
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    fill: (theme) => ({
-      'amber': theme('colors.amber.300'),
-      'yellow': theme('colors.yellow.300'),
+      amber: colors.amber[300],
+      yellow: colors.yellow[300],
    }),
  },
  variants: {},
  plugins: [],
}

```

Semi-relevant side note, and  "fun" fact to add to the confusion. The default `yellow` is the default theme is actually... `amber` 😅 So when you were doing `yellow: theme('colors.yellow.300')`, you were actually getting the `amber-300` color!

Here's your updated Tailwind Play with the correct way to pull in the colors imported from `tailwindcss/colors`:

https://play.tailwindcss.com/zjiiIeFySX?file=config

![image](https://user-images.githubusercontent.com/485747/127274591-37d738a6-27b5-4fce-8d50-1c7d64f7cc2a.png)

Moving this to our [discussions](https://github.com/tailwindlabs/tailwindcss/discussions), since this might help someone else 👍
