### ISSUE TITLE
Don't use transparent keyword for gradients - safari bug

### ISSUE THREAD

**Issue by insanetisane** [tailwindlabs/tailwindcss#5125]
### What version of Tailwind CSS are you using?

v2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

vite

### What version of Node.js are you using?

v16.3.0

### What browser are you using?

Safari

### What operating system are you using?

MacOS

### Reproduction repository

https://codepen.io/dillonbheadley/pen/PomeOaR

### Describe your issue

In safari when the `transparent` keyword us used in a gradient it uses rgb(0,0,0,0) which, when used with a white color stop, results in a dark gradient. instead of using transparent the style should be:

```
  .via-transparent {
    --tw-gradient-stops: var(--tw-gradient-from), rgba(255, 255, 255, 0), var(--tw-gradient-to, rgba(255, 255, 255, 0))
  }
```

**Comment by insanetisane** [comment]
Hmm i just realized the fix isnt as simple as that because when using `from-black` you dont want `rgba(255, 255, 255, 0)` as that will cause a white cast to the gradient. Not sure what the solution is here.

**Comment by adamwathan** [comment]
Hey! Yep this is covered in the docs:

https://tailwindcss.com/docs/gradient-color-stops#fading-to-transparent

We do some magic to make transparent work automatically by default but if you manually use transparent it'll be messed up in Safari because of the bug in Safari.

Here's a link to some info about the Safari bug:

https://ambientimpact.com/web/snippets/safari-bug-with-gradients-that-fade-to-transparent

No plans to do anything different here at the moment, but hope that helps.
