### ISSUE TITLE
jit mode inline class not work

### ISSUE THREAD

**Issue by arishojaei** [tailwindlabs/tailwindcss#5207]
### What version of Tailwind CSS are you using?

npm:@tailwindcss/postcss7-compat

### What build tool (or framework if it abstracts the build tool) are you using?

vue 2, vue-cli-service

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/arishojaei/vue-tailwind-library

### Describe your issue

 have 2 problems, first one is when I write tailwind classes directly in HTML tag, they don't work! and the second one even when I write tailwind classes with `@apply`, `user agent stylesheet` not reset.

For example, if I write this:
```
<button class="my-button">
 Button
</button>

...

<style scoped lang="scss">
.my-button {
 @apply p-[10px] rounded-full bg-blue-500;
}
</style>
```

I get this button:
![Screen Shot 2021-08-14 at 12 27 04](https://user-images.githubusercontent.com/4179565/129439537-b275afb2-d152-4f10-9b7c-e7f038bc91ea.png)

**Comment by adamwathan** [comment]
Hey! The problem is that you are never actually importing your CSS file as far as I can tell, try this:

https://github.com/arishojaei/vue-tailwind-library/pull/1/files

**Comment by bradlc** [comment]
In addition to that, since you have JIT mode enabled you should [configure your `purge` paths](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode). Also, Vue CLI uses an old version of `postcss-loader`, so you need to set `TAILWIND_MODE` to `watch` in your `serve` script (more info on that [here](https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files)). Here's another PR with those changes: https://github.com/arishojaei/vue-tailwind-library/pull/2/files

Once you've applied those 3 changes you should be good to go! 👍
