### ISSUE TITLE
Tailwind 2.2.x breaks Webpack hot-reload module (within a Rails app)

### ISSUE THREAD

**Issue by pil0u** [tailwindlabs/tailwindcss#5263]
### What version of Tailwind CSS are you using?

v2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 4.46.0

### What version of Node.js are you using?

v14.17.4

### What browser are you using?

N/A

### What operating system are you using?

Pop!_OS 20.04

### Reproduction repository

https://github.com/pil0u/issue-tailwind-2.2.x

### Describe your issue

Hi,

On a private repository, I noticed that upgrading TailwindCSS from 2.1 to 2.2 breaks Webpack's hot-reload module (HRM) for every other files _except for_ `app/javascript/stylesheets/tailwind.config.js`.

I have reproduced the issue in [a fresh, minimalist Rails app](https://github.com/pil0u/issue-tailwind-2.2.x) that matches my current configuration.

In the `main` branch, you can find that TailwindCSS is forced to v2.1.4. To check if Webpack's HRM works, simply open the `app/views/layouts/application.html.erb` file, add anything to the HTML, save it, and witness Webpack re-compiling.

In the `2.2.x` branch, I simply force v2.2.0 of TailwindCSS and install it. Now editing and saving the `applicaiton.html.erb` file does not trigger re-compilation. Editing the `tailwind.config.js` file does.

Notice that JIT-mode is enabled.

Any idea how I can maybe tweak my current configuration to make it work again?

Thanks,
Pierre-Loïc

**Comment by bradlc** [comment]
Hey @pil0u. We made some changes to the dependency tracking system in `v2.2.0`. The new default system depends on `dir-dependency` message support in build tools, and some tools do not support this. Check out the release notes for more information: https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#new-dependency-tracking-system-for-just-in-time-mode

Because your project uses `postcss-loader@3.0.0` (`yarn list --pattern postcss-loader`) you need to opt-in to the old tracking system by setting the `TAILWIND_MODE` environment variable to `watch`. Again we have more information about this in the [documentaion](https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files).

**Comment by pil0u** [comment]
Hey @bradlc, thank you for taking the time to write this message. I am so sorry I missed that part in the docs, I was focused on webpack some time before creating this issue, thinking the problem came from it.

The fix is dead simple, I just needed to _RTFM_ :facepalm: 

Thanks again, all the best!
