### ISSUE TITLE
When you use `space-y-4` for example in a container and the you set the `display` of one of the children of this container to `none` It will still have margin bottom.

### ISSUE THREAD

**Issue by yosefbeder** [tailwindlabs/tailwindcss#5331]
### What version of Tailwind CSS are you using?

v2.2.8

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.6, Next.js 11.1.0, webpack 5.28.0

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/yosefbeder/tailwind-bug

**Comment by adamwathan** [comment]
Hey! This is a known limitation but is by design, it would be borderline impossible to make this work with what we have available to us in CSS:

https://tailwindcss.com/docs/space#limitations

Best bet is to just use individual margin utilities for complex situations, or gap if you are comfortable with only supporting Safari 14.1 and above.
