### ISSUE TITLE
before:content-['>']  doesn't work

### ISSUE THREAD

**Issue by soma-ryo** [tailwindlabs/tailwindcss#5334]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

`"next": "11.1.0"` and web playground

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/EMk3HoEN4O

### Describe your issue

Hey Tailwind team!

I'm having an issue about [content-utilities](https://tailwindcss.com/docs/just-in-time-mode#content-utilities) in JIT mode.

According to that document, we can write content value via `content-*` utilities, and it seems like all of them work well.

But I found a bug unexpectedly while I'm trying to use `content-['>']`.

The result of the rendering does not show the content `>`. You can reproduce by the Reproduction repository URL.

**Comment by aggreggator** [comment]
How about the following workaround?
```html
<div before=">" class="before:content-[attr(before)] before:inline-block before:w-[12px] before:h-[12px]">hey</div>
```

**Comment by soma-ryo** [comment]
@aggreggator 
Thanks for replying quickly 👍 

> How about the following workaround?

It looks work correctly!
Now, we can do what we want to do, but I'm still wondering why `content-['>']` doesn't work correctly.

If there is no way to work around this behavior, I'd like you to add "`content-['>']` doesn't work" and "its solution" to the document.

**Comment by aggreggator** [comment]
> Now, we can do what we want to do, but I'm still wondering why `content-['>']` doesn't work correctly.

It does not work, because tailwind has to create a selector with an invalid character `>`.
I'm even not sure if it's possible to create such a selector with escaping the `>`.

I've tried but wasn't successful.
I think using the attribute is much cleaner and simpler solution and the browser does the heavy lifting for encoding/decoding/escaping the content.

**Comment by nghiepit** [comment]
Convert character to hexadecimal will works
```html
<div class="before:content-['\0003e']">hey</div>
```

**Comment by rowild** [comment]
Follow-up question: How can `content` be used with `@apply`?

```css
className:before {
  content: ''    /* <== this one */
}
```

**Comment by amirhosseinfaraji** [comment]
@rowild 
with attribute: 
```css
@apply content-[attr(data-content)] mr-3 text-red-600;
```
with empty content
```css
@apply content-[''] mr-3 text-red-600;
```

**Comment by adamwathan** [comment]
Thanks for providing those workarounds @aggreggator and @nghiepit! I think we can properly support this by improving the regex we use to detect class names in your templates — right now we completely ignore ">" and "<" because they are markers for HTML tags (like `<div>`) but the HTML in the original post parses just fine in browsers, so we should be able to accommodate it.

Will leave this open so we have a chance to look, but the workarounds above (especially the character code option) have basically no downside in the mean time so that's great 👍
