### ISSUE TITLE
JIT mode issues with color

### ISSUE THREAD

**Issue by thousandsofraccoons** [tailwindlabs/tailwindcss#5342]
### What version of Tailwind CSS are you using?

^2.2.9

### What build tool (or framework if it abstracts the build tool) are you using?

"postcss-cli": "^8.3.1",

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

-

### Describe your issue

As always great thanks for this amazing library.

So I used v1.8 before with `npx tailwind init --full` command, which has generated many styles like  `"border-teal-300", "border-teal-500", "border-teal-700", etc`. Besides I've added colors in the middle, like `550, 675, etc`. 

After bumping to v2.2.9 I got significant performance issues, which were discussed many times. So I switched to `mode: 'jit'` which works faster, but requires adding hundreds of lines to purge safelist to work (without a guarantee that there are other classes that might have this issue). 

For obvious reasons rewriting the whole tailwind CSS file into config to make it work is not a viable way. Is there any solution to that? Thank you.

**Comment by adamwathan** [comment]
Hey! I'm not sure what the actual issue here is, you say "JIT mode issues with color" — what's the actual problem exactly? You shouldn't need to add anything to your safelist if you ensure you are writing your HTML in a purge/JIT-friendly way:

[Writing purgeable HTML — tailwindcss.com](https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html)

I'm not sure what you mean when you say "rewriting the whole Tailwind CSS file into config" either. Are you reporting a bug or is this a usage question?

**Comment by raiyansarker** [comment]
I am having a problem but I didn't make an issue just because I'm not sure whether it is an actual issue or its just me.

The problem happens when using NextJS v11.1. They recently ditched Babel and currently using SWC. So basically the tailwind config file is not working. It is showing me errors and I can not add any customization.

I tried changing the extension to ```cjs```, but still not working. How can I fix it?

**Comment by thousandsofraccoons** [comment]
@adamwathan I will provide repo asap, thank you.

**Comment by adamwathan** [comment]
Hey! Going to close this due to inactivity/nothing actionable but if you still believe there is an issue please open a new issue with a reproduction, happy to help but just need to keep our issues tidy.
