### ISSUE TITLE
[2.2.7] Tailwind CLI does not parse imported css files from entrypoint

### ISSUE THREAD

**Issue by robertdrakedennis** [tailwindlabs/tailwindcss#5397]
### What version of Tailwind CSS are you using?

v2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

tailwindcss-cli

### What version of Node.js are you using?

v14.14.0

### What browser are you using?

Firefox 92.0b9 (64-bit) | Chrome 92.0.4515.159

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/robertdrakedennis/tailwind-cli-ignores-imported-files

### Describe your issue

Currently the tailwindcss cli will ignore and not parse any imported css files from the entry-point you give it.

My example repo is a basic html file with two divs, using two different classes ``red`` and ``blue``.

Blue is using the layer tag inside the entry-point css file.

Red is imported in the ``example.css`` file where it is also using the layer tag.

This problem persists using or not using jit.

This problem persists when using or not using the purge setting.

You can view this issue on netlify here: https://tailwind-cli-ignores-imported-files.netlify.app/

**Comment by jhealey5** [comment]
Same issue here, really annoying for `@responsive`

**Comment by adamwathan** [comment]
Hey! Tailwind doesn't handle build-time imports for you, you need a PostCSS plugin like `postcss-import` to do this. The `@import` syntax is valid regular CSS that imports CSS on the client at run time, which is why you are seeing it not get processed. The browser downloads the file you are importing, it's not imported during the build step.

See docs here:

https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports

To fix, just `npm install -D postcss-import` and add it to the beginning of your plugin list in `postcss.config.js`:

```js
module.exports = {
    plugins: {
        'postcss-import': {},
        tailwindcss: {},
        autoprefixer: {},
    }
}
```
