### ISSUE TITLE
mode: 'jit' is not working on Vite

### ISSUE THREAD

**Issue by iqbaltawakkal** [tailwindlabs/tailwindcss#5454]
### What version of Tailwind CSS are you using?

v2.2.14

### What build tool (or framework if it abstracts the build tool) are you using?

vite@2.5.6

### What version of Node.js are you using?

v15.5.0

### What browser are you using?

chrome

### What operating system are you using?

windows

### Reproduction repository

https://github.com/iqbaltawakkal/vite-vanilla-multipages

### Describe your issue

mode: 'jit' is not working, however once I deleted the mode: 'jit', it's working (without Arbitrary value working obviously).

p.s. : tried to find similar issue, didn't find one.

thanks very much in advance!

**Comment by vafanassieff** [comment]
Same for me with :

```
"tailwindcss": "^2.2.14",
"vite": "^2.5.6",
"vite-plugin-vue2": "^1.8.2",
```

**Comment by harvanchik** [comment]
I don't think this is specific to Vite.  Same thing happening to me in Angular 12.  See #5459 for more specific issue.

**Comment by adamwathan** [comment]
Hey @iqbaltawakkal! Your issue is that you haven't listed your templates in your purge config:

```diff
  module.exports = {
    mode: 'jit',
-   purge: [],
+   purge: ['./index.html'],
    darkMode: false, // or 'media' or 'class'
    theme: {
      extend: {},
    },
    variants: {
      extend: {},
    },
    plugins: [],
  }
```

That fixes the issue in your reproduction 👍🏻 

For anyone else having issues, please open a new issue with a reproduction if this isn't the same problem. We don't monitor closed issues so any comments here won't be noticed or followed up on, but new issues we will definitely see. Thanks!
