### ISSUE TITLE
Disabled prefix not working

### ISSUE THREAD

**Issue by Kazuto** [tailwindlabs/tailwindcss#5484]
### What version of Tailwind CSS are you using?

2.2.15

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 5.52.1

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Brave

### What operating system are you using?

Linux

### Reproduction repository

none

### Describe your issue

I've tried several settings in my `tailwind.config.js` already but no matter what I try I can't get the disabled prefix working.

```
mode: 'jit',

variants: {
    extend: {
        opacity: ["disabled"],
        pointerEvents: ["disabled"],
        backgroundColor: ["disabled"],
        cursor: ["disabled"],
    }
}
``` 

This is my Vue component:
```
<template>
  <component
    :is="isType"
    ref="button"
    class="inline-block rounded font-semibold transition-all duration-300"
    :class="{ 
      'text-white bg-indigo-500 hover:bg-indigo-800': color === 'default',
      'text-white cursor-not-allowed': disabled
      }"

      :disabled="disabled"
  >
    <slot></slot>
  </component>
</template>
```

I've tried it in the following ways:
```
:class="{ 
      'text-white bg-indigo-500 hover:bg-indigo-800 disabled:bg-indigo-500 disabled:hover:bg-indigo-500 disabled:cursor-not-allowed': color === 'default',
}"
```

as well as:
```
:class="{ 
    'text-white bg-indigo-500 hover:bg-indigo-800': color === 'default',
    'text-white disabled:opacity-50 cursor-not-allowed': disabled
}"
```

But looking at the app.css the classes should be available:
```
.disabled\:pointer-events-none:disabled {
    pointer-events: none;
}

.disabled\:bg-indigo-500:disabled {
    --tw-bg-opacity: 1;
    background-color: rgba(99, 102, 241, var(--tw-bg-opacity));
}

.disabled\:opacity-25:disabled {
    opacity: 0.25;
}

.disabled\:opacity-50:disabled {
    opacity: 0.5;
}
``` 

and the classes are added properly to the dom too:
```
<a class="inline-block rounded font-semibold transition-all duration-300 px-5 py-2 text-base text-white bg-indigo-500 hover:bg-indigo-800 disabled:bg-indigo-500 disabled:hover:bg-indigo-500 text-white cursor-not-allowed" disabled="true" >Lorem</a>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue here is that an `<a>` tag doesn't have a `disabled` state. If you want to have a disabled state then you probably want a `<button>` instead. If you really want a "disabled" link, then I would create a custom component for it where you add the classes for the disabled state directly when the `disabled` prop is passed (e.g.: `:class={ 'opacity-25': disabled }`). You also have to make sure to either set the `href` to nothing or a hash, or add a `@click` listener to prevent the browser from going to that specific resource.

Here is a simplified example, showing that `a` can't be disabled: https://jsfiddle.net/e1odnhrg/

**Comment by Kazuto** [comment]
Oh right, completely forgot that I've set my button component to a `a` tag. Sometimes the issue is between screen and chair 😅🤣

Thanks for your quick reply :+1:
