### ISSUE TITLE
Container not prefixed with #app when setting important setting in config

### ISSUE THREAD

**Issue by DHFW** [tailwindlabs/tailwindcss#5521]
When using the config setting `important: '#app'` the `.container` class is not prefixed with `#app`.
Version used: 2.2.14/15.

Is this intentional or a bug?

Reproduction in this playground:

https://play.tailwindcss.com/J0o6cTXB0O

**Comment by reinink** [comment]
Hey there! So yeah, this is expected behavior.

The purpose of the "important" option in Tailwind is to give you the ability to override the styles of classes with a higher specificity. This can be especially helpful when using Tailwind in a project that uses existing styles, or even third-party styles, that have a higher specificity than the Tailwind styles.

As for the container, it's actually not a utility, but rather a component. Unlike utilities, the container sets a `max-width` value at each breakpoint using media queries. So in that sense it hasn't been designed to override existing styles.

Often in these situations we've found that folks are actually trying to use the important option as a scoping tool. That's not the intent of this feature. It's simply a hack for increasing specificity of utilities, and not intended as a way to isolate Tailwind to a specific DOM tree.

In the same way, our reset styles are also not prefixed with the important selector either.

That all said, if you're using the new JIT mode, you can manually apply the `!important` rule on a per class basis using an exclamation mark before the class, like this:

```html
<div class="!container">
```

I hope that helps! 🤟
