### ISSUE TITLE
Too early to adopt backdrop-filter blur in Tailwind CSS, it's not supported in latest Firefox.

### ISSUE THREAD

**Issue by rockmandash** [tailwindlabs/tailwindcss#5567]
**What version of Tailwind CSS are you using?**

v2.2.15

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

v12.0.0

**What browser are you using?**

Firefox 92

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/Dmhc4Rd26w

**Describe your issue**

It's too early to adopt backdrop-filter blur in Tailwind CSS since it's not working in the latest Firefox, you'll have to flip two 
 experimental flags in order to work.

Firefox Screenshot:

![image](https://user-images.githubusercontent.com/7580792/134279134-59336a53-55eb-40e7-9874-030ae059f449.png)

Chrome Screenshot:

![image](https://user-images.githubusercontent.com/7580792/134279166-a6b24a6f-7b31-4d99-9267-ac03303e4f8f.png)

**Comment by stefan-schweiger** [comment]
I don't think that's a good reason for not providing it at all. If you want to have a consistent look across browser simply don't use it, use a sensible fallback or use another method altogether.

**Comment by rockmandash** [comment]
But it can be provided from plugins first, and when all modern browsers support the feature, then it can be merged in the core I think.

**Comment by reinink** [comment]
Hey there @rockmandash! So you're absolutely right, Firefox doesn't quite have support for `backdrop-filter` yet, although it [appears to be coming](https://caniuse.com/css-backdrop-filter). Just because something doesn't have full browser support yet, doesn't mean that it's not included with Tailwind CSS.

And the main reason for that is because everyone's threshold here is going to be different. Some people need to build websites for users on IE11, while others are okay with only supporting modern evergreen browsers. We want both types of users to be able to use Tailwind CSS!

Tailwind CSS supports many modern CSS features. We proclaim this boldly [on our website](https://tailwindcss.com/#modern-features). It's your choice as a developer whether you want to use these new CSS features. If you need to support IE11, you'll need to be much more careful with what CSS features you use.

One nice thing about `backdrop-filter` is that it can be implemented in a progressive way. For example, if you look at our Headless UI website, you can see that we're using a background blur behind the site header:

![image](https://user-images.githubusercontent.com/882133/134403772-e25cf27c-3fbd-4085-9afd-69ed953f74fb.png)

But, of course, in Firefox that doesn't work, but it still looks okay:

![image](https://user-images.githubusercontent.com/882133/134403885-eec8ee57-d8b0-4320-9d94-de11ccb68f44.png)

Of course we don't support *all* CSS features. We still try to make a judgment call here. If a feature is gaining browser support and popularity, that's when we start considering it. However, we're unlikely to ever include CSS features that have very poor browser support.

I hope that explanation makes sense!

**Comment by vhscom** [comment]
Perhaps maintainers balked here at the title of this issue but I feel there's a documentation follow-up here to provide more comprehensive information in the Tailwind CSS docs to provide (a) browser support and (b) fallback implementation. In a perfect world we wouldn't have to do cross-browser testing. We don't live in that world. Always test cross-brower and cross-platform.

**Comment by vhscom** [comment]
Perhaps maintainers balked here at the title of this issue but I feel there's a documentation follow-up here to provide more comprehensive information in the Tailwind CSS docs for features which don't work across all major browsers such as (a) browser support warning and (b) fallback implementation(s). In a perfect world we wouldn't have to do cross-browser testing. We don't live in that world. Always test cross-brower and cross-platform.

**Comment by vhscom** [comment]
Perhaps maintainers balked at the title of this issue but I feel there's a documentation follow-up here to provide more comprehensive information in the Tailwind CSS docs for features which don't work across all major browsers such as (a) browser support warning and (b) fallback implementation(s). In a perfect world we wouldn't have to do cross-browser testing. We don't live in that world. Always test cross-brower and cross-platform.

**Comment by vhscom** [comment]
Perhaps maintainers balked at the title of this issue but I feel there's a documentation follow-up here to provide more comprehensive information in the Tailwind CSS docs for features which don't work across all major browsers such as (a) browser support warning and (b) fallback implementation. In a perfect world we wouldn't have to do cross-browser testing. We don't live in that world. Always test cross-brower and cross-platform.

**Comment by vhscom** [comment]
For those who land here looking for a fix for the Firefox issue:
https://blog.braydoncoyer.dev/build-a-glassmorphic-navbar-with-tailwindcss-backdrop-filter-and-backdrop-blur
