### ISSUE TITLE
[divide-y] Top border with `grid-cols-*` and  `divide-y`

### ISSUE THREAD

**Issue by Roman991** [tailwindlabs/tailwindcss#5584]
There shouldnt be the top border line when using `grid-cols`

![image](https://user-images.githubusercontent.com/10634244/134672530-d414a10a-5070-4e23-af1a-9122171961a6.png)

example:
https://play.tailwindcss.com/iQpZcMV8Su

**Comment by adamwathan** [comment]
Hey! This is by design I'm afraid — the divide utilities are just a quick shortcut for adding a border to the top of every element except the first one, they aren't supposed to be "smart" or context-aware or anything. There's no way to know that things wrap over and that the border has to be removed for every 3rd item.

They are really just a utility for writing this CSS:

```css
.divide-y > * + * {
  border-top: 1px solid gray;
}
```

For what you're trying to do I think you just want an actual `<table>` here 👍 

No plans to make this behave any differently (would just be way too complex and outside of the scope of what these are intended for) so going to close, but hope that is helpful context.
