### ISSUE TITLE
translate-x does not work as expected with JIT mode enabled and no base styles

### ISSUE THREAD

**Issue by mjatharvest** [tailwindlabs/tailwindcss#5739]
**What version of Tailwind CSS are you using?**

2.2.16

**What build tool (or framework if it abstracts the build tool) are you using?**

Laravel Mix 6.0.31 with built-in PostCSS

**What version of Node.js are you using?**

15.11.0

**What browser are you using?**

Chrome

**What operating system are you using?**

masOS

**Reproduction URL**

https://play.tailwindcss.com/5565Df9z5h

**Describe your issue**

In my case I did not include the tailwind base styles.

```
/* @tailwind base; */
```

And with JIT mode enabled, using classes `transform translate-x-1/2` doesn't work as expected. The `translate-x-1/2` class has no effect.

However, turn off MIT mode and it works.

The styles compile differently with JIT on...
![Screen Shot 2021-10-08 at 10 35 54 AM](https://user-images.githubusercontent.com/285877/136587227-17b54837-ed93-4c34-a594-9fd187c0dfed.png)

...and with JIT off.
![Screen Shot 2021-10-08 at 10 37 14 AM](https://user-images.githubusercontent.com/285877/136587314-29f28ca2-abd6-4593-9096-f5738e12657e.png)

Hope that all makes sense.

**Comment by adamwathan** [comment]
Hey! This is by design, those styles require certain transform-specific base styles to be added. This is because of the simplified composition stuff we were able to add:

https://tailwindcss.com/docs/just-in-time-mode#simplified-transform-filter-and-backdrop-filter-composition

This is a bit of a breaking change from non-JIT mode because the `transform` class is no longer responsible for setting all of those base variables in order for the simplified composition stuff to work.

If you want to disable Tailwind's reset styles, you should do so by disabling Preflight rather than omitting the base styles:

```js
// tailwind.config.js
module.exports = {
  corePlugins: {
    preflight: false,
  }
}
```

I agree it would be more intuitive if it would work without `@tailwind base` but for now it's necessary, maybe something we can figure out in the future.

**Comment by mjatharvest** [comment]
Thank you very much, @adamwathan! That explanation makes sense, and disabling preflight does the trick 👍

**Comment by JayBox325** [comment]
I'm getting this issue where no transform-based utilities are working and setting preflight to false breaks more than it fixes.

![image](https://user-images.githubusercontent.com/13233809/142609955-30fcae9c-0186-400b-89c7-e5ade16e73d5.png)

I have got the same CSS applied as @mjatharvest's screenshot, but the rotate is not having an effect. I too am running `jit` mode.

**Comment by lyzadanger** [comment]
I'm wondering if this (`base` layer is required for transforms) could be surfaced in JIT gotchas documentation. Our organization is introducing tailwind to an existing project and we've taken the strategy so far of only using the `utilities` layer, which has been convenient (and we expressly do not want `preflight`). Transforms were the first thing I've encountered so far that didn't just magically work and it didn't occur to me there was a dependency on the `base` layer. I don't know what I would have done if I hadn't been able to find this issue thread!
