### ISSUE TITLE
before:-pseudo-variant overrides explicitly set 'content'

### ISSUE THREAD

**Issue by jnns** [tailwindlabs/tailwindcss#5759]
**What version of Tailwind CSS are you using?**

v2.2.16

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CLI

**What version of Node.js are you using?**

v16.10.0

**What browser are you using?**

Firefox 93

**What operating system are you using?**

Linux

**Reproduction URL**

https://play.tailwindcss.com/W5vUF4bvmS

**Describe your issue**

Pseudo element variants include `content: ""` which in some cases overrides explicitly set content through the arbitrary value feature:
 
![Bildschirmfoto von 2021-10-11 19-47-53](https://user-images.githubusercontent.com/206281/136834990-46f976cd-144a-4f86-a351-842b12d52582.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in Tailwind v3.

If you are using JIT mode, then you can already try it by using the v3 alpha version using `npm install tailwindcss@insiders` or `yarn add tailwindcss@insiders`.

If you are using AOT mode, then I would recommend you to try and switch to JIT mode first. If you can't do that for technical reasons / bugs, please open an issue with a minimal reproduction repo so that we can help.
