### ISSUE TITLE
JIT inconsistent behaviour for arbitrary color and position values in linear gradients

### ISSUE THREAD

**Issue by camiloforero** [tailwindlabs/tailwindcss#6128]
**What version of Tailwind CSS are you using?**
3.0.0-alpha.2

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss 8.3.11
vite 2.6.13

**What version of Node.js are you using?**
v16.13.0

**What browser are you using?**
FIrefox

**What operating system are you using?**
Ubuntu 20.04 LTS

**Reproduction URL**
https://play.tailwindcss.com/pDDrSVLrEZ

**Describe your issue**
The playground shows it best; when trying to use TailwindCSS with arbitrary values for background linear gradients:

* When simply using color values with no percentages, it works as expected, and looks the same as declaring the background with vanilla css
* When setting a percentage inside the `from` value, it will compile, and a gradient will exist, but it won't look the same as if declaring the gradient through vanilla css (`bg-gradient-to-r from-[#FF0000,50%] to-[#CCCC00]`)
* When trying to set a percentage inside the `to` value, it won't work at all (`bg-gradient-to-r from-[#FF0000,50%] to-[#CCCC00,85%]`)

**Comment by adamwathan** [comment]
Hey! Don't think this is really a bug per se — what you are trying to specify is the color stop location right, not an actual color?

`from-[{color}]` does work, but it's not currently designed to support adding in the stop value.

That said, it _will_ work if you use the new `_` syntax we switched to for v3 instead of the comma:

```
<div class="bg-gradient-to-r from-[#FF0000_50%] to-[#CCCC00_85%]">
  <!-- ... -->
</div>
```

...but I wouldn't consider this officially supported, and it could stop working if we ever have to change our background image definition to include a manual color stop.

More bullet-proof thing to do in these cases is use an arbitrary value for the background image:

```
<div class="bg-[linear-gradient(to_right,#ff0000_50%,#cccc00_85%)]">
```

Hope that helps!

**Comment by camiloforero** [comment]
Hey @adamwathan , it does help, it works and explains everything, thank you!

But I have a question: where could I have found the `,` to `_` change in arbitrary values?

* The [current JIT documentation](https://tailwindcss.com/docs/just-in-time-mode) still recommends using the `,` for arbitrary values. I assume in the future there will be a `v3` documentation I can select from the topbar, but it doesn't exist yet
* The [two v3.0.0 changelogs](https://github.com/tailwindlabs/tailwindcss/releases) don't mention this change either

And I know of no other place I can find information

So what can I do to be more aware of these new changes?
