### ISSUE TITLE
Purge does not remove styles from plugin components

### ISSUE THREAD

**Issue by pfcodes** [tailwindlabs/tailwindcss#6147]
**What version of Tailwind CSS are you using?**

v2.1.2

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwind-cli (through npx)

**What version of Node.js are you using?**

v17.1.0

**What browser are you using?**

N/A

**What operating system are you using?**

For example: macOS, Windows

**Reproduction URL**

https://play.tailwindcss.com/3NAcPzcdHM?file=config

**Describe your issue**

PurgeCSS does not work on component classes created in the `plugins` part of a base tailwind config used as a preset. This is true even when the requested class to be purged is inside of the PurgeCSS blacklist option.

Command used:
```
npx tailwindcss -c ./tailwind.config.js -i ./input.css -o ./dist/output
```

**Comment by adamwathan** [comment]
I'm guessing this is just because you called the class `button` and the word `button` appears in your HTML (for example even just `<button>` will cause the class to be generated).

Can you create a proper reproduction repository that I can clone and run `npm run build` or whatever to see exactly what you are seeing?
