### ISSUE TITLE
Infinite loop :not() selector with same class name as @apply

### ISSUE THREAD

**Issue by almeric** [tailwindlabs/tailwindcss#6349]
**What version of Tailwind CSS are you using?**

v3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 

**What version of Node.js are you using?**

v17.1.0

**What browser are you using?**

N/A

**What operating system are you using?**

MacOs

**Reproduction URL**

https://play.tailwindcss.com/EYLtonLb16?file=css

**Describe your issue**

```
body:not(.text-emerald-500) {
  @apply text-emerald-500;
}
```
Will cause an infinite loop, eventually exhausting memory. This is similar to https://github.com/tailwindlabs/tailwindcss/issues/3541, except the `:not()` selector.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Yep this is the same issue that Adam talks about here: https://github.com/tailwindlabs/tailwindcss/issues/3541#issuecomment-774727159

It's a circular dependency since the class you are applying is also in the definition. I'll try to make it error instead doing the infinite loop.
