### ISSUE TITLE
Installing 3.0 actually installs 2.+ version

### ISSUE THREAD

**Issue by sasafister** [tailwindlabs/tailwindcss#6356]
When I try to install fresh version of tailwind into my Angular project, it actually installs version 2.2.19 with cli command

```npm install -D tailwindcss```

What I had to do is run this command 

```npm install -D tailwindcss@latest```

That installs 3.0 version. 

I guess the first command should install latest version?

**Comment by joaop-oliveira1** [comment]
I'm having this issue too!

**Comment by sasafister** [comment]
Hmm. That worked for me, but I notice also that if I'm using with postcss

```npm install -D tailwindcss postcss autoprefixer```

I'm not getting postcss.module.js file at all.

**Comment by NarendraPatwardhan** [comment]
@sasafister do you mean postcss.config.js? If so, it is generated by adding a -p flag after `npx tailwindcss init`.

**Comment by sasafister** [comment]
Yep sorry, but it's not generated by that cli command for some reason, at least it doesn't work here

**Comment by arp99** [comment]
Same here, cannot use the new shadow color features😅, for this issue

**Comment by sasafister** [comment]
install it with yarn, it works just fine

**Comment by reinink** [comment]
Hey folks — this is weird. I suspect this has something to do with a local npm cache or something like that. I am hoping this problem goes away (or has already gone away) for you.

I am curious what you get if you run `npm show tailwindcss`. I am seeing v3.0.5 listed:

```sh
tailwindcss@3.0.5 | MIT | deps: 21 | versions: 461
A utility-first CSS framework for rapidly building custom user interfaces.
https://tailwindcss.com
```

Going to close this one, because if anything this is an npm issue, but I appreciate you reporting this either way — please let us know if the problem persists 👍
