### ISSUE TITLE
Discrepancy in v3 docs for overflow-ellipsis vs text-ellipsis

### ISSUE THREAD

**Issue by jshimkoski** [tailwindlabs/tailwindcss#6363]
The upgrade guide says that `overflow-ellipsis` was renamed `text-ellipsis`:

https://tailwindcss.com/docs/upgrade-guide#overflow-clip-ellipsis

However, the Text Overflow page still provides an Overflow Ellipsis section, instructing developers to still use `overflow-ellipsis`:

https://tailwindcss.com/docs/text-overflow

**Comment by jshimkoski** [comment]
After some investigation, it seems that `overflow-ellipsis` does in fact still work. 

Was `overflow-clip` the only utility actually removed? Will `overflow-ellipsis` be removed eventually?

**Comment by adamwathan** [comment]
Fixed the docs, thank you!

`overflow-clip` was indeed the only one changed, because we made it `overflow: clip`. We will keep `overflow-ellipsis` until like v5 or something and remove it when we feel pretty confident it won't affect many people, no reason to remove it if we don't have to and cause people grief.

**Comment by jshimkoski** [comment]
Thank you.
