### ISSUE TITLE
Using `@apply` does not work with `dark:` variant in CSS module/css file 

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [tailwindlabs/tailwindcss#6388]
**What version of Tailwind CSS are you using?**

`^3.0.1`

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.4, Next.js 12.0.7, autoprefixer 10.4.0

**What version of Node.js are you using?**

v16.13.1

**What browser are you using?**

Firefox and Edge (chromium)

**What operating system are you using?**

Windows

**Reproduction URL**

-  Live deploy: https://tailwindcss-darkmode-bug.vercel.app/
- Repo: https://github.com/Dev-CasperTheGhost/tailwindcss-darkmode-bug

**Describe your issue**

When using `@apply` in a css file (can also be a CSS module), it will **not** apply the `dark:` variants. However when using classes, the dark variants do work. 

PS: This may be related to #3942, but I didn't find an actual fix for this issue.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is an interesting one and let me try and explain what happens here:

Dark mode (class based) is currently implemented as `.dark &` this means that in your case this will result in `.dark html`. As you can see this requires a parent element but that doesn't exist above the `html` element.

So what can we do in this case?
One thing we can do is implement dark mode as `['.dark &', '&.dark']`, this means that the selectors will look like this: `.dark html, html.dark {}` and this matches what you want.
However, this also results in _every single darkmode selector_ to be duplicated. This will make your css way bigger than it should be because this issue only exists on the `html` element. Additionally this results in a breaking change.

Instead, what I would suggest is to do this:
```css
html {
  @apply text-neutral-800 bg-white;
}

html.dark {
  @aply text-white bg-neutral-900;
}
```

This is a slightly suboptimal developer experience, but I think it is totally worth it since this only needs to happen for the `html` one. All others can still use the `dark:...` that you used before.

Hope this helps!

**Comment by victorhqc** [comment]
I have the exact same issue when using css modules as in

```typescript
import styles from './styles.module.css';

const MyComponent = () => (
<div className={styles.test}>
  hello world
</div>
);
```

```css
.test {
  @apply bg-white dark:bg-neutral-900 text-neutral-800 dark:text-white;
}
```

It only detects the `light` colors, and my HTML does have the `.dark` class. However, this is not affected if I use the class name directly instead of using `css` modules.

```typescript
import './styles.css';

const MyComponent = () => (
<div className=""test">
  hello world
</div>
);
```

Any idea what could be making this issue?
