### ISSUE TITLE
Purge Keyframes not supported in version 3

### ISSUE THREAD

**Issue by arashHasanzade** [tailwindlabs/tailwindcss#6464]
According to this [issue](https://github.com/tailwindlabs/tailwindcss/issues/3234) we can set option for purge Keyframes in version 2.
But in new version i can't find any documentation for this option of purge.

**Comment by reinink** [comment]
Hey! So by default Tailwind CSS v3.0 already does not include keyframes for stuff that's configured in your `tailwind.config.js` file. For example, if you don't use the `animate-spin` utility, it won't appear in your outputted CSS.

However, Tailwind does not purge keyframes from your custom CSS, simply because we don't know if you need it or not. This is actually how it worked already in Tailwind v2.

Of course you can still purge keyframes from your custom CSS, you'll just need to use another tool for this, like PurgeCSS.

Hope that helps! 💪
