### ISSUE TITLE
Resolve config file relative to the file being transformed instead of cwd

### ISSUE THREAD

**Issue by mischnic** [tailwindlabs/tailwindcss#6517]
**What version of Tailwind CSS are you using?**

v3.0.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Parcel 2 👋 

**What version of Node.js are you using?**

16

**What operating system are you using?**

macOS

**Describe your issue**

A "standard" PostCSS config like

```js
const path = require("path");

module.exports = {
  plugins: [
      require('tailwindcss')
  ]
}
```

causes Tailwind to search for the config file relative to the current working directory because of this

https://github.com/tailwindlabs/tailwindcss/blob/a7263a8f6faf989cb98553491d5c456d0b86de9b/src/util/resolveConfigPath.js#L46-L48

I think it should instead be relative to the file that's being processed. This way you could also have a single project with multiple config files for different parts.

This might have performance downsides if you currently search just once for a config.

**Comment by FranciscoOx** [comment]
I profoundly like your dedicated abilities as the post you distributed has some incredible data which is very valuable for me.

**Comment by Serenit8** [comment]
file of your project, or through a jest.config.js, or jest.config.ts file or through the --config <path/to/file.js|ts|cjs|mjs|json> option. If you'd like to use your package.json to store Jest's config, the "jest" key should be used on the top level so Jest will know how to find your settings:

**Comment by Farr69** [comment]
You can also use this functionality to transform other files, including Console or Windows service application configuration files (for example, FabrikamService.exe.config).

**Comment by Erin69** [comment]
__dirname is not necessarily the same as the current working directory, but fs.readFileSync() uses the current working directory. The current working directory is likely set to whatever it was when you launched node.****

**Comment by Holthaus789** [comment]
Facing same issue here. Help is appreciated.

**Comment by Holthaus789** [comment]
Facing same issue here. Help is appreciated.

**Comment by Edith896** [comment]
Hey bot, I am new here, I will be very grateful, if I get some help regarding this site from you. I will write it accordingly if i need some help!

**Comment by Palmieri78759** [comment]
In this case, deviation refers to the treatment of other config filetypes, and deviation from other tools in the ecosystem, rather than deviation from reporter loading. Reporters are expected to be libraries; the intuition is different.
Attempting to require relative to node_modules/mocha/lib/cli before attempting path.resolve introduces the possibility that mocha accidentally pulls a config file from node_modules or from within mocha itself, when the user wanted to use a local config. It also requires the docs to become more complicated. Right now they say --config is a "path to config file" which clearly explains an intuitive behavior that is identical for all config file extensions. Clarifying that it may use node's module resolution algorithm, but only if there's an explicit .js extension, just complicates things. It is deviating from node's module resolution algorithm as well, because a user can't publish my-common-mocha-config to npm and specify --config my-common-mocha-config. It'll attempt to parse JSON from CWD.

**Comment by Palmieri78759** [comment]
Thanks for sharing. I found a lot of interesting information here. [ForAgentsOnly Login](https://www.foragentsonly.me/)

**Comment by Fuller05767** [comment]
Thanks for sharing. I found a lot of interesting information here.

**Comment by thecrypticace** [comment]
Hey, we spent a good bit of time coming up with a solution here and the result of it is the new `@config` feature for v3.2 which lets you specify the config file location relative to a given CSS file! (see #9405 for more details)

The automatic resolution based on path to the input file (so `@config` isn't needed in some cases) is something we may plan for v4 but this new feature will work for these use cases as well — and it's a bit more powerful since it simplifies using multiple configs with different names which is a fairly common occurrence in projects with a user/admin split.

Thank you for your patience — and for the suggestion! ✨ 

You should be able to test this out in our insiders build in a few minutes once it is published with `npm install tailwindcss@insiders`
