### ISSUE TITLE
From 3.0.2 to 3.0.3 borders color in config is lost

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#6524]
**What version of Tailwind CSS are you using?**

"@tailwindcss/forms": "0.4.0",
"@tailwindcss/line-clamp": "0.3.0",
"tailwindcss": "3.0.3",

**What build tool (or framework if it abstracts the build tool) are you using?**

"postcss": "8.4.5",

**What version of Node.js are you using?**

16

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

COMING SOON

**Describe your issue**

After upgrade from "tailwindcss": "3.0.2" to "tailwindcss": "3.0.3" my borders color is now black instead of `colors.gray.300`.

I'm using this in config:

```js
theme: {
  extend: {
    borderColor: (theme) => ({
      DEFAULT: theme("colors.gray.300", "currentColor"),
    }),
  },
},
```

**Comment by frederikhors** [comment]
Even if I remove that config from the file the borders are black.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Will get it fixed in #6526 and will publish a new release!

**Comment by RobinMalfait** [comment]
@frederikhors the issue was that our new always on defaults layer (required reset for certain utilities) was injected _before_ the `@tailwind base` layer which also had a recent for border colors with `border-color: currentColor`. The layers have been switched and should be fixed.

A v3.0.4 build has just been published, so if you can verify that build that would be awesome. Sorry for the inconvenience!

**Comment by frederikhors** [comment]
Yes, it works now.

Can I get a medal as the fastest Tailwind new release tester?

**Comment by RobinMalfait** [comment]
@frederikhors Does this work for you?

![](https://sdk.bitmoji.com/render/panel/f70171d9-4f76-4409-b78f-8ed9b0076e12-888d7782-1474-482e-8588-de4fda5de576-v1.png?transparent=1&palette=1&width=246)
