### ISSUE TITLE
How to prevent cleaning css files imported from `node_modules`?

### ISSUE THREAD

**Issue by yeshkarluk** [tailwindlabs/tailwindcss#6563]
**What version of Tailwind CSS are you using?**

v3.0.5

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 12.0.7, postcss 8.4.5, autoprefixer 10.4.0

**What version of Node.js are you using?**

v16.10.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://stackblitz.com/edit/nextjs-j8d37p?file=tailwind.config.js

**Describe your issue**
How to prevent cleaning css files imported from `node_modules`?

If css which imported from `node_modules` has duplicated properties, they are excluded from the bundle.

If you open the source file like `node_modules/antd/dist/antd.css`, you can see`.ant-popover-inner` class has 2 properties `box-shadow`, but in chrome devtools you can see that the duplicate properties have been cleared
![photo_2021-12-16 14 45 38](https://user-images.githubusercontent.com/17741812/146366718-9cc579a4-c530-4964-8d9e-268fc521dc68.jpeg)
![photo_2021-12-16 14 45 43](https://user-images.githubusercontent.com/17741812/146366729-a8e17b78-c2c5-4d5e-8b2b-18219f4874eb.jpeg)

**Comment by reinink** [comment]
Hey! So I just pulled down this project, disabled Tailwind CSS entirely, and then ran `npm run build`, and I got the same results.

I think this is actually a minifier issue. When the CSS is minified, the minifier is seeing duplicate `box-shadow` properties, and is removing the first one — since it's not possible to have two `box-shadow` properties at once.

Doing [a quick Google search](https://stackoverflow.com/questions/8004765/css-9-in-width-property), I can see that `\9` is used as an Internet Explorer hack. Unfortunately, this isn't compatible with your CSS minifer.

So yeah, this issue isn't Tailwind related. In fact, since `antd/dist/antd.css` is imported separately from Tailwind CSS, it's run in a separate PostCSS process, meaning Tailwind CSS isn't even able to "see" these styles.

I hope that helps 👍

**Comment by yeshkarluk** [comment]
@reinink 
I think the problem is in the postcss plugin, because the duplicate css properties (from `node_modules`) are not deleted with prev version

tw 2.2.19 — https://stackblitz.com/edit/nextjs-c7nzb3?file=tailwind.config.js (tooltip has **two** property box-shadow)
tw 3.0.5  — https://stackblitz.com/edit/nextjs-j8d37p?file=tailwind.config.js (tooltip has **one** property box-shadow)
