### ISSUE TITLE
Is it just me or hover, cursor-pointer all seem to be broken in the new release

### ISSUE THREAD

**Issue by Klin-Coders** [tailwindlabs/tailwindcss#6565]
**What version of Tailwind CSS are you using?**
 v^3.0.5

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss ^8.4.4, Next.js 12.0.7, autoprefixer ^10.4.0

**What version of Node.js are you using?**
v14.15.4

**What browser are you using?**
Chrome, Safari

**What operating system are you using?**
 macOS

**Reproduction URL**
https://euniquelogistics.com/

**Describe your issue**
Hoover background color and text color doesnt work, cursor-pointer doesnt too and some i am sure havent tested yet

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.
adding curosor-pointer and hover:bg-green-500 faails to work normally

**Comment by Klin-Coders** [comment]
the nav texts don't show the pointer cursor, the signin text doesnt change bg color and text color on hover as well as a pointer cursor

**Comment by reinink** [comment]
Hey! This isn't a cursor (or Tailwind CSS) issue — you'll notice that you're not even able to click on any of the links or buttons on that website. That's because you have an absolutely positioned element that's covering the whole website — preventing the cursor from "touching" the links and buttons.

Hope that helps! 💪

```html
<div class="absolute">
  <div class=" relative w-[100vw] h-[560px] z-[-1]">
    <!-- ... -->
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/882133/146382704-a0c3bc02-b395-43aa-b5a2-9f65acb3435b.png)

**Comment by Klin-Coders** [comment]
> 

Thank you very much
