### ISSUE TITLE
3.0.7: 'rotate.-90' does not exist in theme config

### ISSUE THREAD

**Issue by driskull** [tailwindlabs/tailwindcss#6601]
**What version of Tailwind CSS are you using?**

3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome
**What operating system are you using?**

macOS

**Reproduction URL**

The reproduction works in 2x but not in 3x.

https://play.tailwindcss.com/AfAL4DBMSc?file=css

**Describe your issue**

In 1x, I could use `theme("rotate.-90")` in CSS and it would work fine.

In 3x, I had to add the following into the config in order for the negative values to work. 

```js
{
  theme: {
    extend: {
      rotate: {
              "-90": "-90deg",
              "-180": "-180deg"
            }
      }
  }
}
```

Is this a bug? or by design?

**Comment by adamwathan** [comment]
Hey! In Tailwind 3, the negative prefix is a first class feature of the framework rather than something that is derived from the config, so the negative values no longer exist in the config.

You can use `calc(theme('rotate.90') * -1)` instead, or just write out `-90deg` which is what I would do in this specific case. I'll add this to the list of changes in the upgrade guide, thanks for catching it.
