### ISSUE TITLE
Possible Bug: Tailwind CLI generates unused plugin components style

### ISSUE THREAD

**Issue by enjidev** [tailwindlabs/tailwindcss#6692]
**What version of Tailwind CSS are you using?**

v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CLI

**What version of Node.js are you using?**

v14.16.0

**What browser are you using?**

N/A

**What operating system are you using?**

Arch Linux

**Reproduction URL**

https://stackblitz.com/edit/node-mbztwv?file=tailwind.config.js

**Describe your issue**

I've created a `button` component via a plugin. The `button` has several color schemes, let's say `blue` and `green`. Here's the component selector:

1. `.button`
2. `.button:where(.blue)`
3. `.button:where(.green)`

When I create an element with `class="button"`, Tailwind generates all component styles. The case is the same with the component that has the selector `.button.another-selector`.

Is that a bug?

--- 

My current solution is to create components with this selector:

1. `.button`
2. `.button-blue`
3. `.button-green`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is by design, the reason that this happens is that our detection of classes is simple/dumb by default. More info: https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

The TL;DR is that we will look at your raw content files as plain text. We see `button` and there exists a rule `.button` so we generate that. We also only check for classes, we don't detect attributes or parse more complex css selectors like `.button:where(.blue)`. In this case `.button` exists so we generate that.

The biggest problem is that if you have a `.button`, you can dynamically at runtime add the `.blue` class. But Tailwind is a built tool, we don't ship a runtime so we have no idea whether this rule should exist or not and therefore we generate it.
