### ISSUE TITLE
For same input Stdin produces different output from "-i <file.css>"

### ISSUE THREAD

**Issue by Xeevis** [tailwindlabs/tailwindcss#6865]
**What version of Tailwind CSS are you using?**

v3.0.9

**What build tool (or framework if it abstracts the build tool) are you using?**

Standalone CLI

**What operating system are you using?**

Windows 10

**Describe your issue**

When input is piped from stdin, output will not include any custom classes and layers as it does with `-i <file.css`.

**Reproduction**
1. Download latest [tailwindcss-windows-x64.exe](https://github.com/tailwindlabs/tailwindcss/releases/download/v3.0.9/tailwindcss-windows-x64.exe)
2. Run `PS> echo '@tailwind base;@tailwind components;@tailwind utilities;.foo{@apply bg-gray-200;}' > input.css`
3. Run `PS> .\tailwindcss-windows-x64 -i input.css -o output.css`
4. Run `PS> cat input.css | .\tailwindcss-windows-x64 -o output-stdin.css`
5. **output.css** will have `.foo` class appended to the end while **output-stdin.css** not.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This should be fixed, and will be available in the next release (probably later today).

The only difference is that you have to use `-i -` instead of no input flag at all. The reason for this is because of the halting problem. This `-i -` will tell the CLI to use the stdin instead of a file.

**Comment by Xeevis** [comment]
@RobinMalfait That was fast and seems to be working great, awesome! Thank you very much, you have saved me and surely many others lots of unnecessary fs i/o.
