### ISSUE TITLE
@layer declarations not found when using grouped selectors

### ISSUE THREAD

**Issue by ndimatteo** [tailwindlabs/tailwindcss#6882]
**What version of Tailwind CSS are you using?**
v3.0.9

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss ^8.3.11, Next.js ^12.0.4

**What version of Node.js are you using?**
v14.0.0

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction URL**
https://play.tailwindcss.com/EdpBQBdhBF?file=css

**Describe your issue**
Hey there! You used to be able to group selectors in an `@layer` declaration, but now it's throwing an error.

In the reproduction URL try removing the `h1,` selector and it will work again 😃

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This was indeed working in the older AOT mode, but never worked in JIT mode.

This should be fixed in https://github.com/tailwindlabs/tailwindcss/pull/6922, and will be available in the next release (probably later today).

You can already try it by using the insiders build `npm install tailwindcss@insiders` or `yarn add tailwindcss@insiders`.
