### ISSUE TITLE
`content` - supports scoped packages path?

### ISSUE THREAD

**Issue by 7iomka** [tailwindlabs/tailwindcss#6889]
**What version of Tailwind CSS are you using?**

Latest

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: tailwindcss@latest, next@next,

**What version of Node.js are you using?**

v16.5.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

NO

**Describe your issue**

If I add path to scoped package, finally I only get generated styles for classes found in current `./src` folder, and none from scoped package.

```js
content: ['./src/**/*.{js,ts,jsx,tsx}', '@xx/ui/**/*.{js,ts,jsx,tsx}'],
```

In my next.config.js file I use their `next-transpile-modules` to correctly import non-compiled packages in app.
```js
const withPlugins = require('next-compose-plugins');
const transpileModules = require('next-transpile-modules');

const nextConfig = {
  reactStrictMode: true,
  typescript: {
    ignoreDevErrors: true,
    ignoreBuildErrors: true,
  },
 
  // experimental: {
  //   externalDir: true,
  // },
};

const scopedPackages = ['@xx/ui', '@xx/utils', '@xx/hooks', '@xx/config', '@xx/types'];
const plugins = [transpileModules([...scopedPackages])];
module.exports = withPlugins(plugins, nextConfig);
```

I use yarn monorepo, and I have package with ui components.

**Comment by 7iomka** [comment]
I also tried exprimental `externalDir` to include external code `as is`, but nothing changed - tailwind still ignore this files

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The content paths are file system paths. We don't read from your next.config.js, tsconfig.json, <insert any tool here that allows you to alias packages> ... files.

The solution is to use relative paths, however that can be a bit scary based on where you execute tailwind from. Instead, I recommend to resolve the relative paths to absolute paths from the current `tailwind.config.js` file. 

Here is an example where I made a bunch of assumptions (because I don't know how your project is structured since you didn't provide a repro), so make sure to update any paths that are incorrect.

```js
// Assuming you have the following file system structure (simplified):
// . <root> of the project
// └── packages
//     ├── app
//     │   └── tailwind.config.js
//     ├── config
//     │   └── index.js
//     ├── ui
//     │   └── index.js
//     └── utils
//         └── index.js

// Assuming your `tailwind.config.js` file lives in: <root>/packages/app/tailwind.config.js

let path = require('path')

// Assuming `@xx` is an alias for: <root>/packages
function resolvePackages(...packages) {
  return packages.map(
    (pkg) => path.resolve(__dirname, pkg.replace('@xx', '..')) + '/**/*.{js,ts,jsx,tsx}'
  )
}

module.exports = {
  // ...
  content: ['./src/**/*.{js,ts,jsx,tsx}', ...resolvePackages('@xx/ui', '@xx/utils', '@xx/config')],
}

// Content paths will now look like this:
// './src/**/*.{js,ts,jsx,tsx}',
// '<root>/packages/ui/**/*.{js,ts,jsx,tsx}',
// '<root>/packages/utils/**/*.{js,ts,jsx,tsx}',
// '<root>/packages/config/**/*.{js,ts,jsx,tsx}'
```

If you can't get it to work, please open a new issue with a minimal reproduction repo.
