### ISSUE TITLE
v3.0.11 no longer gets postcss as a transitive dependency

### ISSUE THREAD

**Issue by xt0rted** [tailwindlabs/tailwindcss#6916]
**What version of Tailwind CSS are you using?**

3.0.11

**What build tool (or framework if it abstracts the build tool) are you using?**

none

**What version of Node.js are you using?**

v17.0.1

**What browser are you using?**

N/A

**What operating system are you using?**

Windows

**Reproduction URL**

N/A

**Describe your issue**

Following the instructions at https://tailwindcss.com/docs/installation I installed tailwind and then tried to run `npx tailwindcss init` and received an error saying `Error: Cannot find module 'postcss'`.

This is due to `postcss-js` v4 no longer taking a direct dependency on `postcss` https://github.com/postcss/postcss-js/commit/034b00a9ae1db85f7b628d0195c931938ddcb718.

**Comment by adamwathan** [comment]
Hey! This doesn't appear to be the case, our CLI still uses the bundled `postcss` in my testing (we bundle it ourselves as part of our publishing step):

![image](https://user-images.githubusercontent.com/4323180/148286847-73fed019-9dda-4ad0-a579-5ffa28fcfecd.png)

If you are installing Tailwind locally you need to install PostCSS and Autoprefixer, they are peer dependencies and we mention that in the installation guide:

![image](https://user-images.githubusercontent.com/4323180/148286993-33b9ecd6-a7e7-4355-a3cd-122151cf96d1.png)

Going to close since I can't reproduce but if I'm missing something I apologize 🤦🏻‍♂️ If you can open a new issue with very step by step instructions that make sure I run into the same problem then I can try and track it down.

**Comment by xt0rted** [comment]
I followed the Tailwind CLI steps which say to only install `tailwindcss`. After some more testing this looks to be an issue when using yarn but not when using npm.

**Comment by MrMacStripe** [comment]
I am running into the same issue when installing tailwind on a windows machine. On Mac everything runs fine.

**Comment by sevenseacat** [comment]
I think this should be re-opened - I've just run into the exact same issue.

The documentation for Tailwind CLI (https://tailwindcss.com/docs/installation) only mentions installing `tailwindcss`, but `postcss` is also needed to run `npx tailwind init` (on the next line).

(Using NodeJS v16.13.2, Tailwind CSS 3.0.19)
