### ISSUE TITLE
Chrome console live change not working with v3

### ISSUE THREAD

**Issue by aestheticsdata** [tailwindlabs/tailwindcss#7019]
**What version of Tailwind CSS are you using?**

v3.0.9 (same problem with 3.0.13)

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5

**What version of Node.js are you using?**

v16.3.1

**What browser are you using?**

Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)

**What operating system are you using?**

macOS 11.6

**Describe your issue**

with tailwind 2.2.19 I'm able to change in the Chrome console any tailwind classes and the changes are immediately visible. With tailwind 3.0.9, changing classes in Chrome console does not change anything in realtime.

**Comment by reinink** [comment]
Hey!

So in Tailwind v3.0 we replaced the old engine where all classes were generated "ahead-of-time", with a new "Just-in-Time" engine, which only generates the necessary classes needed for your project. Because of this, Chrome doesn't see all the possible classes, since they don't exist yet.

I think you'll find the following comment that I left on another issue helpful, as it explains in more detail why we made this change: https://github.com/tailwindlabs/tailwindcss/issues/6343#issuecomment-1002199124

I'd also recommend reading this blog post and watching the video there, which goes into even more detail: https://tailwindcss.com/blog/just-in-time-the-next-generation-of-tailwind-css

Finally, if you are looking for this kind of behaviour in the browser, you may want to follow along with what @mpociot is up to - he's building Tailwind CSS specific devtools, and I think this is one of the problem's he's trying to solve: https://twitter.com/marcelpociot/status/1467997181793685504

Alternatively, you can totally just keep using Tailwind CSS v2.0. 👍

Hope that helps!

**Comment by f1ght4fun** [comment]
Hi,

Sorry for asking, but I also agree with @aestheticsdata that part of tailwind being so awesome, esp. during dev cycle, is that you could experiment and apply styles on-the-go in browser seeing changes instantly.

Now in mid-size project 70% of classes is purged, so even though having jit generation is moving forward, maybe there's a chance that there can still be as an option or a flag to disable purge completely for dev ?

Regards

**Comment by reinink** [comment]
> maybe there's a chance that there can still be as an option or a flag to disable purge completely for dev ?

@f1ght4fun The thing is in v3.0 the entire engine in Tailwind CSS has been replaced with the new Just-in-Time engine, meaning there isn't a way to disable it in dev, as it's now just how Tailwind CSS works.

I recommend following those links that I posted — especially to the blog post and video about the JIT engine, and you'll be able to better understand why this change was necessary 👍

**Comment by f1ght4fun** [comment]
@aestheticsdata 

What i ended up doing is making my tailwind.config.js look something like (note that my concern was to have specific most common utility classes available at all times during dev)

tailwind.config.js:

`module.exports = (isProd) => ({
  content: ['./src/**/*.{html,ts}'],
  safelist: isProd ?
    [] :
    [
      {
        pattern: /m[lrbtxy]?-.*/,
      },
      {
        pattern: /p[lrbtxy]?-.*/,
      }
    ],
  corePlugins: {
    preflight: false,
  }
})`

webpack.config.js:

`module.exports = (config) => {
  const isProd = config.mode === "production";
  const tailwindConfig = require("./tailwind.config.js")(isProd);

  config.module.rules.push({
    test: /tailwind\.scss$/,
    use: [
      {
        loader: 'postcss-loader',
        options: {
          postcssOptions: {
            plugins: [
              require('tailwindcss')(tailwindConfig),
            ]
          }
        }
      }
    ]
  });

  return config;
};
`

This way, I can specify utilities and classes using regex I use the most and i need to have available in dev mode and once you build production safelist you can clear it out and purge anything unused.

@reinink 
Can you please advise why with the tailwind.config.js and webpack.config.js specified above, whenever I run ng serve
during build phase i get this warning, though my tailwind config looks legit and i have content entry

"Generating browser application bundles (phase: building)...
warn - The `content` key is missing or empty. Please populate the content key as Tailwind generates utilities on-demand based on the files that use them. For more information see the documentation: https://tailwindcss.com/docs/content-configuration

**Comment by mpociot** [comment]
Thanks for mentioning our browser extension @reinink !
We *just* published the newsletter with all the launch details. Feel free to checkout the DevTools for Tailwind browser extension on our website, where you can even try it out: https://devtoolsfortailwind.com/

It basically gives you back the in-browser-editing in combination with full JIT support, Intellisense autocompletion, and custom config support. Because just like you, I really missed the ability to have _all_ Tailwind classes available within my browser, especially with the new powerful JIT features.

**Comment by await-ovo** [comment]
I've written a webpack plugin that supports "Design in Devtools" and allows you to visually view the current tailwind configuration.

https://www.npmjs.com/package/tailwindcss-webpack-plugin

**Comment by daniel007enirman** [comment]
> I've written a webpack plugin that supports "Design in Devtools" and allows you to visually view the current tailwind configuration.
> 
> https://www.npmjs.com/package/tailwindcss-webpack-plugin

Does this plugin supports vite or nuxt 3

**Comment by SerjoA** [comment]
@reinink that is a major step backwards
the only reason to use tailwind in dev mode is the ability to play with classes in the dev console of the browser
without that its useless as a dev tool
the fact that i need to buy a dev tool to get what it used to do for free - its a big shame unfortunately
