### ISSUE TITLE
with (darkMode:'class'), when CDN is enabled, dark classes are still applied in light mode.

### ISSUE THREAD

**Issue by nekooee** [tailwindlabs/tailwindcss#7081]
Hi,
In the config file, the dark mode is activated as a class (darkMode:'class'). Also in development mode, a CDN has been added. 
Unfortunately, even though the website is in light mode, dark classes are still applied via CDN.

**What version of Tailwind CSS are you using?**

tailwindcss@3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**
Laravel - v8:
postcss@8.4.5, laravel-mix@6.0.39,webpack-cli@4.9.1

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://github.com/nekooee/tailwindcss

**Describe your issue**

![image](https://user-images.githubusercontent.com/6003803/149626439-20f0f5a4-d8e3-49c1-8220-78d32cdfde5c.png)

![image](https://user-images.githubusercontent.com/6003803/149626488-17f63d15-3dd8-418b-95bd-a6a2ef1e2051.png)

**Comment by adamwathan** [comment]
Hey! So the problem here is the Play CDN doesn't read your `tailwind.config.js` file, you need to figure it with an inline script tag as per the documentation:

![image](https://user-images.githubusercontent.com/4323180/149628716-1e9fd4b7-7855-46cc-b622-14350d5f80d3.png)

It's impossible for it to read the file in your project because the browser doesn't have access to the filesystem or anything like that.

Here's a demo:

https://jsfiddle.net/zympwa8g/1/

**Comment by hypercanvas** [comment]
for those using nextjs, i believe you can do this:
`<Script
                src="https://cdn.tailwindcss.com"
                onLoad={() => {
                    window.tailwind = window.tailwind || {};
                    window.tailwind.config = {
                        darkMode: 'class',
                    };
                }}
            />`
