### ISSUE TITLE
JIT compiler scan and compile commented classes 

### ISSUE THREAD

**Issue by CH4R4F** [tailwindlabs/tailwindcss#7087]
**What version of Tailwind CSS are you using?**
_Tailwind v3.0.13_

**What build tool (or framework if it abstracts the build tool) are you using?**
_Tailwind CLI_

**What version of Node.js are you using?**
v16.13.1

**What browser are you using?**
_Firefox_

**Describe your issue**

I just started using tailwind few days ago, I like the idea of JIT compiler, it scans my template files and generate all the css I need which is good option I liked it
_but_: while working on a small project I was making some comments in my **html** but the compiler still read the comments and generate the css styles for commented classes or any comment that is a valid class in tailwind.
_example_: 
``` html
<!-- cards container -->
        <div class="flex flex-wrap gap-8">
          <div class="card"></div>
          <div class="card"></div>
          <div class="card"></div>
          <div class="card"></div>
        </div>
      </div>
```
generated styles will include `container` styles too which is just a comment
```
....
.container{
  width: 100%;
}

@media (min-width: 640px){
  .container{
    max-width: 640px;
  }
}

@media (min-width: 768px){
  .container{
    max-width: 768px;
  }
}

@media (min-width: 1024px){
  .container{
    max-width: 1024px;
  }
}

@media (min-width: 1280px){
  .container{
    max-width: 1280px;
  }
}

@media (min-width: 1536px){
  .container{
    max-width: 1536px;
  }
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is by design so that we are compatible with as many programming languages as possible without evaluating the code to know what the _actual_ class names are. Because a lot of those can be defined at runtime only (imagine if it comes from an API).

If you really don't want this behaviour, then you can define a custom extractor for your html files.

- https://tailwindcss.com/docs/content-configuration#class-detection-in-depth
- https://tailwindcss.com/docs/content-configuration#customizing-extraction-logic

For html, that can look something like this:
```js
module.exports = {
  content: {
    files: ['./src/**/*.html'],
    extract: {
      html: (content) => {
        return content.match(/class="(.*?)"/)
      }
    }
  },
  // ...
}
```
