### ISSUE TITLE
Transform filter is (sometimes) needed in Tailwind 3.x

### ISSUE THREAD

**Issue by mseele** [tailwindlabs/tailwindcss#7140]
**What version of Tailwind CSS are you using?**

v3.0.14

**What build tool (or framework if it abstracts the build tool) are you using?**

vite/2.7.13 

**What version of Node.js are you using?**

v17.4.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/kpjuqMxBT8

**Describe your issue**

I've removed the `transform` filter utilities like described in the [3.0 upgrade guide](https://tailwindcss.com/docs/upgrade-guide#automatic-transforms-and-filters) and it looks like `transition-all` is not applied.

When i re-add the `transform` filter, everything looks good:

https://play.tailwindcss.com/ohCH1OX8Q1

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `transform` is technically not needed, the issue you are seeing is a stacking context issue. Instead of `transform` you can also use `relative` (https://play.tailwindcss.com/RWaLuBReLh) or `isolate` (https://play.tailwindcss.com/QQ0cAGF8y4).

Will take note of it to update the documentation / upgrade guide.
