### ISSUE TITLE
Grid Template Column - Arbitrary Values Not Working

### ISSUE THREAD

**Issue by dark-swordsman** [tailwindlabs/tailwindcss#7290]
**What version of Tailwind CSS are you using?**

v3.0.8

**What build tool (or framework if it abstracts the build tool) are you using?**

NextJS v12.0.9

**What version of Node.js are you using?**

v16.13.1

**What browser are you using?**

Firefox v96.0.3

**What operating system are you using?**

Windows 10 Pro with Debian 11 on WSL 2

**Reproduction URL**

Working: https://play.tailwindcss.com/nW7Pq100Wc

Not Working: https://play.tailwindcss.com/x0b1o7wZgO

**Describe your issue**

Trying to use `repeat(auto-fill, 14rem)` inside `grid-col-[]` (so, as: `grid-col-[repeat(auto-fill, 14rem)]`) does not work. As far as I read in the docs, this is how it is supposed to work.

In the working url, I created a separate class as shown below, added it to the div top class, and it works fine.

```css
.grid-list {
  grid-template-columns: repeat(auto-fill, 14rem)
}
```

In NextJS, I am able to use `style={{ gridTemplateColumns: "repeat(auto-fill, 14rem)" }}` and it works fine. As shown:

![image](https://user-images.githubusercontent.com/7909209/152031471-361d6607-5dee-4cab-a6eb-9ff9ac845cee.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue is that you can't use spaces in your arbitrary values because then you create multiple classes. Either remove the spaces or replace them with an `_`. Checkout the docs on the topic: https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace

Updated example: https://play.tailwindcss.com/HtJBsQzAke
