### ISSUE TITLE
Memory leak in 3.0.18

### ISSUE THREAD

**Issue by Rasool-deldar** [tailwindlabs/tailwindcss#7355]
**What version of Tailwind CSS are you using?**

For example: v3.0.18

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.1, Nuxt.js 2.18.8, webpack 4.*.*

**What version of Node.js are you using?**

For example: v16.13.2

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: Windows

**Reproduction URL**

minimal reproduction: https://codesandbox.io/s/charming-mirzakhani-pwkvh?file=/app.scss

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

![image](https://user-images.githubusercontent.com/58503211/152849706-a8b1f72a-5ff4-46d4-8bf3-d0a4a2f1e644.png)

I have installed tailwind v 3 in nuxt 2, I am working on the project, after a few minutes this error appears and the development server shuts down and I have to restart nodejs, I set it to 12 GB of RAM and the RAM still fills up and this error Please solve this problem

**Comment by aggreggator** [comment]
Your tailwind.config.js is empty.
https://codesandbox.io/s/charming-mirzakhani-pwkvh?file=/tailwind.config.js

**Comment by Rasool-deldar** [comment]
> Your tailwind.config.js is empty. https://codesandbox.io/s/charming-mirzakhani-pwkvh?file=/tailwind.config.js

I have filled in the tailwindcss file
Unfortunately, I did everything on codesandbox, but the Cannot find module error '../assets/scss/main.scss' has not been fixed yet.

https://codesandbox.io/s/charming-mirzakhani-pwkvh?file=/tailwind.config.js:0-3672

**Comment by aggreggator** [comment]
I haven't used Nuxt, but i don't think you are loading the tailwindcss plugin.
```
import tailwindcss from "./tailwind.config.js";
...
  build: {
    postcss: {
      plugins: {
        tailwindcss
      }
    }
  }
};
```
Just the tailwind config is loaded.
I think it's not a tailwind bug, mostly a misconfiguration in the app.
Propose to move it to a discussion and maybe there is somehow who can help.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I don't think this is a Tailwind issue, I changed your codesandbox and made some improvements: https://codesandbox.io/s/mutable-smoke-dbjgm?file=/assets/css/main.css

- Used `css` instead of `scss`
- Used relative paths for the css file using `./assets/css/main.css` instead of `~/assets/css/main.css`
- Used relative paths in the css file for referencing fonts: `../fonts/roboto/RobotoRegular.eot` instead of `fonts/roboto/RobotoRegular.eot`
- You had postcss plugins in your tailwind.config.js file. I moved them to the nuxt.config.js file:
```
"postcss-import": {},
"tailwindcss/nesting": {},
tailwindcss: {},
autoprefixer: {}
```
