### ISSUE TITLE
Dark theme only works on inline class

### ISSUE THREAD

**Issue by Mrbeyond** [tailwindlabs/tailwindcss#7395]
**What version of Tailwind CSS are you using?**

"Version": "^3.0.8",

**What build tool (or framework if it abstracts the build tool) are you using?**

"postcss-load-config": "^3.1.0",  "autoprefixer": "^10.4.1", "svelte": "^3.44.0",

**What version of Node.js are you using?**

Node version :17.0.0

**What browser are you using?**

 Chrome, Operamini

**What operating system are you using?**

OS: Windows and Linux

**Describe your issue**
The dark theme does not work when declared in a component style but only works inline class of the the html tag.
<div class="bg-white dark:bg-black" ></div>:  This works.

The syntax below does not work. 
<div class="theme-test"><div>
<style>
 .theme-test{
  @apply bg-white dark:bg-black;
}
</style>

**Comment by thecrypticace** [comment]
Hey, @Mrbeyond. I took a look and as far as I can tell this is working as expected.

I prepared two Tailwind play examples: The first uses the default (media) dark mode strategy and the second uses the class-based strategy — and both of them work as expected:

Using media strategy: https://play.tailwindcss.com/n7jOG71Q5D
Using class strategy: https://play.tailwindcss.com/8CLOtV6KWp

I did notice you're using Svelte. If you're getting an error I _believe_ this is due to a Svelte limitation — I'll do some digging to confirm. I would suggest putting any CSS with `@apply` inside an imported css file.

**Comment by ohabash** [comment]
@thecrypticace can you think of any reason why `.dog { @apply dark:text-white; }` only works in `media`  but not in `class` mode

**Comment by thecrypticace** [comment]
@ohabash Can you provide a Tailwind Play reproduction of your issue?

**Comment by ohabash** [comment]
I guess i cant. It works in the sandbox. I cant get `dark:` to work in my scss files in `class` mode... I will start looking into the angular install

**Comment by thecrypticace** [comment]
@ohabash if you can prep a reproduction open a discussion and @ mention me and I'll see if I can help you out there :)
