### ISSUE TITLE
Visited classes are not generated

### ISSUE THREAD

**Issue by devcustrom** [tailwindlabs/tailwindcss#7441]
Visited classes are not generated

[Reproduction](https://play.tailwindcss.com/Mi5NOidSAz?file=css)

**Comment by thecrypticace** [comment]
Hey, thanks for the reproduction! The core issue here is that these utilities have `--tw-text-opacity` variables which are used in the color. The browser places fairly strict limitations on what can be styled using `:visited` and how. In this case using a variable at all caused it to be thrown out / ignored. I fixed this in #7458 but it's likely it won't fix all the issues you encounter because of the browser limitations which are outside of our control.

A release should be going out soon (probably tomorrow). In the mean time you can disable the textOpacity plugin for your use case as long as you're not using the legacy `text-opacity-{number}` utilities:
```js
module.exports = {
  corePlugins: {
    textOpacity: false,
  }
}
```
