### ISSUE TITLE
@tailwind base override UI library styles

### ISSUE THREAD

**Issue by GOGOGOSIR** [tailwindlabs/tailwindcss#7500]
**What version of Tailwind CSS are you using?**

v3.0.22

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss:8.0.0 vite: 2.8.0

**What version of Node.js are you using?**

v14.18.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

Introduced tailwindcss to override the button style of VantUI

![image](https://user-images.githubusercontent.com/26272801/154401690-ca785459-3f7e-4fb1-aabf-de9a79434c16.png)

![image](https://user-images.githubusercontent.com/26272801/154401790-40cca281-460b-4c54-a7a3-ddd1990317ae.png)

Can you remove the background-color property of button[type=button]？

**Comment by adamwathan** [comment]
The problem here is the order in which you are loading your CSS. Tailwind's base styles need to come first, and the component library needs to come after:

```
@import 'tailwindcss/base';
@import 'whatever-the-path-is-to-vant-ui';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

Declaration order is really important in CSS, so if you are mixing libraries like this you need to make sure things are being loaded in a sensible order.

No plans to remove the background color reset from buttons, it's a necessary part of the reset to get a consistent cross-browser starting point and dropping it would be a breaking change.

**Comment by mvdstam** [comment]
@adamwathan I see that per TailwindCSS 3.0 the following selector is used for the background color reset:

```css
button,
[type='button'],
[type='reset'],
[type='submit'] {
  ...
}
```

Instead of completely removing the background-color reset for buttons, is it possible to use the following selector:

```css
button {
 ...
}
```

I'm seeing the same problem with [Mantine](https://mantine.dev/), because the `[type=x]` attribute selectors are too specific and thus have too high of a priority. Applying the following patch results in a fixed environment with the reset background-color intact:

```patch
diff --git a/lib/css/preflight.css b/lib/css/preflight.css
index a6d055aaca537f08ed486f4a46ee781603441f0e..64820400dc989f56685db25ecb8bcfb75390d9ba 100644
--- a/lib/css/preflight.css
+++ b/lib/css/preflight.css
@@ -180,10 +180,7 @@ select {
 2. Remove default button styles.
 */
 
-button,
-[type='button'],
-[type='reset'],
-[type='submit'] {
+button {
   -webkit-appearance: button; /* 1 */
   background-color: transparent; /* 2 */
   background-image: none; /* 2 */
```

Is this something you could live with? Cheers.

**Comment by adamwathan** [comment]
@mvdstam Just to follow up here because I've been looking at similar issues, I think the best solution for your situation is to take whatever styles Mantine is applying to `button` and also apply those styles to the same attribute selectors we target in Preflight:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  [type='button'],
  [type='reset'],
  [type='submit'] {
    /* Redeclare Mantine `button` styles here */
  }
}
```

Totally appreciate that this is annoying but I'm not sure what else to suggest, these sorts of conflicts are not really avoidable when you combine multiple CSS frameworks so you have to be explicit about the behavior you want.

**Comment by lnwu** [comment]
Have same issue here, [type='button'] have too high of a priority same with classname, many ui libs using one classname as default styles, it's not easy to make the sorts for css file absolute correctly, why we need that instead of on button tag selector?

**Comment by kitsunekyo** [comment]
@lnwu maybe it helps

https://github.com/tailwindlabs/tailwindcss/discussions/7304#discussioncomment-2256226

**Comment by MFrizzy** [comment]
Hey there !
Here a solution for mantine + tailwind : [mantinedev/mantine:823](https://github.com/mantinedev/mantine/issues/823#issuecomment-1065833889)

 ❤️

**Comment by moonrailgun** [comment]
Same problem and i have no idea how to resolve it without apply patch...

I dont think selector like `[type='button']` is a good idea. Is any context?

**Comment by t0n1zz** [comment]
having the same issue too with solana wallet button, everything works fine at local but when pushing it to vercel it override everything

**Comment by axmad386** [comment]
for anyone struggled with this issue. We can use css @layer to avoid this. Basically the correct layout is 
tailwind base, mantine, tailwind components, then tailwind utilities. This how I done setup tailwind + mantine
- First, install postcss and postcss-import
- edit postcss.config.js 
 ```js
module.exports = {
  plugins: {
    "postcss-import": {}, // add here
    tailwindcss: {},
    autoprefixer: {},
  },
};
 ```
 - edit your main.css entry
 ```scss
@layer tw_base, mantine, tw_components, tw_utilities; //<-- this order is important
@import "tailwindcss/base" layer(tw_base);
@import "tailwindcss/components" layer(tw_components);
@import "tailwindcss/utilities" layer(tw_utilities);

// import the layer css version of mantine
@import "@mantine/core/esm/index.layer.css";
@import "@mantine/notifications/esm/index.layer.css";
// etc
 ```
 Tested using NextJs latest version. Note that when using postcss-import, we should import `@mantine/core/esm/index.layer.css` instead of `@mantine/core/styles.layer.css` since postcss-import ignore package.json export entry

**Comment by mhmd-ninja** [comment]
> ```css-scss
> @import "@mantine/core/esm/index.layer.css";
> ```



> for anyone struggled with this issue. We can use css `@layer` to avoid this. Basically the correct layout is tailwind base, mantine, tailwind components, then tailwind utilities. This how I done setup tailwind + mantine
> 
> * First, install postcss and postcss-import
> * edit postcss.config.js
> 
> ```js
> module.exports = {
>  plugins: {
>    "postcss-import": {}, // add here
>    tailwindcss: {},
>    autoprefixer: {},
>  },
> };
> ```
> 
> * edit your main.css entry
> 
> ```css-scss
> @layer tw_base, mantine, tw_components, tw_utilities; //<-- this order is important
> @import "tailwindcss/base" layer(tw_base);
> @import "tailwindcss/components" layer(tw_components);
> @import "tailwindcss/utilities" layer(tw_utilities);
> 
> // import the layer css version of mantine
> @import "@mantine/core/esm/index.layer.css";
> @import "@mantine/notifications/esm/index.layer.css";
> // etc
> ```
> 
> Tested using NextJs latest version. Note that when using postcss-import, we should import `@mantine/core/esm/index.layer.css` instead of `@mantine/core/styles.layer.css` since postcss-import ignore package.json export entry

Please tell me how can manage fonts, 
so as I understood there are mantine is not overwritten by tailwind base, but in my case for fonts tailwind font should be prioritized

**Comment by axmad386** [comment]
What do you mean, I am not quite understand @mhmd-ninja, just use tailwind utility class like usual. As you can see, the tailwind utilities layer is the last layer, so when you write `font-bold` `font-sans` or etc, it will override any font styling.
