### ISSUE TITLE
`before:text-sky-800` Overrides content from a font icon

### ISSUE THREAD

**Issue by lil5** [tailwindlabs/tailwindcss#7886]
**What version of Tailwind CSS are you using?**

v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CLI

**What version of Node.js are you using?**

v17.7.1

**What browser are you using?**

N/A

**What operating system are you using?**

Linux

**Reproduction URL**

https://codepen.io/lil5/pen/YzYwbaE

**Describe your issue**

Content is being added in classes like `before:text-sky-800` where content should only be expected to be added on `before:text-sky-800 before:content-[>]`

**Comment by adamwathan** [comment]
Hey! This is by design I'm afraid, to make it so people don't have to do `before:content-['']` every time they want to use any pseudo-elements at all.

You can work around this in two ways:

1. Make sure your icon font stylesheet is being inserted after `@tailwind base;`, something like this:

    ```css
    @import "tailwindcss/base";
    @import "my-icon-font-stylesheet.css";
    @import "tailwindcss/components";
    @import "tailwindcss/utilities";
    ```

2. Disable the `preflight` core plugin, which removes all of Tailwind's base styles. This is probably more heavy handed than you want, option 1 is the better option.

    ```js
    // tailwind.config.js
    module.exports = {
      corePlugins: { preflight: false }
    }
    ```

No plans to change this behavior sorry, would be a breaking change and would also make the developer experience worse for every other pseudo-element use case. Sucks that there isn't a super easy way to get the best of both worlds — have to just decide which use-case to favor and we decided on this one.

Hope that helps at least!
