### ISSUE TITLE
1 high severity vulnerability minimist@1.2.5

### ISSUE THREAD

**Issue by hopkins385** [tailwindlabs/tailwindcss#7918]
Hi guys,

just want to make you aware there is a high severity vulnerability in the package minimist@1.2.5 used by tailwindcss.

https://github.com/advisories/GHSA-xvch-5gv4-984h

```
# npm audit report
minimist  <=1.2.5
Severity: high
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist
```

```
├─┬ tailwindcss@3.0.23
│ └─┬ detective@5.2.0
│   └── minimist@1.2.5
```

`npm audit fix` does fix the issue

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Will get it fixed but ultimately these sorts of vulnerabilities are false positives and not actually a concern regardless since Tailwind CSS is a build tool:
- https://overreacted.io/npm-audit-broken-by-design/
- https://twitter.com/dan_abramov/status/1362399290040139776?s=20

**Comment by hopkins385** [comment]
Oh man ... I didn't know that.  
Thanks for your fast feedback! 🙏
