### ISSUE TITLE
Peer modifier not generated using prefix

### ISSUE THREAD

**Issue by bakura10** [tailwindlabs/tailwindcss#7969]
**What version of Tailwind CSS are you using?**

v3.0.23

Hi :).

When using a prefix (specified with the "prefix" option in the config), it seems that peer modifier do not work. For instance, for built-in modifiers, the following class:

```
peer-invalid:tw-block
```

Properly generates:

```
.tw-peer:invalid ~ .peer-invalid\:tw-block {
  display: block;
}
```

However, when defining a custom modifier:

```
addVariant('scrollable', '&.is-scrollable');
```

And using it as below:

```
peer-scrollable:tw-block
```

No CSS is generated by Tailwind.

It seems there are various things that are not working when using custom prefixes that may be worth exploring :).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is because currently the peer and group variants are generated on their own. This means that you have to generate them yourself as well.

```js
addVariant('scrollable', '&.is-scrollable')
addVariant('peer-scrollable', ':merge(.peer).is-scrollable ~ &')
addVariant('group-scrollable', ':merge(.group).is-scrollable &')
```
https://play.tailwindcss.com/RHO8yHZXe4?file=config

This is currently assuming that the `is-scrollable` class exists on the `.group` or `.peer` div. If you want the `is-scrollable` class to be enabled on the div that has the `group-scrollable` or `peer-scrollable` then you can adjust it like this:

```js
addVariant('peer-scrollable', ':merge(.peer) ~ &.is-scrollable')
addVariant('group-scrollable', ':merge(.group) &.is-scrollable')
```

**Comment by bakura10** [comment]
Hi @RobinMalfait ,

thanks for the answer. There is one more issue, on which I have found a similar problem in the discussion : https://github.com/tailwindlabs/tailwindcss/discussions/7917

this is-scrollable class is added in JS but, when adding a variant with a prefix enabled tailwind also prefix this selector that I cannot control. Is there a way to indicate tailwind to not prefix a specific part ?
