### ISSUE TITLE
Incorrect opacity arbitrary value when using percentages.

### ISSUE THREAD

**Issue by antonbehaeghe** [tailwindlabs/tailwindcss#8046]
**What version of Tailwind CSS are you using?**

v3.0.16

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5
postcss-loader 4.3.0
webpack 4

**What version of Node.js are you using?**

v14.18.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows + WSL2

**Describe your issue**

When using an arbitrary value for opacity using percentages, in this case `opacity-[15%]`, it is incorrectly interpolated in production. In development mode it is working correctly. When switching to `opacity-[0.15]`, it is working correctly in both cases.

```
.disabled\:opacity-\[15\%\]:disabled {
    opacity: 1%;
}
```

**Comment by adamwathan** [comment]
Hey! Tailwind generates the correct CSS here, so this must be something that's happening in your minifier if it's only happening in production:

https://play.tailwindcss.com/HbjTHrLV8S

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/4323180/161818997-b1161707-931a-4884-87ac-14caf756f92f.png">

My guess is the minifier is doing something weird because it doesn't expect a percentage, only a number between 0 and 1. Percentage values for `opacity` are a very new thing and not supported at all by Safari for example:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/4323180/161819218-1569ffc4-47c6-4233-89e5-f0b81346a87d.png">

Going to close as not a Tailwind issue but if I'm wrong and you can confirm it's Tailwind's fault please feel free to open a new issue with a reproduction 👍🏻 Thanks!
