### ISSUE TITLE
https cert failing...immediate impact on peoples test sites or sites.

### ISSUE THREAD

**Issue by mrbm** [tailwindlabs/tailwindcss#8066]
<script src="https://cdn.tailwindcss.com"></script>

When running this on westcoast of the USA (los angeles) no issue.

When running this today on east coast, chrome very unhappy about the expired certificate coming from your CDN...yikes.

Additionally, don't know who's in charge of this package, but this works and properly redirects:

https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css

This does not:
https://unpkg.com/tailwindcss@^3.0/dist/tailwind.min.css

Redirects to:
https://unpkg.com/tailwindcss@3.0.23/dist/tailwind.min.css

which is not loaded into unpkg giving error: Cannot find "/dist/tailwind.min.css" in tailwindcss@3.0.23

Hope this helps!

**Comment by reinink** [comment]
@mrbm Thanks for reporting this — we've been trying to reproduce this issue (a bunch of the team is on the east coast), and we're not seeing this problem. We're investigating...

**Comment by mrbm** [comment]
<img width="484" alt="Tailwind Expired 2022-04-08 at 9 38 54 AM" src="https://user-images.githubusercontent.com/391043/162516559-35cf19b3-3b83-40a2-8ee3-e8247cd442c8.png">

Attached is a screenshot of the issue with your certificate being expired....let me know if that helps. Had issues both when that link was embedded and when just visiting it as the top  url.

The time stamp is from PST and was taken from me doing a video chat with somebody in north carolina (east coast)

My browser was chrome on a mac and his computer used chrome on a mac, both with latest version. Not sure if he is intel or M1.

Let me know if this helps

**Comment by thecrypticace** [comment]
What version of macOS are either of you running?

**Comment by thecrypticace** [comment]
My thinking is that your computers are missing the ISRG Root X1 certificate — likely due to being on an older version of macOS.

Let's Encrypt certs use a ISRG Root X1 certificate. When starting up LE they were cross-signed by the "DST Root CA X3" root certificate which expired in September 2021. I'm going to wager a guess that the ISRG X1 root is missing from your system. The thing I'm not certain about is why it would've worked previously. A slight possibility is that the ISRG Root X2 root _is_ installed your computer(s) which may have been in the cert trust chain previously.

More information about the  "DST Root CA X3" cross-sign expiration for Lets Encrypt sites can be found here: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by mrbm** [comment]
The problem is occuring a "test" customer. So am just testing random scenarios and have no control of their computer.

That said this guy is an average joe computer, I've pinged him for more details. The other links i gave you for version 2  from unpkg have no security issues, nor any of the other libraries I'm referencing.

What is the best way to guarantee this wouldn't happen if a user has ISRG Root X2 (don't have an idea how that would happen, he's just a normal user not a developer or even very technical)

I wont be able to make modifications to computers...so a bit worried as a I open this project up to more people.

**Comment by thecrypticace** [comment]
The macOS version is probably fairly key here. Anything older than macOS 10.12 is affected I think. And later versions especially likely as well if they don't update their computer often. If they're on a relatively recent version of macOS just installing pending OS updates should take care of the problem.

Unfortunately, if this issue is related to the root certs X1/X2/whatever then there's not much _we_ can do to work around that. Given that the CDN isn't meant for production use I would say the best way to work around it is to just use either the Tailwind CSS CLI (either standalone or from the npm package) or to use tailwindcss normally as a postcss plugin.

**Comment by mrbm** [comment]
his response:

> 2009 
> Yosemite or something like that

I'm using the library in a "edge" situation (cloudflare).

What i really liked about using this is that it made the file size really small. Would you have another recommendation and do you know why its not working in version 3 on unpkg? I havent had a moment to dive deeper into things, so was just looking for a quick solution.
