### ISSUE TITLE
Transition on rounded-full is not smooth

### ISSUE THREAD

**Issue by indaviande** [tailwindlabs/tailwindcss#8083]
**What version of Tailwind CSS are you using?**
3.0.15

**What version of Node.js are you using?**
For example: v14.17.6

**What browser are you using?**
Firefox 100.0b3

**What operating system are you using?**
macOS

**Reproduction URL**
https://avrilfilms.double.cat/a-propos/

**Describe your issue**
When using the rounded-t-full class `border-radius: 9999px`, if we apply a `transition: border-radius 0.7s ease;`, the transition is actually not smooth (as it goes from 0 to 9999px).
It's actually smoother if you put `border-radius:50%` (but not as rounded as 9999px).

You can check this video:
https://transfer.sh/D0Snl6/Enregistrement%20de%20l%E2%80%99e%CC%81cran%202022-04-11%20a%CC%80%2010.05.14.mov

**Comment by adamwathan** [comment]
Hey! This is just a trade-off necessary for `rounded-full` to actually work on elements that aren't square.

If you use `border-radius: 50%` on say a button, it's shaped like an oval instead of a pill:

https://play.tailwindcss.com/M3pV1Vh4Bf

![image](https://user-images.githubusercontent.com/4323180/162750329-c8d2d50d-d9db-4968-bd9d-1f31e53610ed.png)

We use `9999px` so that it "just works" but it does mean like you've noticed that transitions behave a bit oddly, because if you have something with say a 6px border radius and transition to 9999px, the apparent transition is very fast because the border is fully circular much before the actual value is fully transitioned to 9999px.

In these cases, you'll instead want to transition your border radius to the exact value necessary to get a fully rounded border based on the size of the element.

If the element is 100px in height and width, then you want an exact radius of 50px for the transition to be smooth:

https://play.tailwindcss.com/i2ETGGkOvZ

This can be done using arbitrary values so you don't actually need to add anything else to your config.

Going to close as no plans to change anything about how we implement `rounded-full` in core but hopefully this is helpful!

**Comment by guvenfazli** [comment]
@adamwathan  Thank you so much...
