### ISSUE TITLE
Dynamic text color dont load

### ISSUE THREAD

**Issue by devopg** [tailwindlabs/tailwindcss#8104]
Hi. I use latest vue 3 with vite. And today faced with a problem.

I calculate color from computed property 

color: `text-${percentMore > 0 ? 'green' : 'red'}-800`,

and set: 
:class="i.color"

if you have **never used this color on the site**, then it does not work, while there is a class exists on div. In list of class Chrome we dont see style rules :
![image](https://user-images.githubusercontent.com/61819835/163208599-7d175c09-ee6a-4f3a-bc7e-0b6f11326c17.png)

But if we add plug tag without calculated color like:
`<span class="text-green-800">test</span>
`

**Both this one and that one start working!!!**

next if we remove plug span then the calculated property remains working some time!

 I understand there are some caches in tailwind ?

**Comment by adamwathan** [comment]
Tailwind can't detect class names that use interpolation, see the documentation: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

Once you use a non-interpolated version of that class name it gets added to the CSS file so of course the other one will start working then since the browser will find a class for it, but without having a static version of the class present in your templates, Tailwind will never include that class in the CSS.
