### ISSUE TITLE
RGB opacity with custom variables does not work with referenced values

### ISSUE THREAD

**Issue by bakura10** [tailwindlabs/tailwindcss#8136]
**What version of Tailwind CSS are you using?**

v3.0.24

Hi :).

With the following config:

```
extend: {
  colors: ({ rgb }) => ({
    'current-bg': rgb('--background')
  },

  backgroundColor: ({ theme }) => ({
        'current': theme('colors.current-bg')
  }
}
```

The following opacity modifier works:

```
class="bg-current-bg/70"
```

However, this fails when working the aliased name:

```
class="bg-current/70"
```

**Comment by thecrypticace** [comment]
If you've got the `rgb`/`hsl` functions available you're using the insiders version :)

The reason this happens is because `rgb(…)` returns a function that handles outputting the value for a given opacity but when you call `theme('colors.current-bg')` that function is being called and returning a string for the default (`1.0`) opacity. This is a quirk of how the `theme(…)` function resolves values. Agreed this isn't ideal but getting this to work may not be trivial (but not sure at the moment).

For now you can work around this by doing the following:
```js
backgroundColor: ({ theme }) => ({
  'current': theme('colors')['current-bg'],
},
```

**Comment by bakura10** [comment]
Oh, you're right, I'm using the insiders :D.

The workaround indeed works, a bit hacky but if you feel this is too complex to solve you can close this issue, I am ok with this workaround ;)
