### ISSUE TITLE
Bg-clip-text with gradient clips text on large fonts

### ISSUE THREAD

**Issue by ss-proc** [tailwindlabs/tailwindcss#8280]
**What version of Tailwind CSS are you using?**

3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind play

**What version of Node.js are you using?**

N/a

**What browser are you using?**

Chrome, Firefox, Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/rx2MHq2iZx

**Describe your issue**

I followed the docs for [cropping to text](https://tailwindcss.com/docs/background-clip#cropping-to-text=). On larger font sizes, the text line gets clipped. Notice in the screenshot below, after 7xl font characters like `g` and `y` get truncated at the bottom. This only happens on lines with gradients.

<img width="1920" alt="Screenshot 000243@2x" src="https://user-images.githubusercontent.com/104405893/167065027-8fd8c418-57e7-41a5-a39d-170435b4839b.png">

Thanks in advance for looking into this!

**Comment by thecrypticace** [comment]
Hey! So, the reason you're seeing this is because the background, which the text is being clipped to, isn't quite as big as the text itself. This only happens for flex or block containers. For `inline` the background matches the text but it's drawn in a way that likely won't achieve what you are after. I'm fairly certain this is just a side effect of the font and how the browser draws text. You can work around this by increasing the line-height of the text using `leading-tight` (or some arbitrary value greater than 1 — in my testing `leading-[1.1]` seems to work well). Another alternative is to use `box-decoration-clone` which, in combination with `inline` will achieve something similar but not quite the same as what you're after. I'll note that Safari has had some issues with long wrapping text and `box-decoration-clone` in the past so just be aware of that.

I've prepared a play here to showcase these situations here: https://play.tailwindcss.com/DfqVY70vPK

I "commented out" the relevant classes to show the background by adding a `z-` prefix to them so you can quickly add/remove it for comparison. Nothing special about `z-` — it was just the first thing that popped in my head.

<img width="795" alt="Screen Shot 2022-05-06 at 10 14 45" src="https://user-images.githubusercontent.com/614993/167150817-26fdb033-eaad-48b0-9ece-d0da5b617e75.png">

**Comment by thecrypticace** [comment]
You're very welcome! Glad that works for you! And the `z-` isn't anything special. It just made it so those utilities wouldn't match anything since the class `z-text-transparent` doesn't exist but `text-transparent` does. I could've used anything (or just deleted them).
