### ISSUE TITLE
JIT stop working after change styling class a few times

### ISSUE THREAD

**Issue by ivanchenhz** [tailwindlabs/tailwindcss#8382]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

Angular 12.2.0

**What version of Node.js are you using?**

 v14.17.5

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**
https://github.com/ivanchenhz/angular-tailwind-refresh

**Describe your issue**

The JIT stop working after change the class a few times, even with TAILWIND_MODE=watch
We have noticed this issue after upgrade to 3.0.22, and still seeing it in 3.0.24

**Comment by thecrypticace** [comment]
Hey, thanks for the report! This is a super strange one. As far as I can tell, this is either an Angular or webpack issue (Angular uses webpack under the hood). I tweaked the tailwindcss source so we'd log to the console every time we run and I noticed a few things:
- We run twice initially (once for each css file)
- We run always when saving the tailwind.config.js file
- We run always when saving the style.css file
- We run always when saving the app.component.css file
- We run once more when saving non-css files inside src
- After that second save inside src/ we're not run any further.

After some investigation I believe this has something to do with the `dir-dependency` postcss message type that we use which tells the build tool to run for any file that would be matched by the given `glob` relative to the `src` directory:
```js
{
  plugin: 'tailwindcss',
  parent: '/absolute/path/to/project/here/src/styles.css',
  type: 'dir-dependency',
  dir: '/absolute/path/to/project/here/src',
  glob: '**/*.{html,ts}'
}
```

The reason I believe this is the issue is that if you provide non-glob file names then the problem you're seeing goes away because the resulting dependency will have an absolute path to a specific file rather than a pattern to match against:
```js
module.exports = {
  content: [
    "./src/index.html", // I changed this part
  ],
  theme: {
    colors: {
      ...colors,
    },
    extend: {},
  },
  plugins: [],
}
```

All that being said — this isn't an issue that we can fix but there is a way for you to work around it (albeit a not-so-great workaround) — by specifying each file. You could also use something like `fast-glob` to generate a list for you up front.  I would suggest filing an issue with angular-cli to see if they can help this problem down.

**Comment by thecrypticace** [comment]
Small update here: We're going to investigate this a bit further in angular / webpack and see if we can develop a fix. So don't worry about filing an issue with them if you haven't already.

**Comment by ivanchenhz** [comment]
Ye, sure, thanks for take time on this,
I kind of saw a few similar issues ( in current open issues list ), it should be worth to take care it anyway 😄，

And by the way, I noticed there is a issue talking about memory leak, we are actually facing this too,
Need to restart the dev server at least once a day ( but we love tailwind 👍 ）

**Comment by thecrypticace** [comment]
could you comment on the issue about the memory leak with more details on your setup? node version / os / editors / project size / etc…? It would be very helpful!
