### ISSUE TITLE
Using `important: #important` in `tailwind.config.js` breaks the dark mode.

### ISSUE THREAD

**Issue by Amir-A-M** [tailwindlabs/tailwindcss#8397]
Using `important: #important` in `tailwind.config.js` breaks the dark mode.

Project URL https://github.com/Amir-A-M/tailwind-dark-mode.git

See https://tailwindcss.com/docs/dark-mode and https://mui.com/material-ui/guides/interoperability/#tailwind-css

**Comment by adamwathan** [comment]
Hey! So this is actually expected behavior — `#important` is added to the very beginning of every selector so you end up with selectors like this:

```
#important .dark .dark\:underline
```

This means that you have to put the `dark` class on an element that is a child of your `#important` element, like:

```
<html id="important">
  <body class="dark">
    ...
  </body>
</html>
```

So in your project you'll want to change this to be the `body` instead of the `html` element:

https://github.com/Amir-A-M/tailwind-dark-mode/blob/master/src/App.js#L15

No plans to change this any time soon but hope that helps 👍🏻
