### ISSUE TITLE
Calculated arbitrary values do not take precedence with media queries

### ISSUE THREAD

**Issue by ShaunDychko** [tailwindlabs/tailwindcss#8401]
**What version of Tailwind CSS are you using?**
3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

[Tailwind Play](https://play.tailwindcss.com/SgpzvEkOQZ)

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/SgpzvEkOQZ

**Describe your issue**

When positioning a fixed div using a calculated arbitrary value prefixed with a media query, this arbitrary value does not take precedence over smaller device widths.
**Works**
```html
<div class="fixed left-5 sm:left-0">This div will be positioned at 0 on screens widths > 640px, as expected</div>
```
**Does not work**
```html
<div class="fixed left-5 sm:left-[max(0, -1)]>This div will be positioned at 5 on screen widths > 640px, however it should be positioned at 0</div>
```

**Comment by adamwathan** [comment]
Hey! The problem is that classes can't have spaces, the browser splits classes on spaces so in your demo it thinks `sm:left-max(1,` and `0)]` are two separate classes.

Also, `left: max(1, 0)` is not valid CSS, because the numbers have no units:

<img width="177" alt="image" src="https://user-images.githubusercontent.com/4323180/169690250-c1d61d09-5d72-46c6-9c22-d198df8d5dc4.png">

They need units to be valid:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/4323180/169690274-b2d31bf2-a909-4456-9226-31065b1b06ff.png">

So the solution for you is to use an underscore when you need a space and add units:

https://play.tailwindcss.com/aC6kHIb1WU

Here are the docs on arbitrary values and whitespace: https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace

**Comment by ShaunDychko** [comment]
Thank you so much @adamwathan for your patient and thorough response. I really appreciate it.
