### ISSUE TITLE
Using `sr-only` in scrollable div influences `body` height.

### ISSUE THREAD

**Issue by meesvandongen** [tailwindlabs/tailwindcss#8571]
v3.1.1 - Chrome

https://play.tailwindcss.com/qN8XFYH7f2

Using `sr-only` inside a scrollable container can cause the `body` height to be higher than expected if the parent is `flex`/`justify-center`.

Potential solution: (haven't tested edge cases) make element fixed instead of absolute.

Interestingly, this doesn't happen if the parent has `justify-start`.

**Comment by MichaelAllenWarner** [comment]
The `sr-only` class can do something similar in Safari when it's used in a multi-column layout: https://codepen.io/newcitymike/pen/qBxqEzb

I've likewise wondered if switching `sr-only` to fixed-position would be a good idea, as it would avoid these kinds of rare but hard-to-diagnose issues that come up with absolute-position (hard to diagnose because `sr-only` elements are invisible!). However, I'm not sure if switching to fixed would have any detrimental effects on assistive technology, and [this stackoverflow answer](https://stackoverflow.com/a/66574427) makes me nervous that it might (the bit about `top: 0`).

The person who wrote that answer (Graham Ritchie) seems to have expertise on the subject. I'd post a comment there to ask him about fixed-positioning, but I don't have enough stackoverflow rep; maybe someone who reads this and has enough rep could ask?

**Comment by litebluetips** [comment]
Thanks for the link, keep sharing this type of info

**Comment by rohmann** [comment]
Similar to what @MichaelAllenWarner  is saying, it looks like a quirk in how browsers reconcile `position: absolute` descendants of flexbox containers.

Without a positioned element (having `position: relative` in the ancestry), it tries to position the absolute element relative to the body, but because that's in a scrolling area, that forces the entire scrolling area to be accounted for in the height calculation. Odd it doesn't occur with `justify-start`. I found that it actually does happen if you have two scrolling areas as children of the flex parent. Maybe the browser just takes an optimized path if there's only one child.

You may have already fixed it for your use case but I had some thoughts for posterity on how it can be avoided

1. You could put the `sr-only` element at the top the scrolling area (although this does change the reading order unless `aria-hidden` was used on neighboring content)
2. You could add `relative` to element with `overflow-auto` that will ensure the `sr-only` element positions relative to it instead of the body.
3. Use `sr-only fixed` to reapply `position: fixed`.

The way `sr-only` is setup is pretty industry standard for hiding content from screen readers in it's current form with `position: absolute`. (rather than `fixed`) I'd be hesitant to see that changed just for an edge case like this that may just be a browser rendering issue.

**Comment by adamwathan** [comment]
Yeah unfortunately I don't think it's wise for us to change the implementation here — it's pretty specific and battle-tested by lots of other people and frameworks (we use the same implementation as Bootstrap for example) and I don't want to deviate from that.

I think like @rohmann mentioned this is best just worked around in user-land by making some tweaks to your code. Sort of just have to understand what `sr-only` is doing and understand how the browser handles it and accommodate it as necessary. Hopefully one day we get a native CSS property for this sort of thing, it's pretty ridiculous what we have to do to hide things visually but keep them present for assistive technology.
