### ISSUE TITLE
Arbitrary `content-['hello']` utilities not recognized when using a prefix like `tw-`

### ISSUE THREAD

**Issue by nndnha** [tailwindlabs/tailwindcss#8601]
**What version of Tailwind CSS are you using?**

v3.1.2

**What browser are you using?**

Chrome

**Reproduction URL**

https://play.tailwindcss.com/cjDwL0ojUE

**Comment by adamwathan** [comment]
Thanks for reporting! Looks like this only happens when using a prefix, will get it figured out 👍

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this! Definitely should've caught this one before we released v3.1 — the fix was rather simple thankfully! It'll be in our insiders build in a few minutes (`npm install tailwindcss@insiders` if you want to give it a try) or in a tagged release likely tomorrow. Appreciate you taking the time to report and for the reproduction! 🙌
