### ISSUE TITLE
Tailwind does not recognize classes on the angular component tag

### ISSUE THREAD

**Issue by asafari72** [tailwindlabs/tailwindcss#8699]
I have two components called button and text-box and I use sass to style them. To do this, I gave each component a class like the following:

textbox component:
```ts
@Component({
  selector: 'my-text-box',
  template:`<input type="text">`,
  host: { class: 'editor-container' },
})
export class MyTextBoxComponent {}
```
```scss
@layer components {
    .editor-container {
        @apply block bg-white shadow-sm border border-solid border-black;
    }
}
```
button component:
```ts
@Component({
  selector: 'my-button',
  template:`
  <button>
    Hello
  </button>
  `,
  host: { class: 'my-button' },
})
export class MyButtonComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}
```
```scss
@layer components {
    .my-button {
        & > button {
            @apply p-5 text-sm relative inline-flex items-center justify-center select-none font-medium whitespace-nowrap overflow-hidden text-ellipsis transition-all bg-blue-600;
        }
    }
}
```

The problem arises when the style of my class does not load if the name of the component tag is not the same. For example, I change the **"editor-container**" class with a "**my-text-box**". Everything works fine. (I need this feature to develop components).
In fact, if the class name and tag are the same, the style will be added.

Is this a bug?
Can I use [Customizing extraction logic](https://tailwindcss.com/docs/content-configuration#customizing-extraction-logic) to set tailwind to check tags in addition to classes?

framework: Angular version 14.0.0
tailwind version: 3.1.4
nodejs version: 16.15.0
browser: Chrome
operating system: macOS, Windows

**Comment by asafari72** [comment]
After reviewing again, I noticed that we have a component library that uses tailwind and when used in a separate project, the classes inside the components are not recognized by tailwind.
If I define the config as follows, the output of the file includes all the components, not the ones we used in a separate project.
``` js
module.exports = {
  content: [
    "./projects/myOrg/components/**/*.{html,ts}",
    "./projects/showcase/**/*.{html,ts}",
  ]
};
```

**Comment by litebluetips** [comment]
Did you get any proper solution?, I am also facing the same issue.

**Comment by MohammadHeidari** [comment]
I have the same problem and it creates a lot of unused styles in the production build.

**Comment by mrhasanzadeh** [comment]
I'm also had the same problem. Is there any proper solution to fix it?

**Comment by arashenprog** [comment]
I have same issue, I have developed a UI components library based on angular framework and tailwind and published on the npm. I have to put all the css classes in  one file and load it into my projects, but I need a solution to load only classes which are used in the components which I use in the my web app projects.

**Comment by sinaazemat** [comment]
I'm facing the same issue, is there any fix to this?

**Comment by ErfanRaoofi** [comment]
I have this issue please help me
thanks

**Comment by mehrabix** [comment]
@adamwathan @RobinMalfait @reinink @bradlc
Can't load classes from Angular selectors... any solution?

**Comment by thecrypticace** [comment]
@asafari72 Would you mind providing a small reproduction repo that I can clone with instructions? I don't quite understand what the problem is that you're describing.

**Comment by asafari72** [comment]
Hi, @thecrypticace

Thanks for the feedback

In total I have 2 problems:
1- When the class name is not the same as the component tag name that I put on the main tag, tailwind does not recognize the class and style. (I have explained this in path a with a comment).
2- The classes of tags inside the component are not detected by tailwind (it only detects if I define the component path for tailwind, but the problem is that the style of all components is in the output of the showcase project css file, not those in this project Have been used).

I put the project on this repo:
[https://github.com/asafari72/angular-tailwind-8699](https://github.com/asafari72/angular-tailwind-8699)

Execute the following two commands to execute the project:
- npm run components
- npm start

_Please run each in a separate terminal. (The first command keeps the components library on watch)_

**Comment by asafari72** [comment]
Hi,
Has anyone found a solution?

**Comment by asafari72** [comment]
Hi,
@adamwathan @RobinMalfait @reinink @bradlc @thecrypticace
you can check this topic
Thankful

**Comment by thecrypticace** [comment]
Hey @asafari72,

I think a key point for both of these issues is that Tailwind CSS des not evaluate, parse, traverse, or otherwise "understand" source code. If you want Tailwind CSS to recognize the classes that are used by those components then you need to pass a path to the component source code to the `content` property. Alternatively you can import the already-generated CSS for that library but that's bypassing Tailwind CSS entirely. This applies in any case in which user's use a component library or similar setup that also uses Tailwind CSS. You would need to add `node_modules/package_name/dist` (or similar) to the content array for those classes to be picked up.

Regarding your first point about the class name matching the component tag:
This is because you've specified this class name in the library's stylesheet (`projects/mylib/styles/_text-box.scss`). In this case changing it to `.editor-container` in the source code then references a class that does not exist. Since, as I mentioned above, Tailwind CSS does not evaluate or parse the source code, we cannot change the class name of the output. Tailwind's scanning system is intentionally simplistic. And, even if we were somehow able to do that, we would have no way of knowing what class to change.

Now, Tailwind CSS does pick up `lib-text-box` and that might be a bit confusing because it seems like it's working for one class but not another. However, it's picking up usages of what _might be_ classes in your source code from `src/showcase`. Specifically it sees 'lib-text-box' inside `<lib-text-box>` and considers that a match and outputs the CSS for the `.lib-text-box` Tailwind CSS component that you defined. You can see an example of this here entirely outside of an Angular context: https://play.tailwindcss.com/ev5pOdkZHv?file=css

As for the second point about the classes not being picked up in the library:
The reason the classes used by the library are not being picked up is that, in the source files that Tailwind CSS is scanning, the strings `bg-blue-500`, `bg-green-500`, `rounded`, etc… do not occur anywhere in the code. They occur in library used by the code but that library's sources has not been added to the content array.

This is explained in the documentation here in a couple of spots:
- [Class detection in depth](https://tailwindcss.com/docs/content-configuration#class-detection-in-depth)
- [Working with third party libraries](https://tailwindcss.com/docs/content-configuration#working-with-third-party-libraries)

As I understand it what you're after is the following behavior:
1. The "host" class name of the component does not matter — the styles are still included.
2. Only those styles for the components that are used are included.

Both of these are build-step issues. A plugin or some other build tool needs to understand the angular component source code, rewrite the CSS appropriately (if that's even possible — i'm not knowledgeable enough about Angular to know this). Additionally, the styles would need to be injected for per-component usage not in a global style sheet because including it is automatically going to include all defined styles. And, even further, Angular's CSS included in the bundle would have to be structured in such a way that it can be tree-shaken.

All in all, as far as I can tell, Tailwind CSS is acting as expected here. I'm sure this isn't ideal but the behavior your after I believe is outside the scope of Tailwind CSS as a library. I am more than happy to discuss what could be some possible solutions with you if you like. You can start a discussion and @-mention me there. Might need to be a bit patient with me though because I don't have a very deep understanding of Angular and it's internals.

**Comment by flexGURU** [comment]
when setting tailwind for Angular ensure that the config file is well set:
`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
    },
  },
  plugins: [],
}`

in addition to that, ensure that you have the following in your css:
`@tailwind base;
@tailwind components;
@tailwind utilities;`
