### ISSUE TITLE
Generated css class does not get removed when removed from the index.html file

### ISSUE THREAD

**Issue by franferns** [tailwindlabs/tailwindcss#8701]
Hi 
I use the tailwind CLI installation and add @tailwind utilities then add CSS class to the index.html like the bg-slate-600 .

I see the output generated in the output.css but when I remove this CSS once the generated the output.css does not remove this previously generated CSS. 

The only way i can get this removed css class from my index.html is by restarted the command 
`npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch`

Am I missing something while installing of tailwind ?

Thanks & Regards,
Francis P.

**Comment by thecrypticace** [comment]
Hey! This behavior is an intentional performance optimization. While Tailwind CSS is watching files we do not clear out already generated classes. You can restart the watcher if you need to but generally during development this shouldn't be an issue. And a fresh build will always re-scan the files generating only found classes.
