### ISSUE TITLE
`break-words` not working as expected in safari

### ISSUE THREAD

**Issue by jordanoverbye** [tailwindlabs/tailwindcss#8743]
**What version of Tailwind CSS are you using?**

v3.1.4

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

N/A

**What browser are you using?**

- Safari Version 15.2
- Chrome Version 103

**What operating system are you using?**

macOS

**Reproduction URL**

This bug is visible on the "Word Break" page on the documentation site. 

https://tailwindcss.com/docs/word-break#break-words

**Describe your issue**

In safari, the `break-words` class doesn't work as expected. There are no visual differences between the `break-words` example and the `break-normal` example.

Chrome works as expected.

Screenshot from Safari

<img width="776" alt="Screen Shot 2022-06-30 at 2 28 40 pm" src="https://user-images.githubusercontent.com/6265154/176592965-5faa0cc7-50df-447a-a6f6-cf52cbc5d25a.png">

**Comment by adamwathan** [comment]
I think this is a Safari specific bug where for one reason or another it sometimes misses that it's supposed to break the words. I see it breaking properly here:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/4323180/176663389-b97b3f71-636d-4a9b-b8aa-34e2175d0a32.png">

But then if I resize the window I can see Safari sort of forget to break:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/4323180/176663471-14f88f4e-af86-4a12-bd12-b204c8d41a25.png">

BUT! Then when I toggle the class on and off again it works:

https://user-images.githubusercontent.com/4323180/176663656-e39ea94d-31ab-449d-9686-721ef83f8e84.mov

So unfortunately not sure what we can do here other than file a bug in webkit and hope it gets fixed. Will relay it to someone on our team to try and create a minimal reproduction for the Safari team. It might have something to do with some interplay between the actual text layout and the page layout being built with flexbox or other things that take a double pass to render, because I can't reproduce it in this hyper simple example:

https://play.tailwindcss.com/vGdILR7QbM

**Comment by thecrypticace** [comment]
I can reproduce this in Safari 15.5 but I cannot reproduce this in Safari Technology Preview. Talked with @adamwathan this am about this and he's also unable to reproduce this in the Safari Tech Preview so it looks like this bug has already been fixed it's just not widely available yet. I imagine it won't be until Safari 16 lands in probably September-ish unless we get a surprise bug fix release of Safari in between now and then.
