### ISSUE TITLE
Weird Accent Color Look

### ISSUE THREAD

**Issue by Nie-Mand** [tailwindlabs/tailwindcss#8798]
![image](https://user-images.githubusercontent.com/29363210/177830871-ea729fbf-4c7b-4060-bf6e-b7f38c140e23.png)

Tailwind CSS: 3.0.23
Build Tool: Vite 2.8.0, with React, Post CSS 8.4.6
Node: 16.13.1
Browser: Chrome
OS: Developing on Debian (WSL2), and testing on Windows11 (Chrome)
Tailwind Play URL: https://play.tailwindcss.com/OXEgxDfajb

Issue:
The Accent Color doesn't look, right, with my custom hexadecimal color, I also find a color from the Tailwind Library that looks the same as the broken one, You can clearly see the difference by checking those radio buttons, the first one works, the other 2 are broken (second is using a tailwind defined color and the third is using a color that I'm using) 

Thanks for making the Design great to work with, btw.

**Comment by adamwathan** [comment]
Hey! This is just what the browser does when you use a color that it doesn't think has enough contrast against white. Tailwind isn't actually doing anything here at all, that's just what happens when you set the `accent-color` CSS property, even without Tailwind installed:

https://jsfiddle.net/z132sahr/

So nothing we can do about this I'm afraid. If you don't like how that looks your best bet is to build a totally custom radio button. The `@tailwindcss/forms` plugin can help a bit with that:

https://github.com/tailwindlabs/tailwindcss-forms
