### ISSUE TITLE
Tailwind 3.1.5 significantly increases hot module reloading times in Next.js

### ISSUE THREAD

**Issue by kieranm** [tailwindlabs/tailwindcss#8845]
**What version of Tailwind CSS are you using?**
V3.1.5

**What build tool (or framework if it abstracts the build tool) are you using?**
Next.js 12.2.0

**What version of Node.js are you using?**
Node v16.13.2

**What browser are you using?**
N/A

**What operating system are you using?**
MacOS

**Reproduction URL**
I'm not sure if it's possible to provide a reproduction URL for this issue because the project might have to be large in order for the issue to become apparent. I would be happy to help in any way I can - guidance appreciated.

**Describe your issue**
Upgrading from Tailwind V3.1.4 to V3.1.5 has significantly increased hot module reloading times while developing in Next.js. In our project, initial compilation goes from 5 seconds to over 20 seconds, and incremental reloads have gone from 1.5 seconds to over 10 seconds.

Downgrading the Tailwind version appears to fix the problem.

Before
<img width="825" alt="Screenshot 2022-07-13 at 14 02 39" src="https://user-images.githubusercontent.com/232283/178739916-8e17720c-dc99-4173-b12b-f60084c89948.png">

After
<img width="798" alt="Screenshot 2022-07-13 at 14 02 59" src="https://user-images.githubusercontent.com/232283/178739984-affd6c75-91ea-439f-b720-32c7a985bd0a.png">

**Comment by Shhu** [comment]
I have the same issue using vite + vue
hmr with 3.14 :
![image](https://user-images.githubusercontent.com/2306100/178925843-320ddf93-101c-4663-b789-1eae8e072e1e.png)
hmr with 3.15 and 3.16 :
![image](https://user-images.githubusercontent.com/2306100/178926027-fe76cc29-d761-473e-ac54-e74d906f72b9.png)

Found the problem was in my tailwind.config.js i was using : 
`safelist: process.env.NODE_ENV === 'development' ? [{ pattern: /.*/ }] : [],`

But now i cant have access to every tailwind classes in chrome inspector (purge)

**Comment by RobinMalfait** [comment]
Hey all!

I've been digging into this issue and here is what I found so far. Right now, I'm not sure what the actual issue is that you have @kieranm but looking at the comment from @Shhu I'm suspecting that you are also using some form of pattern safelist which is _very_ broad (`/.*/` basically means *everything*)

In Tailwind CSS v2 and below, we used to generate _every_ utility, component, ..., and then at the very end (typically in production) we purged the CSS you don't use, using Purge CSS. This has worked for a very long time, but at a certain point we started to generate multiple megabyte CSS files. While we could generate them relatively fast this causes a lot of other issues in your toolchain:
- Your browser devtools doesn't like this, because multi-megabyte CSS files are way too huge. Everything is laggy.
- Tools like webpack (which is being used by Next.js under the hood) can't handle large CSS files very well either, especially not in HMR.

While that's an annoying problem, who even generates such large CSS files where 99.99% is unused anyway?

In Tailwind CSS v3, we introduced the JIT engine where we instead of doing this:
- Generate everything (slow, huge)
- Purge (in production only unless configured)

We now _only_ generate the utilities that you used, by scanning your content paths. This has a big benefit because now we do this:
- Generate only what you need (fast, small — only what you use)
- No purging required, because we only generated what you wanted
- Devtools are happy
- webpack and friends are happy

An additional benefit of this approach is that we are now not limited anymore when introducing new features and new utilities to Tailwind CSS because as long as you don't use them, you won't generate them.

However.

Some people now miss the option to see everything in the browser devtools, this is a legit concern but the only way of seeing everything in your browsers devtools is by generating a big CSS file with everything included. We could ship a runtime and generate it on the fly, but even then you won't see the auto complete in the devtools working properly. This, as mentioned above, is not very ideal because the whole build chain suffers from this. If this is the _only_ reason you are currently using a RegEx safelist pattern, then you can take a look at the custom devtools by BeyondCode: https://devtoolsfortailwind.com/

Sometimes people didn't figure out how to properly setup Tailwind CSS and just use a pattern safelist. A pattern like `/.*/` is very simple, but this also means that you are allowing _everything_ to be generated. This means that we are back in Tailwind CSS v2 land, but even worse because the generated CSS is even larger in this case.

If you didn't figure out how to properly setup Tailwind CSS, then I would recommend you to read this part of the docs: https://tailwindcss.com/docs/content-configuration the TL;DR is that you have to list all the files in your `content` section that includes Tailwind CSS classes.

Back to the actual RegEx.

When we detect that one of your safelist patterns consist of a RegEx, then we will do the following:
- Generate all (base) utilities in memory (note this is not actually generating the CSS), this process takes ~50ms on my machine.
- Then, we match each of those utilities against the RegEx pattern(s), and if they match then we include them and generate actual CSS for it.

The base utilities will at the time of writing this generate 86k utilities. In a previous version 3.1.4 this was only ~9k (I will talk more about this in a bit).

The moment you introduce a very very broad RegEx like `/.*/`, we are almost forced to generate everything. Currently the whole process in Tailwind CSS itself would take ~6s. This is way worse than before, but the bigger issue is that the total time is still ~20s (which is also something you noticed). Even if we manage to make Tailwind CSS generate those classes in ~1s, the rest of the toolchain will still suffer because of this huge CSS file.

As mentioned earlier, webpack and your devtools won't be very happy with this.

**Why are we generating 86k utilities in the latest version compared to ~9k in the previous version?**
When we are generating the big lookup list, we are currently only generating base utilities like `underline` or `bg-red-500`, we don't include all possible variants because this would result in gigabytes if not terabytes of CSS if we would generate all combinations of those. (Fun fact, I tried this and I got a Node error that I reached the max length of a string...). Whenever we add new utilities this list will only increase. We also have to generate a few more classes. E.g.: we internally only have `m-1`, but we also should be able to generate negative values `-m-1`. The biggest bump in this number is because we forgot to generate colors with the opacity modifier. This means that if you want to safelist `bg-red-500/10` that this wasn't possible before. Instead we now generate these as well, and if your RegEx matches then we will include it in the final CSS, otherwise we won't.

What's the solution? There is a few things I want to you to look at:

- What is the _actual_ reason you want a safelist RegEx?
   - Is it because you didn't figure out how to setup Tailwind CSS to make it work without it in your codebase?
   - Are you using dynamically generated CSS classes that weren't included otherwise?
   - Is it because you require the classes in the devtools in order to develop?
- What is the _actual_ reason you used a very broad RegEx?
   - Would a more specific RegEx be enough? E.g.: RegExes for only safelisting colors
- Is there another reason?

A temporary solution could be to switch from `/.*/` to `/^[^/]*$/`, this essentially means that we are now only generating utilities that do not include a `/`. This would result in the same ~9k utilities as the previous version.

If we know what the actual reason is, then we can try and provide you with some support to make sure that all the necessary classes are generated and that your builds are as fast as possible!

Again, currently you are asking Tailwind CSS to generate _everything_ and that's basically what it is doing right now. Even if we make Tailwind CSS super fast for this use case, other tools like webpack and your browser devtools will still suffer.

We will make sure to update the docs and provide you with warnings in the console to let you know that you are generating a lot of CSS.

I hope this helps, and I'm looking forward to see how you are using those safelist patterns and why.

**Comment by kieranm** [comment]
@RobinMalfait Thank you for typing this up! 

Our current regex config is this. We only have this because we need to build calendar events programatically using category colours provided by the server. So these classes are not always referred to directly in the code.

```
  safelist: [
    "dark",
    {
      // Backgrounds
      pattern: /bg-.+/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Borders
      pattern: /border-.+/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Ring Color
      pattern: /ring-.+/,
    },
    {
      // Text Color
      pattern: /text-.+/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Gradients
      pattern: /(from|to|via)-.+/,
      variants: ["dark", "hover", "focus", "focus-visible"],
    },
  ],
```

We could look at trimming this down but it wasn't causing us any issues prior to 3.1.5. 

Do you think the opacity modifiers might be what's causing the issue?

Thanks!

**Comment by RobinMalfait** [comment]
@kieranm Hi

Yeah the opacity ones are indeed introduced for all color related utilities. When I use the default config including your safelist patterns, then I can see that we generated 257 326 utilities. Which takes 34.893s for Tailwind CSS alone to complete.

A first optimization you can do is to make sure that the RegEx matches completely, and not just partially. Adding `^` at the beginning and `$` at the end of each RegEx lets us generate 257 263 utilities. That's ~60 fewer utilities, this process takes 32.090s for Tailwind CSS to complete. A ~2s performance improvement.

This optimization looks like this:
```js
  safelist: [
    "dark",
    {
      // Backgrounds
      pattern: /^bg-.+$/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Borders
      pattern: /^border-.+$/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Ring Color
      pattern: /^ring-.+$/,
    },
    {
      // Text Color
      pattern: /^text-.+$/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Gradients
      pattern: /^(from|to|via)-.+$/,
      variants: ["dark", "hover", "focus", "focus-visible"],
    },
  ],
```

You can optimize the RegExes quite a bit more by ignoring those newly added opacity related modifiers (by ignoring `/` in the utility). By using these RegExes:

```js
  safelist: [
    "dark",
    {
      // Backgrounds
      pattern: /^bg-[^/]+$/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Borders
      pattern: /^border-[^/]+$/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Ring Color
      pattern: /^ring-[^/]+$/,
    },
    {
      // Text Color
      pattern: /^text-[^/]+$/,
      variants: ["dark", "hover", "focus", "focus-visible", "group-hover"],
    },
    {
      // Gradients
      pattern: /^(from|to|via)-[^/]+$/,
      variants: ["dark", "hover", "focus", "focus-visible"],
    },
  ],
```

These result in 17 638 utilities, which takes 1.835s for Tailwind CSS alone to complete. This is way way more interesting and should help you out at least in the short run.

Note: I'm only running these checks ones so my numbers could be off here, however you will definitely see the changes because we are doing way less work.

However, instead of dynamically building your class names, you could also play with css variables. This should reduce the overall CSS, and should increase performance even more.

Let me know what you think!

**Comment by thecrypticace** [comment]
Hey all, gonna close this issue given the above explanations from Robin. If you're still having issues or you need more details feel free to comment and we'll try to do our best to help out.

**Comment by NayamAmarshe** [comment]
Can someone please help me? My project requires Tailwind Safelist and because of this, my compile times went from 0.2s to 7s.

Here's what I'm using:
```
  safelist: [
    {
      pattern: /^bg-|shadow-|opacity-/,
      variants: ["hover"],
    },
  ],
```

**Comment by thecrypticace** [comment]
@NayamAmarshe does this help?
```js
  safelist: [
    {
      pattern: /^(bg-[^/]+|shadow-[^/]+|opacity-.+)$/,
      variants: ['hover'],
    },
  ],
```

What I've done here is anchor the pattern on both ends _and_ eliminate the any of the utilities w/ opacities.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe does this help?
> 
> ```js
>   safelist: [
>     {
>       pattern: /^(bg-[^/]+|shadow-[^/]+|opacity-.+)$/,
>       variants: ['hover'],
>     },
>   ],
> ```
> 
> What I've done here is anchor the pattern on both ends _and_ eliminate the any of the utilities w/ opacities.

Thanks a lot! This is a lot faster than before!

**Comment by NayamAmarshe** [comment]
@thecrypticace I'd like to ask, are there any alternatives to safelist?

In my code, I'm randomly assigning one of the classes from this array like so:
`class={colorsList[randomNumber]}`

```js
const colorsList = [
  "bg-red-500",
  "bg-orange-500",
  "bg-amber-500",
  "bg-yellow-500",
  "bg-lime-500",
  "bg-green-500",
  "bg-emerald-500",
  "bg-teal-500",
  "bg-cyan-500",
  "bg-sky-500",
  "bg-blue-500",
  "bg-indigo-500",
  "bg-violet-500",
  "bg-purple-500",
  "bg-fuchsia-500",
  "bg-pink-500",
  "bg-rose-500",
];
```

They're also used with `hover:`, that's why I thought I should use it but it obviously comes with a performance penalty.
Are there any alternatives to this? Where I can pick a random class and use it with hover as well?

**Comment by severinlandolt** [comment]
@thecrypticace thank you so much for these detailed and helpful answers here. Over at [Tremor](https://github.com/tremorlabs/tremor), we use quite a bunch of patterns in our safelist, resulting to longer build times. I followed the advice of anchoring the pattern on both ends cutting our build time in half. 

_Is there anything we can improve in our patterns? e.g. we do not use any opacity._

```js
 safelist: [
    {
      pattern:
        /^(bg-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(text-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(border-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(ring-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900))$/,
    },
    {
      pattern:
        /^(stroke-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    {
      pattern:
        /^(fill-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950))$/,
    },
  ],
```

**Comment by danielx-art** [comment]
Wow, I was struggling with this for the past maybe three days, thought I was going crazy, don't know how I stumbled across this thread and this is exactly whats happeing.  It seems weird that tailwind needs to generate everything, and It would be great if arbitrary, dynamic colors could be easier in Tailwind, more often than not I design components where color is one of the props and it can be any hex value.
Nevertheless, thanks very much for the detailed response and for clarifying this.

**Comment by danielx-art** [comment]
Although the project compiles now, the classes are not applied. If someone is reading this and knows the aswer, please help me.
I want to use the classes:
before:border-t-[${color}]
hover:text-[${color}]
data-[state=open]:text-[${color}]
bg-[${color}]
hover:bg-[${color}]
Where color is a HEX value. So how should I set up my safelist?

**Comment by thecrypticace** [comment]
You don't want to use a safelist for this. It wouldn't work anyway because you're using dynamic classes. What you should do instead is use a CSS variable for the color, and then use that variable in your utilities.

For example, in the dynamic background color case:

```html
<div
  style="--my-custom-color: #663399"
  class="bg-[var(--my-custom-color)]"
>
  Hello, world!
</div>
```

Or, when using a custom, dynamic text color on hover:

```html
<div
  style="--some-custom-text-color: #867530"
  class="hover:text-[var(--some-custom-text-color)]"
>
  Hello, world!
</div>
```
