### ISSUE TITLE
role="button" cursor style should respect aria-disabled="true"

### ISSUE THREAD

**Issue by urugator** [tailwindlabs/tailwindcss#8846]
**What version of Tailwind CSS are you using?**

v3.0.24

**Reproduction URL**

https://play.tailwindcss.com/RjzXXCJwih

**Describe your issue**

Similary to #5768, `[role="button"]` sets cursor to `pointer` ignoring `aria-disabled="true"`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I get why this may look similar to the other issue you linked to but there is a key difference in my opinion which is that the `disabled` attribute has an impact where adding the `disabled` prop disables it and you can't focus or click or interact with it at all.

The `aria-disabled="true"` marks it as disabled, which can improve accessibility because you can still focus it and it will read out that it is disabled, but you can still interact with it (like focus and clicking).

Because of this, I don't think this makes much sense right now to change the cursor for that as well. 

Going to close it for now, but we can always revisit it later.

**Comment by urugator** [comment]
> The aria-disabled="true" marks it as disabled, which can improve accessibility because you can still focus it and it will read out that it is disabled, but you can still interact with it (like focus and clicking).

In the same spirit, `[role="button"]` can improve accessibility, but won't change the element functionality, therefore the cursor shouldn't change.

The thing is that `aria-disabled="true"` is used to indicate disabled state even for elements that do not have a disabled attribute.
Same as `[role="button"]` is used to indicate button for non-buttons elements.

So either accessibility hint should be enough to change cursor style or not, but doing both creates conflicts when used together.

Eg angular material does `.buttonLike:not([aria-disabled=true]) { cursor: pointer }`, but it's completely innefective, because it doesn't (and shouldn't) anticipate that somone else (`tailwind`) changes the default style of `role="button"`.
