### ISSUE TITLE
Buttons have cursor: pointer by default, but should not for accessibility reasons

### ISSUE THREAD

**Issue by MatthewSbar** [tailwindlabs/tailwindcss#8961]
**What version of Tailwind CSS are you using?**

3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 3.0.0 (rollup)

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://stackblitz.com/edit/react-tailwind-qds1vc?file=index.js

**Describe your issue**

While it's common to give `<button>`s `cursor: pointer;`, this is an anti-pattern. The [CSS spec](https://drafts.csswg.org/css-ui-3/#valdef-cursor-pointer) establishes that `cursor: pointer` indicates an element is a link.

[This article](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) has some additional justification for this. I understand many users will want to override this behavior back to the common misuse of `cursor: pointer;`, but Tailwind should be correct by default.

**Comment by adamwathan** [comment]
Yeah agree this is the right default, changing in #8962. Going to put this out in a patch or minor, doesn't really feel "breaking" to me.

**Comment by diegohaz** [comment]
@adamwathan Should this be re-opened since #8962 was reverted in 0a3aad95115685b31c25cb48bb3b5d0bcb8429d3?

> We’re undecided on whether or not this should be released right now so we’ll revert it and revisit it later.

**Comment by DaniGuardiola** [comment]
I second @diegohaz, this should be reopened.

**Comment by hichemfantar** [comment]
Any plans to revisit this?

**Comment by ccchapman** [comment]
Buttons should not have `cursor: pointer` by default.

> [Microsoft’s design guides](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742466%28v=vs.85%29.aspx) talk about weak affordance:
> 
> Text and graphics links use a hand […] pointer […] because of their weak affordance. While links may have other visual clues to indicate that they are links (such as underlines and special placement), displaying the hand pointer on hover is the definitive indication of a link. To avoid confusion, it is imperative not to use the hand pointer for other purposes. For example, command buttons already have a strong affordance, so they don’t need a hand pointer. The hand pointer must mean “this target is a link” and nothing else.
> 
> [Apple’s Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Pointers.html) states that the hand cursor should be used when “the content is a URL link”.
> 
> [W3C User Interface guidelines](https://www.w3.org/TR/CSS21/ui.html#propdef-cursor) says the same thing again with “The cursor is a pointer that indicates a link”.
> 
> From ["Buttons shouldn’t have a hand cursor" by Adam Silver](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b#.b33l7fivt)

**Comment by kachkaev** [comment]
The `next` branch no longer sets `cursor: pointer` for buttons [in `preflight.css`](https://github.com/tailwindlabs/tailwindcss/blob/2fe249963583e436961adc59cf9988af454e3da5/packages/tailwindcss/preflight.css). So I guess that v4 will no longer add `cursor: pointer` 🎉

**Comment by teajaymars** [comment]
This is a fine stylistic choice but I think it's specifically bad for accessibility. I don't think the justification makes sense at all.

* All the buttons on the cited Microsoft article use `cursor:pointer`.
  * (The article seems geared toward native app designers, not web UI norms)
 * All the buttons on Adam Silver's Medium article also use `cursor:pointer`.

It's the regular, normal, expected behaviour. Our alpha website just failed accessibility testing specifically because users thought our buttons were broken -- because they've stopped showing the "normal" interaction cursor. [This is in the context of .gov.uk work](https://design-system.service.gov.uk/components/button/) where (for better or worse..) accessibility has become an obsession.

Don't expect this will change now it's in Tailwind 4. But I'll say that in our local context the accessibility argument points in exactly 180' the other direction. Here's the snippet for anyone backing it out:

```css
@layer base {
  button,
  [role='button'] {
    cursor: pointer;
  }
  button:disabled,
  [role='button']:disabled {
    cursor: default;
  }
}
```

**Comment by hichemfantar** [comment]
Thanks for the snippet and opinion but I believe it should be opt in instead of opt out which is the default html behavior, also buttons in every operating system i've used (window, macos, linux) use the same behavior which is no hand cursor.

**Comment by hichemfantar** [comment]
@teajaymars if you still feel strongly about your opinion then feel free to write an in depth article on the subject like the one OP [mentioned](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) in the description. I'm curious to know more about your opinion.

@kachkaev since this topic is very controversial, it might be a good idea to include a notice in the button documentation in tailwind that mentions this and offers a snippet that devs can copy paste in their css to get the hand cursor effect.

**Comment by markau** [comment]
I am probably the least smart person in this thread but I've been using the web for 32 years and _**on the web**_ I expect things you can click to have a hand cursor. The cursor change is the affordance of a clickable element. If the specification says otherwise then it needs to be updated in my opinion instead of trying to change decades of user expectations. Anyway, easy fix thanks to @teajaymars :)

**Comment by brunobely** [comment]
@hichemfantar shouldn't it be enough that the article linked uses Google's homepage as an example for what to do but, in fact, *all* buttons on the Google homepage use the pointer cursor now? shadcn/ui recently switched to cursor-default on buttons and it's so hard to tell what's clickable.

**Comment by diegohaz** [comment]
> [@hichemfantar](https://github.com/hichemfantar) shouldn't it be enough that the article linked uses Google's homepage as an example for what to do but, in fact, _all_ buttons on the Google homepage use the pointer cursor now? shadcn/ui recently switched to cursor-default on buttons and it's so hard to tell what's clickable.

If it's hard to distinguish clickable elements without a pointer cursor, touch device users (not only on mobile) will struggle with your app anyway. Isn't it the case to offer better affordance in both idle and hover states?

**Comment by kerryj89** [comment]
The web has evolved rapidly and the vast majority of users are accustomed to seeing pointer cursor for interactive elements on the web.  Was there a true accessibility concern here or are we just ignoring what users find normal today for the sake of honoring some harmless dusty spec and OS conventions?

**Comment by DaniGuardiola** [comment]
This is just a default. If you prefer `cursor: pointer` by default, do this (as suggested by @teajaymars):

```css
@layer base {
  button,
  [role='button'] {
    cursor: pointer;
  }
  button:disabled,
  [role='button']:disabled {
    cursor: default;
  }
}
```

And you're done. While I consider this an interesting discussion, I don't think it's gonna change in Tailwind CSS and further comments are just spam.

**Comment by lessquo** [comment]
This is an interesting discussion. On the [documentation website](https://tailwindcss.com/docs/box-sizing), none of the buttons use `cursor: pointer;` anymore. Some have hover styles, like background color changes or animations, while others have no hover effects at all—which feels a bit awkward. I think it's more important to add some kind of hover feedback for all buttons to improve the user experience.

That said, using `cursor: pointer;` for buttons is pretty much the de facto standard. I can't think of any popular websites that don't do this. I really wonder what percentage of developers using Tailwind CSS end up manually adding this style to their CSS files.

**Comment by AmodeusR** [comment]
> I understand many users will want to override this behavior back to the common misuse of cursor: pointer;, but Tailwind should be correct by default.

You know how bad your recommendation is, and still you did it? What's the point of "being correct" if first of all, literally no one does it the "correct way" (even accessibility websites show buttons with cursor pointer), and secondly, it'll just increase boilerplate and configuration to do what **actually** right?

We shouldn't keep with old standards just because, and things evolved since then. Just like words don't mean what they mean, but what people **think** what they mean, a cursor pointer for people means it's a clickable, so it means something is clickable, not that it's a link only.

In the end, there's literally no "accessibility" issue here, only somenoe trying to preserve old and rusty standards that makes zero sense in the modern web for no good reason.

**Comment by diegohaz** [comment]
> > I understand many users will want to override this behavior back to the common misuse of cursor: pointer;, but Tailwind should be correct by default.
> 
> You know how bad your recommendation is, and still you did it? What's the point of "being correct" if first of all, literally no one does it the "correct way" (even accessibility websites show buttons with cursor pointer), and secondly, it'll just increase boilerplate and configuration to do what **actually** right?

I'm not sure you understand what 'literally' means. I just checked a few accessibility websites, and they all use the default cursor, except for the W3C site, which uses `cursor: pointer` for checkboxes (but not for other buttons).

*   https://www.w3.org/
*   https://www.w3.org/WAI/ARIA/apg/
*   https://adrianroselli.com/
*   https://w3c.github.io/aria/

Regardless, sticking with defaults is objectively the right approach for Tailwind. If you really believe `cursor: pointer` is a better default, you should file issues with the browser engine developers so they can consider changing it universally.

**Comment by bernaferrari** [comment]
The original motivation for the change was "Linear is using pointer default and I believe that will be the future". Linear is now using pointer click again and everybody is complaining that pointer is not the default. Shadcn/ui has dozens of issues with many upvotes asking to bring pointer click back by default (this tweet alone has 600 likes https://x.com/shadcn/status/1915038859529949498). I never saw the other end of the discussion, people asking for cursor: default.

**Comment by diegohaz** [comment]
> Adrianroselli is using cursor:pointer, w3 is using cursor:pointer on buttons. There are a few places they don't, but overall they do.

That information is false. Adrianroselli consistently uses `cursor:pointer` for links and form submit buttons (which act like links), but not for other types of buttons. The W3C is generally consistent as well, although there are a few exceptions, like checkboxes and some isolated elements.

It's the opposite: *There are a few places they <del>don't</del> <ins>do</ins>, but overall they <del>do</del> <ins>don't</ins>*.

**Comment by hichemfantar** [comment]
It’s simple, cursor default helps me differentiate between links and buttons, especially now that buttons and links are styled similarly.

**Comment by MGSimard** [comment]
> Buttons should not have `cursor: pointer` by default.
> 
> > [Microsoft’s design guides](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742466%28v=vs.85%29.aspx) talk about weak affordance:
> > Text and graphics links use a hand […] pointer […] because of their weak affordance. While links may have other visual clues to indicate that they are links (such as underlines and special placement), displaying the hand pointer on hover is the definitive indication of a link. To avoid confusion, it is imperative not to use the hand pointer for other purposes. For example, command buttons already have a strong affordance, so they don’t need a hand pointer. The hand pointer must mean “this target is a link” and nothing else.
> > [Apple’s Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Pointers.html) states that the hand cursor should be used when “the content is a URL link”.
> > [W3C User Interface guidelines](https://www.w3.org/TR/CSS21/ui.html#propdef-cursor) says the same thing again with “The cursor is a pointer that indicates a link”.
> > From ["Buttons shouldn’t have a hand cursor" by Adam Silver](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b#.b33l7fivt)
> 
> [@thecrypticace](https://github.com/thecrypticace) Could this issue be reopened?

This is an unfathomably hilarious take when nearly all non-navigational buttons on https://www.microsoft.com/ have cursor: pointer. From searchbar trigger, to submenu triggers, dialog/popover closes, pricing tab buttons, accordions and carousel cycling. The only one I could find not using cursor: pointer is the dropdown input.

**Comment by moonjoungyoung** [comment]
This decision fundamentally contradicts Tailwind's core philosophy of developer experience and pragmatic defaults.

If 99% of developers need to override a default, it's not a good default—it's bureaucratic pedantry that ignores real-world usage patterns.

Tailwind CSS was created to make web development faster and more intuitive, not to enforce academic interpretations of 20-year-old specs that even the spec authors themselves don't follow on their own websites.

When Microsoft's own website uses `cursor: pointer` on buttons while their design guidelines say otherwise, when shadcn/ui gets hundreds of complaints about this change, and when actual accessibility testing shows users perceive buttons WITHOUT pointer cursors as "broken"—maybe it's time to acknowledge that web standards have evolved beyond rigid specifications.

A framework should optimize for the 99% use case, not force the entire ecosystem to write boilerplate CSS because of ideological purity. This isn't about "correctness"—it's about creating friction where none should exist.

The web has democratically decided that `cursor: pointer` means "clickable." Fighting this consensus doesn't make Tailwind more accessible; it just makes it more annoying to use.

**Comment by jaspersorrio** [comment]
We can override this behaviour by following this guide https://tailwindcss.com/docs/upgrade-guide#buttons-use-the-default-cursor

**Comment by jaspersorrio** [comment]
@adamwathan could you reconsider this again? 

@moonjoungyoung wrote this a few months ago and he has a good point. Many developers have also upvoted his comment.

> This decision fundamentally contradicts Tailwind's core philosophy of developer experience and pragmatic defaults.
> 
> **If 99% of developers need to override a default, it's not a good default**—it's bureaucratic pedantry that ignores real-world usage patterns.
> 
> Tailwind CSS was created to make web development faster and more intuitive, not to enforce academic interpretations of 20-year-old specs that even the spec authors themselves don't follow on their own websites.
> 
> When Microsoft's own website uses `cursor: pointer` on buttons while their design guidelines say otherwise, when shadcn/ui gets hundreds of complaints about this change, and when actual accessibility testing shows users perceive buttons WITHOUT pointer cursors as "broken"—maybe it's time to acknowledge that web standards have evolved beyond rigid specifications.
> 
> A framework should optimize for the 99% use case, not force the entire ecosystem to write boilerplate CSS because of ideological purity. This isn't about "correctness"—it's about creating friction where none should exist.
> 
> The web has democratically decided that `cursor: pointer` means "clickable." Fighting this consensus doesn't make Tailwind more accessible; it just makes it more annoying to use.

**Comment by brunobely** [comment]
@jaspersorrio +1, [a pointer tells most users that something is clickable](https://www.nngroup.com/articles/button-states-communicate-interaction/), not that it's a link.

If, 20 years later, "they" still want the hand to mean *link*, not *clickable*, they're welcome to propose a new cursor type that shows an actual chain link icon rather than a finger - which, to any reasonable person, symbolizes the action you perform with your finger on a mouse: a click.

**Comment by robclancy** [comment]
buttons not being a pointer is just fucking stupid, no need to say anything else

**Comment by xBurnsed** [comment]
I can't believe this is even something we have to discuss. This is a no-brainer.

Buttons should have a pointer cursor — it gives users clear UX feedback that the element is clickable.

If not, what's the difference between a button and a badge? That the button's hover effect is enough to signal it can be clicked? Well, guess what — badges can also have hover effects, and they're not meant to be clicked.

I can't believe this. I couldn't care less about what the CSS specs say. If 99% of your users are overriding the default for your library, then the default is what needs to change.

**Comment by sydneyvaughn75-ops** [comment]
Completely agree — buttons should have a pointer cursor by default. It’s a
core UX signal that the element is clickable. Relying solely on hover
effects isn’t enough, because non-clickable elements like badges can also
have hover styles.

If most users are overriding the default anyway, it’s a strong sign that
the library default should reflect common expectations.

**Comment by nikelborm** [comment]
And yet, Google's web.dev site recommends adding `cursor` pointer to buttons and all interactive elements to increase their recognizability as being interactive

> Buttons show the default cursor when you hover over them, as shown on the Default Button.
> 
> For the Save button, we add cursor: pointer to show that it is interactive. When the button is disabled, we change it to cursor: wait to show that the work represented by the button is happening

https://web.dev/learn/css/cursors-and-pointers

**Comment by erikdemarco** [comment]
this is a big mistake. 99% of developer will prefer cursor for button. just look top 1k websites compare how many website use and not use cursor for button. it doesnt need high IQ to reason.

**Comment by DouglasCalora** [comment]
For me this makes no sense, this is a big loss for usability.

**Comment by matinzd** [comment]
The web has its own interaction patterns, and cursor styles are part of them. Unlike native apps, web pages are mostly made up of non-interactive content. Text can be selected, images can often be dragged, and large portions of a page do nothing when you hover over them. Because of that, the pointer cursor has become a simple and familiar signal that an element is clickable.

Users have spent decades learning these conventions. Whether something is technically an HTML `<button>`, a link, or a custom component doesn't matter. What matters is that interactive elements are easy to recognize. Removing the pointer makes buttons less discoverable, especially in modern interfaces where buttons are often styled with minimal borders or no obvious visual cues.

Comparing websites to native apps also isn't a good argument. They have different interaction models and different user expectations. Good UX follows the conventions of the platform users are on, not the conventions of a different platform.

The fact that browsers historically didn't apply `cursor: pointer` to `<button>` elements by default isn't evidence that it's the better experience. Browser defaults have changed many times over the years. If adding the pointer makes interactive elements more obvious at essentially no cost, then it's a practical usability improvement, not something that should be removed for the sake of consistency with native apps.
