### ISSUE TITLE
Gradient stop breaks with mediaquery

### ISSUE THREAD

**Issue by silveltman** [tailwindlabs/tailwindcss#8978]
**What version of Tailwind CSS are you using?**

@astrojs/tailwind: ^0.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Astro

**What version of Node.js are you using?**

16.5.1

**What browser are you using?**

N/A, tried Chrome and Firefox

**What operating system are you using?**

Windows

[**Reproduction URL**](https://play.tailwindcss.com/V8VenQzI76)

**Describe your issue**

Gradient breaks when using media queries in a specific way.

```
<div class="bg-gradient-to-b from-black/0 via-black sm:via-black/50 to-black absolute inset-0" />
```

Works fine on smalles screens, but when bigger it breaks. Goes black/0 > black-50 > black/0, instead of Goes black/0 > black-50 > black/100.

**Comment by adamwathan** [comment]
Hey! So the reason this happens is because the implementation of `via-*` overrides the `to-*` value to transparent, expecting that you would provide your own `to-*` when you don't want transparent. When you use `sm:via-black/50` this is overriding the non-breakpoint specific `to-black` you've set.

To fix this you just need to re-specify the `to-*` value as well:

```html
<div class="bg-gradient-to-b from-black/0 via-black to-black sm:via-black/50 sm:to-black  absolute inset-0" />
```

Totally understand that this feels like it should just work but it's something we can't change at this point for backwards compatibility reasons. Thankfully it's still super easy to do what you want, just need to add the extra class 👍
