### ISSUE TITLE
Separator not forcing usage

### ISSUE THREAD

**Issue by Triloworld** [tailwindlabs/tailwindcss#9015]
Tailwind not forced on use of different separator
Live example have same issue: https://play.tailwindcss.com/3Ic58ImPqc (styles apply which is bug)

Separator is required to separate added styles from other existing systems

Maybe this is because of weird one? Then need to be some documentation what is allowed

**Comment by thecrypticace** [comment]
The separator is meant for separating multiple variants. It looks (as far as I can tell) that it is working as intended. `md:w-1/3` is not being applied where as `md§w-1/3` is:

<img width="1595" alt="Screen Shot 2022-08-04 at 15 14 25" src="https://user-images.githubusercontent.com/614993/182934420-7b10bc12-ad27-49d3-aec0-8ebab7ad3df2.png">

Since you said you were mixing this with other systems were you looking to [use a prefix](https://tailwindcss.com/docs/configuration#prefix) instead?

**Comment by Triloworld** [comment]
You mean that they merge and are usage together in mixed way? 
> md:w-1/3 is not being applied
> The separator option lets you customize which character should be used to separate modifiers

Example:
Like if used is ok for different separator:
> h-full md§w-1/3
And usage:
> md§w-1/3
Block usage of:
> md:w-1/3
That's correct?
If block then usage of prefix mean that I can mix more systems and documentation need to be updated

Prefix won't work in systems like Drupal: https://www.drupal.org/project/drupal/issues/3252587 (they fixed it just recently)

Propose to add note about merging default option or not in documentation:
https://tailwindcss.com/docs/configuration#separator

**Comment by thecrypticace** [comment]
I'm not 100% certain what you're trying to say but if I understand it correctly:

If you set the separator to `§` then `md§w-1/3` will works and `md:w-1/3` will not because the separator has been changed. This behavior is what the separator documentation describes (you can change the separator from `:` to another character of your choosing)

**Comment by Triloworld** [comment]
> I'm not 100% certain what you're trying to say but if I understand it correctly:
> 
> If you set the separator to `§` then `md§w-1/3` will works and `md:w-1/3` will not because the separator has been changed. This behavior is what the separator documentation describes (you can change the separator from `:` to another character of your choosing)

Yes but `md:w-2/3` works normal and we like to not have working - custom separator allow default one which is not desired. Why ":" work as default one? Documentation say and I quote:
> We use a colon by default (:), but it can be useful to **CHANGE** this if you’re using a templating language like [Pug](https://pugjs.org/) that doesn’t support special characters in class names.

It won't change, It ADD new separator instead. That's what you write and what I refer to. I get TWO separator : default and custom one. Documentation can be updated by this issue or change behaviour to reflect existing concept.

**Comment by Triloworld** [comment]
User cases:
- We have problem like PUG or cms like Drupal to use syntax, we use two of them
- We use CDN that have different setup that local one
- We can have files that use custom one and aren't available to other environment which produce errors (export field from data which have class or files that are generated).

Like to update documentation.
@thecrypticace pleas open if you see some improvements there :) Like to contribute
