### ISSUE TITLE
Using CSS variable or alpha-value in `theme.ringColor.DEFAULT` doesn't work

### ISSUE THREAD

**Issue by dcastil** [tailwindlabs/tailwindcss#9016]
**What version of Tailwind CSS are you using?**

v3.1.7

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 3.0.4

**What version of Node.js are you using?**

v14.14.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/V7MWdx7jh3

**Describe your issue**

Using a CSS variable for `theme.ringColor.DEFAULT` in the Tailwind config makes Tailwind use its default value instead of the specified one.

None of these values work:
- `rgb(var(--primary, 113 97 236) / <alpha-value>)`
- `rgb(var(--primary, 113 97 236))`
- `var(--primary, rgb(113 97 236))`
- `rgb(113 97 236 / <alpha-value>)`

**Comment by thecrypticace** [comment]
Hey, so yeah this indeed doesn't work. It has to do with us injecting the default ring opacity into the color. Because of the way things work with the default ring color fixing this would cause breaking changes. Whenever v4 comes around we'll be changing how that works but there's an existing feature flag to enable the behavior today:
```js
  future: {
    respectDefaultRingColorOpacity: true,
  },
```

With this flag enabled we no longer inject the default opacity into the defined color (or fall back when we fail to do so). With this change `rgb(var(--primary, 113 97 236))` will work. As for `<alpha-value>` support — we could add that but it would only ever get filled in with the default ring opacity so it doesn't seem like a super important thing enable support for (may change our mind on that tho).

Here's a Tailwind Play example with the feature flag enabled: https://play.tailwindcss.com/LbCOCPaJG8?file=config

Hope that helps — feel free to comment further if you have questions! ✨
