### ISSUE TITLE
1 Warning of base Component

### ISSUE THREAD

**Issue by Sijad99** [tailwindlabs/tailwindcss#9046]
<img width="1440" alt="Screen Shot 2022-08-08 at 04 27 10" src="https://user-images.githubusercontent.com/49100288/183316178-703c2d6c-ab3c-40ef-8cca-2a8645f6d459.png">

Hi. 
my Vscode  showing to me this warning and because my extension often say correctly, I should report this to you.
Thanks

**Comment by thecrypticace** [comment]
Hey, so this style is present intentionally. The lint error you're getting is a rather poor error as it doesn't take into account that the styles can be overridden. Basically the reason this exists is because the `display` of these replace elements can still be changed to `inline` by users and the vertical-align is there to target those scenarios. You can find more details in the link in the comment above the code: https://github.com/jensimmons/cssremedy/issues/14#issuecomment-634934210
