### ISSUE TITLE
"border" utility doesnt work when "base" isn't included

### ISSUE THREAD

**Issue by ringeringeraja** [tailwindlabs/tailwindcss#9089]
**What version of Tailwind CSS are you using?**

v3.1.7

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.14, webpack 5.72.0

**What version of Node.js are you using?**

v16.15.1

**What browser are you using?**

Qutebrowser / Chromium

**What operating system are you using?**

Linux

**Describe your issue**

I'm using Tailwind on my Vue project, but I'd prefer to use only "utilities" ("base" will mess up with the font making it larger). Every single utility will work if I use only "@tailwind utilities" in my CSS root, but weirdly "border" and its related utilities won't. If I then include "base" as long with "utilities", it will start to work again.

I don't see any reason for it being like it is, so I'll call it a bug.

**Comment by thecrypticace** [comment]
Hey, appreciate the report. So this is intentional on our part. Enabling `border` to work like it does — by just adding the border class — is one of the jobs of `preflight`: https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally

If you want to not include preflight you can replicate this in your own CSS by using the styles from the documentation.
