### ISSUE TITLE
Arbitrary selectors do not work with the group- selector

### ISSUE THREAD

**Issue by LeptoFlare** [tailwindlabs/tailwindcss#9138]
**What version of Tailwind CSS are you using?**
v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**
next v12.2.4

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/v4zwsTiLaY

**Describe your issue**

Hello, as the title says, I'm unable to use arbitrary variants with the group- selector.

```jsx
                  <DropdownMenu.Item key={status} className="group">
                    <div className="flex items-center gap-3 rounded-md px-3 py-2 group-[&[data-highlighted]]:bg-primary-700">
                      <div className={parsed.classes}>{parsed.icon}</div>
                      <div className="">{parsed.text}</div>
                    </div>
                  </DropdownMenu.Item>
```

As you can see, I'm trying to use the `[&[data-highlighted]]:` arbitrary selector, and I've added `group-` to the start of it to target the parent element.

I've tested whether the `group` attribute works as intended with `group-hover` and whether the `[&[data-highlighted]]` works on it's own on the level above. Both of these work so I am sure that it's an issue with it combined together.

I've also tried putting `group-` inside of the arbitrary selector such as: `[group-&[data-highlighted]]` which does not work.

---

This is my first time creating a bug report like this so sorry if I messed something up 😅

**Comment by adamwathan** [comment]
Hey! So right now Tailwind doesn't have any concept of like "parameterized variants", so a variant can only be a named variant (like `hover:`), or an arbitrary variant (like `[&[data-highlighted]]`), it can't like a dynamic mix of both. This is something we do want to play with for a future release though and have prototyped a bit already.

In your case you just want to write an arbitrary variant that includes the actual implementation of the group stuff:

```
[:merge(.group)[data-highlighted]_&]:text-green-700
```

https://play.tailwindcss.com/5PxWajQ4lg

Going to close since not a bug but hopefully a feature we add for v3.2 or v3.3 👍

**Comment by LeptoFlare** [comment]
Thanks for the response, can you give an explanation on what exactly `:merge(.group)[data-highlighted]_&` does?
I'm a bit confused why there's an `_&` at the end instead of the start, and what `:merge` does

**Comment by adamwathan** [comment]
Sure, so the point of the `group` stuff is to add a parent selector right? So given a class like `group-hover:font-bold`, we need to generate this selector:

```css
.group:hover .group-hover\:font-bold
```

The way you generate that selector is with this variant string:

```
.group:hover &
```

...which is why in the arbitrary variant the `&` goes at the end.

The `:merge` directive is a special Tailwind directive for making sure `.group` only appears in the final selector once. Consider this example:

```
group-hover:group-focus:font-bold
```

Without doing anything special, this would generate this selector which is wrong:


```
.group:hover .group:focus .group-hover\:group-focus\:font-bold
```

Notice the double `.group` at the beginning? The `:merge` directive tells the compiler to merge `.group` with any existing `.group` instances in the selector so there's only one:

```
.group:focus:hover .group-hover\:group-focus\:font-bold
```

Hope that helps!
