### ISSUE TITLE
"items-center" and  "justify-center"

### ISSUE THREAD

**Issue by oosswwaalldd** [tailwindlabs/tailwindcss#9151]
**What version of Tailwind CSS are you using?**

v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.1, Next.js 10.0.9, webpack 5.28.0
postcss: 8.4.12
next: 12.0.9

**What version of Node.js are you using?**

NodeJS v16.14.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

"items-center" and  "justify-center" do not work when using them in a simple div. To see the issue do this:

```
<div class="flex flex-col justify-center items-center">I am Centered</div>
```

The words are not centered in a column flex way.

I reverted to v3.0.23 and it works as expected

**Comment by adamwathan** [comment]
Looks like it's working to me, it is just applying this CSS which has been the same since v0.x:

```css
... {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
```

The behavior in Tailwind is the same as just writing that CSS by hand so it's not a Tailwind-specific thing you are running into here:

https://play.tailwindcss.com/duPxueN56u
https://jsfiddle.net/3jg0bqtk/

If you think it's a real bug please open another issue but include a proper reproduction where we can switch between v3.0.23 and the current version and see a difference in behavior, thanks ❤️
