### ISSUE TITLE
Impossible to override upper-declared classes

### ISSUE THREAD

**Issue by Andrew01011997** [tailwindlabs/tailwindcss#9161]
v 3.1.3
React 17.0.2

It is currently not possible to use styles from the same object, such as `rounded-md rounded-full`, due to the hierarchy of value declarations.
It would be better if the next class with the same logic, such as rounding, overrides all previous classes.

Thanks for your work!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This is not something that is possible. The order of classes in your HTML doesn't matter, the specificity in your CSS does. If the specificity is the same, then the order matters in your CSS file, not in your HTML file.

There is nothing we can about that in Tailwind CSS since that's how the browser works. However there are a few solutions:

1. Do not rely on applying the same type of class at the same time. Instead apply them conditionally. E.g.: In React you could do something like this `className={isSuperRound ? 'rounded-full' : 'rounded-md'}`
2. Assuming you are writing some form of React/Vue component and that `rounded-md` is applied by default, and you want to pass in a `class` prop and merge it. In this case, it's better to accept a dedicated prop with some `type` so that you can apply the correct styling based on that type. Accepting a `className` as a prop if classes already exists can be a footgun (which is probably what you are seeing now).
3. Another solution to the previous item is that you can use `!rounded-full` in the passed props which adds a `!important` to the CSS and will guarantee that it overrides the previous. This could result in other unwanted bugs and this is not encouraged but it is a workaround to the problem.
4. Last but not least, you can implement a `default` variant which lowers the specificity and in turn allows for overridable classes. This also can have problems in older browsers where the `:where` is not supported. Example: https://play.tailwindcss.com/antuRg9q2Y?file=config

But again, I would recommend you to bypass this problem altogether by applying the fixes in 1. and 2.
