### ISSUE TITLE
Setting important: true in config breaks ping animation example

### ISSUE THREAD

**Issue by sglvladi** [tailwindlabs/tailwindcss#9225]
**What version of Tailwind CSS are you using?**

3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

N/A

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

Working (``important: false``): https://play.tailwindcss.com/HUMFio3EBW?size=540x720
Not working (``important: true``): https://play.tailwindcss.com/nv1Qf0AeW1?size=540x720

**Describe your issue**

Setting ``important: true`` in the config seems to mess up the [ping animation example](https://tailwindcss.com/docs/animation#ping) provided in the docs. This may be happening with other animations as well, but I have not tried it. 

Removing the ``!important`` flag from the following css seems to fix the issue:

```css
.opacity-75 {
  opacity: 0.75 !important;
}
```

**Comment by thecrypticace** [comment]
Hey, so unfortunately this is because Chrome updated fairly recently to [follow the CSS spec](https://www.w3.org/TR/css-cascade-4/#cascade-sort). I believe this is the relevant commit if you're curious: https://github.com/chromium/chromium/commit/f1c2621fc05bc4ae9ebbede8129b866f94786e94.

Browsers used to let animations override important properties. However, since this does not follow the spec, they have been changing this behavior. Now important declarations override animations but not transitions. FF follows the spec here as well. Safari has not yet updated to handle this situation.

Essentially this is a side effect of using `important: true`. Now, any CSS property that is marked as `!important` overrides any property used by keyframes. This has been [discussed previously](https://github.com/tailwindlabs/tailwindcss/discussions/8483#discussioncomment-2855686). My suggestion there was, if you need to increase the specificity, your only global option in this case is to use an important selector to scope all of Tailwind CSS's utilities to only apply under that ID: `important: '#myapp'`

Another smaller (but localized) option is that, if you are using `important: true` because you need to make a _small number_ of utilities important you can disable it and instead make them important on a case-by-case basis by prefixing the utility with a `!`. For instance the utility `!underline` produces `text-decoration-line: underline !important` while leaving all the other utilities alone. This would allow you to use animations with those properties/utilities that do not need to be important.

If at all possible though, I would suggest not using `important: true` at all. It's exists more for people that need to integrate Tailwind CSS with third party libraries and existing CSS — and, as you've encountered, it unfortunately has limitations. If you can get by without it that would be preferred. I _wish_ there was something we could do to fix this. Unfortunately, due to the nature of `!important`, anything we do to the selector won't change anything unless the property inside that new rule is _also_ `!important` which still presents the same problem.

Hopefully that helps. Let me know if you have any further questions.
