### ISSUE TITLE
Duplicate negative selectors with "-" part of prefix

### ISSUE THREAD

**Issue by ryanaltvater** [tailwindlabs/tailwindcss#9287]
**What version of Tailwind CSS are you using?**

3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Gulp 4.0.2

**What version of Node.js are you using?**

18.4.0

**What browser are you using?**

Brave

**What operating system are you using?**

macOS

**Describe your issue**

I'm looking at my generated CSS output and I'm seeing duplicate negative selectors being written 2 different ways where the "-" is before and after the prefix. When I remove the prefix from my configuration or change it to a "_", the duplicates don't exist. This seems to only happen with anything that has a negative value (margin, z-index, etc), when a "-" prefix is defined. Below is an example of it happening with margin.

```
.dx--my-0 {
    margin-top: -0px;
    margin-bottom: -0px
}
.dx--my-1 {
    margin-top: -8px;
    margin-bottom: -8px;
}
```

```
.-dx-my-0 {
    margin-top: -0px;
    margin-bottom: -0px
}
.-dx-my-1 {
    margin-top: -8px;
    margin-bottom: -8px
}
```

I did find [this](https://github.com/tailwindlabs/tailwindcss/pull/7295) from February, and it reads very similarly to the issue I'm experiencing.

**Comment by thecrypticace** [comment]
Hey! 👋 

Any chance you could provide a reproduction? I can't reproduce this issue on Tailwind Play. We do allow _both_ usages for backwards compatibility purposes (the dash before and after the prefix) however we should only be outputting utilities for the ones you are actually using.

**Comment by ryanaltvater** [comment]
So I just did a fresh installation with the below configuration, and got the same result of `.-dx-*` and `.dx--*` for utility classes with negative margins.

```
module.exports = {
  content: [],
  corePlugins: [
      'backgroundColor',
      'fontFamily',
      'fontSize',
      'fontStyle',
      'fontWeight',
      'margin',
      'padding',
      'preflight',
      'textColor',
      'zIndex',
  ],
  prefix: 'dx-',
  safelist: [{
      pattern: /.*/,
  }],
}
```

**Comment by thecrypticace** [comment]
Ah I see. So, in this case, Tailwind CSS is acting correctly. We match and generate both utilities for backwards compat purposes and your safelist pattern is telling Tailwind CSS to match absolutely everything it knows how to generate. You'll want to modify your safelist to exclude one or the other:
- Exclude `dx--` negative utilities: `/^-?dx-(?!-).+$/`
- Exclude `-dx-` negative utilities: `/^dx-.+$/`

You'll note I also anchored the utilities. This is generally a better idea if you need to not match everything otherwise you could happen to match something _inside_ the name of a utility which can lead to unexpected matches (depends on your pattern tho)

**Comment by ryanaltvater** [comment]
This is exactly the help I was hoping for. Your solution worked perfectly. Thank you!
