### ISSUE TITLE
Rotate behave differently using "rotate()" and arbitrary css

### ISSUE THREAD

**Issue by fullstackneo** [tailwindlabs/tailwindcss#9292]
**What version of Tailwind CSS are you using?**

v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-import, tailwindcss,

**What version of Node.js are you using?**

v16.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**
Please just hover on the blocks to reproduce my problem
![chrome-capture-2022-8-8](https://user-images.githubusercontent.com/97574983/189281864-c164bf68-ec4d-4e96-be04-34f06813ca4e.gif)

[https://play.tailwindcss.com/Xb56zPEkca](https://play.tailwindcss.com/Xb56zPEkca)

**Describe your issue**

The two blocks behave differently when applying same degree rotation using

- tailwind's "rotate(1020deg)"
- arbitrary css "[transform: rotate(1020deg)]".

Only by adding 'translate' will the block rotates to the correct degree.

`hover:[transform:translate(0,0)_rotate(1020deg)]`

I know I can define and use a "rotate-1020" class in @layer component to override certain styles, but in daily work, I am using vanilla css more often in @layer utilities to define extra classes. I am not sure whether this is a bug or not, but I am really confused by the rotation problem, so could you please help me explain? Big Thanks!!!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

To me it looks like they are both rotating to the correct spot, but the "transition" to it is different.

I don't know what the result is you want, do you expect it to spin fast or not spin at all?

If you want it to spin fast, and don't want to add the `1020deg` version to your config, then you can use arbitrary values like `hover:rotate-[1020deg]` which has the same effect as adding it to your config.

> I know I can define and use a "rotate-1020" class in https://github.com/layer component to override certain styles, but in daily work, I am using vanilla css more often in https://github.com/layer utilities to define extra classes.

Do you mean that you are using `@apply` in the vanilla css, or just vanilla css?
```css
.my-custom-class-using-apply {
  @apply rotate-0 hover:rotate-[1020deg];
}
```

Currently in Tailwind the different transform classes are combined using css variables so that they are composeable, this means that `translates` are also present which could result in this strange result. The moment you use arbitrary properties `[translate:rotate(1020deg)]` you are escaping Tailwind's default behaviour and it is no longer making the translate property composable.

The behaviour you see where adding `translate(0,0)` or not is also just what the browser does and nothing we can do about that in Tailwind itself. In the future we might be able to remove the composition once the individual properties are available: https://web.dev/css-individual-transform-properties/

That said, if your goal is to have the "slow" rotation that's going counter clockwise, then you can update your values a bit.

- `1020deg` can be simplified to `300deg` (almost 3 rotations less so slower, but still going clockwise)
- `300deg` can also be simplified to `-60deg` (which makes it rotate the other way)

They all result in the final same position, but the amount of rotations / direction is different: https://play.tailwindcss.com/vEENO1fiNX

Hope this helps!

**Comment by adamwathan** [comment]
It looks like what's happening here is a difference in how the browser transitions transforms when the starting transform has a different "shape" than the final transform.

https://play.tailwindcss.com/6z3GU3qQNo?file=css

This vanilla CSS will spin around a bunch like you want:

```css
.vanilla-rotate {
  transform: translate(0,0) rotate(0);
}

.vanilla-rotate:hover {
  transform: translate(0,0) rotate(1020deg);
}
```

But this vanilla CSS won't, it just rotates to the final position without spinning:

```css
.vanilla-rotate-2 {
  transform: translate(0,0) rotate(0);
}

.vanilla-rotate-2:hover {
  transform: rotate(1020deg);
}
```

Kinda surprising to me honestly but seems like that's what the browser does.

I don't see a way for us to influence this behavior unfortunately, at least not without throwing away the ability to compose transforms which is an important part of our API.

So the learning here is just to make sure if you are transitioning to a custom transform, make sure your start and end transforms are defined with the same "shape", and this is just a CSS thing not a Tailwind-specific thing. As long as you use our provided classes like `hover:rotate-[1020deg]` things will just work, but if you want to use arbitrary properties then you will want to make sure the generated value has the same shape as the value Tailwind is starting from, or that you use arbitrary properties for both the start and end phases of the transform 👍🏻

**Comment by fullstackneo** [comment]
Thank you for your patient reply, @RobinMalfait  and @adamwathan  . I was expecting those two have the same animation effect. Since the starting state "rotate-0" adds other properties (skew, translate) with 0 value, which will result in unexpected animation behaviour.

I was not writting overriding style using tailwind class in @layer component, because I prefer to avoid so many '@apply's in a nested animation class. But please take a look at the following code. I guess there might be users like me, using tailwind in HTML and following vanilla css class at the same time to make more complex animaiton css. 

```
@layer utilities {
  .menu-active {
    width: 75px;
    span {
      transform: rotateY(280deg);
    }
    .btn {
      transform: translate(50%, -50%);
      div {
        right: 50%;
      }
      div:first-child {
        top: 4px;
        transform: **translate(0, 0)** rotate(1020deg);
      }
      div:last-child {
        top: 11px;
        transform: **translate(0, 0)** rotate(1020deg);
      }
    }
  }
}

```

Since I have to add an extra "translate(0,0)" to fulfill the animation, which is a little bit unintuitive. I recommend mentioning that for users in [doc regaring animation](https://tailwindcss.com/docs/scale) using only tailwind class or vanilla css class to avoid strange animation transition. Another suggestion would be tailwind and css become more seamless in animation css properties in the future. 

Thank you again for your help! Much appreciate it!
