### ISSUE TITLE
Custom Utilities not found in ~80% of dev builds

### ISSUE THREAD

**Issue by dkress59** [tailwindlabs/tailwindcss#9311]
**What version of Tailwind CSS are you using?**
v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

* Webpack 5.74.0
  * webpack-cli v4.10.0
  * sass-loader v13.0.2
  * postcss-loader v7.0.1
    * postcss-import
    * tailwindcss/nesting
    * tailwindcss
    * autoprefixer
  * style-loader v3.3.1
  * css-loader v6.7.1
  * style-loader v3.3.1
*  React v18.2.0

**What version of Node.js are you using?**
v18.9.0

**What browser are you using?**
any

**What operating system are you using?**
macOS Monterey, Debian 11 (bullseye)

**Reproduction URL**
https://github.com/dkress59/eleaves-issue-repro

**Describe your issue**

*Issue Description:*
When running the app through webpack-dev-server (whether with docker compose, or "natively"), in four out of five times the build fails, because my custom utilities are not found. After several tries of restarting without changing any code, the compilation miraculously succeeds. In production builds this issue somehow never occurs, the difference there being A) not using webpack's devServer feature and B) using [MiniCssExtractPlugin](https://webpack.js.org/plugins/mini-css-extract-plugin/)'s loader instead of the classic style-loader. Using MiniCssExtractPlugin for the dev builds, as well, does not help, though.
More detailed information on the exact error and the general project setup are included in the reproduction repo's readme.

*Expected Behaviour:*
Custom Tailwind Utilities are found in every dev build instead of just being found occasionally.

**Comment by thecrypticace** [comment]
Hi! So this is a super weird one but it has to do with the order that files are built in webpack.

The gist of how your project is laid out is:
1. You have an sass file that defines utilities.
2. Each package has an `index.tsx` file that imports an scss file
4. Inside this scss file it imports the common utilities scss file.
6. Additionally, each component has it's own tsx file
7. Which imports their own scss file.
8. And each of these files `@apply` utilities from the first common import.

Essentially:
  - Common Package -> `file.scss` -> `@layer utilities`
  - App Package 1 ->
    - `index.tsx` -> index.scss -> `@import common/file.scss`
    - `component-1.tsx` -> `component-1.scss` -> `@apply my-utility`
    - `component-2.tsx` -> `component-2.scss` -> `@apply my-utility`

In webpack it will compile and run as much things in parallel as it can. In your case what's happening is that:
  - `index.tsx`, `component-1.tsx`, `component-2.tsx` are all compiled in parallel
  - These CSS files are then processed in parallel
  - And the order in which these are processed is not guaranteed (especially since there's no dependencies between them)

When Tailwind CSS processes `common/file.scss` we store utilities in a shared context for the whole process. This lets it be applied by _any_ file used in your project. However, if that file gets processed before the main CSS you will run into this problem. This is unfortunately not something we have enough control of to fix. This is up to whatever build tool you are using.

I would suggest one of a few things:
- Define these utilities in your config with custom plugins
- Import the utilities in the scss file for each component (this could very well cause other issues though since you'd be defining the same utilities more than once — so i'm not actually sure if this would work)
- Since you're using sass you might be able to use imports + mixins instead here.

Hopefully that's enough info and ideas to help move forward. Let me know if you have any further questions. ✨

**Comment by dkress59** [comment]
Heya, thanks a lot for your insight! Now I can make sense of it and know how to tackle the problem 🙌  I'll leave another comment once I've found a solution.

**Comment by dkress59** [comment]
I found a fix:

As described by @thecrypticace, I have a `common/util.scss` which includes my custom utilities. There also is a `common/index.scss` which imports the `util.scss` and is imported by every app's entry point, inside the `index.tsx`. So while every sub-component may have its own stylesheet using the common utilities, all common styles are imported at the entry point of any of the monorepo's apps.

So with the troubleshooting help that I got here, I simply added a separate loader for the `index.scss` to prioritise it over all other `.scss` imports:

```ts
module: {
	rules: [
		{
			test: /(?<!index)\.s?css?$/i,
			use: [
				isProduction
					? MiniCssExtractPlugin.loader
					: 'style-loader',
				'css-loader',
				'postcss-loader',
				'sass-loader',
			],
			exclude: /node_modules/,
		},
		{
			// prioritise scss that imports custom utilities
			test: /index\.s?css?$/i,
			use: [
				isProduction
					? MiniCssExtractPlugin.loader
					: 'style-loader',
				'css-loader',
				'postcss-loader',
				'sass-loader',
			],
			exclude: /node_modules/,
		},
```

*Note: In the reproduction repo the issue still occurs. In the real project it doesn't. My guess is that this is because there are only two `index.scss` found, but in the real project there are many, many more other `.scss` files to be loaded than in the reproduction repo – so the order of the now two loaders does not seem to do the trick, it's just that the loader for the explicit `index.scss` files compiles fast enough.*
