### ISSUE TITLE
Transforms do not work without importing base

### ISSUE THREAD

**Issue by snaptopixel** [tailwindlabs/tailwindcss#9314]
**What version of Tailwind CSS are you using?**

v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

StencilJS/rollup

**What version of Node.js are you using?**

v16.17.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/mhI5n4GOWy

**Describe your issue**

I'm using tailwind on top of a ui that already has it's own reset, so I'm not importing `base`. The `transform` class does not seem to provide default values for the expected vars (which I assume are set as part of base) and so none of the transforms work.

```css
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
```
Should become something like
```css
    transform: translate(var(--tw-translate-x, 0), var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) skewX(var(--tw-skew-x, 0)) skewY(var(--tw-skew-y, 0)) scaleX(var(--tw-scale-x, 1)) scaleY(var(--tw-scale-y, 1));
```

**Comment by adamwathan** [comment]
Hey! This is by design, you should always include `@tailwind base` even if you are using your own reset. If you're using your own reset, you'll want to disable preflight rather than not use `@tailwind base`:

```js
// tailwind.config.js
module.exports = {
  // ...
  corePlugins: { preflight: false },
}
```

Here's the relevant docs: https://tailwindcss.com/docs/preflight#disabling-preflight

**Comment by adamwathan** [comment]
To follow up quickly, this approach doesn't actually work the way you'd hope:

```
    transform: translate(var(--tw-translate-x, 0), var(--tw-translate-y, 0)) rotate(var(--tw-rotate, 0)) skewX(var(--tw-skew-x, 0)) skewY(var(--tw-skew-y, 0)) scaleX(var(--tw-scale-x, 1)) scaleY(var(--tw-scale-y, 1));
```

It's important that each variable gets reset to whatever its "no-op" value is on a per element basis, otherwise the variable values will be inherited from parent elements which messes things up. For example if a parent has `rotate-3` on it and a child has `translate-x-4`, the child will _also_ be rotated because it will see that the rotate variable has been set further up the tree. So it's important that `--tw-rotate` is reset to `0` on a per element basis using the `*` selector.

**Comment by snaptopixel** [comment]
Thanks @adamwathan, makes sense!
