### ISSUE TITLE
When disabled preflight, border-solid will add 1.5px border-width, which is not expected.

### ISSUE THREAD

**Issue by fkworld** [tailwindlabs/tailwindcss#9372]
**What version of Tailwind CSS are you using?**

3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.16
autoprefixer 10.4.11
vite 3.0.9
typescript 4.8.2

**What version of Node.js are you using?**

v16.16.0

**What browser are you using?**

Edge 105.0.1343.42

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/PnrWKkWuNL

**Describe your issue**

When disabled preflight, border-solid will add 1.5px border-width, which is not expected.

**Comment by adamwathan** [comment]
Hey! Yep this is what happens when you add a solid border in regular CSS without using Tailwind at all, see here:

https://jsfiddle.net/jk0nyust/

If you aren't using Preflight, then you are using the browser's default styles and have to work around them accordingly by making sure to always set the border-width when adding `border-solid`. Preflight is designed to make this sort of thing less annoying but of course if you disable Preflight there's nothing we can really do to help here.

**Comment by fkworld** [comment]
I see. Thanks.

I hate css! I didn't find any description of the linkage between border-style and border-width in MDN. MDN only given an example: https://developer.mozilla.org/en-US/docs/Web/CSS/border-style#examples.
