### ISSUE TITLE
leading-tight (line height) is disregarded at certain viewport sizes

### ISSUE THREAD

**Issue by steven-tey** [tailwindlabs/tailwindcss#9381]
I'm doing the following:

```
<h1 className="text-5xl sm:text-6xl leading-tight sm:leading-tight">Some long title text</h1>
```

And for some reason the line height value is different for `sm` and non-`sm` viewports. 

A look into Chrome console shows that the line-height attribute is disregarded in the non-`sm` viewport 😮 

![CleanShot 2022-09-20 at 20 16 43](https://user-images.githubusercontent.com/28986134/191392744-3c3fa8ed-0078-4a3f-80bb-2f238eb35562.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The font size utilities come with a default line height: https://tailwindcss.com/docs/font-size the `text-6xl` one ships with `line-height: 1;` by default, but you also are using the `sm:leading-tight` class which overrides the default one shipped with the font size utility. That's why the top rule shows `line-height: 1.25;` and the bottom one has a line through it.

Depending on what you want, there are a few solutions you can apply.
1. Do you want to keep the `line-height: 1;`? In that case you can remove the `sm:leading-tight`
2. Do you want the `1.25`, then what you are doing is correct.

**Comment by steven-tey** [comment]
Oh, interesting, TIL! And thanks for replying so quickly – y'all are amazing!! 🤩
