### ISSUE TITLE
Dark mode not working when using important with selector.

### ISSUE THREAD

**Issue by addgod** [tailwindlabs/tailwindcss#9438]
**What version of Tailwind CSS are you using?**

For example: v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: laravel mix: 6.0.49

**What version of Node.js are you using?**

For example: v16.13.2

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: Linux

**Reproduction URL**

Do not have one.

**Describe your issue**

When using the important config option set to a selector, it precedes the .dark class in the generated css. So when adding .dark to the html tag it will not trigger dark mode.

Example of generated code
```
#app .dark .dark\:border-gray-700 {

border-color: rgba(var(--colors-gray-700))
}
```

Example of how it should be implemented.
```
.dark #app .dark\:border-gray-700 {

border-color: rgba(var(--colors-gray-700))
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is expected behaviour right now, the important selector (`#app`) is added to the beginning of every selector, so you end up with selectors like this:
```
#app .dark .dark\:border-gray-700
```

This means that you have to put the `dark` class on an element that is a child of your `#app` element, like:
```html
<html id="app">
  <body class="dark">
    ...
  </body>
</html>
```

No plans to change this any time soon but hope that helps 👍🏻
