### ISSUE TITLE
TailwindUI template Salient needs rewording

### ISSUE THREAD

**Issue by marky291** [tailwindlabs/tailwindcss#9441]
This is a slight humorous find I noticed when looking at the template, the concept of the template is to market your next big SAAS platform, but when looking at pricing, it says our software wont work well for you. I could not find a tailwindUI github issue tracker so posting here.

- View [https://salient.tailwindui.com/](https://salient.tailwindui.com/)
- Scroll down to payment section.
- Text shows 'It doesn’t matter what size your business is, our software won’t work well for you.'

Expected: 'From starter to enterprise, we support your business requirements.'

<img width="744" alt="Screenshot 2022-09-28 at 23 05 43" src="https://user-images.githubusercontent.com/5384515/192897357-bf682112-09ac-4c33-ba97-3c55a2b9ff38.png">

Should be noted, that the title being 'for everyone' is not true if its marketing pricing for business.

**Comment by maccman** [comment]
I agree - we need to fix that asap.

Also I noticed you're sending around passwords in plain-text. That is unacceptable!! 

<img width="404" alt="CleanShot 2022-09-28 at 15 56 03@2x" src="https://user-images.githubusercontent.com/2142/192902797-8cf7f98a-7c3f-48b8-9206-e479c194ebb9.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

But this is all done on purpose to make it a bit more pleasant to read while you are exploring our templates. The templates are templates, not real products you can use right away. In this case, you can't actually buy the "TaxPal" software as an accounting software tool. It's the template _you_ can use to build _your_ product.

We also don't know what _you_ want to build with these templates, so it is impossible for us to write the correct marketing prose everywhere for your specific application.

We used an example product to showcase what a real marketing page for a product could look like. The alternative would be that we used `Lorem ipsum` everywhere and placeholder images like https://via.placeholder.com/300x150, but we chose to put some humor in it instead of making it boring. Just look at any other place on the page, or any other template. 👍 


About the Tailwind UI issue tracker, that can be found here: https://github.com/tailwindlabs/tailwindui-issues

**Comment by marky291** [comment]
@RobinMalfait I thought as much when reading, it was just odd that it was subtle humour, and saw it as a bug, thanks 👍
