### ISSUE TITLE
Removed css classes arent removed from output.css

### ISSUE THREAD

**Issue by therealcoolpup** [tailwindlabs/tailwindcss#9450]
**What version of Tailwind CSS are you using?**

v4.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

React 18

**What version of Node.js are you using?**

v16.17.1

**What browser are you using?**

Brave

**Describe your issue**

When I remove css classes I only use once they stay in the output.css file even when running the compiler.

**Comment by AviAvinav** [comment]
@therealcoolpup Can you tell me how can I reproduce this? Are you using vite or create-react-app

**Comment by therealcoolpup** [comment]
@AviAvinav Hello, i used normal create react app without vite.

I then tried in the app component to set background image with className="bg-[url('/path/to/img.svg')]"

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This behavior is an intentional performance optimization. While Tailwind CSS is watching files we do not clear out already generated classes. You can restart the watcher (or save your tailwind.config.js file) if you need to but generally during development this shouldn't be an issue. And a fresh build will always re-scan the files generating only found classes. 

Hope that answers your question.
