### ISSUE TITLE
Preflight breaks max-height image in flexbox in Safari

### ISSUE THREAD

**Issue by tiotdev** [tailwindlabs/tailwindcss#9638]
**What version of Tailwind CSS are you using?**

Reproduced in Tailwind Play v3.2.1

**What browser are you using?**

Safari 15.6.1 / Safari 16.0

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/aWe0GgX487

**Describe your issue**

Adding Tailwind breaks image resizing inside a flexbox in Safari.

The example is a minimal reproduction of the issue.

The example looks great in Chrome and Firefox:

<img width="616" alt="chrome" src="https://user-images.githubusercontent.com/18411522/197365905-562fbf31-169e-4682-850d-e78b87509fa1.png">

But is broken in Safari:

<img width="826" alt="safari" src="https://user-images.githubusercontent.com/18411522/197365911-739cb302-1c94-4afe-b603-300a3571db34.png">

After removing `@tailwind base;` in the CSS tab in Tailwind Play (or alternatively, disabling preflight in config), the output is the same in all browsers:

<img width="826" alt="safari_without_tailwind" src="https://user-images.githubusercontent.com/18411522/197365927-a2fd2713-fc44-447f-81c8-ece8c2240c8c.png">

**Comment by thecrypticace** [comment]
I think this is a Safari problem. Chrome and FF add an implicit `aspect-ratio` CSS property to images with a width and height which affects the intrinsic flex layout. Safari does not do this. But even when adding it explicitly in Safari it produces a different layout. Notably this doesn't get "fix" even when omitting `@tailwind base` because the layout in Safari is stretched significantly.

Leaving these notes so I can take a deeper dive into this later.

**Comment by adamwathan** [comment]
So this is because of this rule here in Preflight:

https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L359

This has benefits (as described in the comment in Preflight) but also introduces this behavior. Unfortunately it would be a very big breaking change for us to do anything differently here so not sure what to do.

One thing worth noting — while the result is the _same_ in all browsers after removing Preflight, it's not the same as the original result you posted in Chrome:

Chrome w/Preflight:

![image](https://user-images.githubusercontent.com/4323180/199244570-110b64f3-1ef2-43de-92b7-2bc40f845f3a.png)

Chrome w/o Preflight:

![image](https://user-images.githubusercontent.com/4323180/199244606-77490d04-c466-4b75-932c-95264a572991.png)

You can see that the aspect ratio is totally distorted.

Can you describe the particular UI you are trying to build in more detail? Maybe we can come up with another way to build it where this isn't a concern.

**Comment by tiotdev** [comment]
Thank you! It seems that relying on flexbox for image resizing is not a good idea, I had no idea that Safari renders so differently.
I am building an image grid. I have managed to rewrite my component by defining the aspect ration as a custom style for each individual image with ```style={{ flexGrow: `calc(${image.width}/${image.height})` }}```: https://truvvl-blog-awesomeblog-lr1czvm92-julianpeters.vercel.app/welcome-to-travelfeed-an-example-post

**Comment by reinink** [comment]
@tiotdev Hey nice! Glad you got this figured out.

Just thinking, you could probably do this without the `calc`:

```jsx
<img src="..." style={{ flexGrow: image.width / image.height }} />
```

Untested...just an idea 👍
