### ISSUE TITLE
Using the word container as a variable/prop includes the css class

### ISSUE THREAD

**Issue by thaoms** [tailwindlabs/tailwindcss#9678]
**What version of Tailwind CSS are you using?**

v3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.18, postcss-cli 9.1.0, webpack 5.72.0

**What version of Node.js are you using?**

For example: v16.9.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

```
export type ModalProps = PropsWithChildren<
    {
        size?: 'large' | 'medium' | 'small'
        'aria-labelledby'?: string;
        'aria-described-by'?: string;
        isOpen: boolean;
        container?: Element;
    }
>;

export default function Modal(props: ModalProps): ReactElement | null {
    const size = props.size ?? 'medium';

    if (!props.isOpen) {
        return null;
    }

    return createPortal(
        (
            <Fragment>
                <dialog
                    className={`modal modal--${size}`}
                    aria-labelledby={props['aria-labelledby']}
                    aria-describedby={props['aria-described-by']}
                >
                    {props.children}
                </dialog>
                <div className="modal-backdrop" />
            </Fragment>
        ),
        props.container ?? document.body
    );
```
**Describe your issue**

When looking at the code example, using the word 'container' as in `props.container` it is actually including the `.container` class in my css output. I'm not using the container word anywhere else.

**Comment by adamwathan** [comment]
Hey! Yep this is just the nature of how class detection in Tailwind works:

https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

Same thing happens if your code contains the words “flex” or “grid”. To us this trade off is worth it for Tailwind to work with more tools. If we tried to actually parse and understand the code we could only support a small number of templating languages and you’d have lots of situations where things didn’t work that you’d expect to work because we couldn’t detect that something was intended to be used as a class.

You can disable the container plugin if this really bugs you 👍🏻

**Comment by thaoms** [comment]
> Hey! Yep this is just the nature of how class detection in Tailwind works:
> 
> https://tailwindcss.com/docs/content-configuration#class-detection-in-depth
> 
> Same thing happens if your code contains the words “flex” or “grid”. To us this trade off is worth it for Tailwind to work with more tools. If we tried to actually parse and understand the code we could only support a small number of templating languages and you’d have lots of situations where things didn’t work that you’d expect to work because we couldn’t detect that something was intended to be used as a class.
> 
> You can disable the container plugin if this really bugs you 👍🏻

Alright, thanks for your answer! We'll fix it be leveraging the prefix.
