### ISSUE TITLE
Arbitrary responsive screen values not working with custom screen values

### ISSUE THREAD

**Issue by treb00** [tailwindlabs/tailwindcss#9718]
**What version of Tailwind CSS are you using?**

v3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

[Tailwind play](https://play.tailwindcss.com/Rvy9zvRfRo?file=config)

**What version of Node.js are you using?**

[Tailwind play](https://play.tailwindcss.com/Rvy9zvRfRo?file=config)

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

[Tailwind play](https://play.tailwindcss.com/Rvy9zvRfRo?file=config)

**Describe your issue**

The arbitrary responsive screen values (`example: max-[1000px]:flex-col`) not working if at least one screen value is added in tailwind config, either in the theme.screens or theme.extend.screens. If you try to remove that one screen value in the provided example, it works again.

If you make a custom screen like:
`screens: {
   sm: '500px'
}`
it still works. However, if you do this:
`screens: { sm: { max: '500px' } }`
it stops working.

**Comment by thecrypticace** [comment]
The `min` and `max` variants are disabled for screen configurations when objects are present. You will also notice that `max-sm:*`, `max-md:*`, etc… don't generate anything. This is an intentional design limitation for now. This is discussed in the description of [#9558](https://github.com/tailwindlabs/tailwindcss/pull/9558#restrictions) in the "restrictions" section. The tl;dr is we did this for simplicity and predictability.

We also issue a warning in the console for the arbitrary value case. We do _not_ in the case of pre-configured screens because we would end up adding invalid suggestions to Intellisense (because we would say we explicitly support a value only to then not generate anything for it). This warning is surfaced in the browser console for Play and the CDN and the terminal for Node:

<img width="776" alt="Screen Shot 2022-11-02 at 16 31 50" src="https://user-images.githubusercontent.com/614993/199596892-7cc0e559-6762-4502-8ca7-06596543a513.png">

![Screen Shot 2022-11-02 at 16 39 04](https://user-images.githubusercontent.com/614993/199597958-087f697a-418f-4afb-94a5-28ffab4081eb.png)
