### ISSUE TITLE
TailwindCSS > 3.1.8 in linux doesn't resolve content paths correctly

### ISSUE THREAD

**Issue by leokolezhuk** [tailwindlabs/tailwindcss#9763]
**What version of Tailwind CSS are you using?**
3.2.2

**What build tool (or framework if it abstracts the build tool) are you using?**
vue 3.2.41, vue-cli 5.0.8, webpack 5.74.0

**What version of Node.js are you using?**
tested on16, 18, it is irrelevant.

**What browser are you using?**

Irrelevant

**What operating system are you using?**

Ubuntu, Windows 10

**Reproduction URL**

Can provide if requested. 

**Describe your issue**
When using latest tailwindcss, content resolution behavior is broken in Linux.

I have a project with the following tree structure. Notice there are two .ce.vue files where actual tailwind classes are present.
![image](https://user-images.githubusercontent.com/18228108/200348544-ced17d49-0904-41eb-90ed-08a23736812b.png)
The tailwind.config.js is the following:
![image](https://user-images.githubusercontent.com/18228108/200349077-7e0f2a0f-da88-4823-9ec2-02eb20a7c1f5.png)

**When project is built with vue-cli under Windows 10, tailwind css classes are extracted correctly.**
**When doing the same under Ubuntu, no tailwind css classes are extracted.** 
Downgrading to tailwind 3.1.8 resolved this issue. Therefore, I believe it is an issue with tailwindcss.

**Comment by thecrypticace** [comment]
Could you share the _full path_ to one of your content files?

**Comment by leokolezhuk** [comment]
Hi @thecrypticace ,

Thanks for having a look at this.
Below is the full path to the tailwind.config.js file:
- **Ubuntu:** /home/lk/fc-vector/src/Vector.Configuration.Spa/tailwind.config.js

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this. Comically enough this was a lurking bug even in 3.1 that only revealed itself if your content paths were specified using absolute paths (for instance if you're using `path.resolve`). We switched to using absolute paths in a bunch of places internally for consistency reasons and it broke this. Basically, because your main `.vue` file had `@tailwind` directives in it we wouldn't pick it up for changes.

We do some normalization on paths in one case but not another which is why this bug didn't appear on Windows because the path separator is switched after normalization.

This should be available to test via our insiders build in a few minutes: `npm install tailwindcss@insiders`

Thanks for reporting the bug! This one was an interesting one to track down haha.

**Comment by leokolezhuk** [comment]
That was probably the quickest bug fix in the history of open source! Thanks a lot, @thecrypticace!
