### ISSUE TITLE
CDN Not reachable

### ISSUE THREAD

**Issue by EngAhmedMahmoud** [tailwindlabs/tailwindcss#9770]
I am trying to reach this [3.2.1](https://cdn.tailwindcss.com/3.2.1) it's not reachable and some times it works and sometimes not work and my whole site css totally not appeared.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

It should always work since it is behind a CDN and they normally have pretty good uptime. That said, you mentioned:

> "and my whole site css totally not appeared."

We explicitly call out in our documentation that you should not use this in production, so I would recommend you to setup Tailwind the proper way and the CLI should give you everything you need 👍 

> The Play CDN is designed for development purposes only, and is not the best choice for production.
> 
> https://tailwindcss.com/docs/installation/play-cdn

For setting up Tailwind with the CLI, take a look at this resource: https://tailwindcss.com/docs/installation

**Comment by adamwathan** [comment]
Hey! Seems like it's working here:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/4323180/200542286-bf54091c-8423-4089-9676-02352074d994.png">

I highly recommend not using the CDN in production though as @RobinMalfait mentioned — it's meant for prototyping only.

I've just added uptime monitoring to the CDN, so will pay attention to any issues and if the uptime appears to be an issue we'll definitely dig in to it.

**Comment by LucidNinja** [comment]
Hey @adamwathan - I know this is a bit old, but is there a versioned CDN for Tailwind, like with Bootstrap? I'm a huge TailwindCSS fan and typically use it for Next.JS apps, but in some cases, I need a CSS solution for existing applications or enterprise CMSs - it would be nice to be able to use the CDN for this. I guess the alternative is to copy any markup from the CMS or application and create a temporary build of it locally?? Any light you can shine on this would be great! Thanks!!
