### ISSUE TITLE
The project is broken after upgrade to antd 5, i.e. NEVER use tailwindcss when you choose a UI library

### ISSUE THREAD

**Issue by GuichiZhao** [tailwindlabs/tailwindcss#9888]
In `@tailwind base`, there is something like  `background-color:transparent` which break the button style in antd 5. When I choose to turn it off using `preflight: false`, everything else is broken, I am in a serious trouble now

Something like, never use other library when choosing tailwindcss should be highlighted in the doc please

**Comment by reinink** [comment]
Hey!

So generally you should be able to use Preflight with UI libraries — most of the styles in Preflight are meant to go unnoticed, and are designed to simply smooth over cross-browser inconsistencies. That said, there are a few opinionated styles in there that can be surprising when you first encounter them. We've done our best to explain all this in our docs here:

https://tailwindcss.com/docs/preflight

Hope that helps, and I'm glad you got this figured out in your project 👍

**Comment by reinink** [comment]
Hey @GuichiZhao, just a quick follow up on this. You might find this discussion helpful: https://github.com/tailwindlabs/tailwindcss/discussions/5969

Others have experience the same issue, and the cause was CSS being in the wrong order. Adam explains that here: https://github.com/tailwindlabs/tailwindcss/discussions/5969#discussioncomment-1577581

So, you might just need to tweak the order of your CSS to fix the issue 👍

**Comment by Webbrother** [comment]
The reason of the issue is a wrong order of `style` tags that tailwind adds to `head`.
See the explanation here: https://github.com/ant-design/ant-design/issues/38794#issuecomment-1364501286

**Comment by coder-xiaotian** [comment]
I solved it: https://github.com/tailwindlabs/tailwindcss/discussions/5969#discussioncomment-6648458

**Comment by liuyib** [comment]
It is really stupid to setting `background-color: transparent` for button in preflight, I can't see the benefit of that.

Please remove `background-color: transparent` in preflight! thanks @reinink
