### ISSUE TITLE
Prose blockquote includes the `<cite>` part in the quotes

### ISSUE THREAD

**Issue by williamd5** [tailwindlabs/tailwindcss#9913]
**What version of Tailwind CSS are you using?**

v3.2.4

**Reproduction URL**
https://play.tailwindcss.com/KXYTkNccoM

**Describe your issue**

The prose plugin adds opening and closing quotes to the contents of `<blockquote>`. However, the `<cite>` is also included in these quotes, which does not look quite correct.

![image](https://user-images.githubusercontent.com/66572326/203661152-4746200e-4a66-42a3-a97e-37612896341f.png)

**Comment by thecrypticace** [comment]
Hey! So, yeah we do add quotes to the beginning and end. However, this is intentional.

Per the HTML spec, citations and attributions do not belong inside a `<blockquote>` element. They must be placed [alongside it](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element):
> Attribution for the quotation, if any, must be placed outside the blockquote element.

> … relate a quote to its attribution (which is not part of the quote and therefore doesn't belong inside the `blockquote` itself)

But, I see what effect you are after. You want the citation to appear with the same style as the blockquote. I've prepped a small Tailwind Play snippet that shows how you can achieve this effect using `figure`, `figcaption`, `blockquote`, and `cite`: https://play.tailwindcss.com/CkrhO7I1GE

The only slightly odd bit is the use of `text-[var(--tw-prose-quotes)]` which allows you to use things like `prose-gray`, `prose-slate`, `prose-zinc`, etc… which tweak the colors used. If you don't use these classes, you can replace it with `text-gray-900` (or whatever other color you want — personally I think a lighter color also works quite well in this context).

Hope this helps! Let me know if you have any further questions. ✨ 

p.s. Good quote — love his skits!

**Comment by williamd5** [comment]
Thank you, this is exactly what I needed.
