### ISSUE TITLE
Wrong order of custome breakpoints

### ISSUE THREAD

**Issue by PhilippLeh** [tailwindlabs/tailwindcss#9946]
**What versions are you using?**

latest version of tailwind with Next.js

**Describe your issue**

If you add new breakpoints, they will be added in the css file after the original ones. With the mobile first approach, this leads to undesirable behavior as smaller breakpoints are now prioritized higher. This bug only occurs on a production build. 

Custome Breakpoints:
![Bildschirmfoto 2022-11-28 um 07 50 56](https://user-images.githubusercontent.com/61593457/204212408-0e7c8381-35ee-4741-94f2-a90886491319.png)

Undesirable behavior (lb is used and not xl, because of the wrong order in the css file):
![Bildschirmfoto 2022-11-28 um 07 56 02](https://user-images.githubusercontent.com/61593457/204213234-a9025293-dd2d-4d6c-8e39-96ac372a1967.png)

![Bildschirmfoto 2022-11-28 um 07 59 20](https://user-images.githubusercontent.com/61593457/204214213-efb542e7-066a-407a-92d4-8348067f1626.png)

![Bildschirmfoto 2022-11-28 um 08 00 12](https://user-images.githubusercontent.com/61593457/204214232-6745f757-4436-4444-868a-a9c8c25d642a.png)

**Comment by thecrypticace** [comment]
So we automatically sort screens, which means this _should_ work. However, there are occasionally cases where it won't work (for example, if you have multiple screens with mixed units). If the automatic sorting of screens doesn't work you can override your screens config instead of extending it like so:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    screens: {
      sm: '640px',
      s: '700px',
      md: '768px',
      la: '800px',
      lb: '900px',
      lc: '950px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
  },
  plugins: [],
}
```

Now, regarding your note "This bug only occurs on a production build.". We don't output CSS differently for production versus dev builds. This means it's likely a built tooling problem where something is minifying and re-ordering the resulting CSS. This is not something we can control.
